### ISSUE TITLE
Error when inscribing on SIGNET: "could not import commit tx recovery key - because: JSON-RPC error: transport error: Couldn't connect to host: Resource temporarily unavailable (os error 35)

### ISSUE THREAD

**Issue by batcavekid** [ordinals/ord#1044]
error: could not import commit tx recovery key
because: JSON-RPC error: transport error: Couldn't connect to host: Resource temporarily unavailable (os error 35)

**Comment by rot13maxi** [comment]
did something happen to your bitcoin-core instance?

**Comment by philmartin2525** [comment]
@rot13maxi, I got this error while trying to run `ord preview`. I am able to run `ord info` `ord index run` and `ord server` successfully. Any thoughts on why this would be the case? Happy to share more information but I'm not sure what would be useful yet.
