### ISSUE TITLE
Announcements

### ISSUE THREAD

**Issue by casey** [ordinals/ord#1060]
I need a way to announcing events, features, milestones, etc.

Some ideas:
- A mailing list
- Just spam people on twitter
- An RSS feed on ordinals.com
- A blog
- A discord channel

**Comment by rot13maxi** [comment]
Substack + post on twitter seems to be a pattern that's emerged. You have the space on the newsletter/blog to both do release-notes type posts and also do longer form content about why things are the way they are, interesting ideas you're mulling over, etc. Twitter is a place to have people commend and get spammed.

**Comment by casey** [comment]
Seems reasonable to me!
