### ISSUE TITLE
Guide to installing bitcoin core

### ISSUE THREAD

**Issue by casey** [ordinals/ord#1062]
Installing and running bitcoin core is one of the biggest stumbling blocks for new users. We should write or link to a guide that makes this as simple as possible on different operating systems.

**Comment by Psifour** [comment]
Happy to contribute with a long-form guide for anyone on Penguin-flavored OSs. Will dump my command history from the last one I setup, add some of the best practices I skipped (checking hashes..), and write it up.

**Comment by Magicking** [comment]
The guides « How-to install Bitcoin Core + Ord » for Windows and Mac are on Discord and written by [@lolo_streams](https://twitter.com/lolo_streams) at:
 - [Bitcoin Core + ord On Mac](https://discord.com/channels/987504378242007100/1076163605713661993/1076163605713661993)
 - [Bitcoin Core + ord on Windows](https://discord.com/channels/987504378242007100/1076160439840419860/1076160439840419860)

They contains text and screenshot that can easily be embedded in a markdown post to be displayed on the ordinals.com website.
This is a good-first-issue!
