### ISSUE TITLE
Show Github activity in Discord eg. via a webhook

### ISSUE THREAD

**Issue by batcavekid** [ordinals/ord#1065]
This could be in the #development channel or its own dedicated channel, and might show for example new commits, PRs, and issues as they are made.

**Comment by Psifour** [comment]
We could implement this very simply, but it would require the MANAGE_WEBHOOKS permission (or an Admin on Discord to create the webhook. This is more of a design decision and would depend on the appetite of @casey to do so.

Steps to implement (to optimize for easy 2-3 minute setup):
1) Create discord channel to house updates (maybe a name like #development-feed?)
2) Right-click Channel -> Settings -> "Webhooks" -> "Create Webhook" -> Configure and take note of Webhook URL
3) Open the repo webhook settings (https://github.com/casey/ord/settings/hooks/new)
4) Payload URL should be the Webhook URL created in step 2 appended with "/github"
5) Content type should be "application/json"
6) Set to trigger on "everything" (radio button)
7) Verify that webhook works by monitoring channel after closing issue :D
