### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by casey** [ordinals/ord#1080]
All inscriptions are displayed with a white background on ordinals.com. We could let inscriptions specify an RGBA background color, and use that instead. We could also let inscriptions specify an RGBA foreground color, and use that for the color of text inscriptions.

Currently, inscriptions that look good over a white background can be transparent, but inscriptions that look good on a black background must be opaque and provide the black background themselves.

We could also use the foreground and background color as highlight colors on /inscription pages, to give them a little more personality.

**Comment by nammaki** [comment]
Sounds nice, any progress on this? ❤️‍🔥

**Comment by casey** [comment]
I'm inclined not to do this, so that inscription pages are uniform.
