### ISSUE TITLE
Persist locked UTXOs

### ISSUE THREAD

**Issue by casey** [ordinals/ord#1147]
`lockunspent` locks UTXOs and prevents them from being used in automatic coin selection. However, locked UTXOs are only stored in memory and are cleared on restart. We should persist locked UTXOs somehow.

`lockunspent` supports a `persistent` argument which persists locked UTXOs to the database. However, this is not supported by rust-bitcoincore-rpc.

**Comment by raphjaph** [comment]
Open PR in upstream
