### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by casey** [ordinals/ord#1248]
React to vote for the next major feature:

- 👍 #802 
- 😄 #1249
- 🎉 #1247 
- ❤️ #783
- 🚀 #876
- 👀 #1082
- 😕 #794

**Comment by veryordinally** [comment]
We are working on #783 as the first item of this roadmap currently and are planning to release that during the week starting March 6th. More details to follow in #783

**Comment by 0attack** [comment]
do you have an updated time frame now?
