### ISSUE TITLE
Generative content for every sat

### ISSUE THREAD

**Issue by casey** [ordinals/ord#1280]
I was sort of thinking about this before using lifehash. I love lifehash, but I think it needs to be even cooler. What kind of algorithm produces interesting super long form generative content for 2.1 quadrillion seeds?

- Weird coats of arms
- Minecraft-like worlds

**Comment by casey** [comment]
Input would be the sat number

**Comment by casey** [comment]
It could also take its current UTXO as input.

**Comment by nammaki** [comment]
This looks like a good match for the work being discussed in https://github.com/casey/ord/issues/1838 🥳
