### ISSUE TITLE
Add RSS feed icon

### ISSUE THREAD

**Issue by casey** [ordinals/ord#1288]
Add an RSS feed icon somewhere, so people can find it.

**Comment by Psifour** [comment]
Something like this what you have in mind?
![image](https://user-images.githubusercontent.com/6956441/218285797-a8b832eb-5c29-435c-a2f6-20e5e3920924.png)

**Comment by raphjaph** [comment]
maybe embed it into the navbar and make it fit the colorscheme?

**Comment by Psifour** [comment]
I can agree with that. Will recolor it and present a few additional options momentarily.
