### ISSUE TITLE
Twitter/Discord bot that posts new inscriptions

### ISSUE THREAD

**Issue by raphjaph** [ordinals/ord#1293]

**Comment by Psifour** [comment]
Should this be implemented in ord or as a separate service? Can be done over a webhook to circumvent the need for a full Discord bot (or built as a full bot if we have other Discord automation that is desired).

**Comment by raphjaph** [comment]
I wrote a quick python bot that just takes screenshots of rendered inscriptions. It's very hacky but it works: https://github.com/raphjaph/ord_bot_py 
https://twitter.com/ord_bot

**Comment by Psifour** [comment]
I believe Casey has mentioned (when discussing better Discord embeds) that the use of a Selenium-style solution (forget specific dependency he didn't want) wasn't the target. It is possible that I took that out of context, but I had assumed (based on the synthesis of that and the need for an inscription feed) that it would effectively be the RSS feed, but with a pretty output on the Discord side.

**Comment by raphjaph** [comment]
Yes, having a selenium and browser dependency is kind of inelegant but it is the quickest way to get good renderings of inscriptions. If you want to add a Discord bot a great first step would be adding webhooks into `ord` as you mentioned above. If you need any help/pointers let us know!
