### ISSUE TITLE
Get off of rust-bitcoincore-rpc fork

### ISSUE THREAD

**Issue by casey** [ordinals/ord#1295]
We depend on https://github.com/casey/rust-bitcoincore-rpc/pull/10, but I don't think we ever opened a PR to get it into rust-bitcoincore-rpc. We should open a PR, so we can get off our fork.

**Comment by gruve-p** [comment]
https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/288 created

**Comment by raphjaph** [comment]
We off our fork now
