### ISSUE TITLE
Keep index synced in background

### ISSUE THREAD

**Issue by casey** [ordinals/ord#1322]
Currently, the index syncs whenever you run a command. It would be nice if it were possible to run the index as a daemon in the background, and have `ord` connect to it whenever it needed to query the index state. This is a pretty large feature, since we'd need to:

- Add a command for running the index as a daemon
- Create an API for querying the daemon
- Modify existing commands to communicate with the daemon via the API
- Figure out if this mode is required or optional, e.g. can you still use `ord` without having `ord daemon` run in the background?

**Comment by kvnn** [comment]
> I am sync'ing in the background rn with a script but native better.

Hi. Could you share your script?

**Comment by nhodges** [comment]
> Would be ideal. I am sync'ing in the background rn with a script but native better.
> 
> Idea for faster initial sync:
> 
> 1. instruct user to sync before bitcoin node is fully synchronized: `ord index`
> 2. later, if index is daemon, have it sync periodically during bitcoin node sync (similar to this issue)

:wave: are you just running `ord wallet inscriptions` or something at some interval?

**Comment by nhodges** [comment]
> Would be ideal. I am sync'ing in the background rn with a script but native better.
> 
> Idea for faster initial sync:
> 
> 1. instruct user to sync before bitcoin node is fully synchronized: `ord index`
> 2. later, if index is daemon, have it sync periodically during bitcoin node sync (similar to this issue)

@batcavekid 

:wave: are you just running `ord wallet inscriptions` or something at some interval?

**Comment by liuser** [comment]
If this automatic synchronization issue is resolved, please let me know

**Comment by raphjaph** [comment]
Would be cool to have this feature! I think @niftynei mentioned she was working on this.

**Comment by raphjaph** [comment]
got this now
