### ISSUE TITLE
Add links to mempool.space

### ISSUE THREAD

**Issue by casey** [ordinals/ord#1335]
I often want to look up blocks, transactions, and outputs on mempool.space. We should include links on those pages to make it easier. Will have to take signet/mainnet/testnet into account.

**Comment by Psifour** [comment]
Relevant http endpoints and an icon to add to the right of the block, tx, and outputs links 
![image](https://user-images.githubusercontent.com/6956441/218286634-870afe3b-b741-4331-b377-3157b90e183b.png)


`https://mempool.space/block/*blocknumber*`
`https://mempool.space/block/*blockhash*`
`https://mempool.space/tx/*transactionhash*`
`https://mempool.space/address/*address*`

**Comment by raphjaph** [comment]
I think we don't do this. just keep it simple and link internally
