### ISSUE TITLE
Markdown

### ISSUE THREAD

**Issue by casey** [ordinals/ord#1351]
Should we support markdown? Either users compile markdown to HTML, or we render md inscriptions in JS or on the server to HTML. Would be clean and compact to support markdown inscriptions.

**Comment by techcapo** [comment]
Yes we should. I started a blog chain, i'm inscribing posts in markdown as `text/plain` would be cool to get a formatted view on ordinals dot com. Inscribing precompiled HTML feels like bloat.

**Comment by nammaki** [comment]
Please support this 🙏
