### ISSUE TITLE
Allow SVG and HTML inscriptions to access chain statistics

### ISSUE THREAD

**Issue by casey** [ordinals/ord#1385]
HTML and SVG inscriptions should be able to access:

- Current chain height
- Block hash at particular height
- Sat the inscription is on, etc

This is probably something to do after we figure out #1082.

**Comment by DEFSTALKR** [comment]
calling chain height, yes please!

**Comment by casey** [comment]
I don't like the idea of keyword replacement, it seems error prone, and the same thing can be supported by whitelisting endpoints. Inscription ID can be retrieved from the URL. The sat the inscription is on and the height of the block in which the inscription was made are both good ideas.

**Comment by onchainguy-eth** [comment]
@casey but how do I get the inscription ID (or some URL containing it) from inside the inscription content? Maybe I missed that somewhere 🤔

**Comment by casey** [comment]
@onchainguy-eth Since inscriptions are served at `/content/<INSCRIPTION_ID>`, you can get the path with `window.location.pathname()` and then split on `/` to get the inscription ID.

**Comment by onchainguy-eth** [comment]
@casey ok thanks I get what you mean then! 🙏 This allows displaying HTML (XML) based recursive inscriptions to be displayed on the ord frontend or on other sites which integrate the inscription content via iframe.

**Comment by joaomendoncaa** [comment]
On second thought, you won't be able to listen to requests on other inscriptions...

Food for thought nonetheless! 😄

**Comment by onchainguy-eth** [comment]
@casey I've proposed a lightweight solution for making generative art on ordinals easier. It works without any find and replace [here](https://github.com/ordinals/ord/pull/2222). Appreciate your feedback 🙏

**Comment by raphjaph** [comment]
Closing this because we have recursion now.

**Comment by raphjaph** [comment]
Currently not possible but will add. Here's the issue: https://github.com/ordinals/ord/issues/2262
