### ISSUE TITLE
GLIBC_2.32 not found

### ISSUE THREAD

**Issue by jacobburrell** [ordinals/ord#1430]
I've got the following issue twice on two separate instances:

`ord: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ord)`

Has anyone had the same issue? 

Ubuntu 20.04.1 LTS

**Comment by dude513** [comment]
Consider upgrading to Ubuntu 22.04 to have a higher version of GLIBC.

```
sudo apt update -y && sudo apt upgrade -y
sudo do-release-upgrade -d
```

To check GLIBC version.

```
ldd --version | head -n1
```

**Comment by jacobburrell** [comment]
Thanks!

That worked. Probably should mention in dependency or requirement somewhere, or improve the error message.

**Comment by casey** [comment]
Good idea! Can someone open a PR to add this to the readme?

**Comment by AlexLloyd0** [comment]
I have the same issue on Debian 11, and an OS upgrade to is not feasible for this machine. Building from source worked though

**Comment by pavillag** [comment]
Is there a way to update `:~$ ldd --version | head -n1
ldd (Ubuntu GLIBC 2.27-3ubuntu1.6) 2.27` to any of the supported ord versions? 
![image](https://user-images.githubusercontent.com/30845498/217844800-c7abe682-fbe2-48fb-9567-124b816a85b7.png)

**Comment by missingpurpose** [comment]
> Is there a way to update `:~$ ldd --version | head -n1 ldd (Ubuntu GLIBC 2.27-3ubuntu1.6) 2.27` to any of the supported ord versions? ![image](https://user-images.githubusercontent.com/30845498/217844800-c7abe682-fbe2-48fb-9567-124b816a85b7.png)

Having the same issue, are you using the AWS Full node as well?

**Comment by 0xBeans** [comment]
same issues as @pavillag and @missingpurpose , running on EC2

**Comment by dude513** [comment]
`ord` requires GLIBC version 2.32 or higher.
To compile from source, first we need to install gawk and bison that are used in compiling Glibc:

```
sudo apt-get install gawk bison -y
```

Download and unpack the source, then configure a separate build directory and install glibc-2.34:

```
wget -c https://ftp.gnu.org/gnu/glibc/glibc-2.34.tar.gz
tar -zxvf glibc-2.34.tar.gz && cd glibc-2.34
mkdir glibc-build && cd glibc-build
../configure --prefix=$HOME/glibc-2.34
```
Compile and install. Compiling can take some time.

```
make 
make install
```
The second way (**recommended**) is to upgrade to Ubuntu 22.04.
Make sure you saved your keys and made all necessary backups since the upgrade can damage your current environment.

```
sudo apt update -y && sudo apt upgrade -y
sudo do-release-upgrade -d
```

**Comment by 0xBeans** [comment]
<img width="762" alt="Screen Shot 2023-02-10 at 2 00 48 AM" src="https://user-images.githubusercontent.com/103160460/218062345-72b94fe0-22c3-4fa5-a49b-bf5d26efb20c.png">

@dude513 when running `make install` (also used sudo to confirm) I run into this error.

Also, it is not possible to update ubuntu on an EC2 instance the recommended way.

**Comment by pavillag** [comment]
> `ord` requires GLIBC version 2.32 or higher. To compile from source, first we need to install gawk and bison that are used in compiling Glibc:
> 
> ```
> sudo apt-get install gawk bison -y
> ```
> 
> Download and unpack the source, then configure a separate build directory and install glibc-2.34:
> 
> ```
> wget -c https://ftp.gnu.org/gnu/glibc/glibc-2.34.tar.gz
> tar -zxvf glibc-2.34.tar.gz && cd glibc-2.34
> mkdir glibc-build && cd glibc-build
> ../configure --prefix=$HOME/glibc-2.34
> ```
> 
> Compile and install. Compiling can take some time.
> 
> ```
> make 
> make install
> ```
> 
> The second way (**recommended**) is to upgrade to Ubuntu 22.04. Make sure you saved your keys and made all necessary backups since the upgrade can damage your current environment.
> 
> ```
> sudo apt update -y && sudo apt upgrade -y
> sudo do-release-upgrade -d
> ```

Ran the commands below and was successful in upgrading the GLIBC version to 2.35 in my 22.04 server. Unsuccessful when trying to update on a 18.04. Thanks for the help!
> sudo apt update -y && sudo apt upgrade -y
> sudo do-release-upgrade -d

**Comment by dude513** [comment]
I doubt you can upgrade from 18 to 22 skipping the release in between, for the same reason I think compiling glibc from source had some issues for you on 18. Anyways, I am glad it helped.

**Comment by 0xBeans** [comment]
@pavillag did you start your fullnode from an blank EC2 instance or did you a purchase an existing on from the marketplace?

**Comment by pavillag** [comment]
> @pavillag did you start your fullnode from an blank EC2 instance or did you a purchase an existing on from the marketplace?

I started my fullnode from a new Ubuntu VM in Azure. I was able to download the full node, but did so in a18 instead of a newer version. I am now doing so in a 22. _

**Comment by mgdevereux** [comment]
@0xBeans and @missingpurpose   Having the same issue here. going through stack exchange looking for a fix but no luck.   I am using the Bitcoin Fullnode By: Techlatest.net which has not been a good experience so far.   Any luck finding a solution since?

**Comment by tripluca** [comment]
> > `ord` requires GLIBC version 2.32 or higher. To compile from source, first we need to install gawk and bison that are used in compiling Glibc:
> > ```


this did not work for me as it requires an upgrade to GLIBC which did not go through.
This worked: 

> $ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
> $ cd
> $ sudo apt install git
> $ git clone https://github.com/casey/ord.git
> $ cd ord
> $ cargo build --release
> $ target/release/ord --help
