### ISSUE TITLE
Figure out how to encourage contributors

### ISSUE THREAD

**Issue by casey** [ordinals/ord#1439]
- More "good first issues", help people find manageable things to work on
- Better insight into prioritization, help find things that are needed and we're likely to merge
- Opportunities to review and discuss, so people can contribute expertise ideas without needing to code

**Comment by rot13maxi** [comment]
PR Review Club?

**Comment by rot13maxi** [comment]
Ignore my last. you already did that :P

**Comment by raphjaph** [comment]
We have made Ordinals Coding Club on Discord private but we could have an announced session once a week, where people can join and watch us code and review code.
