### ISSUE TITLE
Vulnerability disclosure hotline

### ISSUE THREAD

**Issue by casey** [ordinals/ord#1442]
Probably just my email address or something but good to figure out.

**Comment by rot13maxi** [comment]
I'd recommend you make a new email alias just for it (even if it just goes to your email). Put that on a page with a GPG key

**Comment by casey** [comment]
Sounds good. I should set up MX records for ordinals.com, so it can be casey@ordinals.com.

**Comment by casey** [comment]
I'll probably use a Google Workspace, since I like gmail, but I've been hesitant since it's heavy and has a per-seat cost.
