### ISSUE TITLE
indexing is very slow

### ISSUE THREAD

**Issue by OrpingtonClose** [ordinals/ord#1444]
Attempting to index bitcoin using `ord index` but it's excruciatingly slow at around the 400000 block mark.
Is there anything that can be done to make the process quicker? Synced the bitcoin node on a huge ramdisk and I'm running ord indexing database on the same ramdisk. Syncing on my local non-ramdisk machine and the speed is kind of similar.

**Comment by dude513** [comment]
Related to https://github.com/casey/ord/issues/1377. @OrpingtonClose
