### ISSUE TITLE
Figure out why /inscriptions is slow

### ISSUE THREAD

**Issue by casey** [ordinals/ord#1454]
I think that there are some inscriptions that are very heavy to load, and slow down fully rendering pages in which they appear. I haven't looked into it too heavily, but using load=lazy might help:

https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading

**Comment by raphjaph** [comment]
We are loading the content from Bitcoin Core so maybe that's bottleneck

**Comment by OrdinalChad** [comment]
lag starts on the explorer at ordinals.com/inscriptions/19701 with the voids
and basically bricks out when more of them are minted around ordinals.com/inscriptions/20100

**Comment by OrdinalChad** [comment]
ordinals.com/inscriptions/49200 loads fine in the page but scrolling past ordinal 49162 is very slow

**Comment by OrdinalChad** [comment]
this page is also omega slow
ordinals.com/inscriptions/57020

**Comment by casey** [comment]
Next step on this is figuring out what the offending inscriptions are.
