### ISSUE TITLE
Show stable inscription sequence number when listing inscriptions (both wallet and website)

### ISSUE THREAD

**Issue by veryordinally** [ordinals/ord#1455]
Show the number of the inscription as shown on the website when listing inscriptions from the wallet.

Planning to work on this.

**Comment by casey** [comment]
One concern with surfacing the inscription number right now is that inscription numbers depend on knowing all inscriptions before a given inscription, and when we update the protocol, there will be new inscriptions which old clients ignore, which will give different clients a different view of inscription numbers.

So for example, we haven't made a endpoint that lets you look up inscriptions by number, because those URLs might be unstable.

So given that numbers are unstable, should we surface them in the CLI?

**Comment by VirtuallyThere** [comment]
As just discussed - having a stable sequence numbering scheme would be high value and should be doable. We need to make sure to also count inscriptions that are invalid from a perspective of the current client version to make this stable across future upgrades.

We should get the multiple inscriptions per transaction changes implemented before working on this issue.

**Comment by veryordinally** [comment]
Executive decision by @casey to keep existing numbers stable: https://twitter.com/rodarmor/status/1626621385618628608

Details to be worked out.

**Comment by tyjvazum** [comment]
Where can I find details about the original bug?

**Comment by tyjvazum** [comment]
> I think this ship has sailed in the sense that people are attached to the existing inscription numbers, so in true Bitcoin fashion, we now how to work around our past mistakes.
> 
> Context:
> 
>     1. The degens at rug radio like stability: https://twitter.com/rodarmor/status/1626620947691356161
> 
>     2. Inscription with perfect number that would change: https://ordinals.com/inscription/8d740dbfeb7da687b772dc343848b933dfecb3c29b16891c77df2e2c587097fbi0
> 
> 
> We are now committed to the existing numbers. New priorities:
> 
>     * Fixing the original bug
> 
>     * Hard-coding the hidden inscriptions by inscription id so that when the bug is fixed, those specific inscriptions stay hidden
> 
>     * Surfacing the hidden ordinals one day as an easter egg, maybe as nega inscriptions with negative numbers that count down from 0.

Where can I find details about the bug?

**Comment by tyjvazum** [comment]
> I think this ship has sailed in the sense that people are attached to the existing inscription numbers, so in true Bitcoin fashion, we now how to work around our past mistakes.
> 
> Context:
> 
>     1. The degens at rug radio like stability: https://twitter.com/rodarmor/status/1626620947691356161
> 
>     2. Inscription with perfect number that would change: https://ordinals.com/inscription/8d740dbfeb7da687b772dc343848b933dfecb3c29b16891c77df2e2c587097fbi0
> 
> 
> We are now committed to the existing numbers. New priorities:
> 
>     * Fixing the original bug
> 
>     * Hard-coding the hidden inscriptions by inscription id so that when the bug is fixed, those specific inscriptions stay hidden
> 
>     * Surfacing the hidden ordinals one day as an easter egg, maybe as nega inscriptions with negative numbers that count down from 0.

Where can I find details about the bug?

**Comment by nammaki** [comment]
> I think this ship has sailed in the sense that people are attached to the existing inscription numbers, so in true Bitcoin fashion, we now how to work around our past mistakes.
> 
> Context:
> 
>     1. The degens at rug radio like stability: https://twitter.com/rodarmor/status/1626620947691356161
> 
>     2. Inscription with perfect number that would change: https://ordinals.com/inscription/8d740dbfeb7da687b772dc343848b933dfecb3c29b16891c77df2e2c587097fbi0
> 
> 
> We are now committed to the existing numbers. New priorities:
> 
>     * Fixing the original bug
> 
>     * Hard-coding the hidden inscriptions by inscription id so that when the bug is fixed, those specific inscriptions stay hidden
> 
>     * Surfacing the hidden ordinals one day as an easter egg, maybe as nega inscriptions with negative numbers that count down from 0.

Is this bug related to https://github.com/casey/ord/issues/1841 or is it a different issue? 🤔
