### ISSUE TITLE
Front page and /inscriptions moderation

### ISSUE THREAD

**Issue by casey** [ordinals/ord#1465]
It would be nice to have a way to prevent graphic content from being displayed on the front page. It hasn't been a problem so far, but could in the future, and right now requires manual intervention. Eventually, we'll probably have to stop the frontpage from showing all new inscriptions.

An idea is that you can set a height in the `ord.yaml` config file, and the server will not display inscriptions on the front page or /inscriptions above that height. Every day we review, hide graphic stuff, and update the height. I don't like this idea, since it's super heavy handed, but could be a good option if we get overwhelmed.

**Comment by hantuzun** [comment]
Cloudflare CSAM Scanning could be used: https://blog.cloudflare.com/the-csam-scanning-tool/

**Comment by casey** [comment]
Good idea. I think I should probably turn that on.

**Comment by casey** [comment]
Just applied for NCMEC CyberTipline credentials, which are required to turn on the CSAM scanning tool.

**Comment by casey** [comment]
First step we came up with was to give wildman and @VirtuallyThere SSH keys to the ordinals.com server, so they can add inscriptions to the config file manually. This has minimal risks because:

- no private keys or credentials are on the ordinals.com server
- it is a standard hetzner server, so can just spin up a new one if it gets hosed
- deploy script is a one-liner. index will be hosed, but it will rebuild.

Next steps:
- make a tool that people can use which doesn't require trust
- eventually prevent new inscriptions from hitting the feed without having to hide them everywhere

**Comment by hantuzun** [comment]
> it is a standard hetzner server, so can just spin up a new one if it gets hosed

Running blockchain software, any kind, is against Hetzner's ToS.

> make a tool that people can use which doesn't require trust

Designing such a trustless tool that is durable against unnecessary censorship would be hard. If it's not a solved problem, I think it'd be really hard to solve.
A practical approach could be to have moderator users that edit the blocklist from a UI.

**Comment by raphjaph** [comment]
> > it is a standard hetzner server, so can just spin up a new one if it gets hosed
> 
> Running blockchain software, any kind, is against Hetzner's ToS.

We realized this a couple weeks ago but decided just to let it run until we get banned

**Comment by casey** [comment]
This will be closed with the CSAM scanning tool as a first line of defense. Second line of defense is mods sshing into the server and removing content manually. Third line of defense will be some kind of lighting-based reporting system where you pay a few sats to flag and we manually review.

**Comment by casey** [comment]
We have fully given up on any kind of moderation T_T
