### ISSUE TITLE
[Feature Request] Inscribe and send in the same transaction

### ISSUE THREAD

**Issue by dannydeezy** [ordinals/ord#1470]
It would be great if `ord wallet inscribe` had an option `--destination`, where the ordinal goes upon reveal. This would allow "minting" directly to a third party degen

**Comment by casey** [comment]
This would be great. This is relatively easy to do, so I added "good first issue".

**Comment by hantuzun** [comment]
If someone can handhold me, I can work on this the next week.

**Comment by raphjaph** [comment]
Looks like someone beat you to it #1512. 

@hantuzun If you have another issue/feature you would like to tackle, let me know. I'd be happy to give you some pointers!

**Comment by veryordinally** [comment]
Implemented in #1536
