### ISSUE TITLE
Link to awesome-ordinals

### ISSUE THREAD

**Issue by BTCGandalf** [ordinals/ord#1480]
Yo, hope this is what you meant in your Tweet. If not, apologies. 

[Ordinals Informational Resource Compilation Site](https://ordinals.wtf)

**Comment by hantuzun** [comment]
I created a similar repo ([awesome-ordinals](https://github.com/neu-fi/awesome-ordinals)), just a little bit earlier than your "issue". I don't know about the tweet but I don't think this conversation belongs to a project issue.

**Comment by casey** [comment]
Awesome, thank you! I want to make a list of great links somewhere? Maybe a new docs page called "links" that has everything in sections? Can start with just the link to @BTCGandalf's page.

**Comment by casey** [comment]
Ahh, wait, @hantuzun's awesome ordinals is sweet. We should direct everyone to there. We should add @BTCGandalf's page to that if it hasn't been added already, and add a link to awesome ordinals somewhere in our docs and other places that are prominant.

**Comment by BTCGandalf** [comment]
@hantuzun Casey had asked me to create an issue here for my page. Awesome ordinals is cool, great job. I'm going to link to it on ordinals.wtf.

P.S. Sorry, I'm a github noob and realised now that this issue should have been something like "Link to ordinals.wtf". Everyday's a school day.

**Comment by casey** [comment]
> P.S. Sorry, I'm a github noob and realised now that this issue should have been something like "Link to ordinals.wtf". Everyday's a school day.

This is actually on me 😅 I hijacked the title to reflect that we should link to ordinals.wtf from awesome-ordinals. My thinking is that since awesome-ordinals is a GitHub repo, community members can contribute to it, and we can use it for as the main repository for ordinals links.

**Comment by BTCGandalf** [comment]
Sounds good to me.

**Comment by raphjaph** [comment]
got some examples in the docs now
