### ISSUE TITLE
Preview command breaking ord

### ISSUE THREAD

**Issue by dworac** [ordinals/ord#1484]
After running `ord preview` command ord doesn't work anymore.  

After inspecting the code I'm thinking it might have to do with this line in whic the regtest network is hardcoded. My best guess is that trying to open `bitcoind` with another network is somehow messing the ord indexes or something.

https://github.com/casey/ord/blob/938b5cc97d48d026fd9250eae661d1e87286b377/src/subcommand/preview.rs#L35

I'm not experienced in rust but trying to do what I can to fix it.

**Comment by dworac** [comment]
I deleted the `index.redb` file and it's re-indexing again, so it makes that indeed the db indexes got messed up with the mix of network. 

I think that will fix it for now. For anyone wondering, the file is located in `.local/share/ord/index.redb`

**Comment by casey** [comment]
What error message are you getting? It's hard to know what's going on without an error message to go off of. Please feel free to reopen with the message.

**Comment by dworac** [comment]
After running the `ord preview` command once any other command (such as `ord wallet balance` or `ord index`) that requieres indexes didn't work at all. No error log, no output, nothing, just blank cursor. 

Is it normal that `regtest` network is hardcoded on the `preview` command?

**Comment by dworac** [comment]
I understand now. Thanks for the clarification!

**Comment by casey** [comment]
You bet!

**Comment by kvnn** [comment]
I believe I encountered this issue. See https://github.com/casey/ord/issues/1809
