### ISSUE TITLE
Export descriptor

### ISSUE THREAD

**Issue by cryptoquick** [ordinals/ord#1507]
What'd be really useful is to be able to export an xpub descriptor, so I can load it into Blue Wallet as a watch-only wallet. That way I can get notifications when my txs are mined. But it'd also be helpful to be able to export the xprv descriptor also, in case the original mnemonic isn't saved.

**Comment by andrewtoth** [comment]
This can be done with `bitcoin-cli -rpcwallet="ord" listdescriptors`.

**Comment by casey** [comment]
This can definitely be done with bitcoin-cli. I also think it would be reasonable to provide a native ord wallet command for this. The less that people have to drop into bitcoin-cli, which is unfamiliar (especially because it requires passing the right wallet name to `-rpcwallet`, the better.

**Comment by raphjaph** [comment]
`ord wallet dump`
