### ISSUE TITLE
community Content Moderation of ordionals.com suggestion. 

### ISSUE THREAD

**Issue by Fiach-Dubh** [ordinals/ord#1514]
I have a suggestion for content moderation of your ordinals website. enable people to pay via bitcoin/lightning to censor an image and flag it for your review. the amount they pay can be returned to them (maybe even return more than paid?) by you if it's a legitimate flag/content take down. or you keep the amount if it's a wrongful report and then make the image/content viewable again.

minimum amount to censor? say 21000 satoshis? 

return 30000 satoshis if the report is legitimate? (have the user enter in a lnurl or onchain return address as a requirement (so you can return the funds) before displaying an invoice/payment address for censorship)

keep the 21000 satoshis if it's a false report.

**Comment by casey** [comment]
I like this a lot. I think we wouldn't return it, and it would be a small amount, so really it's about creating at least a minimal barrier to reporting so we get good reports.

To troll people, every time something gets flagged but it's actually fine, we could double the price to flag it again. If people want to keep paying exponentially increasing amounts of sats to hide random inscriptions, that's fine by me.

I actually think the initial minimum amount should be 1 sat. (Or whatever the smallest practical amount is.) The actual amount can be adjusted easily as a config option, and just being able to successfully make a lightning payment is already a high barrier to entry.

**Comment by Fiach-Dubh** [comment]
you can gamify it for sure. but you may not want to be dealing with mass false reports. could be fun your way.

**Comment by casey** [comment]
Moderation doesn't seem to be much of a problem in practice.
