### ISSUE TITLE
I get `error: Database already open. Cannot acquire lock.` when I try to run various commands. Is this related? I see he had a similar error above.

### ISSUE THREAD

**Issue by casey** [ordinals/ord#1518]
I get `error: Database already open. Cannot acquire lock.` when I try to run various commands. Is this related? I see he had a similar error above.

_Originally posted by @lylepratt in https://github.com/casey/ord/issues/1458#issuecomment-1418392513_

**Comment by casey** [comment]
Are you getting these errors from `ord` commands or `bitcoin-cli` commands? If it's `ord`, then it sounds like you have an `ord` command running somewhere else. If it's `bitcoin-cli`, then you might be trying to open a wallet that's already open.

**Comment by lylepratt** [comment]
apparently I had a stuck `ord index` command. didn't originally launch it to background though, so not sure what happened.

**Comment by MattSenter** [comment]
Ah yes, that was my issue as well. Thank you for your trouble!

**Comment by casey** [comment]
Ahh, nice. Could we make this better by adding an error message?

**Comment by casey** [comment]
Something like "another copy of `ord` may be running"

**Comment by kevinfaveri** [comment]
Hey @casey. maybe we can make it so that you can run the wallet still? rn even using the wallet for inscribing NFTs is not possible because it will say it is locked on the server/indexer I have running
