### ISSUE TITLE
Add command to "top up" postage on inscribed UTXO

### ISSUE THREAD

**Issue by rot13maxi** [ordinals/ord#1538]
By default, `ord wallet inscribe` creates a UTXO with 9999 sats worth of padding for "postage", to pay future tx fees. If you think that an average sending an inscription is in the 111-5something range, then that means an inscription can be send around ~20 times before its postage is depleted. Ordinal Theory tells us that as long as we add newer sats (sats that were mined at a later block height)  to the UTXO, then the inscribed sat will still be the first one in the output. Given a wallet with some outputs that have later ordinal numbers than the inscribed sat, we should have a command to "refill" or "top up" the postage on an inscribed sat.

**Comment by casey** [comment]
> Ordinal Theory tells us

❤️

> as long as we add newer sats (sats that were mined at a later block height) to the UTXO, then the inscribed sat will still be the first one in the output

The age of the sats actually doesn't matter or change the order in an output. You can have sats in an output out of order, it only matters how they appeared in the inputs. I'm thinking though that maybe I'm being unclear somewhere about this, since actually someone else thought this. Maybe something in a doc or FAQ or something is weirdly phrased?

Whenever the postage dips below the dust limit, it should be topped up to TARGET postage.

**Comment by rot13maxi** [comment]
Ah! You are correct!

I haven’t looked at the current ‘send’ implementation. Will it automatically top up the postage? If not, thats where this should go: it should happen as part of a send, not a discrete step.

**Comment by rot13maxi** [comment]
Just took a quick poke around send. I think there’s a spot in there for this. We probably want a flag to either pick an output to replenish with, or offer a confirmation or something. Youd hate to pad with some exotic ordinal when you have a stack of commons in the corner.

**Comment by casey** [comment]
> Ah! You are correct! I haven’t looked at the current ‘send’ implementation. Will it automatically top up the postage? If not, thats where this should go: it should happen as part of a send, not a discrete step.

I'm actually not sure if we do that. I *think* we implemented it but it's been a while 😅 #1557 actually just tracks checking if it's supported.

**Comment by BTCAlchemist** [comment]
In #1538 (which is closed), @veryordinally said they reviewed code and tested a way to use funds from a cardinal UTXO to send an ordinal UTXO with low postage. What is the command(s) to do this?

In addition, if a user who does not use ord wallet has an ordinal UTXO with dust postage, how could this be rescued without importing their entire seed phrase (e.g. import the private key with the UTXO into ord wallet)?

**Comment by casey** [comment]
I think this happens automatically if postage is too low.
