### ISSUE TITLE
Arbitrary Protocols for Envelopes

### ISSUE THREAD

**Issue by tyjvazum** [ordinals/ord#1548]
I've completed (what I think are all of) the main changes required to implement initial support of arbitrary protocols for envelopes as my comments in issue [https://github.com/casey/ord/issues/1501](https://github.com/casey/ord/issues/1501) describe.

This would allow developers to create additional protocols, which I think of as extensions of the `ord` protocol. I have use cases in mind, that I'd like to develop, such as an identifier system that would enable nice implementations of features like collections and provenance. These extensions would expand the overall Ordinals ecosystem (and Bitcoin ecosystem), allowing more to be built on top of and around it, without the core `ord` code needing to consider extensions directly.

There are primarily two areas of changes: 1) allowing an optional `protocol_id` to be passed into the program by the user, which goes into the `envelope` in the transactions, and 2) allowing the user to specify what protocols the server should monitor for, with arbitrary protocols lacking the usual `ord` behavior.

There is an open question as to how the protocol specifier should look in the envelope, with the following two options available, where "protocol" is the extension protocol specifier:

```
OP_FALSE
OP_IF
  OP_PUSH "ord"
  OP_PUSH "protocol"
  OP_1
  OP_PUSH "text/plain;charset=utf-8"
  OP_0
  OP_PUSH "Hello, world!"
OP_ENDIF
```

```
OP_FALSE
OP_IF
  OP_PUSH "protocol"
  OP_1
  OP_PUSH "text/plain;charset=utf-8"
  OP_0
  OP_PUSH "Hello, world!"
OP_ENDIF
```

Is this something the project is interested in? If so, I'll continue working on it to produce a PR for review. In any case, I'm open to all available feedback.

**Comment by casey** [comment]
I think that envelope protocols other than `"ord"` will not be supported by `ord` the binary, so we can only add things for other protocols if someone writes PRs and those PRs are easy to review and land, and don't make the code complicated.

All future planned upgrades to ordinals, like provenance, offers, etc, don't require additional protocols, and can work by extending `ord` envelopes. Additionally, publishing arbitrary data like in #1501, can also be supported by `ord`, either by inscribing a sat and then burning it, or in some other way.

So I *think* that this is something that would be hard to merge, unless the PR was very simple, the functionality was not confusing to users, and what people want to do is legitimately something that cannot be done with `ord` protocol envelopes.
