### ISSUE TITLE
Fix signet.ordinals.com and testnet.ordinals.com

### ISSUE THREAD

**Issue by casey** [ordinals/ord#1559]
I messed up signet.ordinals.com today in a redeploy. Figure out how to get it back up.

**Comment by casey** [comment]
This is due to `ord` not being able to read the cookie file, probably just a permissions issue.

**Comment by paulkania** [comment]
Is this why the ordinals.signet.com is down? I'm getting a cloudflare 521 error

**Comment by kyranjamie** [comment]
+1, would be super helpful for testing ord sending implementations

**Comment by aviwol** [comment]
For now if any one would like, I have deployed a signet node with explorer:
https://signet.ordapi.xyz/

**Comment by 0xFreeman-AI** [comment]
Any update on `signet`, get the `Error code 522`

**Comment by linxux** [comment]
Any update on `signet.ordinals.com`?
Still, get the error - `Connection timed out Error code 522`.

**Comment by casey** [comment]
These are back online.
