### ISSUE TITLE
Consider turning on mempoolfullrbf on the ordinals.com bitcoin core instances

### ISSUE THREAD

**Issue by casey** [ordinals/ord#1576]

**Comment by garyray-k** [comment]
yes.

**Comment by casey** [comment]
I appreciate the `yes`, but I want to know why this makes sense specifically for the ordinals.com bitcoin core nodes. These actually don't process transactions or care much about the mempool at all. I'm hoping to understand whether or not I should do this independent of whether I want to support full RBF on the network.

**Comment by garyray-k** [comment]
In that case, my response would be 🤷‍♂️. 

Unless there's mempool considerations in the logic, doesn't seem to make sense to change anything from default.

**Comment by petertodd** [comment]
I agree that mempoolfullrbf=1 with stock Bitcoin Core should have no direct affect on ordinals.com

Indirectly, you would be providing a small bit of support to Luxor pool, which is both mining full-rbf, and oversized ordinals.

OTOH running my [full-rbf peering fork of Bitcoin Core](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2022-December/021270.html) provides a small benefit to people making ordinals, as the fact that full-RBF peering nodes are strongly interconnected provides a way to ensure that straightforward attempts to censor ordinals fail. But, I suspect those attempts are going to be utter failures anyway, as I doubt anyone is putting enough effort into running enough nodes to make any difference.

Finally, with more work my full-rbf peering code could be a good way to create an interconnected network of nodes that accept oversized ordinals. But that needs more work to avoid the signature hashing DoS attacks that oversized non-segwit transactions are vulnerable too.
