### ISSUE TITLE
Allow previewing the effect of a transaction

### ISSUE THREAD

**Issue by casey** [ordinals/ord#1590]
Users sometimes need to manually construct ordinal-aware transactions. To make this easier, let's add some way to preview manually constructed transactions.

> I want to do something where you can paste a hex transaction in the block explorer (privacy considerations and users posting transactions they don't want to broadcast are an issue, so may want to limit to local only, or need to pass a flag to turn on this functionality and it's disabled for public instances) and see what the ordinals/inscriptions on the outputs would be, so you can check manually constructed transactions.

**Comment by LyricalString** [comment]
What happened with this?
