### ISSUE TITLE
Show mnemonic after creation with `wallet mnemonic`

### ISSUE THREAD

**Issue by raphjaph** [ordinals/ord#1595]
No sure if we should have this because this makes the job for scammers very easy

**Comment by rot13maxi** [comment]
I like the idea of having this. Maybe some very loud text that says "NEVER GIVE THIS TO ANYONE EVER" or something could help

**Comment by casey** [comment]
I would definitely support some kind of loud warning. I can't think of a way to not show the mnemonic that doesn't make it easier to miss. We could add a prompt like "PRESS RETURN TO DISPLAY MNEMONIC", however in general I'm against including interactive steps like this. I think users need to keep in mind that all commands will do what they do immediately and without user intervention. If you don't think there's a confirmation step before something dangerous, but there is, you're fine. If you think there's a confirmation step but they're isn't, you're hosed.

**Comment by haxBTCgit** [comment]
I like the push for confirmation consistency. What if the command reflects it will have a confirmation step? Like `ord wallet --confirm-mnemonic`. Confirm in this case is reference to "you will need to pass a confirmation step" as well as "I would like to confirm what my mnemonic is".

That way, the confirmation step can scream in big bold terminal dominating text: "DO NOT GIVE THIS OUT TO ANYONE. DO NOT HAVE ANYONE NEAR BY WHEN DISPLAYING THIS. DO NOT SHARE YOUR SCREEN WITH ANYONE WHILE DOING THIS. IF ANYONE TOLD YOU TO DO THIS, YOU ARE MOST LIKELY BEING SCAMMED."

**Comment by casey** [comment]
We don't actually store the mnemonic, just the derived derivation path, and I don't think we'd want to change that in order to do this.
