### ISSUE TITLE
Package ord for as many package managers as possible

### ISSUE THREAD

**Issue by casey** [ordinals/ord#1609]
Ideally, we could get `ord` into as many package repositories as possible. Homebrew should be a high priority. I think we already meet their notability and popularity guidelines. We cannot maintain these packages, so interested community members, ideally people who are already familiar with Rust and packaging Rust binaries for the repo they're working with.

You don't need our permission! Feel free to package `ord` and open an issue to add the install steps to the readme. Consult the readme of [casey/just](https://github.com/casey/just) for ideas of how to list packages in the readme. I like the two tables there.

Here's my priority list so far:

1. Nix: https://nixos.org/ - I think we can create a nix file which allows a user to start bitcoind, and ord, in one command, and it will work on many platforms.
2. Codespaces: Getting ord working in codespaces, so one-lick to get started.
4. mynode86 - node-in-a-box solution that supports x86
5. regtest replit
6. raspi blitz - (most?) open source node-in-box solution
7. docker - commonly used by node-in-boxes like start9, so having an example docker container for them to work off of would be awesome
8. homebrew - very common, macs are easy, super common dev platform

**Comment by earthgohan** [comment]
Could you kindly provide a cdylib version of this library, as it would greatly assist in the building of wasm and the creation of web wallets.

**Comment by casey** [comment]
@earthgohan Off topic for this issue! I noticed you opened an issue, which is great, but try not to comment on unrelated issues: #1621

**Comment by casey** [comment]
@btcviking expressed an interest in packaging this for homebrew. I know him afk, and it would be great if someone we knew and trusted were managing such a popular package.

**Comment by casey** [comment]
I think this is best left up to individual contributors, and not done by the project.
