### ISSUE TITLE
Documentation on manual index.redb upgrade 

### ISSUE THREAD

**Issue by ygtdmn** [ordinals/ord#1623]
I recently got a copy of index.redb but I get this error:
`error: Manual upgrade required. Expected file format version 109, but file is version 107`

I looked everywhere but there is no information on how to do a manual upgrade.  It would be great to have it somewhere.

**Comment by JLMoriart** [comment]
I got the same error after switching from the pre-built .exe to compiling from source.

@UnioDex, what/where is index.redb? Are you sure that's the file it's talking about?

**Comment by UnioDex** [comment]
> I got the same error after switching from the pre-built .exe to compiling from source.
> 
> @UnioDex, what/where is index.redb? Are you sure that's the file it's talking about?

somewhere in the %APPDATA% if you're on Windows I don't actually remember. Search for index.redb in app data roaming and local folder and delete it to index it from the beginning. If you don't want to index all from scratch go back to an older version.

**Comment by cmdallas** [comment]
For anyone looking at this on Linux.
In my case, I built a new unstable version of `ord` and started receiving `error: Manual upgrade required. Expected file format version 109, but file is version 107`. I just backed up the old `index.redb` and let `ord` re-index.

```
# Backup index.redb
sudo mv /root/.local/share/ord/index.redb /root/.local/share/ord/index.redb.bak
```

If for some reason the file is in a different location, use the following command to locate it:

```
sudo find /* -type f -name "index.redb"
```

**Comment by ittechguruuu** [comment]
haha! It's like nightmare!

First I don't want to spent 3 days of my life to wait index again and download https://github.com/casey/ord/issues/1701#issuecomment-1429420873 

Then got error and fix it https://github.com/casey/ord/issues/1710  via upgrade 0.4.2 -> 0.5.0 

And now I got an error again "manual index.redb upgrade" - and now 3 day more? Oh my god! @casey save us!

**Comment by bnonni** [comment]
@cmdallas do you know where `index.redb` is on Mac by default? I did run the `find` command you suggested, but I'm not sure I fully trust the results. For context, my laptop crashed overnight during the ord wallet sync, and based on the traceback, I think it was a RAM issue. Now, I'm worried that the paths from the `find` command of the locations of `index.redb`, while valid, are cached locations and not the original file, so I'd like to know the default storage location.

**Comment by bnonni** [comment]
@ittechguruuu I feel your pain right now. I am in the same board 😭

**Comment by dozer-eth** [comment]
@bnonni ran into this on a mac as well.  for me it was installed at `/Users/<your username>/Library/Application\ Support/ord/index.redb`.  deleting that worked (ord then reindexed everything).
