### ISSUE TITLE
install: error: Could not determine target from output of `uname -m`-`uname -s`

### ISSUE THREAD

**Issue by random9brat** [ordinals/ord#1628]
So basically the name in the title...

root@ubuntu:/ssd/ordinals# curl --proto '=https' --tlsv1.2 -fsLS https://ordinals.com/install.sh | bash -s
install: error: Could not determine target from output of `uname -m`-`uname -s`, please use `--target`: armv7l-Linux

Also if I try to download it directly from:

git clone http://github.com/casey/ord
cd ord/
cargo build

It says that I need to update some rustc from 1.61 to 1.65 which is not a rust package at all from what I understand navigating and installing...

Any help would be appreciated ;) tnx

**Comment by random9brat** [comment]
I installed directly with the cargo build command (updated rustc to 1.67 somehow) but I still cant find ord commands with ord --version or ord wallet create...

**Comment by vinniejames** [comment]
Similar trouble here installing on Umbrel

```
umbrel@umbrel:~ $ curl --proto '=https' --tlsv1.2 -fsLS https://ordinals.com/install.sh | bash -s
install: error: Could not determine target from output of `uname -m`-`uname -s`, please use `--target`: aarch64-Linux
```

**Comment by bnonni** [comment]
Same problem over here. Helping a friend install ord on myNode setup running aarch64-Linux, but it appears there is not a release for that cpu arch. @vinniejames we tried installing the [aarch64-apple-darwin version](https://github.com/casey/ord/releases/download/0.4.2/ord-0.4.2-aarch64-apple-darwin.tar.gz) too, but no luck. We are currently trying to build from source similar to @random9brat, will update.

**Comment by vinniejames** [comment]
@bnonni I was able to compile it from source to get it running. git pull the repo then run the build commands, once it's done add the new output folder to your $PATH

**Comment by bnonni** [comment]
@vinniejames thank you!

We ended up installing from source like you're mentioning, and then updated path to include the build. Didn't throw the --release flag on cargo build, so it built to target/debug, but adding `/home/user/ord/target/debug/` to path worked!

For others:
1. git clone [http://github.com/casey/ord](https://github.com/casey/ord)
2. cd ord/
3. cargo build --release
4. export PATH=/path/to/ord/target/release:$PATH

Then try running `ord --help`

**Comment by random9brat** [comment]
I tried to insert path script (4. step) but still doesnt work. I did it within ord/target/release dir

**Comment by bnonni** [comment]
@random9brat can you send what you ran exactly? Did you replace `/path/to/` with the actual path to the `ord/target/release` folder? E.g. in our setup, the exact path to the `ord/target/release` was: `/home/admin/ord/target/release`.

You also may need to add number 4 to your shell profile. Something like ... 

```
echo 'export PATH=/home/admin/ord/target/debug:$PATH' >> ~/.bash_profile
source ~/.bash_profile
ord -v
```
