### ISSUE TITLE
Create a guide that shows users how to run ord on a server

### ISSUE THREAD

**Issue by casey** [ordinals/ord#1635]
Just set up some friends with their own ord instance (going to be sick when it gets announced) and getting them set up with our host for ordinals.com, was super easy. I think we should make it a priority to document how to do this, since it's very easy to pay $50 a month to some host and do it that way.

I helped them build from source w/our deploy script, but that's because they want to run a public instance. For normal users, they can just run a script as root on an box with apt, and they can get set up in one command.

**Comment by jcarv79** [comment]
A step by step guide?

**Comment by raphjaph** [comment]
#1655
