### ISSUE TITLE
Indexing does nothing?

### ISSUE THREAD

**Issue by futuremihai** [ordinals/ord#1661]
I used the inscribe command a few days ago when my indexing started.

Got to around 550K or so out of 775K blocks.

Today I figured I would reboot the instance.

![image](https://user-images.githubusercontent.com/51002703/218231903-68284137-a959-4bfb-8a81-d5a353655de1.png)

When I use the same command, the slider bar doesn't appear and it seems nothing is happening, the program is stuck?

Edit: I am checking the system monitor and it never goes above 1% CPU usage.

Edit 2: 
![image](https://user-images.githubusercontent.com/51002703/218233382-9fa068e6-4f07-4683-9e6b-92a9ee38ae94.png)
I just renamed my original index to index2, and now it's indexing from scratch again... what could cause that and how do I fix it? Was my index (now index2) corrupted or something?

After changing the original file back to index.redb it no longer works, again.

**Comment by wujcwujcwujc** [comment]
Hello, I just solved this problem, you can specify --data-dir, u can start it。
but it too slow

**Comment by wujcwujcwujc** [comment]
or 
1、ps 
2、kill - 9 （ord ）

**Comment by Psifour** [comment]
To continue indexing it is best to call `ord index`

In my testing I have found that doing this anytime I am unsure has avoided almost all errors that other's have reported with their index(ing/s)

**Comment by pavillag** [comment]
Is it ok if I don't see the progress bar? 
![image](https://user-images.githubusercontent.com/30845498/219057832-92a07e63-c9f6-4d29-8ec1-450d210e97e4.png)
