### ISSUE TITLE
JSON-RPC error: transport error: unexpected HTTP code: 404

### ISSUE THREAD

**Issue by Shimizu96** [ordinals/ord#1675]
Hello, so I'm running a full node with those settings in bitcoin.conf located in .bitcoin folder. OS is Ubuntu

`txindex=1
server=1
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
rpcport=8332
rest=1
maxmempol=900`

Issue is that when i do 

ord index

I get

`error: JSON-RPC error: transport error: unexpected HTTP cpde: 404`

I must say that i did run the command

`ord --rpc-url 127.0.0.1:8332`

trying to figure out a solution.
Yet, the issue was still there without running the --rpc-URL command and using this bitcoin.conf file:

`txindex=1
server=1
rest=1`

Help would be greatly appreciated

**Comment by kaspar-nl** [comment]
Did you already confirm with `bitcoin-cli` that you node is synced and working?

**Comment by andrewtoth** [comment]
Make sure txindex is synced. Run `bitcoin-cli getindexinfo`.

**Comment by krishnadude98** [comment]
> Make sure txindex is synced. Run `bitcoin-cli getindexinfo`.

{
}


i am getting this output while calling it how to solve this

**Comment by andrewtoth** [comment]
@krishnadude98 add `txindex=1` to your bitcoin.conf file and restart Bitcoin Core or start it with `-txindex` option.
