### ISSUE TITLE
> seeing similar behavior on AWS hosted windows machine. was smooth sailing until block 335,000. after that getting the below error consistently every 5000 blocks

### ISSUE THREAD

**Issue by BitcoinDickbutts** [ordinals/ord#1678]
> seeing similar behavior on AWS hosted windows machine. was smooth sailing until block 335,000. after that getting the below error consistently every 5000 blocks
> 
> `[2023-02-07T06:04:59Z ERROR ord::index::updater] failed to fetch block 400033, retrying in 2s: JSON-RPC error: transport error: Couldn't connect to host: An established connection was aborted by the software in your host machine. (os error 10053)`
> 
> ![image](https://user-images.githubusercontent.com/42014195/217163292-633df5b6-69fa-468a-b5e4-86c4d256c552.png)

Index still running 13 hours later with the same behavior (error every 5000 blocks) on the ☝🏾 system.

I started this process on a locally hosted machine and got the error much earlier (block 29400, block 122629, block 129636). No discernible pattern on when the error is occurring on this system. Hope it helps!

_Originally posted by @skyrover7 in https://github.com/casey/ord/issues/813#issuecomment-1421368429_

**Comment by andrewtoth** [comment]
See #1648.
