### ISSUE TITLE
Require bitcoin 24 for everything

### ISSUE THREAD

**Issue by casey** [ordinals/ord#1686]
I think this might make it simpler, not sure, open to discussion.

**Comment by gnoblin** [comment]
why would this make it simpler? thanks

**Comment by raphjaph** [comment]
makes codebase simpler

**Comment by andrewtoth** [comment]
Which config options or rpc commands introduced in 24 does ord make use of?

**Comment by casey** [comment]
> Which config options or rpc commands introduced in 24 does ord make use of?

Good question!

rawtr descriptiors, for backing up the reveal transaction's pre-tweaked taproot key. (Pre-tweaked with the reveal transactions tapscript.)

**Comment by friedger** [comment]
This is bad for Bitcoin Knots users (currently, only bitcoin 23)

**Comment by jtraub91** [comment]
This seems non-ideal, since it forces users to upgrade their node in order to use `ord`

**Comment by raphjaph** [comment]
Our wallet uses specific taproot and descriptor wallet features that only 24 and up support. You can still run the explorer with a lower version but no wallet commands.
