### ISSUE TITLE
Create Viewer for glbs

### ISSUE THREAD

**Issue by BLE77** [ordinals/ord#1707]
So inscribing GLBs WORKS just need front end to be fixed to be able to view it now? https://ordinals.com/inscription/2ab9c03109114de3b27a277392a082f39df718937170fa52a6a68c0a5ef7c078i0 this is proof of inscription

**Comment by casey** [comment]
Correct! First order of business for creating a glb viewer: come up with a convention for the camera. Does the gltf format define a "main" camera that we can use to position the viewer camera?

Going to the source spec is always best: https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#glb-file-format-specification

**Comment by BLE77** [comment]
So I propose we use https://modelviewer.dev/ as the viewer. The Glbs themselves are just the 3D data and the viewer just places the model in the middle. Here's an example of model viewer 
https://formfunction.xyz/@os_whs/68Rwi7UTa6BL2XSdBjTGc2pp6oYQMk2HuZQ41hz5awzD?width=1080&height=1080

**Comment by casey** [comment]
I don't want to have to think about dependencies yet, please see my question about main camera above. I want to understand the format we're trying to support, rather than grabbing a large, hard to understand dependency that might be making weird choices.

**Comment by BLE77** [comment]
So glb itself wont define a camera. It just stores "(geometry, key frames, skins), and images" data. Also im not a giga brain like yall I just mess with code until it works so sorry if im not much help.

**Comment by BLE77** [comment]
There's another viewer that's open source called three.js btw could be more your ethos

**Comment by casey** [comment]
Done in #2369.
