### ISSUE TITLE
Ord Wallet Restore - Error on 'budget'

### ISSUE THREAD

**Issue by Prestonsr** [ordinals/ord#1709]
Hey,

Running Ord Version 0.5

Command

./bin/ord wallet restore <Mnemonic>

returns an error: Found argument 'budget' which wasn't expected, or isn't valid in this context

I checked on the BIP39 wordlist and on Sparrow, 'budget' is correct.

~PR

![Screenshot 2023-02-12 115052](https://user-images.githubusercontent.com/85415429/218333646-afaed05f-a340-46ca-b23b-0ea6e174ae6b.jpg)

**Comment by Psifour** [comment]
Wrap the mnemonic in quotes. We should maybe consider a more detailed error message for this case.

**Comment by casey** [comment]
> Wrap the mnemonic in quotes. We should maybe consider a more detailed error message for this case.

Great idea! Should we add a dummy trailing varargs, and if that isn't empty, throw an error?

**Comment by mmigli** [comment]
any testing or update on the above issue? I also cannot restore my wallet and I tried wrapping my seed phrase in quotes. It gives the "error: Found argument 'second' which wasn't expected, or isn't valid in this context" for the second word in the seed phrase/mnemonic.

**Comment by Prestonsr** [comment]
Thanks for the info everyone.

mmicli I have not gone back to test the quotes yet. Will check after I'm done indexing...
