### ISSUE TITLE
testnet.ordinals.com is out of sync

### ISSUE THREAD

**Issue by earthflower** [ordinals/ord#1727]
The testnet at https://testnet.ordinals.com/ is currently out of sync. The last block indexed in the testnet is block 2417545 with a timestamp of 2023-01-23 14:12:26 UTC.

It would be great to have the testnet running smoothly again.

**Comment by Sirgulator** [comment]
I think it is actually completely stuck? Has not moved a bit in days.

**Comment by qalqi** [comment]
Yep! Looks stuck
Tesnet shall be good
