### ISSUE TITLE
AssumeIndex

### ISSUE THREAD

**Issue by Kodylow** [ordinals/ord#1728]
Similar to AssumeUTXO, one way to speed up indexing is to allow the user to download a snapshot of the ordinal index at a specific blockheight and begin validating/updating from there. 

This has significant differences and security tradeoffs vs building the index from source that merit debate/discussion, post any thoughts you have on the topic in this issue.

**Comment by 77yaldash** [comment]
Duplicate of #

**Comment by andrewtoth** [comment]
@Kodylow can you try my speedup branch? https://github.com/casey/ord/issues/1648#issuecomment-1426565987. Myself and several testers have been able to sync in an hour or two. I don't think it's necessary to pursue some kind of snapshot feature for the normal sync.

For --index-sats maybe...

**Comment by Kodylow** [comment]
On it
