### ISSUE TITLE
thread 'main' panicked at 'attempt to subtract with overflow'

### ISSUE THREAD

**Issue by dooglus** [ordinals/ord#1729]
I have a single cardinal utxo and no ordinals. I attempt to inscribe on the 1000th sat of the utxo and get a panic:

    $ ord --version
    ord 0.5.0
    16:00:14 me@hair:~/Programs/ord$ ord wallet inscriptions
    []
    $ ord wallet outputs
    [
      {
        "output": "e9df4cefd24bed2c75d2d5c00a35af7bc82886675da7d8ae2d00ea71b258fb9d:0",
        "amount": 1000000
      }
    ]
    $ RUST_BACKTRACE=1 ord wallet inscribe --satpoint e9df4cefd24bed2c75d2d5c00a35af7bc82886675da7d8ae2d00ea71b258fb9d:0:1000 /tmp/ord/1.txt
    thread 'main' panicked at 'attempt to subtract with overflow', src/subcommand/wallet/inscribe.rs:132:5
    stack backtrace:
       0: rust_begin_unwind
                 at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
       1: core::panicking::panic_fmt
                 at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
       2: core::panicking::panic
                 at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:111:5
       3: ord::subcommand::wallet::inscribe::Inscribe::calculate_fee
                 at ./src/subcommand/wallet/inscribe.rs:132:5
       4: ord::subcommand::wallet::inscribe::Inscribe::run
                 at ./src/subcommand/wallet/inscribe.rs:94:58
       5: ord::subcommand::wallet::Wallet::run
                 at ./src/subcommand/wallet.rs:58:35
       6: ord::subcommand::Subcommand::run
                 at ./src/subcommand.rs:69:31
       7: ord::arguments::Arguments::run
                 at ./src/arguments.rs:14:5
       8: ord::main
                 at ./src/lib.rs:162:21
       9: ord::main
                 at ./src/bin/main.rs:2:3
      10: core::ops::function::FnOnce::call_once
                 at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/ops/function.rs:507:5
    note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
    $ 

I'm using --regtest if that matters.

**Comment by dooglus** [comment]
I tried a bunch of offsets into the utxo. Anything I tried from :1000 to :9999 panicked, but :10000 was ok. That sounnds like the target postage size.

So I tried changing `TARGET_POSTAGE` in `src/subcommand/wallet/transaction_builder.rs` to 2345 from 10000 and found that now the panic only happens up to sat offsets of 2344:

    $ ord wallet inscribe --dry-run --satpoint e40d8d162242489a11c1ff3588dc2f958b705255d21ac3f1cb2970d976f802ad:2:2344 /tmp/ord/1.txt
    thread 'main' panicked at 'attempt to subtract with overflow', src/subcommand/wallet/inscribe.rs:132:5
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    $ ord wallet inscribe --dry-run --satpoint e40d8d162242489a11c1ff3588dc2f958b705255d21ac3f1cb2970d976f802ad:2:2345 /tmp/ord/1.txt
    {
      "commit": "f13634f362c990f388a2e174752778df629e1e4c531a0b5b654202b9eda0165b",
      "inscription": "8c0113219d5574998e6d93ada5f35d53ce6e8015c0d3decb84676a325a9cf42ei0",
      "reveal": "8c0113219d5574998e6d93ada5f35d53ce6e8015c0d3decb84676a325a9cf42e",
      "fees": 197
    }
    $

**Comment by pokrovskyy** [comment]
Seems like postage goes first so you can't inscribe before the postage. Need to look into the code to confirm
