### ISSUE TITLE
index Kill erro

### ISSUE THREAD

**Issue by wujcwujcwujc** [ordinals/ord#1733]
![image](https://user-images.githubusercontent.com/105530519/218681056-d2fb3a1f-bc09-46bf-a600-fc1e932223bc.png)
When I killed ord, it did nothing when I started it again, the cursor kept flashing, and occupied the process, and nothing was displayed in the foreground。

**Comment by raphjaph** [comment]
If you killed (non-graceful shutdown) `ord` while it was indexing then the database might be corrupted/in an invalid state. You will have to delete `index.redb` and restart.
