### ISSUE TITLE
ordinals.com links/redirects

### ISSUE THREAD

**Issue by casey** [ordinals/ord#1734]
Allow adding short redirect links in a config file

**Comment by Dhananjay-12** [comment]
hi @casey , can I try this. I'm new actually.

**Comment by raphjaph** [comment]
Feel free to open a PR!

**Comment by casey** [comment]
I think we haven't nailed down the design yet, lat's wait to do that.

**Comment by hustlaaa** [comment]
Happy to help out here

**Comment by nammaki** [comment]
Looks like there are people wanting to help out with this...
