### ISSUE TITLE
os error 10060

### ISSUE THREAD

**Issue by Plexzy** [ordinals/ord#1745]
I have my bitcoin core node running completely fine and at the latest block. I am trying to inscribe but it will not let me and it shows me this error:

error: JSON-RPC error: transport error: Couldn't connect to host: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)

OR 

error: Failed to send commit transaction
because: JSON-RPC error: RPC error response: RpcError { code: -26, message: "non-mandatory-script-verify-flag (Witness program was passed an empty witness)", data: None }

I successfully inscribed 5 images yesterday with 5 utxos back-to-back. However now that I have 100 utxos loaded up to incribe, I keep getting these errors in ord. It shows me error 10060 at times when doing wallet balance, but a retry fixes it, however this is not the case for inscribing.

The command I am running is ord --bitcoin-data-dir <bitcoinfolderpath> --cookie-file <cookiefilepath> wallet inscribe --fee-rate <fee> <filepath>

My config file contains these:

txindex=1
rest=1
server=1
rpcallowip=127.0.0.1
rpcport=8332

(also tried without rpcport and rpcallowip and still the same issue)

My bitcoind launch command is just a datadir to the bitcoin folder.

I have tried NUMEROUS fixes such as editing my config, restarting bitcoind, restarting pc, etc. None were effective. I would really appreciate some help. Thanks.

**Comment by Psifour** [comment]
To help debug, remove these two lines from bitcoin.conf and restart your bitcoind
`rpcallowip=127.0.0.1
rpcport=8332`

Also, I thought `--fee-rate` went before the sub-command `inscribe`

If that still fails please provide any relevant error logs.

**Comment by Plexzy** [comment]
> 
Removed both and restarted. Tried putting fee rate before inscribe but it is an invalid command, so it does go after. 

Got this error now.

error: Failed to send commit transaction
because: JSON-RPC error: RPC error response: RpcError { code: -26, message: "non-mandatory-script-verify-flag (Witness program was passed an empty witness)", data: None }


The error above is one that I have been getting as well. So I either get error 10060 or the one I just stated above.

**Comment by belovie** [comment]
i have this too. have had it for weeks. tried a long list of things, none of which worked. I even bought an external ssd and redownloaded the bitcoin core node and the ord wallet again. still happens.

**Comment by hao168** [comment]
我也是这个错误，有人解决了吗

**Comment by huguojunsy** [comment]
Me too.

**Comment by ImCitizen13** [comment]
Any solution for this "Bug", I'm having the same issue
