### ISSUE TITLE
Wallet Balance cmd error

### ISSUE THREAD

**Issue by tdw1221** [ordinals/ord#1749]
Hi, I set up the wallet and most of its functions (create, receive address, etc.) seem to work fine except that I am getting an error check time running ``cargo run wallet balance``

Has any one run into similar issues ?

``
$ cargo run wallet balance
    Finished dev [unoptimized + debuginfo] target(s) in 4.46s
     Running `target/debug/ord wallet balance`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TryFromIntError(())', /home/admin/.cargo/registry/src/github.com-1285ae84e5963aae/redb-0.12.1/src/tree_store/page_store/mmap/unix.rs:14:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
``

**Comment by tweili** [comment]
My guess: your computer is running a 32bit version. check https://github.com/cberner/redb/issues/471

**Comment by tdw1221** [comment]
> 

In deed you are right, thanks for letting me know. So it seems there's no easier fix than completely revamp my node's OS to a 64bit one?
