### ISSUE TITLE
Feature Request: API - lookup inscription by inscription number

### ISSUE THREAD

**Issue by dannydeezy** [ordinals/ord#1761]
I'd like to easily be able to lookup inscriptions by number, i.e. inscription 1, inscription 2, 3, 4 etc.

**Comment by whoabuddy** [comment]
You can do this through something like [this Ordinals HTTP API](https://ordapi.xyz/), and there are likely more variation coming (Hiro was working on one iirc).

Would that resolve the issue?

**Comment by nammaki** [comment]
This is such an obvious feature 🙏

**Comment by casey** [comment]
This is now possible.
