### ISSUE TITLE
Make `--fee-rate` mandatory for `wallet inscribe`

### ISSUE THREAD

**Issue by veryordinally** [ordinals/ord#1767]
This is open from #1747: We merged  #1755 which made `--fee-rate` mandatory for `wallet send`. For consistency need it for `wallet inscribe` as well.

_Originally posted by @raphjaph in https://github.com/casey/ord/issues/1747#issuecomment-1432203690_

**Comment by kranthicodes** [comment]
Just curious whats the current fee rate by default to inscribe ?

**Comment by veryordinally** [comment]
Solved in #1897
