### ISSUE TITLE
Ord wallet balance

### ISSUE THREAD

**Issue by say-sar** [ordinals/ord#1774]
I am doing the following:
Running bitcoind with commands -txindex -prune=0
I run ord and restore my wallet with 12 secret phrases.
i run this command on ord: 
ord wallet receive and it gives me my address.  
Everything is going good until I enter the command:
ord wallet balance. 
Today I'm running the 0.5.0 version, which gives me a  _ as my result and stays frozen on that. 
Yesterday i was running the 0.4.2 version and it would give me a response of 0 balance. Even though I had funds verified through mempool by copying the first address it would give me.
Both versions 0.4.2 and 0.5.0 gave me the same initial address after restoring my wallet each time.

**Comment by RarePepeMaximalist** [comment]
You may be running into this bug https://github.com/casey/ord/issues/1589

You need to manually trigger a rescan of the wallet to pickup all the historical transactions

Someone wrote this guide which has some details
https://gist.github.com/windsok/5b53a1ced6ef3eddbde260337de28980#importing-into-ord-wallet
