### ISSUE TITLE
Inscriptions not showing vs sparrow

### ISSUE THREAD

**Issue by noggie-noggie** [ordinals/ord#1776]
Hi

My sparrow wallet shows all my inscriptions fine however when I restore the same wallet in ord I get:

F:\Bitcoin\Ord>ord --cookie-file "F:\Bitcoin\DL\.cookie" wallet balance
{
  "cardinal": 10000
}

F:\Bitcoin\Ord>ord --cookie-file "F:\Bitcoin\DL\.cookie" wallet inscriptions
[]

vs sparrow.

![image](https://user-images.githubusercontent.com/113180818/219480456-19f3576c-7160-46c5-9bae-ea6d4f0133b3.png)

Discord suggested I raise an issue here.

**Comment by RarePepeMaximalist** [comment]
You may be running into this bug https://github.com/casey/ord/issues/1589

You need to manually trigger a rescan of the wallet to pickup all the historical transactions

Someone wrote this guide which has some details
https://gist.github.com/windsok/5b53a1ced6ef3eddbde260337de28980#importing-into-ord-wallet

**Comment by noggie-noggie** [comment]
Appreciate the feedback.

i deleted the original ord wallet and retored mine again just incase it was an old wallet. same issue.

i don't want to resync the whole chain again, it took days last time.

i am not sure where to paste this : bitcoin-cli -rpcwallet=ord rescanblockchain 767430 to try it out as my core has no console

**Comment by noggie-noggie** [comment]
I rescanned as suggested from the above block, still no luck

**Comment by noggie-noggie** [comment]
So overview:

Windows 10 64b

Followed: 
https://docs.ordinals.com/guides/inscriptions.html

- I used sparrow wallet to collect inscriptions.
- installed bitcoincore and synced
- installed ord wallet from the above
- followed this video for any issues I didn't understand : https://www.youtube.com/watch?v=rTIoAUIWDaE
- synced ord and retired the same seed phrase as sparrow
- balance showing 0
- I created a new address in ord to send some btc to it to see if it worked
- works and shows that one transaction, no inscription showing

**Comment by RarePepeMaximalist** [comment]
Any chance you're using a passphrase on the wallet with sparrow?

`ord` does not currently support importing wallets with passphrases.

**Comment by noggie-noggie** [comment]
I used my 12 word seed phrase.
I also generated a new address through ord in the same wallet and sent some BTC to it and it registered as a transaction.

seems it's just not showing inscriptions.

I have successfully sent 8 ordinals with sparrow so far but would prefer this.

**Comment by RarePepeMaximalist** [comment]
Are you sure you setup your sparrow wallet with a script type of `Taproot (P2TR)` when you originally set it up? You can check this in the settings tab. Only Taproot wallets can be imported directly into `ord`

**Comment by noggie-noggie** [comment]
sure did :) 

Im guessing im going to have to redo everything and resync as this is an odd issue

![image](https://user-images.githubusercontent.com/113180818/219557113-7a1da402-4ee1-4f5a-8c07-18308d6b8638.png)

**Comment by RarePepeMaximalist** [comment]
Yeah I'm unsure what the issue is here - I have done exactly what you have done and migrated a wallet from sparrow into `ord` successfully. The only catch was needing to do the blockchain rescan.

Can you trigger the rescan while looking at your bitcoin `debug.log` to check that you see logs in there indicating it is rescanning the wallet?

**Comment by noggie-noggie** [comment]
debug log didnt add anylines except from the last time I had the node running

![image](https://user-images.githubusercontent.com/113180818/219560313-6873d47a-3698-4af0-acc7-51ba8a48e74d.png)
