### ISSUE TITLE
Indexing from Dec 2022

### ISSUE THREAD

**Issue by marspoolxyz** [ordinals/ord#1779]
ord is indexing the whole bitcoin blockchain and its about 31 GB takes sometime. 

Do you we need to index from day one of the BTC. Why don't we starts 2022-12-14 20:32:00 UTC
The very first ordinal inscriped. 

Thank you 

Join Now for more details
https://discord.gg/QdDRQjfH

**Comment by andrewtoth** [comment]
Hi @marspoolxyz - this is implemented in https://github.com/casey/ord/pull/1759. If you could help test that would be great!

**Comment by kalibox** [comment]
I have the same question- its a new wallet and I'm ok with indexing from early/mid Dec '22 onwards and not from block 1.

**Comment by kalibox** [comment]
> Hi @marspoolxyz - this is implemented in #1759. If you could help test that would be great!

How can I help test this out?

**Comment by andrewtoth** [comment]
@kalibox 
```
git clone https://github.com/andrewtoth/ord
cd ord
git checkout batch-tx-requests
cargo run --release -- index
```

**Comment by kalibox** [comment]
> @kalibox
> 
> ```
> git clone https://github.com/andrewtoth/ord
> cd ord
> git checkout batch-tx-requests
> cargo run --release -- index
> ```

Thank you!

**Comment by kalibox** [comment]
Do I need to parse any additional switches? Like the first inscription height or anything else? @andrewtoth

**Comment by andrewtoth** [comment]
No, this should be enough to test.
If you already have an index, you can run `cargo run --release -- --index index2.redb index` to test a fresh index at `index2.redb`. But it would also be helpful to see how well it works with an already in progress index.

**Comment by andrewtoth** [comment]
On my linux laptop I can index in 41 minutes. Run with `time cargo run --release -- index` to see how long it takes on your machine.

**Comment by kalibox** [comment]
Running this now, it has made a considerable difference. CPU isn't being hammered either. @andrewtoth

**Comment by kalibox** [comment]
New index file also has a much smaller footprint so far. About 50% of the way in now.

**Comment by kalibox** [comment]
Ok, inexplicably stuck at 767412/777361 now..

**Comment by kalibox** [comment]
Strange
![image](https://user-images.githubusercontent.com/38479785/219962372-d0cc88ca-7f7f-4d31-88a7-b03a0f3a634c.png)

**Comment by andrewtoth** [comment]
That's where it actually starts indexing.

**Comment by andrewtoth** [comment]
You need `txindex=1` in your bitcoind config. Check that it is synced with `bitcoin-cli getindexinfo`. If that just returns `{}` you don't having txindex set.

**Comment by kalibox** [comment]
> That's where it actually starts indexing.

Yeah thought as much but keeps erroring out with that ^^ error message (screenshot in previous message).

**Comment by kalibox** [comment]
txindex=1 has been set since a long time ago and node is fully synced:

```
{
  "txindex": {
    "synced": true,
    "best_block_height": 777362
  }
}

```

**Comment by andrewtoth** [comment]
Does it say anything in your Bitcoin debug.log?

**Comment by andrewtoth** [comment]
What os are you on?

**Comment by andrewtoth** [comment]
Does `bitcoin-cli getrawtransaction <txid>` return that tx?

**Comment by kalibox** [comment]
Nothing out of the ordinary in the btc debug.log but then again I'm only logging coindb. BTC node is Ubuntu 20.04 and ord client on Ubuntu 22.04.

**Comment by kalibox** [comment]
> Does `bitcoin-cli getrawtransaction <txid>` return that tx?

Does this look right to you?
![image](https://user-images.githubusercontent.com/38479785/219962859-4f591bf7-3780-4e16-90d5-431e72c6df00.png)

**Comment by kalibox** [comment]
> Does `bitcoin-cli getrawtransaction <txid>` return that tx?

Does this look right to you?
![image](https://user-images.githubusercontent.com/38479785/219962960-6a681214-9463-41d9-8f6a-f158fcee55bc.png)

**Comment by kalibox** [comment]
Actually, nevermind. Found the problem. The RPC URL needs to be in `http://<ip_address>:<tcp_port>` format. Fixed that and it's now ingesting and indexing blocks. Up to block 767461 now.

**Comment by andrewtoth** [comment]
What format was it before? I think that could be a bug I introduced, thanks for testing!

**Comment by kalibox** [comment]
> What format was it before? I think that could be a bug I introduced, thanks for testing!

Just `ip_address`, if i remember correctly.

**Comment by kalibox** [comment]
Is this going to be merged with @casey's `ord` repo?

**Comment by andrewtoth** [comment]
You can follow along at #1759.

**Comment by kalibox** [comment]
Can I use this db with casey's version, you think?

**Comment by andrewtoth** [comment]
It doesn't change the db, so yes.

**Comment by kalibox** [comment]
> It doesn't change the db, so yes.

Awesome! Thanks for improving user experience @andrewtoth. Much appreciated.

**Comment by andrewtoth** [comment]
@kalibox did you manage to finish syncing? How long did it take?

**Comment by kalibox** [comment]
> @kalibox did you manage to finish syncing? How long did it take?

I was going to say- its taking a while but it might be because I'm on a low-resourced VM.

**Comment by kalibox** [comment]
On 768000/777373 now

**Comment by kalibox** [comment]
But CPU and RAM don't appear to be the bottleneck though..

**Comment by andrewtoth** [comment]
That seems very slow. How many cores do your vms have? This approach benefits a lot from multithreading.

**Comment by andrewtoth** [comment]
@kalibox what version of bitcoind are you using? V22 and before will be much slower to fetch transactions. If you are running from a popular image distro, I know some are several versions behind.

**Comment by kalibox** [comment]
> @kalibox what version of bitcoind are you using? V22 and before will be much slower to fetch transactions. If you are running from a popular image distro, I know some are several versions behind.

I'm running the latest version v0.24.0.1 but I suspect the slowness is because of the VM ord is running on.

**Comment by kalibox** [comment]
Any ideas why it throws this from time to time:

`Resource temporarily unavailable (os error 11)`

Restarting the process kicks it back into life but I've seen it happen a couple times.

**Comment by andrewtoth** [comment]
No, can you describe your setup in more detail? What machines are bitcoind and Ord installed on? How are they connected?

**Comment by kalibox** [comment]
> No, can you describe your setup in more detail? What machines are bitcoind and Ord installed on? How are they connected?

bitcoind runs a on a Ubuntu 20.04.5 LTS VM. CoreLightning node + ord client sit on a separate Ubuntu 20.04.5 LTS VM.

**Comment by andrewtoth** [comment]
They are running in a cloud provider? How much ram + cpu are they allocated?

**Comment by kalibox** [comment]
> They are running in a cloud provider? How much ram + cpu are they allocated?

btc node has a isci disk attached to (1TB) which serves as the main data directory for the blockchain. It has 4x vCPUs and 8GB RAM allocated; the CL/ord node has 2x vCPUs and 2GB RAM.

**Comment by kalibox** [comment]
> They are running in a cloud provider? How much ram + cpu are they allocated? I will try and replicate as close as possible.

Negative, I have a serverfarm at home. Its all local to my home network.

**Comment by andrewtoth** [comment]
I would guess it would sync faster from giving it more vcpu.

**Comment by kalibox** [comment]
> I would guess it would sync faster from giving it more vcpu. But the error I'm not sure. Will investigate.

I'll give it a couple more and see if that helps. Thanks for the suggestion.

**Comment by kalibox** [comment]
> I would guess it would sync faster from giving it more vcpu. But the error I'm not sure. Will investigate.

Looking at `top`, the vcpu doesn't look its being stressed tho.

**Comment by s3ton** [comment]
Hello people, I'm also experiencing a very long time for the wallet to index the blocks. My setup is not the fastest to be honest. What can I do to speed it up?
What are the folders that are used the most in the process?
the folder where I store the blocks is on a HDD while the chainstate and indexes folders are on an SSD

**Comment by kalibox** [comment]
> I would guess it would sync faster from giving it more vcpu. But the error I'm not sure. Will investigate.

Fully synced to the node now. Wallet has been setup. Going to test sending funds to it and inscribing before I develop more confidence in holding ordinals of any value. Thank you once again for all the help @andrewtoth.

**Comment by kalibox** [comment]
> Hello people, I'm also experiencing a very long time for the wallet to index the blocks. My setup is not the fastest to be honest. What can I do to speed it up? What are the folders that are used the most in the process? the folder where I store the blocks is on a HDD while the chainstate and indexes folders are on an SSD

All I can say is follow what we've done in this thread and you should be up and running in no (well.. some) time.

**Comment by kalibox** [comment]
Also, it looks like #1759 has been merged with the main branch now. ggs @andrewtoth

**Comment by s3ton** [comment]
> Also, it looks like #1759 has been merged with the main branch now. ggs @andrewtoth

So I guess I have to stop the current indexing by killing it, then I should rebuild from source, and then run it again?
Thanks for the help!

**Comment by s3ton** [comment]
The merge of #1759 helped because it skipper all the blocks until the latest ones.
It’s still incredibly slow though, is it because I’m running it on a HDD ?
Just to give you an idea I left it running for 8 hours and it’s still indexing at block 770500.
Sometimes it takes almost 1 minute for 1 block.

Syncing the blockchain with txindex felt faster 😅

**Comment by s3ton** [comment]
UPDATE: this is pretty bad. I stopped the syncing and now that I restarted it it resumed back from 767000 or something like that instead of block 770500 where I stopped it
Pinging @andrewtoth cause they might want to know about this test I just did

**Comment by andrewtoth** [comment]
@s3ton yeah using an HDD will be much slower. Hmm how did you stop the indexing? If you didn't let it shutdown on its own it will lose the progress for the last 5000 or so blocks.
This seems normal to me. Use an SSD if you want it to sync faster.

**Comment by s3ton** [comment]
> @s3ton yeah using an HDD will be much slower. Hmm how did you stop the indexing? If you didn't let it shutdown on its own it will lose the progress for the last 5000 or so blocks.
> This seems normal to me. Use an SSD if you want it to sync faster.

I stopped it by using bitcoincli stop.
Was there 💐a better way? 😅

**Comment by andrewtoth** [comment]
Yeah ctrl-c in the ord terminal. If bitcoind shuts down from under it ord won't commit the uncommitted blocks. Hmm maybe there's a way we can have it commit anyways if that happens.

**Comment by kalibox** [comment]
Yeah SSD is the way to go. I'll need to look at upgrade options as well as my NAS (also isci host) run spinneys in RAID. I was able to sync ok albeit slowly but my workaround is I've created a cron task to kick in in the background and index every 30mins. This way, when I need `ord` to be operationally ready, it will be.

**Comment by s3ton** [comment]
>I was able to sync ok albeit slowly but my workaround is I've created a cron task to kick in in the background and index every 30mins. This way, when I need `ord` to be operationally ready, it will be.

Is it really the only option to set up a cron task to have ord always up to date?
I don’t mind but it doesn’t look like the most elegant solution.

**Comment by soenkehahn** [comment]
> Is it really the only option to set up a cron task to have ord always up to date? I don’t mind and I’ve done the same for now, but it doesn’t look like the most elegant solution.

@s3ton: `ord server` is meant to run the ord explorer (the website). But it _also_ keeps the index in sync, I think. So you could run e.g. `ord server --http-port 8080` instead of the cron job.
