### ISSUE TITLE
Running ord wallet inscribe FILE is abnormal

### ISSUE THREAD

**Issue by lins575757** [ordinals/ord#1780]
`thread 'main' panicked at 'assertion failed: order <= self.get_max_order()', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\redb-0.13.0\src\tree_store\page_store\buddy_allocator.rs:367:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\redb-0.13.0\src\tree_store\page_store\page_manager.rs:1420:43
stack backtrace:
   0:     0x7ff6f50e0a52 - <unknown>
   1:     0x7ff6f51047fb - <unknown>
   2:     0x7ff6f50d82ea - <unknown>
   3:     0x7ff6f50e079b - <unknown>
   4:     0x7ff6f50e33a9 - <unknown>
   5:     0x7ff6f50e302b - <unknown>
   6:     0x7ff6f50e3c41 - <unknown>
   7:     0x7ff6f50e39ce - <unknown>
   8:     0x7ff6f50e174f - <unknown>
   9:     0x7ff6f50e3680 - <unknown>
  10:     0x7ff6f514b8a5 - <unknown>
  11:     0x7ff6f514bda6 - <unknown>
  12:     0x7ff6f4f17d2c - <unknown>
  13:     0x7ff6f4f26b10 - <unknown>
  14:     0x7ff6f4f2856e - <unknown>
  15:     0x7ffa0ecc1030 - <unknown>
  16:     0x7ffa0ecc4ede - is_exception_typeof
  17:     0x7ffa0eccf3d0 - _C_specific_handler
  18:     0x7ffa0ecc414c - is_exception_typeof
  19:     0x7ffa0eccfd11 - _CxxFrameHandler3
  20:     0x7ffa28fc8b9f - _chkstk
  21:     0x7ffa28f58b63 - RtlUnwindEx
  22:     0x7ffa0eccf89e - _C_specific_handler
  23:     0x7ffa0ecc2e05 - is_exception_typeof
  24:     0x7ffa0ecc3224 - is_exception_typeof
  25:     0x7ffa0ecc4248 - is_exception_typeof
  26:     0x7ffa0eccfd11 - _CxxFrameHandler3
  27:     0x7ffa28fc8b1f - _chkstk
  28:     0x7ffa28f55b9a - RtlRestoreContext
  29:     0x7ffa28f52e63 - RtlRaiseException
  30:     0x7ffa266e40ac - RaiseException
  31:     0x7ffa0ecc66c0 - CxxThrowException
  32:     0x7ff6f50f3858 - <unknown>
  33:     0x7ff6f50e3eab - <unknown>
  34:     0x7ff6f50e3c97 - <unknown>
  35:     0x7ff6f50e398b - <unknown>
  36:     0x7ff6f50e174f - <unknown>
  37:     0x7ff6f50e3680 - <unknown>
  38:     0x7ff6f514b8a5 - <unknown>
  39:     0x7ff6f514b99c - <unknown>
  40:     0x7ff6f4f1cb7e - <unknown>
  41:     0x7ff6f4f1ca93 - <unknown>
  42:     0x7ff6f4f1ca93 - <unknown>
  43:     0x7ff6f4f1ca93 - <unknown>
  44:     0x7ff6f4f1ca93 - <unknown>
  45:     0x7ff6f4f1ca93 - <unknown>
  46:     0x7ff6f4f1ca93 - <unknown>
  47:     0x7ff6f4f1ca93 - <unknown>
  48:     0x7ff6f4f1ca93 - <unknown>
  49:     0x7ff6f4f1ca93 - <unknown>
  50:     0x7ff6f4f1ca93 - <unknown>
  51:     0x7ff6f4f1ca93 - <unknown>
  52:     0x7ff6f4f1ca93 - <unknown>
  53:     0x7ff6f4f1ca93 - <unknown>
  54:     0x7ff6f4f1ca93 - <unknown>
  55:     0x7ff6f4f1ca93 - <unknown>
  56:     0x7ff6f4f1ca93 - <unknown>
  57:     0x7ff6f4f1ca93 - <unknown>
  58:     0x7ff6f4f1ca93 - <unknown>
  59:     0x7ff6f4f1ca93 - <unknown>
  60:     0x7ff6f4f1ca93 - <unknown>
  61:     0x7ff6f4f1ca93 - <unknown>
  62:     0x7ff6f4f126b9 - <unknown>
  63:     0x7ff6f4f27b3d - <unknown>
  64:     0x7ff6f4b34e0c - <unknown>
  65:     0x7ff6f4b91876 - <unknown>
  66:     0x7ff6f4aeb4e4 - <unknown>
  67:     0x7ff6f4c3b198 - <unknown>
  68:     0x7ff6f4ca92da - <unknown>
  69:     0x7ff6f494715b - <unknown>
  70:     0x7ff6f4901036 - <unknown>
  71:     0x7ff6f490100c - <unknown>
  72:     0x7ff6f50d051e - <unknown>
  73:     0x7ff6f490107c - <unknown>
  74:     0x7ff6f512a084 - <unknown>
  75:     0x7ffa273455a0 - BaseThreadInitThunk
  76:     0x7ffa28f2485b - RtlUserThreadStart
thread panicked while panicking. aborting.`

**Comment by bnonni** [comment]
Second this issue. Just got this error this morning after trying to sync the stupid ord wallet for 3 days. Crashed my computer and now I can't run ord 😢.

**Comment by lins575757** [comment]
> Second this issue. Just got this error this morning, however, I ran `wallet balance` and this got thrown, not inscribe. This error comes after trying to sync the stupid ord wallet for 3 days. Crashed my computer and now I can't run ord 😢.

I solved it. need to delete the index file to rebuild the index, but it is really big, about 32GB. You can use the version before ord, and the index file will be much smaller.

**Comment by bnonni** [comment]
Nevermind ... sigh 😞 

> but once a lock is poisoned then all future acquisitions will return this error.

**Comment by bnonni** [comment]
For reference, I'm running ord 0.4.2 and I had to simply rename the index.redb file and rerun `ord index` to start from the beginning. Could not find a solution to the original PoisonError.
