### ISSUE TITLE
Flaky tests

### ISSUE THREAD

**Issue by casey** [ordinals/ord#1787]
We have some flaky tests that fail randomly. This is important to fix because otherwise our edit/test/debug loop gets slow. We want that to always stay fast for a good dev experience.

We need to:

1. Figure out exactly which tests are flaky
2. Figure out why they're flaky
3. Come up with an idea for how to fix them
4. Fix them!

**Comment by vollumc** [comment]
5. Profit!

**Comment by terror** [comment]
n.b. This might have to do with axum leaking open file descriptors, or not closing them quickly enough.
