### ISSUE TITLE
ord wallet balance issue

### ISSUE THREAD

**Issue by partnercloudsupport** [ordinals/ord#1796]
Hi...While doing the ord wallet balance it hung at 350000. I closed the terminal...tried to run the command again and now it is waiting to issue the command. Any guidance on if the indexing for balance hangs again? Thanks everyone!

**Comment by GaloisField2718** [comment]
Hi. I tried to reboot my machine and now it's pretty good but still really long. It was shorter to download Bitcoin chain than to index...

**Comment by GaloisField2718** [comment]
I think there are files where we can optimise calling indexing blocks. Maybe into this src/subcommand/wallet/balance.rs

**Comment by partnercloudsupport** [comment]
@GaloisField2718  thanks for the feedback. Will try!

**Comment by GaloisField2718** [comment]
And I suppose do you see this https://github.com/casey/ord/discussions/1791#discussion-4871670.

You download the git-branch of andrewtoth and run `cargo run wallet balance`. 
If you don't run `wallet balance` it will open `ord` help

**Comment by Magicking** [comment]
Hey are you still experimenting the issue with the latest release @partnercloudsupport ?
