### ISSUE TITLE
How to update ord?

### ISSUE THREAD

**Issue by DanielHook15** [ordinals/ord#1816]
I have installed version 0.5.0 by building it from source as follows:

git clone https://github.com/casey/ord.git
cd ord
cargo build --release

What is the correct way to update it to the newest version of ord?

**Comment by dude513** [comment]
@DanielHook15 `git pull` to "pull" latest commits and build again with `cargo build --release`.

**Comment by DanielHook15** [comment]
Thank you for the fast help! This means in total to run the following lines?

git pull https://github.com/casey/ord.git
cd ord
cargo build --release

**Comment by dude513** [comment]
> Thank you for the fast help! This means in total to run the following lines?
> 
> git pull https://github.com/casey/ord.git cd ord cargo build --release

```
cd ord
git pull
cargo build --release
```

**Comment by DanielHook15** [comment]
That works, thanks!

**Comment by andrewtoth** [comment]
Just doing a `gut pull` will put you at the latest commit, which could be unstable.

You really want to be on the latest release. To do that run
```
git fetch
git checkout 0.5.1
```

**Comment by DanielHook15** [comment]
Thanks a lot for this important correction!

**Comment by DanielHook15** [comment]
cd ord
git fetch
git checkout 0.5.1
cargo build --release

**Comment by pavillag** [comment]
Thank you for the patience with all the questions. I just can't find an ord directory. Should it be in my /bin directory?

**Comment by andrewtoth** [comment]
First run `git clone https://github.com/casey/ord`.

**Comment by pavillag** [comment]
Thank you! That worked for me! 

For other people that end up looking, this is what I ran:

`git clone https://github.com/casey/ord.git`
`cd ord`
`git checkout 0.5.1`
`cargo build --release`

**Comment by pavillag** [comment]
Ran `cargo build --release` and let it finish. Now after running `ord --version` I still get 0.5. Am I missing something?

**Comment by pavillag** [comment]
Ok figured it out. Here are additional steps:

```
git clone https://github.com/casey/ord.git
cd ord
git checkout 0.5.1
cargo build --release
```
`which ord` This gives you a path 
`cd target/release`
`./ord --version` - Should show version you are trying to install 
`cp ord` + [PATH ABOVE WHEN YOU RAN WHICH ORD]
