### ISSUE TITLE
How to inscribe continuously?

### ISSUE THREAD

**Issue by brucexiu** [ordinals/ord#1845]
After I inscribed a NFT with 1 sat/vbyte, my wallet was stuck and the left cardinal is zero. So I have to wait the tx confirmed.  How can I inscribe 5 NFTs continuously without waiting the first tx confirmed?

**Comment by ordinalism** [comment]
Ah.. same issue i am also facing.. sometime it works once the next block is created and indexed.

**Comment by droplister** [comment]
Fund your wallet with at least 5 separate txs, one per file, so there is an available utxo for each inscription.

**Comment by brucexiu** [comment]
> Fund your wallet with at least 5 separate txs, one per file, so there is an available utxo for each inscription.

On trying, thanks.

**Comment by DanielHook15** [comment]
Do I need to generate a new address for each transaction (by repeatedly using `ord wallet receive`) or can I send all 5 transactions to the same address?

**Comment by cideight** [comment]
> Fund your wallet with at least 5 separate txs, one per file, so there is an available utxo for each inscription.

How this works practical?

**Comment by GaloisField2718** [comment]
> Do I need to generate a new address for each transaction (by repeatedly using `ord wallet receive`) or can I send all 5 transactions to the same address?

That's a good question! Do you have the answer ?

**Comment by casey** [comment]
We now have batch inscribing, check out the guide: https://docs.ordinals.com/guides/batch-inscribing.html

**Comment by idodou** [comment]
How do I set destination for batch inscribing ?

error: the argument '--batch <BATCH>' cannot be used with '--destination <DESTINATION>'

**Comment by raphjaph** [comment]
Will add this soon
