### ISSUE TITLE
Connecting to remote bitcoind rpc does not work - I/O error: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by bensig** [ordinals/ord#1849]
I am trying to sync the ord index from a remote node. I'm able to connect using `bitcoin-cli` over an SSH tunnel but I cannot connect using ORD.

Unclear how to use ORD config files - I was unable to find examples. On another device, I ran bitcoind locally and ord was able to connect, however, the sync looks like it will take 5 days. 

What do I need to do in order to connect to the remote node? I have the `rpcuser` and `rpcpassword` set in my bitcoin.conf file - as you can see below, `bitcoin-cli` picks this up without any additional params and is able to connect.

Thanks in advance to anyone who has figured this out. Happy to write a guide once it's working.

```
$ bitcoin-cli getblockchaininfo            
{
  "chain": "main",
  "blocks": 778563,
  "headers": 778563,
  "bestblockhash": "00000000000000000000645bb6d45b3c5c25b8c21256a8c8077e220c251673d0",
  "difficulty": 43053844193928.45,
  "time": 1677532116,
  "mediantime": 1677530983,
  "verificationprogress": 0.9999989442947635,
  "initialblockdownload": false,
  "chainwork": "00000000000000000000000000000000000000004149b604c3d540e595d5c450",
  "size_on_disk": 522202348662,
  "pruned": false,
  "warnings": ""
}

$ ord index                
error: failed to connect to RPC URL
because: I/O error: No such file or directory (os error 2)
```

**Comment by so7ow** [comment]
Tell ord about your bitcoin data location:

`ord --bitcoin-data-dir /path/to/bitcoin index`

**Comment by afeezaziz** [comment]
I am trying to connect to a QuickNode RPC but still fail. Facing the same problem as @bensig . Have you found out how to solve this?

**Comment by so7ow** [comment]
You all need to specify the RPC url and the RPC credential for ord to connect to the remote node. 

```
      --bitcoin-rpc-pass <BITCOIN_RPC_PASS>
          Authenticate to Bitcoin Core RPC with <RPC_PASS>.
      --bitcoin-rpc-user <BITCOIN_RPC_USER>
          Authenticate to Bitcoin Core RPC as <RPC_USER>.
      --rpc-url <RPC_URL>
          Connect to Bitcoin Core RPC at <RPC_URL>.
```

**Comment by raphjaph** [comment]
You can also pass in the password and username as environmental variables: `BITCOIN_RPC_USER` and `BITCOIN_RPC_PASS`

**Comment by afeezaziz** [comment]
I have tried both and unable to do so. By the way, quicknode doesnt have username/password. Not sure it affect this or not.

**Comment by raphjaph** [comment]
Does Quicknode use the plain Bitcoin Core RPC or do they do something custom?

For example, are you able to connect to your Quicknode with `bitconi-cli`?

**Comment by Lucklyric** [comment]
QuickNode is a customized RPC with token-based HTTPS authentication. Hence, I believe you are not able to connect to QuickNode directly from bitcoin-cli

**Comment by raphjaph** [comment]
Then you also won't be able to do so with `ord`. Going to close this since this seems resolved
