### ISSUE TITLE
RpcError { code: -4, message: "Wallet already loading.", data: None }

### ISSUE THREAD

**Issue by ezlifesg** [ordinals/ord#1850]
C:\bitcoin-24.0.1\ord>ord wallet receive
error: JSON-RPC error: RPC error response: RpcError { code: -4, message: "Wallet already loading.", data: None }

C:\bitcoin-24.0.1\ord>ord.exe wallet receive
error: JSON-RPC error: RPC error response: RpcError { code: -4, message: "Wallet already loading.", data: None }

it was working for a week for me, but recently I had ran into this issue.. can someone please help

**Comment by Magicking** [comment]
It seems to be an error related to your bitcoin node wallet, do you have any log with it if you are still experimenting the issue?

**Comment by unzyp** [comment]
> It seems to be an error related to your bitcoin node wallet, do you have any log with it if you are still experimenting the issue?

I got this issue, and my bitcoin node still syncing. How to solve this issue?

`error: JSON-RPC error: RPC error response: RpcError { code: -4, message: "Wallet file verification failed. Failed to create database path '/Users/mymac/Library/Application Support/Bitcoin/wallets/ord'. Database already exists.", data: None }
`

**Comment by Magicking** [comment]
In your case the error message is different and is saying that you already created an ord wallet

**Comment by raphjaph** [comment]
Reopen if still relevant
