### ISSUE TITLE
Running 'ord server' seems to leave the index in bad state, delays next ord launch

### ISSUE THREAD

**Issue by so7ow** [ordinals/ord#1861]
Running 'ord server' works as expected. Ctrl-C to exit also seems to behave as expected. However, each time after running 'ord server' and then exiting, the NEXT time I run ord I get a long delay (up to 20-30 min for a with-sats index) before it picks up with indexing and does whatever new command I've given it.

macOS 13.2.1 / M1 Max / 32 GB RAM / SSD
ord 0.5.1

**Comment by gmart7t2** [comment]
I see exactly the same thing. It takes about 25 minutes before the "listening on" text shows up. If I hit control-C at that point and rerun "ord server" it takes another 25 minutes. While waiting it is constantly reading about 22 MB/s from the drive that holds the index file. That means it's reading around 33 GB of the 116 GB index file.

**Comment by victorkirov** [comment]
Same here. With the logs on TRACE, there is literally nothing logged during that period either :/

**Comment by nick07002** [comment]
Exact same issue I am facing..

**Comment by raphjaph** [comment]
Fixed by #2275
