### ISSUE TITLE
Cache all /preview endpoints

### ISSUE THREAD

**Issue by orenyomtov** [ordinals/ord#1889]
Currently, the work done in #1318 sets caching headers for all the `/content` endpoints, and for HTML `/preview` endpoints.

But it does not set the cache headers for `/preview` endpoints that are images, or any other mime type other than HTML.

Images are the most common inscription type, so this should bring considerable caching and performance benefits.

**Comment by veryordinally** [comment]
Testing in https://github.com/veryordinally/ord/tree/caching-headers-1889

**Comment by casey** [comment]
Previews are now cached.
