### ISSUE TITLE
[2023-03-08T06:17:15Z ERROR ord::index::updater] Couldn't receive txs Failed to fetch raw transaction: code -5 message No such mempool transaction. Use -txindex or provide a block hash to enable blockchain transaction queries. Use gettransaction for wallet transactions.

### ISSUE THREAD

**Issue by Sudocrypto** [ordinals/ord#1895]
Is there a way to fix this [2023-03-08T06:17:15Z ERROR ord::index::updater] Couldn't receive txs Failed to fetch raw transaction: code -5 message No such mempool transaction. Use -txindex or provide a block hash to enable blockchain transaction queries. Use gettransaction for wallet transactions.

**Comment by david1025** [comment]
Same problem

**Comment by bobdos** [comment]
put txindex=1 in bitcoin.conf, then it's fixed.

**Comment by 0xdigiscore** [comment]
> put txindex=1 in bitcoin.conf, then it's fixed.
I added txindex=1 to the conf file, restarted the bitcoin core wallet, still the same error, I use testnet

**Comment by heipacker** [comment]
> 

https://github.com/casey/ord/issues/1824
