### ISSUE TITLE
Transactions are not confirmed

### ISSUE THREAD

**Issue by gregorymalov** [ordinals/ord#1917]
For the very first time, it was successful to create one inscription, now transactions are not confirmed, I suspect because of the small fee rate

<img width="557" alt="Снимок экрана 2023-03-11 в 21 30 29" src="https://user-images.githubusercontent.com/53757772/224508408-186dad47-3935-4ad7-8032-5985409a87ff.png">

<img width="804" alt="Снимок экрана 2023-03-11 в 21 35 40" src="https://user-images.githubusercontent.com/53757772/224508424-16d5f897-0e83-4a04-8c32-73930e2527fe.png">

The balance is completely debited

<img width="563" alt="Снимок экрана 2023-03-11 в 21 36 35" src="https://user-images.githubusercontent.com/53757772/224508755-b202f4e0-dd2e-40cc-bea2-cdd10522bbe8.png">

<img width="570" alt="Снимок экрана 2023-03-11 в 21 37 04" src="https://user-images.githubusercontent.com/53757772/224508790-e461a21c-8f2e-4a51-962f-cf6171d4b56e.png">

https://mempool.space/tx/b8d7cd6ba8e2c3387d6c1dfd33ef542ed82aa36425a9a7c2f903a803aaca7015

Help me )

**Comment by ysw1011** [comment]
你需要设置fee：./ord --wallet tord wallet inscribe 1.html --fee-rate 6，但是你没有，所以你只能等，有一个清除本地内存池交易的bitcoin cli命令，但是我不建议你用，因为会把你钱包里数据给搞丢。所以你只能等。或者创建一个新钱包，把当前钱包余额转过去 同来产生新的UTXO
