### ISSUE TITLE
【 How to get inscription information from Bitcoin's original transaction】如何从bitcoin的原始交易中获取inscription信息？

### ISSUE THREAD

**Issue by ysw1011** [ordinals/ord#1940]
我们在从bitcoin的原始交易中获取inscription信息的时候遇到一些困难，虽然得到了一些期望的内容，但是内容并不完整，并且其中有很多意外的信息。有没有一种方法从bitcoin的原始交易数据中清晰的获取到inscription信息？

We encountered some difficulties when obtaining the inscription information from the original bitcoin transaction. Although we got some expected content, the content was incomplete and contained a lot of unexpected information.Is there a way to cleanly obtain information from Bitcoin's raw transaction data?

下面是我获取到的一些例子：
Here are some examples of what I got:
JSON 
hex: 20117f692257b2331233b5705ce9c682be8719ff1b2b64cbca290bd6faeb54423eac06756e69736174069ee495e986016d0063036f7264010118746578742f706c61696e3b636861727365743d7574662d38004a7b2270223a226272632d3230222c226f70223a226465706c6f79222c227469636b223a227365616c222c226d6178223a2231303030303030222c226c696d223a2231303030303030227d68

Method: b' \x11\x7fi"W\xb23\x123\xb5p\\\xe9\xc6\x82\xbe\x87\x19\xff\x1b+d\xcb\xca)\x0b\xd6\xfa\xebTB>\xac\x06unisat\x06\x9e\xe4\x95\xe9\x86\x01m'

Address: b'c\x03ord\x01\x01\x18text/plain;charset=utf-8\x00J{"p":"brc-20","op":"deploy","tick":"seal","max":"1000000","lim":"1000000"}h'

TEXT 
hex: 20bd8aab5577cc902bdfc314719b4f4d6691d9fe66280f25da1fc0c46ad125b804ac0063036f7264010118746578742f706c61696e3b636861727365743d7574662d38000923632e302e3126300a68

Method: b' \xbd\x8a\xabUw\xcc\x90+\xdf\xc3\x14q\x9bOMf\x91\xd9\xfef(\x0f%\xda\x1f\xc0\xc4j\xd1%\xb8\x04\xac'

Address: b'c\x03ord\x01\x01\x18text/plain;charset=utf-8\x00\t#c.0.1&0\nh'

PNG 
hex: 208a76ea6e8a5c5acfc5292c196893fba58758c792bd984f91aab5999390f979d0ac0063036f7264010109696d6167652f706e67004d6e0189504e470d0a1a0a0000000d49484452000000140000001408060000008d891d0d00000006624b474400ff00ff00ffa0bda7930000012349444154388d637cbd2af83f03150113350d1b1a06b22073762d2f62b87f4b994151ed2ec3f4e5a90c4738aee1d5fc7a55307e03efdf5266c86d3663985c7b8ae1e5fc8f0caad3a5f11a281ab616c350b89703fdae3328aadd65985c7b8a4151ed2e0383f45f825875ba348368d85adc2e9cbe3c95e1e5fc8f100d6402b80b8f705c23dd302cae644257403240d343bf74f82cf2334e4df8e458d0058eac726160606060b059be8781818181e1b6df0b1479d54d120c52cb7911eac2f6e037105d81ea2609ac2e41570703702fbf5e158ce11a62c06dbf1728891bc585af57053388faad457119362f238be3cc29c88622dbfeffff7f148c6c01b6bc8c61a068d85a9ce186ee52f46c8761a068d85a8205022143e106c20d93fe4b54e4c0d4a01b0a004c39833ee0cce95b0000000049454e44ae42608268

Method: b' \x8av\xean\x8a\\Z\xcf\xc5),\x19h\x93\xfb\xa5\x87X\xc7\x92\xbd\x98O\x91\xaa\xb5\x99\x93\x90\xf9y\xd0\xac'

Address: b'c\x03ord\x01\x01\timage/png\x00Mn\x01\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x14\x00\x00\x00\x14\x08\x06\x00\x00\x00\x8d\x89\x1d\r\x00\x00\x00\x06bKGD\x00\xff\x00\xff\x00\xff\xa0\xbd\xa7\x93\x00\x00\x01#IDAT8\x8dc|\xbd*\xf8?\x03\x15\x01\x135\r\x1b\x1a\x06\xb2 sv-/b\xb8\x7fK\x99AQ\xed.\xc3\xf4\xe5\xa9\x0cG8\xae\xe1\xd5\xfczU0~\x03\xef\xdfRf\xc8m6c\x98\\{\x8a\xe1\xe5\xfc\x8f\x0c\xaa\xd3\xa5\xf1\x1a(\x1a\xb6\x16\xc3P\xb8\x97\x03\xfd\xae3(\xaa\xdde\x98\\{\x8aAQ\xed.\x03\x83\xf4_\x82Xu\xba4\x83h\xd8Z\xdc.\x9c\xbe<\x95\xe1\xe5\xfc\x8f\x10\rd\x02\xb8\x0b\x8fp\\#\xdd0,\xaedBW@2@\xd3C\xbft\xf8,\xf23NM\xf8\xe4X\xd0\x05\x8e\xacra````\xb0Y\xbe\x87\x81\x81\x81\x81\xe1\xb6\xdf\x0b\x14y\xd5M\x12\x0cR\xcby\x11\xea\xc2\xf6\xe07\x10]\x81\xea&\t\xac.AW\x07\x03p/\xbf^\x15\x8c\xe1\x1ab\xc0m\xbf\x17(\x89\x1b\xc5\x85\xafW\x053\x88\xfa\xadEq\x196/#\x8b\xe3\xcc)\xc8\x86"\xdb\xfe\xff\xff\x7f\x14\x8cl\x01\xb6\xbc\x8ca\xa0h\xd8Z\x9c\xe1\x86\xeeR\xf4l\x87a\xa0h\xd8Z\x82\x05\x02!C\xe1\x06\xc2\r\x93\xfeKT\xe4\xc0\xd4\xa0\x1b\n\x00L9\x83>\xe0\xcc\xe9[\x00\x00\x00\x00IEND\xaeB`\x82h'

**Comment by GaloisField2718** [comment]
interested by solutions

**Comment by GaloisField2718** [comment]
Yes i Read so especially yesterday 😄 I have things that I must understand but I saw this. 
My interest here was more : how with this data know what was push on Bitcoin ? How to “read” these files or the file push on chain ?

**Comment by GaloisField2718** [comment]
> Do you mean purely through the command line? The extra information you see are Bitcoin Script OP codes. We use a special construction called an "envelope" to store inscription data inside a taproot witness. You can read more here: https://docs.ordinals.com/inscriptions.html. Our rust code to parse inscriptions is in `/src/inscription.rs`.

Thank you for answer. 😁

**Comment by phpmac** [comment]
> Do you mean purely through the command line? The extra information you see are Bitcoin Script OP codes. We use a special construction called an "envelope" to store inscription data inside a taproot witness. You can read more here: https://docs.ordinals.com/inscriptions.html. Our rust code to parse inscriptions is in `/src/inscription.rs`.



> 我们在从bitcoin的原始交易中获取inscription信息的时候遇到一些困难，虽然得到了一些期望的内容，但是内容并不完整，并且其中有很多意外的信息。有没有一种方法从bitcoin的原始交易数据中清晰的获取到inscription信息？
> 
> We encountered some difficulties when obtaining the inscription information from the original bitcoin transaction. Although we got some expected content, the content was incomplete and contained a lot of unexpected information.Is there a way to cleanly obtain information from Bitcoin's raw transaction data?
> 
> 下面是我获取到的一些例子： Here are some examples of what I got: JSON hex: 20117f692257b2331233b5705ce9c682be8719ff1b2b64cbca290bd6faeb54423eac06756e69736174069ee495e986016d0063036f7264010118746578742f706c61696e3b636861727365743d7574662d38004a7b2270223a226272632d3230222c226f70223a226465706c6f79222c227469636b223a227365616c222c226d6178223a2231303030303030222c226c696d223a2231303030303030227d68
> 
> Method: b' \x11\x7fi"W\xb23\x123\xb5p\\xe9\xc6\x82\xbe\x87\x19\xff\x1b+d\xcb\xca)\x0b\xd6\xfa\xebTB>\xac\x06unisat\x06\x9e\xe4\x95\xe9\x86\x01m'
> 
> Address: b'c\x03ord\x01\x01\x18text/plain;charset=utf-8\x00J{"p":"brc-20","op":"deploy","tick":"seal","max":"1000000","lim":"1000000"}h'
> 
> TEXT hex: 20bd8aab5577cc902bdfc314719b4f4d6691d9fe66280f25da1fc0c46ad125b804ac0063036f7264010118746578742f706c61696e3b636861727365743d7574662d38000923632e302e3126300a68
> 
> Method: b' \xbd\x8a\xabUw\xcc\x90+\xdf\xc3\x14q\x9bOMf\x91\xd9\xfef(\x0f%\xda\x1f\xc0\xc4j\xd1%\xb8\x04\xac'
> 
> Address: b'c\x03ord\x01\x01\x18text/plain;charset=utf-8\x00\t#c.0.1&0\nh'
> 
> PNG hex: 208a76ea6e8a5c5acfc5292c196893fba58758c792bd984f91aab5999390f979d0ac0063036f7264010109696d6167652f706e67004d6e0189504e470d0a1a0a0000000d49484452000000140000001408060000008d891d0d00000006624b474400ff00ff00ffa0bda7930000012349444154388d637cbd2af83f03150113350d1b1a06b22073762d2f62b87f4b994151ed2ec3f4e5a90c4738aee1d5fc7a55307e03efdf5266c86d3663985c7b8ae1e5fc8f0caad3a5f11a281ab616c350b89703fdae3328aadd65985c7b8a4151ed2e0383f45f825875ba348368d85adc2e9cbe3c95e1e5fc8f100d6402b80b8f705c23dd302cae644257403240d343bf74f82cf2334e4df8e458d0058eac726160606060b059be8781818181e1b6df0b1479d54d120c52cb7911eac2f6e037105d81ea2609ac2e41570703702fbf5e158ce11a62c06dbf1728891bc585af57053388faad457119362f238be3cc29c88622dbfeffff7f148c6c01b6bc8c61a068d85a9ce186ee52f46c8761a068d85a8205022143e106c20d93fe4b54e4c0d4a01b0a004c39833ee0cce95b0000000049454e44ae42608268
> 
> Method: b' \x8av\xean\x8a\Z\xcf\xc5),\x19h\x93\xfb\xa5\x87X\xc7\x92\xbd\x98O\x91\xaa\xb5\x99\x93\x90\xf9y\xd0\xac'
> 
> Address: b'c\x03ord\x01\x01\timage/png\x00Mn\x01\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x14\x00\x00\x00\x14\x08\x06\x00\x00\x00\x8d\x89\x1d\r\x00\x00\x00\x06bKGD\x00\xff\x00\xff\x00\xff\xa0\xbd\xa7\x93\x00\x00\x01#IDAT8\x8dc|\xbd*\xf8?\x03\x15\x01\x135\r\x1b\x1a\x06\xb2 sv-/b\xb8\x7fK\x99AQ\xed.\xc3\xf4\xe5\xa9\x0cG8\xae\xe1\xd5\xfczU0~\x03\xef\xdfRf\xc8m6c\x98\{\x8a\xe1\xe5\xfc\x8f\x0c\xaa\xd3\xa5\xf1\x1a(\x1a\xb6\x16\xc3P\xb8\x97\x03\xfd\xae3(\xaa\xdde\x98\{\x8aAQ\xed.\x03\x83\xf4_\x82Xu\xba4\x83h\xd8Z\xdc.\x9c\xbe<\x95\xe1\xe5\xfc\x8f\x10\rd\x02\xb8\x0b\x8fp\#\xdd0,\xaedBW@2@\xd3C\xbft\xf8,\xf23NM\xf8\xe4X\xd0\x05\x8e\xacra````\xb0Y\xbe\x87\x81\x81\x81\x81\xe1\xb6\xdf\x0b\x14y\xd5M\x12\x0cR\xcby\x11\xea\xc2\xf6\xe07\x10]\x81\xea&\t\xac.AW\x07\x03p/\xbf^\x15\x8c\xe1\x1ab\xc0m\xbf\x17(\x89\x1b\xc5\x85\xafW\x053\x88\xfa\xadEq\x196/#\x8b\xe3\xcc)\xc8\x86"\xdb\xfe\xff\xff\x7f\x14\x8cl\x01\xb6\xbc\x8ca\xa0h\xd8Z\x9c\xe1\x86\xeeR\xf4l\x87a\xa0h\xd8Z\x82\x05\x02!C\xe1\x06\xc2\r\x93\xfeKT\xe4\xc0\xd4\xa0\x1b\n\x00L9\x83>\xe0\xcc\xe9[\x00\x00\x00\x00IEND\xaeB`\x82h'



> > Do you mean purely through the command line? The extra information you see are Bitcoin Script OP codes. We use a special construction called an "envelope" to store inscription data inside a taproot witness. You can read more here: https://docs.ordinals.com/inscriptions.html. Our rust code to parse inscriptions is in `/src/inscription.rs`.
> 
> Thank you for answer. 😁

hi there,Can you provide more instructions on parsing data? Is there nodejs, python type code that explains how parsing json data to get text or png works?

**Comment by phpmac** [comment]
How is it generated and how is it parsed?
