### ISSUE TITLE
Bitcoin node space occupies too much disk space, how to reduce it and ensure the normal operation of ord data?

### ISSUE THREAD

**Issue by echoWeb3** [ordinals/ord#1948]
Bitcoin node space occupies too much disk space, how to reduce it and ensure the normal operation of ord data?

**Comment by Psifour** [comment]
Running Bitcoin Core in pruned mode is not supported at this time. 

It is _possible_ to do so if you were to stub all code that may request blocks outside of your pruned region, but this would be a non-optimal solution and instead I would redesign the indexer logic to not rely on Bitcoin Core outside of initial sync.

**Comment by andrewtoth** [comment]
> Running Bitcoin Core in pruned mode is not supported at this time. 
> 
> It is _possible_ to do so if you were to stub all code that may request blocks outside of your pruned region, but this would be a non-optimal solution and instead I would redesign the indexer logic to not rely on Bitcoin Core outside of initial sync.

It's actually not possible because the indexing and server both rely on using `txindex`, which is incompatible with pruning.
