### ISSUE TITLE
synced ord index

### ISSUE THREAD

**Issue by AdmiralOrange** [ordinals/ord#1962]
I have a full node, I have an Ord client - but I somehow are unable to run "RUST_LOG=info ord index" - where do I have to type this in? In Terminal I get "command not found" - maybe this is not the full command I need to type in on my iMAC? Sat hunting guide is outdated it says - but where is a valid one now? Some people say they have to build bitcoind from source??? How to do this? The Ordinal Theory Handbook doesn't mention it. Some say I need Homebrew. Some say I need XCode via Apple Developer? What are the tools I need to have installed on iMAC for being able to run Ord Client? Maybe there is a guide for beginners on iMAC? In short: how to connect my ORD Client to my Bitcoin Core Node and start indexing?

**Comment by DanielHook15** [comment]
If you have installed ord, just type "ord index" in the terminal. The instructions in the handbook worked fine for me.

**Comment by AdmiralNeo** [comment]
Sent from Proton Mail for iOS
Thx bro. But I am unable to connect my Ord Client to my Full Node. You happen to know who to achieve this?

Thx a lot in advance

**Comment by so7ow** [comment]
This is not an issue with ord; "command not found" simply means you're in the wrong location to execute the file. First, change directory to wherever your ord executable file is. For example, if the ord executable is located in ~/bin, you could do this:
```
cd ~/bin
ord index
```

Or you could combine those steps by simply typing this:
```
~/bin/ord index
```
I suspect you'll run into a few more issues before you're successfully indexing. The ord Discord is probably the best place to get real-time support: https://discord.gg/ordinals

**Comment by so7ow** [comment]
You'll need to use the --cookie-file switch to tell ord where your bitcoin cookie is.

**Comment by so7ow** [comment]
"No cookie file" is not an option. If you don't have a cookie file, that's why it's not working.

**Comment by AdmiralNeo** [comment]
Bitcoin.conf is now: txindex=1
                                  server=1
Still no cookie file

**Comment by so7ow** [comment]
How are you looking for the file? It's named `.cookie` and it's hidden by default in macOS. Go look in your bitcoin datadir and do this:

[See hidden files on Mac via Finder](https://setapp.com/how-to/show-hidden-files-on-mac#:~:text=See%20hidden%20files%20on%20Mac%20via%20Finder&text=In%20Finder%2C%20open%20up%20your,hidden%20files%20will%20become%20visible.)

**Comment by AdmiralNeo** [comment]
<img width="684" alt="Bildschirm­foto 2023-03-30 um 14 40 36" src="https://user-images.githubusercontent.com/125405780/228838891-2d9d414d-d139-4411-aa95-95f8858bc6ab.png">

All I have is this folders

**Comment by AdmiralNeo** [comment]
<img width="502" alt="Bildschirm­foto 2023-03-30 um 15 10 39" src="https://user-images.githubusercontent.com/125405780/228846608-80ed1710-12db-4d1b-ba1c-1ea3e3f308a2.png">

And this is my conf-file

**Comment by so7ow** [comment]
You need to remove the RPCuser and RPCpassword lines.

**Comment by so7ow** [comment]
> You'll need to use the `--cookie-file` switch to tell ord where your bitcoin cookie is. 

Now you need to do this.

**Comment by AdmiralNeo** [comment]
THX a lot - almost there: ~/bin/ord --index
error: The argument '--index <INDEX>' requires a value but none was supplied

**Comment by so7ow** [comment]
See previous message. You need the `--cookie-file` switch. So it'll be something like this:

```
~/bin/ord --cookie-file /Volumes/path/to/your/.cookie index
```

**Comment by AdmiralNeo** [comment]
<img width="413" alt="Fatal Error Indexing for Ord" src="https://user-images.githubusercontent.com/125405780/228870184-976b648b-97b8-431f-b720-332d8e93cfe0.png">

Started indexing till block 597136 and than a fatal error stopped it and BTC went down

**Comment by AdmiralNeo** [comment]
Maybe cause I renamed the data directory to BTCCore without spaces - will restart and try again

**Comment by so7ow** [comment]
Ah, yeah. You can't just rename bitcoins files out from under it....

**Comment by AdmiralNeo** [comment]
Ord is indexing again - but slows down considerable above 767500

**Comment by AdmiralNeo** [comment]
THX bro - you helped me a lot! Guess Linux/Unix-knowledge helps a lot? Is there any material out there to learn a little bit more about syntax?

**Comment by so7ow** [comment]
Yeah, command line is foreign to many people. Check out:

```ord --help``

https://docs.ordinals.com/

**Comment by AdmiralNeo** [comment]
Indexing is done - Bitcoin CLI loadwallet doesn't work now
<img width="659" alt="Bildschirm­foto 2023-03-30 um 22 45 10" src="https://user-images.githubusercontent.com/125405780/228960169-cdae2b84-3228-42c3-be92-97509711b253.png">

**Comment by so7ow** [comment]
Did you create your wallet? `ord wallet create`?

**Comment by AdmiralNeo** [comment]
Oh shit - no. I made it in Bitcoin Core somehow. And it is also named Ord. And I have the wrong passphrase as well to empty it and do it again the right way. You happen to know how to reset the passphrase?

**Comment by so7ow** [comment]
If that wallet is empty, just delete it from your file system. It'll be in your bitcoin datadir.

**Comment by AdmiralNeo** [comment]
Yeah almost empty, only 0.001 BTC just for playing around. Will continue this sysiphus-work tomorrow. THX so far.

**Comment by so7ow** [comment]
Get that sent out first! 😲

**Comment by AdmiralNeo** [comment]
Can I send it out without the proper passphrase?

**Comment by so7ow** [comment]
No, I imagine not. I've never worked with passphrase-protected wallets on Bitcoin Core, though, so don't take my word for it.

**Comment by AdmiralNeo** [comment]
Did ord wallet create successfully - run ~/bin/ord --cookie-file "/Volumes/Extreme Pro/BTC Core/.cookie" wallet sats but get an error message:
error: JSON-RPC error: RPC error response: RpcError { code: -4, message: "Wallet file verification failed. SQLiteDatabase: Unable to obtain an exclusive lock on the database, is it being used by another instance of Bitcoin Core?\n", data: None }

**Comment by so7ow** [comment]
The `--index-sats` flag only does anything on fresh creation of your index file. So you need to delete/rename your old index.redb file before using it, or specify a new index file using the `--index` flag. (Creating a sats index on a Mac seems to take like a week or more, too.)

**Comment by AdmiralNeo** [comment]
OMG - lol. Maybe the Ordinal Theory Handbook should be corrected to say ord --index-sats instead of ord --index ... THX for the help so far

**Comment by so7ow** [comment]
It does... in the sat hunting section:

https://docs.ordinals.com/guides/sat-hunting.html

**Comment by AdmiralNeo** [comment]
There is written:
Run RUST_LOG=info ord index. It should connect to your bitcoin core node and start indexing.

**Comment by so7ow** [comment]
Yeah, that's for inscribing. The sat hunting section describes how to use --index-sats. The documentation is far from perfect...

**Comment by AdmiralNeo** [comment]
> so7ow

I can't find a file named index.redb

**Comment by so7ow** [comment]
I believe the default location is something like `/Users/<your username>/Library/Application Support/ord/index.redb` but it doesn't matter because you can just leave that one there and make new file:

```
ord --index-sats --cookie-file /whatever/path/.cookie --index /path/to/new/sats-index.redb index
```

**Comment by AdmiralNeo** [comment]
Getting better - now I run ~/bin/ord --index-sats  --cookie-file "/Volumes/Extreme Pro/BTC Core/.cookie" --index "/Volumes/Extreme Pro/BTC Core/index.redb" index

But after some time I get error:[indexing blocks] █████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 148572/784941thread 'main' panicked at 'internal error: entered unreachable code', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.13.0/src/tree_store/btree_mutator.rs:967:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by so7ow** [comment]
That's over my pay grade, sorry.

**Comment by AdmiralNeo** [comment]
~/bin/ord --cookie-file "/Volumes/Extreme Pro/BTC Core/.cookie" wallet sats
error: JSON-RPC error: transport error: Couldn't connect to host: Broken pipe (os error 32)

Indexing worked till block 160.000 - maybe iMAC is simply too weak. I tried sat-hunting with the index.redb-file I had and got this error ...
