### ISSUE TITLE
sat ranges isn't calculated when coinbase tx contains more than one output address

### ISSUE THREAD

**Issue by dajuguan** [ordinals/ord#1972]
In this tx https://testnet.ordinals.com/tx/6856e198907e75bf83e2bedc39900fe3d1a54c865aed9c480bc04ef28d395907, [the first output sat range](https://testnet.ordinals.com/output/6856e198907e75bf83e2bedc39900fe3d1a54c865aed9c480bc04ef28d395907:0) is not calculated. 
<img width="827" alt="image" src="https://user-images.githubusercontent.com/13568446/227727244-ac084b58-9579-45d5-b3fd-a7c831d0567e.png">

However, in the [following tx](https://testnet.ordinals.com/output/eeabc70063d3f266e190e8735bc4599c811d3a79d138da1364e88502069b029c:1) these sat ranges are found again and it's right.
So to avoid misleading, I suggest that the sat ranges should be calculated and showed correct in the coinbase tx.

**Comment by gmart7t2** [comment]
https://ordinals.com/tx/01b5b5344cd2f74365a40ab8e8a29b95c17df76e14ad6f42f6833074535fc565 is a coinbase with 2 outputs. Its sat ranges are shown.

What you may have discovered is that sat ranges are only stored for unspent outputs. Once an output is spent its ranges are passed to the outputs it funded.
