### ISSUE TITLE
Add support for generative art collections through parent/child references

### ISSUE THREAD

**Issue by ericatallah** [ordinals/ord#1982]
**Why:**

To enable and encourage artists to inscribe generative art collections in the most efficient manner possible.  With the advent of the Ordinals protocol, we feel it's becoming increasingly important to set good standards and best practices for optimizing block space usage.

For example, an entire art collection can be inscribed on a single ordinal by creating an HTML or SVG file which can accept url parameters to render different pieces in the collection.  Check out the OnChainBirds parent collection for a good example:
https://ordinals.com/content/551e65f2839c776524df295ccc25ce3cbd214fa3134f18b67264069250c9bbd2i0?tokenID=45

We can change the `tokenID` url param to render any of the 10k pieces in the collection.
Collections inscribed in this manner can save considerable space, and prevent unnecessary bloat on the btc blockchain.  Using the JSON format proposed below for each child, we can observe a space savings of more than **99.7%** (**159.5mb**) for the OnChainBirds collection alone.  Rough calculation:
```
If each child had to inscribe the complete svg image (~16kb each), for the entire 10k collection we get:
10000*16kb = **160mb**

If we instead use a simple JSON pointer (.045kb each), for the entire 10k collection we get:
10000*.045kb = **0.45mb**
```
Moreover, the example above is only demonstrating space savings gained from a simple pixel art collection.  The space savings can be orders of magnitude greater when dealing with 3d/animated art, such as what can be generated with libraries such as threejs.  Instead of importing this large lib for each child inscription, we only need to import it once in the parent.

**What:**

This request is to add support for a child inscription pointer mechanism.  These child inscriptions are JSON documents containing url parameters that instruct the parent inscription to render a specific item in the collection.  A proposed JSON spec, in it's simplest form, is given below.  It is expandable to accept any number of url parameters, and can contain other optional fields such as `metadata` or similar.

**How:**

Since all art is contained in the parent, we can add a simple redirect to render the parent inscription with included url parameters. There are 3 constraints which must be met, in the child inscription, before the redirect can happen:
1. The child inscription must have a parent inscription.
2. The child inscription's body data must be valid JSON.
3. The child inscription's body JSON data must contain a field named "use_p", with any value.

Proposed JSON standard for child pointer inscriptions:
```
{
   "use_p": 1,
   "params": ["tokenID=4969"]
}
```

We have an open PR, with included test coverage, which implements the above functionality:
https://github.com/raphjaph/ord/pull/7

Any thoughts/feedback/code review are greatly appreciated.

**Comment by timechainz** [comment]
I like the idea.  Would change params to a js object so it could be better handle complex parameters and be interpreted by URLSearchParams (or equivalent).   

```
 {
   "use_p": 1,
   "params": {
      "tokenID": 4969
   }
}
```

Also, I would modify the 1st constraint to require that the parent is either html or svg before redirecting.  Without this check I think your code could double-redirect allowing holders to create children (grandchildren of the html) that would look like children.

**Comment by ericatallah** [comment]
Great points.  Regarding the double-redirect thing, instead of restricting to parent html or svg content types, we can do the opposite and prohibit redirecting to a parent with JSON content type.

**Comment by casey** [comment]
I think this is covered by recursive inscriptions, since now an inscription can reference another inscription via the `/content` endpoint.
