### ISSUE TITLE
"unknown denomination" errors on multiple inscriptions

### ISSUE THREAD

**Issue by punk3700** [ordinals/ord#1983]
hey guys.. do you happen to know what this error is.. i ran into this issue when trying to send some inscriptions.  here is one of them.

ord wallet send --fee-rate 3 bc1pcsmusfcyv8al7zycncespvzf26qfqwtjhpg4xupjcs8t66y89a0qrwtfxr 0cd4554ef970e765b3278e3929d2e42258479b514d39bdbd87e6807a6f5f7c0i0

error: Invalid value "0cd4554ef970e765b3278e3929d2e42258479b514d39bdbd87e6807a6f5f7c0i0" for '<OUTGOING>': unknown denomination: cd4554ef970e765b3278e3929d2e42258479b514d39bdbd87e6807a6f5f7c0i0

thanks!

**Comment by extraordinal** [comment]
It doesn't seem like `0cd4554ef970e765b3278e3929d2e42258479b514d39bdbd87e6807a6f5f7c0i0` is a valid inscription id (starting with a 0). So it is interpreting the leading "0" as an amount of btc/sats to send and the remainder of the hash as the unit of currency, as you usually specify `1000sats` or `0.0001btc` etc. Are you sure that is the correct inscription id?

**Comment by gmart7t2** [comment]
Where the F?

`0cFd4554ef970e765b3278e3929d2e42258479b514d39bdbd87e6807a6f5f7c0i0`

Put the missing `f` after the `0c` at the start and it will work.

**Comment by gmart7t2** [comment]
> It doesn't seem like `0cd4554ef970e765b3278e3929d2e42258479b514d39bdbd87e6807a6f5f7c0i0` is a valid inscription id (starting with a 0).

Starting with 0 is fine. It's because it is less than 66 characters long that it is disqualified from being parsed as an inscription id.
