### ISSUE TITLE
Transaction not found after `inscribe`

### ISSUE THREAD

**Issue by GaloisField2718** [ordinals/ord#1988]
Hello everyone, 

Few days ago, I tried to inscribe one image : 
The commit : dcdc0cd7dcaef1a9e7a2ba6c9b6a3f50d73731d9a0dec127b71e098908f49dd3
The reveal : 31e2fd07ad5a83f90d9c1d6fa2058f11a1dd1aa62943aab92798e45933ace92e

 Both transactions are not found on mempool.space with the message : "Transaction not found.
Waiting for it to appear in the mempool..."

Can I cancel or remove this transaction ? If I wait is this transaction will be canceled by itself ?

**Comment by extraordinal** [comment]
Is it because you gave it a low transaction fee (or did not specify one with e.g. `--fee-rate 10`? Check this issue with a few strategies to remove it or bump it: https://github.com/casey/ord/issues/1519

**Comment by GaloisField2718** [comment]
Ok yeah it’s very possible. 
But now I don’t know what can I do with this.

**Comment by soenkehahn** [comment]
Sorry, I can't really help with this. But I *think* you might find it easier to get help with this on the [ordinals discord](https://discord.gg/ordinals).
