### ISSUE TITLE
Add authentication to `ord server`

### ISSUE THREAD

**Issue by olivbau** [ordinals/ord#2001]
Is it possible to add a basic auth on `server` command ?

**Comment by olivbau** [comment]
Since it was not possible to add basic auth on `server` command,
I proposed an implementation: #2004

**Comment by casey** [comment]
Sorry for letting this sit for so long, and thank you for the PR!

I think discussing what authentication is for and whether or not it's necessary is a precondition to reviewing/merging a PR. Before considering an implementation, we need to determine what's needed, and we can then move on to considering an implementation. I'm going to close #2004 for now, until we figure out whether authentication is necessary, and what problem it's solving.

Can you describe why you need `ord server` to support authentication?

**Comment by olivbau** [comment]
I may have a bit of an unusual usecase, I use `ord server` more as an API than as a site.
That's why I want to protect the server with a basic auth against spam and so on.

Indeed maybe for the moment the basic auth is not very relevant,
but I think that when `ord server` will have API endpoints (I dont know if it's plan yet) it will make sense to be able to protect the endpoints from spam.

**Comment by raphjaph** [comment]
We might do this in the future but do not need this for now.
