### ISSUE TITLE
Mnemonic word incompatible with wallet restore

### ISSUE THREAD

**Issue by BitcoinWay** [ordinals/ord#2005]
Hi guys , went to restore a sparrow wallet i have into ord and received an error:

error: Found argument 'connect" which wasn't expected, or isn't valid in this context. 

Yup you guessed it, "connect" is one of my mnemonic words.

**Comment by gmart7t2** [comment]
ord wallet restore "seed phrase words"

The seed phrase should be in quotes like that.
