### ISSUE TITLE
.stl inscription type does not download with .stl filetype appended to the download

### ISSUE THREAD

**Issue by joe-rodgers** [ordinals/ord#2014]
When you download a .stl inscription, it saves to PC WITHOUT .stl filetype appended to the end of the file name. (I hope I am using the correct language!) 

The user must rename the file, and add .stl to the end of the file name (in windows not sure about other platforms. 

Try for yourself, download the content in inscription 70602

https://ordinals.com/inscription/423b8403b8250bf226dec3d2ed342d971491ca8aaeaaab9d5d628d7dc744e2adi0

**Comment by casey** [comment]
I think this is an issue with browsers. When a browser downloads a web page, it uses the MIME type to determine what extension to give it. In the case of STL, it doesn't know what extension to give it.
