### ISSUE TITLE
Should we add a Dockerfile?

### ISSUE THREAD

**Issue by casey** [ordinals/ord#2032]
There have been a few issues requesting Docker support, and a few PRs adding a Dockerfile. Before being ready to merge a PR, I need to know the answers to the following questions:

1. Why is Docker support useful? What problems does it solve?
2. What should the Dockerfile do?

**Comment by vnprc** [comment]
I have need of a docker instance that can connect to a docker bitcoin node and enable testing of minting, custody, and transfer of inscriptions. It would be useful to run the ord server as well to see these tests in a web browser.

Docker enables automated deployment and customization of architecture. Our existing dev environment is built on docker so this would enable rapid and seamless integration. Other solutions like nix may solve the same problems but docker is IMO currently the most common and well-supported containerization layer for business.

**Comment by blieb** [comment]
I love to run ord in my kubernetes cluster. So a dockerfile would help with that.

**Comment by casey** [comment]
What would a minimal dockerfile do? Just run ord? How would it connect to bitcoind?

**Comment by blieb** [comment]
> What would a minimal dockerfile do? Just run ord? How would it connect to bitcoind?

I think it should just be able to run ord server (people can change command when needed). Would be nice if you can give bitcoind rpc url, rpc user and rpc password via env variables (can be used in bash script to start ord)

**Comment by casey** [comment]
I still don't really see what a docker file offers over running the command directly.

**Comment by bensig** [comment]
@casey docker allows you to run an instance of the indexer separately from being able to inscribe using the same ord data. Very useful to most deployers who run everything in a docker anyway.

**Comment by bensig** [comment]
Anyway - here is a docker for ord https://github.com/bensig/docker-ord
