### ISSUE TITLE
Cursed Inscription Tracking Issue

### ISSUE THREAD

**Issue by casey** [ordinals/ord#2045]
It would be desirable to modify `ord` to recognize the following:

- Multiple inscriptions per transaction, for efficient batching
- Inscriptions on inputs after the first, which is useful for collections
- Multiple inscriptions on the same sat, so that the entire history of a sat doesn't need to be checked to determine if a new inscription is valid
- Inscriptions with unrecognized even headers, so that new even headers don't cause upgraded clients to disagree about inscription numbers

An idea for how to do this is:

- Modify ord to recognize the above currently invalid inscriptions, including retroactively in old blocks, but consider these new inscriptions "cursed" and assign them negative inscription numbers. Since they would not receive positive inscription numbers, they would not disrupt existing inscription numbers
- At a future, pre-announced block height X, new inscriptions that would have been cursed before X are now not cursed, or "blessed", and receive a positive inscription number instead of a negative one.

The reasoning for this strange scheme is as follows:

- I don't like changing old inscription numbers by fiat.
- I want to make previously invalid inscriptions appear on [ordinals.com](http://ordinals.com/) as soon as possible, and giving them a negative inscription number allows that with minimal changes to the code. Hopefully making them visible will help further the conversation, let people see how many exist, and make everything more concrete.
- Having a pre-announced block height at which previously invalid inscriptions would now be valid allows ample time for everyone to upgrade.
- Negative inscription numbers would always be perma-unstable.
- We could use this same scheme again in the future. Some new way of making inscriptions is desirable, they initially receive negative numbers, and at a pre-announced flag day they enter the main sequence.

**Comment by dannydeezy** [comment]
let's curse these babays!!!

**Comment by lgalabru** [comment]
Are you saying that batched inscriptions - which should actually be the go to / most used pattern - will be "cursed"?
How do you envision handling bugs within "cursed" inscriptions?

**Comment by paradisd** [comment]
Yeahhhh we curse!!!!

**Comment by yueliulin** [comment]
How to identify which inscriptions are cursed

**Comment by dannydeezy** [comment]
i'm concerned about https://github.com/casey/ord/pull/2109 which makes it appear that inscriptions with unrecognized even tags will be "unbound" which i think means "not assigned to a sat"

what is the reasoning for this decision? I would think they should be assigned to the top sat as if the even tags weren't there?

**Comment by DrJingLee** [comment]
Now the cursed inscriptions are on fire....

**Comment by penguin4238** [comment]
its fun

**Comment by OumArEtH** [comment]
ahhhhhhh i'm cursing

**Comment by MiLin188** [comment]
I like cursed inscriptions

**Comment by buxor** [comment]
Surely there should be a way to attach cursed inscriptions to sats and have them recognized as ordinals albeit negative ordinals. Although however this is decided, I'm all for seeing these really creative solutions here. It's exciting to be involved this early in something that will be so monumental in the future. Kudos to all you builders. 🙌

**Comment by HYAIPE** [comment]
I'd like to share my perspective on the matter, having completed my initial full collection under the "Glitch," which I consider to be a cursed ordinals. The concept for this collection originated in 2022, sparked by the question, "What if we existed in a glitched world?" It seems to me that everyone who participated in this endeavor is currently experiencing that very reality. Now, what lies ahead for cursed ordinals? The future remains uncertain, but I view it as an evolution within the realm of "Glitch" art.

The pressing question now is whether this will lead to a totalitarian decision that stifles innovation. I believe there are alternative approaches to address this issue, given that it has already exceeded initial expectations. Some have suggested imposing limitations. Although I don't possess full knowledge of the current situation, the potential for fascinating explorations with this concept is enormous. I personally envision organizing scavenger games to restore these creations to their original forms or engaging in similarly extraordinary endeavors. The possibilities for creators to conceive and construct remarkable works using this concept are boundless.

Don't fuck it up.

"They love you then they hate you, that's the curse"

**Comment by Esterklu** [comment]
let's curse!

**Comment by akajimeagle** [comment]
The community rallied around these, adds some really cool lore to ords, and I know the community wants to build support for them! Let's keep them bound!

**Comment by steddyman** [comment]
63k cursed inscriptions in 24 hours, suggests the community loves the lore and culture around cursed ordinals.

I think it would be a mistake to eliminate this art from existence.  It plays well into the rarity narrative introduced with sat hunting and ordinals.

**Comment by tyjvazum** [comment]
I'm willing to support unrecognized even tags being transferable in [arb](https://github.com/tyjvazum/arb) by removing the current restriction without making such inscriptions unbound. This can be implemented relatively quickly. Future upgrades using even tags will still be possible by using an activation height system. Is anyone interested in this solution?

**Comment by dannydeezy** [comment]
> I'm willing to support unrecognized even tags being transferable in [arb](https://github.com/tyjvazum/arb) by removing the current restriction without making such inscriptions unbound. This can be implemented relatively quickly. Future upgrades using even tags will still be possible based on activation height. Is anyone interested in this solution?

i'd suggest not doing anything _quickly_, better to take our time and find a solid consensus so we don't have conflicting implementations

**Comment by tyjvazum** [comment]
> > I'm willing to support unrecognized even tags being transferable in [arb](https://github.com/tyjvazum/arb) by removing the current restriction without making such inscriptions unbound. This can be implemented relatively quickly. Future upgrades using even tags will still be possible based on activation height. Is anyone interested in this solution?
> 
> i'd suggest not doing anything _quickly_, better to take our time and find a solid consensus so we don't have conflicting implementations

By "relatively quickly" I meant there are no major technical hurdles. I agree in general, but I unfortunately think conflicting implementations are inevitable given the lack of public planning and the fact that the only consensus mechanism available is social. Imagine what would have happened with Bitcoin clients if there had been no consensus through PoW.

**Comment by lgalabru** [comment]
@casey we may have to add another rule, to get cursed inscription fully backward compatible: satoshis inscribed with a cursed inscription can be re-inscribed, with a cursed inscription (multiple times) or an inscription (only once).
There are many instances of satoshis that have been mis-inscribed in the past (inscription on 2nd input or whatever), and that were re-inscribed correctly later. 
With your current spec, the satoshi would be bound to a cursed inscription with the first transaction, and the second, "legit" inscription would fail (because the satoshi is already bound to a cursed inscription). As a consequence, the inscription number sequence as we know it would break.

**Comment by veryordinally** [comment]
> @casey we may have to add another rule, to get cursed inscription fully backward compatible: satoshis inscribed with a cursed inscription can be re-inscribed, with a cursed inscription (multiple times) or an inscription (only once). There are many instances of satoshis that have been mis-inscribed in the past (inscription on 2nd input or whatever), and that were re-inscribed correctly later. With your current spec, the satoshi would be bound to a cursed inscription with the first transaction, and the second, "legit" inscription would fail (because the satoshi is already bound to a cursed inscription). As a consequence, the inscription number sequence as we know it would break.

@raphjaph this is an interesting point - should look at when doing reinscriptions

**Comment by veryordinally** [comment]
The current plan is to tackle these step by step to make some forward progress. Current work in in #2145 where we recognize the first, second and third type of cursed inscription from this issue, but (temporarily) treat the first and the third type as unbound (until we fully implement reinscriptions). This unblocks #783. 

We will likely then implement reinscriptions next, and then the other open types of re-inscriptions, both from this tracking issue and from other sources like #2139, and the activation block height mechanism from this issue. Please expect this to take a few weeks to work through.

Please be aware that negative inscription numbers are UNSTABLE and WILL CHANGE as more types of cursed inscriptions are integrated.

**Comment by BatBushRacks** [comment]
@veryordinally thank you so much for this info... all sounds like a great plan... what about the bound or unbound treatment of https://github.com/ordinals/ord/pull/2109... you mention "temporarily" for the other types... can we get a commitment that https://github.com/ordinals/ord/pull/2109 will be bound?

**Comment by raphjaph** [comment]
First steps: https://github.com/ordinals/ord/releases/tag/0.6.0

**Comment by BatBushRacks** [comment]
@raphjaph based on your continued avoidance I take it as a no on doing what the community wants on https://github.com/ordinals/ord/pull/2109... if so at least be brave enough to say so... otherwise commit to them being bound... open source includes open discourse...

**Comment by dstarks47** [comment]
Hey all, first time writing in one of these. so I sent my cursed bitcoin punks all to one sparrow addy . then I imported my xverse seed into sparrow after that. Then i sent each one of them one by one to the xverse imported wallet. Now I’m unsure if I own them still because i check the output tx ID on cursed ordinal. com and its a different address. 

another strange thing that happened is I went to ordinals. com and it seems a string of IP looking numbers replaced the "https" on the site's link but it showed all cursed inscriptions starting from -1 
[
(http://176.9.24.92:3333/inscription/674fa50f50cadfb86e43e1f375398a01cf5a8277204be932a17462d1dff91e16i0)

that is the website link ^

**Comment by joostjager** [comment]
Suppose the taproot annex would be standardized, how could this potentially benefit inscriptions? The taproot annex allows adding arbitrary data to each input of a transaction without bothering with commit/reveal and encoding using opcodes.

More background: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2023-June/021731.html

**Comment by casey** [comment]
@joostjager Great observation that inscriptions could be made in the taproot annex! Not having to make a commit transaction would be a big win.

**Comment by joostjager** [comment]
Yes I thought so too. Only standardization and potential DoS risks still need more discussion. Today is seems hard to get an annex tx mined: https://twitter.com/joostjgr/status/1664672721794367498
