### ISSUE TITLE
Annex detection incorrect

### ISSUE THREAD

**Issue by casey** [ordinals/ord#2052]
Our taproot annex detection code looks wrong. It is currently:

```rust
    let script = witness
      .iter()
      .nth(if annex {
        witness.len() - 1
      } else {
        witness.len() - 2
      })
      .unwrap();
```

But it should be:

```rust
    let script = witness
      .iter()
      .nth(if annex {
        witness.len() - 3
      } else {
        witness.len() - 2
      })
      .unwrap();
```

Id est, if the annex is present, we look one more element back for the script.

**Comment by panicfarm** [comment]
You should prob use [`tapscript()`](https://docs.rs/bitcoin/latest/bitcoin/blockdata/witness/struct.Witness.html#method.tapscript) from `bitcoin::blockdata::witness::Witness`
