### ISSUE TITLE
preview server need bitcoind?

### ISSUE THREAD

**Issue by bitcodernull** [ordinals/ord#2059]
when i run preview server
i got the errors:  
bitcoind is not found

I use the remote bitcoin , Do i need install bitcoind to run preivew

I run the ord server ,It don't need bitcoind

thanks

**Comment by GaloisField2718** [comment]
I have my `bitcoind` which is running and with cookie file specified but I got the same error.

up for solution ^^

**Comment by raphjaph** [comment]
yes, you need bitcoind for all commands.
