### ISSUE TITLE
how can i make ord cli interacting with my website

### ISSUE THREAD

**Issue by SharinganKazekage** [ordinals/ord#2060]
hey any idea how can i make ord cli interacting with my website ? i have my own node right now

**Comment by zhwindy** [comment]
Actually no, ord wallet client not provide external api

**Comment by GaloisField2718** [comment]
Maybe running a js or python script from your website which can make command in `ord`. 

I think about it but maybe there are vulnerabilities which should be considered. Nevertheless, in localhost it can be possible to have a first try. 

Interested to chat about it :)

**Comment by SharinganKazekage** [comment]
> Maybe running a js or python script from your website which can make command in `ord`.
> 
> I think about it but maybe there are vulnerabilities which should be considered. Nevertheless, in localhost it can be possible to have a first try.
> 
> Interested to chat about it :)

I created and make it interact with my website, don't do that people would run malicious code in your server

**Comment by M1chlCZ** [comment]
There is no issue with making calls to cli (through some custom API], which will then return JSON, so you can then parse it and show it as needed.

**Comment by SharinganKazekage** [comment]
> There is no issue with making calls to cli (through some custom API], which will then return JSON, so you can then parse it and show it as needed.

how

**Comment by M1chlCZ** [comment]
> > There is no issue with making calls to cli (through some custom API], which will then return JSON, so you can then parse it and show it as needed.
> 
> how

Normally call it from something like javascript:

```
var exec = require('child_process').exec;

exec('ord wallet inscriptions',
    function (error, stdout, stderr) {
        var result = JSON.stringify(stdout)
		-- use data gathered --
        console.log('stderr: ' + stderr);
        if (error !== null) {
             console.log('exec error: ' + error);
        }
    });
```

Granted, I suck at JS, I copied first stackoverflow solution

Simple...

**Comment by SharinganKazekage** [comment]
> > > There is no issue with making calls to cli (through some custom API], which will then return JSON, so you can then parse it and show it as needed.
> > 
> > 
> > how
> 
> Normally call it from something like javascript:
> 
> ```
> var exec = require('child_process').exec;
> 
> exec('ord wallet inscriptions',
>     function (error, stdout, stderr) {
>         var result = JSON.stringify(stdout)
> 		-- use data gathered --
>         console.log('stderr: ' + stderr);
>         if (error !== null) {
>              console.log('exec error: ' + error);
>         }
>     });
> ```
> 
> Granted, I suck at JS, I copied first stackoverflow solution
> 
> Simple...

there is a library in python subprocess, maybe i can use it you think? it allow to interact with command

**Comment by M1chlCZ** [comment]
> > > > There is no issue with making calls to cli (through some custom API], which will then return JSON, so you can then parse it and show it as needed.
> > > 
> > > 
> > > how
> > 
> > 
> > Normally call it from something like javascript:
> > ```
> > var exec = require('child_process').exec;
> > 
> > exec('ord wallet inscriptions',
> >     function (error, stdout, stderr) {
> >         var result = JSON.stringify(stdout)
> > 		-- use data gathered --
> >         console.log('stderr: ' + stderr);
> >         if (error !== null) {
> >              console.log('exec error: ' + error);
> >         }
> >     });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Granted, I suck at JS, I copied first stackoverflow solution
> > Simple...
> 
> there is a library in python subprocess, maybe i can use it you think? it allow to interact with command

You cat use absolutely any language, which allows you to interact with system. So Python will absolutely work : )
