### ISSUE TITLE
Inscription creation doc assembly code has mistake

### ISSUE THREAD

**Issue by roadbuilder** [ordinals/ord#2075]
the document at https://docs.ordinals.com/inscriptions.html incorrectly shows `OP_1` in the inscription example.

this does not work and does not match the Rust ord code. 

What i tshould have is `OP_PUSHBYTES_1 1` not `OP_1`

Existing doc still shows: 
![image](https://user-images.githubusercontent.com/74831504/236973851-baf902b1-078b-4082-9020-6b079702aba3.png)

Actual working example on sciptpath.info shows the correct value which matches the inscribing code in the Rust tests also: 
![image](https://user-images.githubusercontent.com/74831504/236974005-061cd8b2-7782-435b-9100-e6206827ee99.png)

A clear example of the ord rust code is here: https://github.com/casey/ord/blob/52c4d57ddf515ca828e97694121e67dd263b226e/src/inscription.rs#L397

where `&[1],` can only be achieved by 
`OP_PUSHBYTES_1 1` not `OP_1`

**Comment by raphjaph** [comment]
We've changed it to `OP_PUSH`. Still not technically correct but the docs in that place are just schematic.
