### ISSUE TITLE
error: reorg detected at or before 789147

### ISSUE THREAD

**Issue by onbermejo** [ordinals/ord#2080]
When trying to get the balance it is giving me this error:
error: reorg detected at or before 789147

**Comment by so7ow** [comment]
ord can't handle a re-org gracefully. you need to delete your index.redb and index again from scratch.

**Comment by dumojun101** [comment]
error: reorg detected at or before 2472976

**Comment by raphjaph** [comment]
We finally have reorg resistance: https://github.com/ordinals/ord/pull/2320
