### ISSUE TITLE
Error ord installing in Ubuntu

### ISSUE THREAD

**Issue by BeycanDeveloper** [ordinals/ord#2084]
I am getting this error in install process on the Ubuntu. I already searched and tried some commands and packages but still same.

![image](https://github.com/casey/ord/assets/50718965/322456ee-a125-4701-bf3b-aa317977a6f4)

**Comment by wanyvic** [comment]
try to build from source.

**Comment by raphjaph** [comment]
Please reopen if you still have this problem
