### ISSUE TITLE
error: reorg detected at or before 789603

### ISSUE THREAD

**Issue by zhwindy** [ordinals/ord#2087]
ord wallet client (0.5.2) , how to fix this issue?

**Comment by wanyvic** [comment]
The reorg function is not implemented yet. you can try to add the feature using the 'savePoint' function of redb.
https://github.com/casey/ord/discussions/1951

**Comment by icenberg** [comment]
> ord doesn't handle reorgs so it breaks if there's a reorg which there always are. you need to delete the index.redb file then run ord index again which will reindex from scratch.

Where is this file cant find it ?

**Comment by raphjaph** [comment]
We finally have reorg resistance: https://github.com/ordinals/ord/pull/2320
