### ISSUE TITLE
error: list requires index created with `--index-sats` flag

### ISSUE THREAD

**Issue by GaloisField2718** [ordinals/ord#2089]
Hello everyone,

I am on MacOS and I'm running my node in an external disk not in the default place.

When I run `ord --cookie-file=/path/to/my/cookie.file info ` I get `"index_path": "Default_data_dir"`.

When I run `ord --cookie-file=/path/to/my/cookie.file --index-sats index` nothing happen.

And so, when I try command sats relative like `ord --cookie-file=/path/to/my/cookie.file list 9995fa18c1ac70f81706dd8829f1a7c243952374cd7d3b2471ab38fa34ffeb32:0` I get the error : `error: list requires index created with `--index-sats` flag`.

I suppose that the last issue is related to previous one but I don't know how to modify `index_path`. I tried to specify folders which are on bitcoin node folder but nothing work.

I don't know what can I do and if people had got some similar errors.

**Comment by casey** [comment]
The index needs to be created with the `--index-sats` flag in order for sats to be tracked. Is this fixed if you delete your index and recreate it with `--index-sats`?

**Comment by GaloisField2718** [comment]
Yes indeed thanks it was because I put the satpoint and it doesn't know how to fill I suppose. But yeah now it's running under ord-16 and soon with `--index-sats` when I'll have a bigger disk ^^
Thanks for your answer
