### ISSUE TITLE
Inscription with another tag parsing error 

### ISSUE THREAD

**Issue by l2xl** [ordinals/ord#2100]
According to the docs, an inscription envelop has tagged content inside. Curently there are two tags used:

- 0: content field (means media binary pushes)
- 1: content-type field (like image/png)

If assuming the protocol is scalable it should be able to correctly handle any other tags in an envelop. Effectively it should raise an error or skip unknown tags. The latter is more preferable.

https://blockstream.info/testnet/tx/0f977c533f5038d779a6bb6038692a9ae2e11c5687676cfc4719dc2f082f7ac5?expand

This testnet inscription contains additional tag which is read incorrectly by ord adding the tag to the end of the content
The tag has value 2 and is intended to indicate inscription collection (just FYI)

It looks like it needs just several lines to fix it at the ord sources and allow an inscription to have any extended tags

**Comment by raphjaph** [comment]
We have two kinds of tags, even and odd. If it encounters and unrecognized even tag it won't index. You can add an odd tag though and it should index the inscription
