### ISSUE TITLE
 ord wallet create=> Error: Couldn't connect to host: Resource temporarily unavailable (os error 11)

### ISSUE THREAD

**Issue by starmapz** [ordinals/ord#2102]
Not sure if it is related to my recent version upgrade.

Running bitcoincore at same rpc url as before, but ord wallet create fails after I upgraded the ord wallet. (used to work in older ver)

**Comment by GaloisField2718** [comment]
In general, it's because `bitcoind` doesn't finished to synchronise. 
Rpc url connection was released on `ord` ?
In general it's with cookie-file and no problem of accessing if `bitcoind` is synchronised
