### ISSUE TITLE
Many inscriptions in 1 utxo 

### ISSUE THREAD

**Issue by dvncan** [ordinals/ord#2120]
There are 10 inscriptions in this location, it is causing an error when trying to transfer the inscriptions out of my wallet.

https://ordinals.com/output/2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0

`
error: cannot send 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:20000 without also sending inscription 18e09100b38a7174bdfea4a1c505a16bcdd4af2b4dbed3a1b7cf1cf7ad82dfdei0 at 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:0
error: cannot send 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:30000 without also sending inscription 18e09100b38a7174bdfea4a1c505a16bcdd4af2b4dbed3a1b7cf1cf7ad82dfdei0 at 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:0
error: cannot send 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:40000 without also sending inscription 18e09100b38a7174bdfea4a1c505a16bcdd4af2b4dbed3a1b7cf1cf7ad82dfdei0 at 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:0
error: cannot send 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:50000 without also sending inscription 18e09100b38a7174bdfea4a1c505a16bcdd4af2b4dbed3a1b7cf1cf7ad82dfdei0 at 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:0
error: cannot send 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:60000 without also sending inscription 18e09100b38a7174bdfea4a1c505a16bcdd4af2b4dbed3a1b7cf1cf7ad82dfdei0 at 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:0
error: cannot send 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:70000 without also sending inscription 18e09100b38a7174bdfea4a1c505a16bcdd4af2b4dbed3a1b7cf1cf7ad82dfdei0 at 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:0
error: cannot send 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:80000 without also sending inscription 18e09100b38a7174bdfea4a1c505a16bcdd4af2b4dbed3a1b7cf1cf7ad82dfdei0 at 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:0
error: cannot send 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:90000 without also sending inscription 18e09100b38a7174bdfea4a1c505a16bcdd4af2b4dbed3a1b7cf1cf7ad82dfdei0 at 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:0
error: cannot send 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:100000 without also sending inscription 18e09100b38a7174bdfea4a1c505a16bcdd4af2b4dbed3a1b7cf1cf7ad82dfdei0 at 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:0
error: cannot send 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:110000 without also sending inscription 18e09100b38a7174bdfea4a1c505a16bcdd4af2b4dbed3a1b7cf1cf7ad82dfdei0 at 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:0
error: cannot send 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:133950 without also sending inscription 18e09100b38a7174bdfea4a1c505a16bcdd4af2b4dbed3a1b7cf1cf7ad82dfdei0 at 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:0
error: cannot send 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:143950 without also sending inscription 18e09100b38a7174bdfea4a1c505a16bcdd4af2b4dbed3a1b7cf1cf7ad82dfdei0 at 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:0
`

**Comment by Werwolf888** [comment]
Yes I too have the same problem for the inscriptions created yesterday. :(((
It's a critical bug! I think the developers need to pay attention to this long-standing problem and finally solve it in some way.
