### ISSUE TITLE
Create Hash/

### ISSUE THREAD

**Issue by aguinaldok4** [ordinals/ord#2124]
https://docs.github.com/en/communities/documenting-your-project-with-wikis/creating-a-footer-or-sidebar-for-your-wiki#creating-a-sidebar

If you create a file named _Footer.<extension> or _Sidebar.<extension>, we'll use them to populate the footer and sidebar of your wiki, respectively. Like every other wiki page, the extension you choose for these files determines how we render them.

**Comment by veryordinally** [comment]
Please be more specific and use this repo for ordinals-related issues only.
