### ISSUE TITLE
Install script failing?

### ISSUE THREAD

**Issue by so7ow** [ordinals/ord#2129]
Multiple reports in the Discord tech-support channel of no response when running this install command:

`curl --proto '=https' --tlsv1.2 -fsLS https://ordinals.com/install.sh | bash -s`

Has anything changed recently in the script?

**Comment by osvaldorosales96** [comment]
Same here, I used the command a month ago without a problem and now it returns no response.
There is no problem downloading the script with curl, apparently the problems is running it

**Comment by MDevG** [comment]
Same issue here. I've built it from source code as a workaround.

**Comment by creamplanet** [comment]
I noticed the same problem. Looks like someone figured out that it was due to "casey/ord" instead of "ordinals/ord" https://github.com/ordinals/ord/pull/2155.

**Comment by LightRider5** [comment]
Yes, the repo was renamed. I created a PR. #2155
