### ISSUE TITLE
Considering revisiting the inscription content wire format

### ISSUE THREAD

**Issue by lgalabru** [ordinals/ord#2137]
The current content type approach is expensive and limiting the kind of content that can be done through Inscriptions. 
We sometime see the content type of inscriptions being mis-qualified, because the content type is not available in the wire-format.
It'd be great to revisit this inscription content wire format, taking into accounts feedbacks from this community (ie metadata for all these JPEGs), and leveraging the work and thoughts that went into other projects.
There are a lot of fascinating ideas behind [IPLD](https://ipld.io) that were battle tested through IPFS and that would add a new dimension to ordinals.

Inscription content type officially supported: 
https://github.com/ordinals/ord/blob/03f6867755c246cf4ea64b9d85134558ce06b9b5/src/media.rs#L19-L40

**Comment by lgalabru** [comment]
Erratum, the content type is present in the inscription `text/plain;charset=utf-8`.
The issue is coming from something else.

**Comment by tyjvazum** [comment]
@lgalabru, I like the concepts. What do you have in mind specifically?

I think issue https://github.com/ordinals/ord/issues/1523 might have been similar in terms of both content type and metadata ideas, which @casey shot down before, as you can see in the comments.

I agree with you that both things are quite desirable. I already support arbitrary metadata in [arb](https://github.com/tyjvazum/arb) and would like to do something with the content types. Let's work on these.

**Comment by casey** [comment]
This issue is too general.
