### ISSUE TITLE
Weird bug! The inscription image is not displayed, although the content length and content type are displayed correctly.

### ISSUE THREAD

**Issue by Werwolf888** [ordinals/ord#2143]
One of inscriptions is not displaying although the content length and content type are displayed correctly.
There is a blank space displayed instead of an image. There seems to be a bug in the inscription creation process. 
The other inscriptions in the same collection, which contain similar images, are displayed successfully.
This corrupted inscription was created via ORD wallet on VPS with full bitcoin node. 

Parameters of the inscription after creation:
{
  "commit": "dfa51dd18e1a3904c0c653e839e803afcb98ce3b5e84f385c6787d637c3ab6a0",
  "inscription": "8f1d7a8bafe6f5ecf76601de4ed22a8cd3a6d0f9c681dde3fd44445e10eab43di0",
  "reveal": "8f1d7a8bafe6f5ecf76601de4ed22a8cd3a6d0f9c681dde3fd44445e10eab43d",
  "fees": 84800
}
Link:
https://ordinals.com/inscription/8f1d7a8bafe6f5ecf76601de4ed22a8cd3a6d0f9c681dde3fd44445e10eab43di0

<img width="878" alt="Screenshot 2023-06-02 at 17 54 45" src="https://github.com/ordinals/ord/assets/111801153/f6fb494d-d038-4eaa-8bbb-f73ac4ecc626">

**Comment by raphjaph** [comment]
Should be displaying now. Was probably a caching issue
