### ISSUE TITLE
How to set the amount of sats linked to the ordinal

### ISSUE THREAD

**Issue by PRChain** [ordinals/ord#2159]
Like the '546sats' in the pic:
![image](https://github.com/ordinals/ord/assets/35719581/782c5414-c6cd-4034-8c54-d585c690d288)

I can't find a option use " ord wallet inscribe  --help"

**Comment by PRChain** [comment]
This's mine, always 10000
![image](https://github.com/ordinals/ord/assets/35719581/17d34068-1f1c-4fbb-852c-3bb7c6c4e518)

It's the txt:
![image](https://github.com/ordinals/ord/assets/35719581/1da4e233-b67f-4ccd-9618-9e29152d1873)

On testnet.

**Comment by omarkilani** [comment]
https://github.com/ordinals/ord/pull/1994

**Comment by raphjaph** [comment]
You can now set a custom postage: https://github.com/ordinals/ord/pull/2331
