### ISSUE TITLE
"Time traveler Sats"?!

### ISSUE THREAD

**Issue by ryguy077** [ordinals/ord#2179]
The same sat is in 2 different outputs at the same time on Ordinals.com

I tried to "cut" all but 1 sat from the original output, and somehow the ranges overlap now indexed.

The same sat in 2 places at once

/output/51e891b737ae9a745baa0d77ee9942e452d73304f41d1325a2644890ea8eca55:1
/output/0bcb99da94250a66cd7187ad165dff2b461a7ad30581a5ba1e34492f76abbbee:0

[https://imgur.com/cVnnWp7](url)
[https://imgur.com/D67IDy5](url)

**Comment by casey** [comment]
I checked, and output 0bcb99da94250a66cd7187ad165dff2b461a7ad30581a5ba1e34492f76abbbee:0 has been spent, so it contains no sats.

**Comment by ryguy077** [comment]
> I checked, and output 0bcb99da94250a66cd7187ad165dff2b461a7ad30581a5ba1e34492f76abbbee:0 has been spent, so it contains no sats.

Still an issue imo Casey, breaks ordinal because you won't find a utxo that has the sat ending in 441, and you'll see the sat ending in 440 in 2 UTXOs (same place same time)

https://ordinals.com/output/ff63870e0ce35d94ce99500a52c3929e0f739140eac8493657e50e10b97f4a96:0
https://ordinals.com/output/51e891b737ae9a745baa0d77ee9942e452d73304f41d1325a2644890ea8eca55:0

2 current UTXOs. 

Sat ending in 440 is in 2 places at once, 441 doesn't exist unless I'm missing something. I can still ord find the *441 sat and satpoint, but try to find a UTXO it's in

**Comment by Psifour** [comment]
The sat ending in 440 is only in one of those places. Range is [start,end) not [start,end]

441 is located in the UTXO I provided just now.

**Comment by casey** [comment]
Ranges are half-open, meaning that they don't contain the final sat in the range. So sat range `[742707557807033–742707557828440]` does not contain sat 742707557828440.
