### ISSUE TITLE
redb slow down when bump to v0.20.0 compare with v0.17.0

### ISSUE THREAD

**Issue by BillZong** [ordinals/ord#2183]
@casey @raphjaph 
Hi, casey, raph.

I've tried redb version v0.17.0 about 2 weeks ago.
The configs are default, we only modified the commit step from 5000 blocks to 5000 cache_values or 10 blocks.
The time consuming when indexing main net  is OK in AWS node.
While bumping redb version to v0.20.0 or v0.22.0, the time consuming increases significantly.

https://github.com/cberner/redb/issues/603
I've tried what cberner descibed: "make a BTreeMap for faster insertion before commit".
Tried with 8GB cache, sorted commit, and don't find too much improvement IMO.

Here are some flame graphs I've taken. Hope it will help.
I didn't benchmark v0.17.0 yet, due to not compatible db file version and lots of tests failed when downgrade database version.
But I'll keep an eye on it, and update this issue once it get done.

* v0.20.0
![flamegraph-v0 20 0](https://github.com/ordinals/ord/assets/4676655/0036a349-0c81-4ed4-8fac-a6b6346e914c)

* v0.22.0
![flamegraph-v0 22 0](https://github.com/ordinals/ord/assets/4676655/5cb6ddaf-28c5-4f01-a914-05ebd92aa1a9)

* v0.22.0-sorted-commit
![flamegraph-v0 22 0-sorted-commit](https://github.com/ordinals/ord/assets/4676655/ab0d2913-ba21-488f-8882-89efcb0a4247)

**Comment by veryordinally** [comment]
We merged redb 1.0.2 - indexing performance comparable to 0.13.0 with sufficient cache.
