### ISSUE TITLE
Towards OIPs - Ordinals Improvement Proposals; draft repo started

### ISSUE THREAD

**Issue by Anarkoic** [ordinals/ord#2184]
As Ordinals continues to grow, it could be close to time for an Improvement Proposal structure.

I offer up this draft repo as a start towards that:

https://github.com/Anarkoic/oips

It includes a template and one proposal which I will mention in a separate issue.

Template:

https://github.com/Anarkoic/oips/blob/main/oip-template.md

Feedback invited.

**Comment by tyjvazum** [comment]
@Anarkoic, I think there should be an OIP structure too. Some work is being done at https://github.com/ordocs/oip. Additionally, a related discussion can be found at https://github.com/ordinals/ord/discussions/2156.

**Comment by casey** [comment]
I'm not sure we need a formal OIP structure at the moment. GitHub issues are probably okay for now. Others are free to do this though.
