### ISSUE TITLE
OIPs draft: Extensible Headers for Inscriptions, in particular for Protocol level compression support

### ISSUE THREAD

**Issue by Anarkoic** [ordinals/ord#2185]
I've started drafting an Ordinals Improvement Proposal for protocol-level support for additional HTTP header mapping. The main motivation here is for compression support, given that Inscription file size is key. Current approaches are less than ideal.

Here's a preliminary draft, which can be fleshed out further if there's interest

https://github.com/Anarkoic/oips/blob/main/OIPS/oip-draft-extensible-headers.md

**Comment by Anarkoic** [comment]
Thanks, great points, will think through these some more.

**Comment by tyjvazum** [comment]
@Anarkoic, I support compression in [arb](https://github.com/tyjvazum/arb) if you want to take a look.
