### ISSUE TITLE
Recursive Inscription links not working on iOS Safari

### ISSUE THREAD

**Issue by bruffstar** [ordinals/ord#2187]
It appears that /content/ links are not working on Safari on iOS in the block explorer. 

Example: https://ordinals.com/inscription/cf58bbc5db189aab538c927dc7cabcb399d06868ef64e163d408a8abdd8c479ci0

The iframe loads, but the linked content does not: 

<img width="314" alt="image" src="https://github.com/ordinals/ord/assets/1890098/fbb00f06-b9bd-41b2-bd61-486fd4401298">

**Comment by casey** [comment]
Unfortunately this is a known issue that can't be fixed. Safari doesn't implement the content security policy header spec correctly, so the whitelisting method used to allow requests to `/content/` paths doesnt' work.
