### ISSUE TITLE
How to split one UXTO that contains 4 inscriptions?

### ISSUE THREAD

**Issue by pdm1230** [ordinals/ord#2191]
aa

**Comment by omarkilani** [comment]
You need to move the satpoints from the back of the output to the front.

**Comment by pdm1230** [comment]
>

**Comment by pdm1230** [comment]
> 

Hi, thanks for your advice. But when I try
`wallet send target_address inscription_4_id`
still get the same error..

**Comment by omarkilani** [comment]
Hi @pdm1230 

Can you see if https://sating.io/ will work for you?

Make sure you send them from the end to the beginning there too. Make sure you have another UTXO at the same address to use for fees.

To make `ord` do this you would need to patch the code to ignore any inscription checks and treat them as raw sats.

**Comment by pdm1230** [comment]
@raphjaph @casey How should I do? Thanks

**Comment by winktool** [comment]
> You need to move the satpoints staring from the back of the output to the front.
> 
> E.g.:
> 
> UTXO1: [ ins1 ins2 ins3 ins4 ]
> 
> Find the sat point for ins4, use `ord wallet send` to move it to a new address.
> 
> Now your UTXOs look like:
> 
> UTXO1: [ ins1 ins2 ins3 ] UTXO2: [ ins4 ]
> 
> Repeat the process for ins3 and ins2.
> 
> The reason you work from the end to the beginning is so you can protect your inscription sat points from being used for fees or as padding for other inscriptions.

How do I achieve this? Can I achieve this using psbt?
