### ISSUE TITLE
How to reduce the block space of recursive inscriptions by more than 80% 

### ISSUE THREAD

**Issue by 0xgeekery** [ordinals/ord#2197]
I recommend supporting the NFT-BRC-721 format for displaying inscriptions, which is a more than 80% reduction in block space for recursive inscriptions.

<img width="987" alt="nft-brc-721" src="https://github.com/ordinals/ord/assets/101918902/8ec5fbb5-4e13-4ec7-8628-7e6aab9d2531">

Contrast:
The following comparison is a random selection of NFTS to make the comparison, different nfts will be different.

<img width="1219" alt="comparison" src="https://github.com/ordinals/ord/assets/101918902/a7ff58e2-472f-4ba1-8320-0276aeb9b6d4">

Reduced storage space:
1000B - 165B =  835B

There are more advantages here:
https://twitter.com/geekey_eth/status/1669539745251328000?s=20

This will mint  an NFT very simple, users only need to mint, users do not need to know HTML and JS.

**Comment by oxJasonPage** [comment]
The structural design is really great.
NFT is not just a picture, it should be a community, a tribe. It's a collection. If you put the parser on the chain, it's more decentralized.

**Comment by bingryan** [comment]
recursive inscriptions are not only designed for NFT, right?

**Comment by oxJasonPage** [comment]
Yes, recursive inscriptions are cross-references between different inscriptions, and developers can build different products based on this feature. I feel that the NFT-BRC-721 architecture is really great and I hope that more people will recognize it.
If we use NFT-BRC-721, the inscription storage space will be greatly reduced.

**Comment by bodily11** [comment]
I think we can get even more efficient than this. You should look at our BitGen standard: 
https://bioniq-1.gitbook.io/bitgen-bitcoin-generative-ordinals-standard-alpha/

**Comment by casey** [comment]
BRC-721 is a nonstarter:

- Uses inefficient text based encoding
- Doesn't provide blockspace savings, since recursive inscription can be as small as `<script src=/content/ID></script>`
- Uses pubkeys, doesn't fit in utxo model
- Super complicated
- Duplicates a bunch of functionality of existing inscriptions
- Points to offchain content
