### ISSUE TITLE
Ordinal Insceiption

### ISSUE THREAD

**Issue by OnlyOneProdigy** [ordinals/ord#2201]
Hey there, 
I have an Image issue with an inscription. It shows a low fidelity image in place of a 4k image I inscribed.
Here is the Inscription ID  67c6552f15b42f7981b0da2a9a0445039b7a11595b2642a36dae11a46a4d2eaai0
what do I need to do to correct this image to a 4k, It appears to be a thumbnail image. 
https://magiceden.io/ordinals/item-details/67c6552f15b42f7981b0da2a9a0445039b7a11595b2642a36dae11a46a4d2eaai0
Thank you

**Comment by raphjaph** [comment]
We only show content that has been put on-chain. You cannot change what you have inscribed.
