### ISSUE TITLE
Raise signet limit from 1024 bytes to match mainnet limit?

### ISSUE THREAD

**Issue by thecolorblocks** [ordinals/ord#2216]
With the release of recursive inscriptions, might there be a need to test recursive and dynamic ordinal inscriptions on signet first before releasing to mainnet? We tried to upload a javascript file of about 600,000 bytes on signet and could not do so.

**Comment by casey** [comment]
Signet does not have a fee market, and is a shared resource, so the low limit is intentional. You can use regtest, which doesn't have a size limit, for testing.
