### ISSUE TITLE
Should we provide runtime environment for executing JavaScript code

### ISSUE THREAD

**Issue by sondotpin** [ordinals/ord#2221]
When we insribe js code to insription, there is a requirement to provide a runtime environment. Is there a plan?

**Comment by onchainguy-eth** [comment]
What is the use case for this?

**Comment by sondotpin** [comment]
Can create a fully onchain game with server in a nodejs runtime environment, and code in an insription

**Comment by onchainguy-eth** [comment]
You can do that already by inscribing the JS code and then loading it on a node JS server yourself.

**Comment by casey** [comment]
Inscriptions can use the browser JS runtime.
