### ISSUE TITLE
testnet.ordinals.com displays someone's resume

### ISSUE THREAD

**Issue by so7ow** [ordinals/ord#2226]
I believe this should be the testnet version of ordinals.com, no? It's currently displaying some kind of resume template or something.

<img width="1098" alt="Resume_-_Start_Bootstrap_Theme" src="https://github.com/ordinals/ord/assets/633079/d929b5c8-5bae-4164-ba02-38abda2d14b7">

**Comment by veryordinally** [comment]
Removed the DNS entries for testnet.ordinals.com and signet.ordinals.com until we have those explorers up and running again. Had stopped running them due to disk space shortage.

**Comment by veryordinally** [comment]
https://github.com/ordinals/ord/issues/2227
