### ISSUE TITLE
Allow customizing inscription postage

### ISSUE THREAD

**Issue by pokrovskyy** [ordinals/ord#2235]
Currently it is not possible to customize inscription postage which defaults to 10,000 sats. It seems a reasonable feature to add, both to decrease postage as well as increase it. Any hint on implementing this or is it too convoluted?

**Comment by gmart7t2** [comment]
https://github.com/gmart7t2/ord has a `--postage` flag that does what you're looking for

**Comment by raphjaph** [comment]
we allow this now as well
