### ISSUE TITLE
After Update to 0.8.0 - error: DB corrupted

### ISSUE THREAD

**Issue by TheRealFuture42** [ordinals/ord#2239]
After update my ord wallet i run into the following error:

```
ord --index-sats ... wallet inscriptions
error: DB corrupted: Expected file format version 1, found 109
```

**Comment by so7ow** [comment]
You need to reindex for the new version. Rename/delete index.redb and run the index from scratch.

**Comment by TheRealFuture42** [comment]
I had guessed :(

**Comment by nick07002** [comment]
> You need to reindex for the new version. Rename/delete index.redb and run the index from scratch.

somehow I cannot find index.redb anywhere, do you happen to know the location of it?

**Comment by so7ow** [comment]
It depends on your operating system. Defaults to ~/Library/Application Support/ord in macOS. %appdata%\ord in Windows. Linux, you're on your own. Search for index.redb...

**Comment by nick07002** [comment]
after deleting, it started indexing and keep failing again:

[indexing blocks] ███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████░░░░░░ 767427/798578[2023-07-13T23:28:39Z ERROR ord::index::updater] Couldn't receive txs expected value at line 1 column 1
[indexing blocks] ███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████░░░░░░ 767429/798578[2023-07-13T23:29:11Z ERROR ord::index::updater] Couldn't receive txs expected value at line 1 column 1

**Comment by raphjaph** [comment]
That should be a recoverable error. Does it make no progress at all?

**Comment by raphjaph** [comment]
Going to close since this seems to be solved. If not please comment and reopen.
