### ISSUE TITLE
Extremely slow indexing at 0.8.0

### ISSUE THREAD

**Issue by victorkirov** [ordinals/ord#2241]
I don't know if it's just me but indexing at 0.8.0 is incredibly slow.

At 0.7.0 and before, it used to race until the first block that had ordinals and then take a few ms to 2 secs to process each block.

With 0.8.0, it processes the inscriptionless blocks very fast and, once it gets to block 767430, it immediately starts taking between 1 and 60 seconds per block.

Update: I switched back to ord 0.6.2 and indexing is definitely much faster at 0.1 to 2 secs a block

**Comment by omarkilani** [comment]
The indexer is now fsyncing to disk every 5000 blocks, which makes it take much longer.

**Comment by victorkirov** [comment]
It doesn't actually get to the fsync part though. 

I have RUST_LOG set to info. If I query the blockheight, I get 764999, so it's synced up to that block and is in the process of indexing blocks 765000 to 770000 before running an fsync. Each block is taking anywhere between 1 and 60 seconds to index, completely randomly. One block might take 55 seconds and the next one about a second, then the next 25 seconds. They all have a similar amount of transactions in each block.

As mentioned, 0.6.2 runs quickly and steadily in the same chunk of blocks.

**Comment by omarkilani** [comment]
Hmmm...

You could try passing in different values of db cache size:

https://github.com/ordinals/ord/commit/594c14f4fb9880fadf24f487feeaeb4fc03f6283

To see if that helps?

**Comment by victorkirov** [comment]
Magic! It worked! Thank you 😄

**Comment by victorkirov** [comment]
Out of interest, what was the default before? Did it just use as much as it could?

I have 64gb on my server so it must've been using 16gb when it was slow. I switched it to 25gb and now it's fast. Wondering what the magic number is.

**Comment by victorkirov** [comment]
Wait, I lied. It's fast initially then it slows down a lot very rapidly. Will try and dig a bit deeper.

**Comment by bingryan** [comment]
@victorkirov  Can you show the screenshot of CPU, memory and disk usage?

**Comment by victorkirov** [comment]
It's all good. This was on my NAS with NAS drives. On an NVME, it's very close to the speed of previous versions, so no biggy.
