### ISSUE TITLE
[bug] when i execute `ord server` got internal eror

### ISSUE THREAD

**Issue by weixuefeng** [ordinals/ord#2243]
```
thread 'main' panicked at 'internal error: entered unreachable code', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/redb-0.13.0/src/multimap_table.rs:110:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by weixuefeng** [comment]
> ```
> thread 'main' panicked at 'internal error: entered unreachable code', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/redb-0.13.0/src/multimap_table.rs:110:18
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```

i have not runner user

**Comment by victorkirov** [comment]
Are you on version 0.7.0? There was this issue with redb which should be fixed in 0.8.0.

https://github.com/ordinals/ord/issues/2218

**Comment by nick07002** [comment]
> Are you on version 0.7.0? There was this issue with redb which should be fixed in 0.8.0.
> 
> #2218

0.8.0 has this issue too. 
same error

**Comment by weixuefeng** [comment]
> when i use 0.8.0, it's worked.

**Comment by nick07002** [comment]
after deleting the redb file, indexing started and then failed like below, tried a couple times, same error.


after deleting, it started indexing and keep failing again:

[indexing blocks] ███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████░░░░░░ 767427/798578[2023-07-13T23:28:39Z ERROR ord::index::updater] Couldn't receive txs expected value at line 1 column 1
[indexing blocks] ███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████░░░░░░ 767429/798578[2023-07-13T23:29:11Z ERROR ord::index::updater] Couldn't receive txs expected value at line 1 column 1

**Comment by raphjaph** [comment]
Going to close since this seems to be solved. If not please comment and reopen.
