### ISSUE TITLE
index run stop at 767435/797003

### ISSUE THREAD

**Issue by supriwahyu** [ordinals/ord#2245]
when i run ord it stop at 767435/797003, bitcoind is all sync, but ord is stop and could not make any progress, i use 0.8.0, can someone help me? please

**Comment by krishnadude98** [comment]
which command u are using for ord syncing

**Comment by supriwahyu** [comment]
i use ord --bitcoin-data-dir <my-bitcoin-directory> index run, i use linux and install bitcoin core using snap the directory is different so i use --bitcoin-data-dir, well its not actually stop, but its really really slow progress, but i cant finish it, because its always indexing, and so till now i still cant inscribe, and thanks for the response

**Comment by krishnadude98** [comment]
try bitcoin-cli getindexinfo and check whether latest best block is same as that of  bitcoin-cli getblockchaininfo header

**Comment by supriwahyu** [comment]
i was checked it, its said my best_block_height: 798514 and the headers: 800314, its different, probably its because i stop sync 2 weeks ago, so its 14 days behind, i just start sync it again, but the issue is when i was indexing with ord its really slow, even tho my bitcoind is sync with trindex also, is that normal?

**Comment by krishnadude98** [comment]
mine seems pretty fast right now are u using ord latest version 0.8.1?

**Comment by supriwahyu** [comment]
not yet, i just installed it but not use it yet, maybe this update will fix the issue, thanks again for responding

**Comment by raphjaph** [comment]
This could be because of a reorg. The new release prevents this so you will have to delete the database, download the new version and reindex. Should work cleanly from then on onwards.
