### ISSUE TITLE
preview scaling distorting images

### ISSUE THREAD

**Issue by SerRat44** [ordinals/ord#2247]
i am inscribing somebodies collection on special sats, it is a collection of 800x800 pixel bitcoin inspired abstract art and is is not scaling well in the previews on ordinals.com or ord.io but it looks amazing on ME, you can verify the real image quality by saving or checking the content preview. you can see in the examples provided it is shifting entire rows of pixels around.

it would be really great if we could solve this, the art is incredible and deserves to be seen with the correct scaling. thank you.

ordinals.com examples:
https://ordinals.com/inscription/0286cc778ee8beecbed6d9331dbb6f6197c7e30322ed9637a8ddcf4d6ae00989i0
https://ordinals.com/inscription/83c102a93b72fcc0ff378d59e5fb6e94619f23e32eac860f793aebde7ce11962i0
https://ordinals.com/inscription/ba056b19235cd4132cfe035f478500ce11f30e725c4753f2d012172ab9d81ba8i0
https://ordinals.com/inscription/e1c38ca5d510dd601444968ea083ec3aa1f705dc55e96a8a1cef4439340f6386i0

same items on ME:
https://magiceden.io/ordinals/item-details/0286cc778ee8beecbed6d9331dbb6f6197c7e30322ed9637a8ddcf4d6ae00989i0
https://magiceden.io/ordinals/item-details/83c102a93b72fcc0ff378d59e5fb6e94619f23e32eac860f793aebde7ce11962i0
https://magiceden.io/ordinals/item-details/ba056b19235cd4132cfe035f478500ce11f30e725c4753f2d012172ab9d81ba8i0
https://magiceden.io/ordinals/item-details/e1c38ca5d510dd601444968ea083ec3aa1f705dc55e96a8a1cef4439340f6386i0

**Comment by raphjaph** [comment]
I just looked at it and it renders fine for me on both /content and /preview. No shifting of rows either. Which browser did you use?

**Comment by SerRat44** [comment]
its fine when i click on the actual links but when i look from this link i can clearly see that its missing entire lines of pixels, the numbers in the bottom left and the info on the right is impossible to read. on ME its pretty clear, i can read all the small text no problem. also it works fine on mobile, only desktop is skipping rows of pixels

https://ordinals.com/inscription/f75d08660276fc2b5fa474e748032cccfc268ac16a3c0e380f4886e8a46535a0i0

**Comment by casey** [comment]
I think this is just an artifact of the size that it's rendered at. Try making the window smaller on ordinals.com, and as the inscription scales down, you'll see that it can look better at smaller sizes. I don't think there's much we can do here.
