### ISSUE TITLE
Inscribing onto coinbase is not an unbound inscription.

### ISSUE THREAD

**Issue by wanyvic** [ordinals/ord#2249]
https://github.com/ordinals/ord/blob/11913c491ab78f5a4bc95e300b138b48b1376af3/src/index/updater/inscription_updater.rs#L330-L339

The outpoint in line 333 is null, but `flotsam.origin.unbound` is not equal to `true`.

https://ordinals.com/inscription/c1e0db6368a43f5589352ed44aa1ff9af33410e4a9fd9be0f6ac42d9e4117151i0
![image](https://github.com/ordinals/ord/assets/26783673/a34f017c-e09b-4c07-a66f-fc2e5827397e)

Should `unbound` also be set to `true` in this case?

**Comment by casey** [comment]
It's okay for unbound inscriptions to have positive inscription numbers.
