### ISSUE TITLE
error: JSON-RPC error: transport error: HTTP response too short: length 0, needed 12.

### ISSUE THREAD

**Issue by jerrygzy** [ordinals/ord#2254]
my bitcoin node is running in macos docker, with port 8332 - 8333 mapped,  

in the macos terminal, I tested port 8332 is OK,

```
nc -vz 127.0.0.1 8332
Connection to 127.0.0.1 port 8332 [tcp/*] succeeded!
```

but when I run ord, I got following error,

```
./ord --bitcoin-rpc-user bitcoin --bitcoin-rpc-pass password  server
error: JSON-RPC error: transport error: HTTP response too short: length 0, needed 12.
```

does anyone know what's the problem?

**Comment by raphjaph** [comment]
Sometimes when `bitcoind` hasn't completely started yet or there have been too many requests this happens. The server usually recovers from this without any issue. If you run the wallet command you usually just have to run it again. This is a spurious error and maybe there is an elegant fix for it but it's difficult to reproduce.

**Comment by raphjaph** [comment]
If you can find an elegant way to get rid of this, open a PR :) Closing for now but feel free to reopen.

**Comment by Khademreza3912** [comment]
> Sometimes when `bitcoind` hasn't completely started yet or there have been too many requests this happens. The server usually recovers from this without any issue. If you run the wallet command you usually just have to run it again. This is a spurious error and maybe there is an elegant fix for it but it's difficult to reproduce.

**Comment by Khademreza3912** [comment]
bc1pgqmnmt0kzv43ueg6erlqja35j5gdrm6w8nd7d94y8u34cg7q0k0s0ts7x7

**Comment by Khademreza3912** [comment]
> mapped

48213ee03a9329924720c5ebc23bbf1bc2df12f1
