### ISSUE TITLE
/Content indexing issue.

### ISSUE THREAD

**Issue by elocremarc** [ordinals/ord#2255]
There is a issue with the following inscription on the live version of ordinals.com
https://ordinals.com/content/5c7cf1201531e2ec61df14aa6a82a53b209276e5f9fcfe4daedca060d5deceebi0

A local copy of the index will not reproduce this issue. It works fine on a local explorer.

This inscription renders fine under `/preview` and `/inscription`
However on `/content` it says the inscription doesn't exist. 

Here is the html of the inscription. 
https://github.com/cypherpunklab/manifesto/blob/main/manifesto.html

**Comment by raphjaph** [comment]
Seems to work now. Probably was a caching issue
