### ISSUE TITLE
Add current sat recursive endpoint

### ISSUE THREAD

**Issue by raphjaph** [ordinals/ord#2262]
Discussion: https://github.com/ordinals/ord/discussions/2200

**Comment by casey** [comment]
I'd actually argue that we shouldn't provide an endpoint that  returns the current sat, for a few reasons:

1. The sat which is inscribed is known at inscribe time, and doesn't change. So, the inscriber can just include the sat number / rarity / whatever in the inscription, and no endpoint is needed.
2. If you want to calculate the rarity, number, etc, someone can inscribe a helper JS library which calculates these things, which is then available from any inscription via recursion.
3. If an endpoint which returned the current sat was provided, it would be something like `/sat/INSCRIPTION_ID`, and the caller would be required to provide the correct inscription ID, so there would be no guarantee that the current inscription ID was passed. The caller could pass any inscription ID, to make the endpoint return any inscribed sat.

**Comment by casey** [comment]
Closing this for the reasons above, although this doesn't actually cover what's discussed in #2200. Opening #2277 to track.
