### ISSUE TITLE
Available endpoints

### ISSUE THREAD

**Issue by anbello** [ordinals/ord#2263]
I would like to know which other of this endpoints 
https://github.com/ordinals/ord/blob/master/src/subcommand/server.rs#L145
are available from inside an inscription other then the ones described here:
https://docs.ordinals.com/inscriptions.html#recursion

Thanks
Andrea

**Comment by casey** [comment]
Available endpoints are [documented here](https://docs.ordinals.com/inscriptions/recursion.html), all other endpoints are unavailable.
