### ISSUE TITLE
Stopping "ord --index-sats index" takes a long time with 0.8

### ISSUE THREAD

**Issue by wagmiwiz** [ordinals/ord#2265]
It takes between 20 and 30 minutes to **stop** ord that is indexing sats.

A few times I thought something was wrong and then force closed it. This then resulted in super long start times (which I assume is due to db recovery https://github.com/ordinals/ord/issues/2256).

Posting this in case there is something that can be optimised during the shutdown process. If it is what it is then please close the issue of course :)

**Comment by gus4rs** [comment]
It didn't fix it, see https://github.com/ordinals/ord/issues/3819 and https://github.com/ordinals/ord/issues/3469
