### ISSUE TITLE
Overflow error compiling miniscript on macOS

### ISSUE THREAD

**Issue by sangaman** [ordinals/ord#2271]
```
  Compiling miniscript v9.0.1
error[E0275]: overflow evaluating the requirement `F: FnMut<(&Pk,)>`
  |
  = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`miniscript`)
  = note: required for `&mut F` to implement `FnMut<(&Pk,)>`
  = note: 128 redundant requirements hidden
  = note: required for `&mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut ...` to implement `FnMut<(&Pk,)>`
  = note: the full type name has been written to '/Users/dmcnally/github/ord/target/release/deps/miniscript-93579cecabee682e.long-type-10470458130272265009.txt'

For more information about this error, try `rustc --explain E0275`.
```

I'm using `rustc 1.71.0 (8ede3aae2 2023-07-12)` on an amd64 macOS ventura machine.

**Comment by raphjaph** [comment]
I tried to reproduce but everything works on my Mac. What command are you using to compile and are you compiling from master?

**Comment by veryordinally** [comment]
Had another report, but also can't reproduce. Is this using the latest rust version 1.71.0?

**Comment by raphjaph** [comment]
I'm using the exact same rust version (`rustc 1.71.0 (8ede3aae2 2023-07-12`).

**Comment by veryordinally** [comment]
Seems to be this https://github.com/rust-lang/rust/issues/110475

**Comment by veryordinally** [comment]
Workaround is here: https://github.com/uncomputable/rust-simplicity/commit/1b8a825e8919c6205b7ae05a4fdafd6134baa0d8

**Comment by billyrestey** [comment]
Confirming rolling back to rust 1.70.0 didn't produce the error. Good enough for me for now!

thank you for the suggestion @veryordinally

**Comment by niftynei** [comment]
this worked for me to fix/patch over the problem: https://github.com/ordinals/ord/pull/2280
