### ISSUE TITLE
GLTF/GLB files not showing correctly on explorer

### ISSUE THREAD

**Issue by AdditiveFiles** [ordinals/ord#2274]
**Issue Overview:**
Currently, when requesting or fetching GLTF/GLB files using the /content/inscription_id endpoint in our application, the files are being served without any file extension. This creates inconvenience and inconsistency as the files should ideally be served with their appropriate extensions for proper identification and usage.

**Expected Behavior:**
We expect the GLTF/GLB files to be served with their respective extensions when requesting or fetching them through the /content/inscription_id endpoint. This would enable seamless integration and consistent handling of the files across our application.

**Steps to Reproduce:**
Make a request or fetch the GLTF/GLB file using the /content/inscription_id endpoint.
Observe the response and note that the file is served without any file extension.

**Additional Information:**
This issue affects our application's functionality and makes it challenging to process the GLTF/GLB files correctly. It is important to serve the files with their appropriate extensions for compatibility with other systems and tools that rely on these file formats. We believe that addressing this issue would enhance the overall usability and interoperability of our application.

Please let me know if any further information is required.

**Comment by raphjaph** [comment]
The data model of inscriptions is that of a HTTP response so the MIME type of the file is set in the `Content-Type` header. The .glb file extension has the MIME type `model/gltf-binary`.

**Comment by billyrestey** [comment]
Noticing that ordinals.com recognizes the MIME type correctly (model/gltf-binary) but the frontend is not displaying the 3D object properly.

example: https://ordinals.com/inscription/d0567fd09a67cc512a9270d8f55d2e891b78d6026f13a370ffed570e494f1100i0

other explorers seem to be displaying properly:
Ordiscan - https://ordiscan.com/inscription/17486115
Ord io - https://www.ord.io/11637870

![image](https://github.com/ordinals/ord/assets/127281751/db9e7874-908f-4c63-8959-329da5bfa5ca)

**Comment by raphjaph** [comment]
Ok good catch, will reopen

**Comment by raphjaph** [comment]
Still have to deploy to ordinals.com but just merged #2369
