### ISSUE TITLE
Improve  performance of `wallet inscriptions` by iterating first over outputs instead of all inscriptions

### ISSUE THREAD

**Issue by veryordinally** [ordinals/ord#2282]
We currently iterate over all inscriptions (currently >16 million), and check for every single one if the satpoint is in our wallet. For wallets with typical number of outputs it would be much more efficient to iterate over outputs and check if it has an inscription.

_Originally posted by @raphjaph in https://github.com/ordinals/ord/pull/2279#discussion_r1264747317_

**Comment by gmart7t2** [comment]
This is how I fixed this issue: https://github.com/gmart7t2/ord/commit/8b105818b9dbadd170250e519b7be9d7cdae37a4

**Comment by gmart7t2** [comment]
I made a PR for my fix for this: #2310

**Comment by raphjaph** [comment]
Closed by #2310
