### ISSUE TITLE
Cursed inscription not showing

### ISSUE THREAD

**Issue by victorkirov** [ordinals/ord#2289]
This is a strange one. There is a cursed inscription coming up here: https://cursedordinals.com/inscription/3a6e2be9c9ff2b9cc533c020774e47ccb33910252c15ccf563876097aace755ai0

But not on ordinals.com:
https://ordinals.com/inscription/3a6e2be9c9ff2b9cc533c020774e47ccb33910252c15ccf563876097aace755ai0

What I noticed is the content type looks a bit strange. From the witness hex, the inscription seems to have this as its content type: `text/plain;charset=utf-8Bcursed` 
or hex
`18746578742f706c61696e3b636861727365743d7574662d38014206637572736564`

Is that why it's not showing up on ord? Should it be showing up? 👀

**Comment by casey** [comment]
This inscription should show up on latest master.

**Comment by victorkirov** [comment]
> This inscription should show up on latest master.

Awesome! Thanks. Will it require a re-index?

**Comment by casey** [comment]
Yup, it will, unfortunately T_T

**Comment by victorkirov** [comment]
🙈 Cool, thank you for sorting it out! I'll wait for the official v0.9.x release 🙌
