### ISSUE TITLE
Is it possibility to Import Ord Wallet to another wallet?

### ISSUE THREAD

**Issue by TheRealFuture42** [ordinals/ord#2293]
Is it possibility to Import Ord Wallet to another wallet like Unisat, Xverse,Hero, Ordinalsafe?

**Comment by veryordinally** [comment]
Yes, the 12 word seed phrase can be imported, and ord used a standard taproot derivation path. But, the mentioned wallets may still not find the inscriptions and BTC in the ord wallet - at least for Unisat and Xverse, they don't behave like a normal Bitcoin HD wallet, but instead just derive one fixed address from the seed and just recognize inscriptions there.

**Comment by TheRealFuture42** [comment]
Are there other wallets that do this better?

**Comment by viru9** [comment]
hi @veryordinally , are you talking about importing the Unisat wallet using a single private key ? , if yes how can we see the single private key on ord wallet ?

**Comment by TheRealFuture42** [comment]
I'm not sure if this is technically possible, but if there were a function in the Ord Wallet that would allow me to send inscriptions in bulk to another wallet with a single address (Unisat, Xverse, Hiro, Ordinalsafe) within a single transaction, that would be acceptable. Is that fundamentally possible?

The problem is, I can send each inscription within a script, but that would result in massive transaction costs.

**Comment by TheRealFuture42** [comment]
I have spoken to the Unisat developers but they will not be adding a function to import from Ord Wallet.
