### ISSUE TITLE
ord cannot finish indexing

### ISSUE THREAD

**Issue by vmsobral** [ordinals/ord#2296]
Guys I'm having some trouble indexing with ord. Every time is stops around block 767400 with the following error:

```bash
[2023-07-21T23:47:11Z ERROR ord::index::updater] would sleep for more than 120s, giving up
[2023-07-21T23:47:11Z ERROR ord::index::updater] failed to fetch block 767461: JSON-RPC error: transport error: Couldn't connect to host: Resource temporarily unavailable (os error 11)
```

Althouhg it seems to increase the block count everytime I run `ord index run`, it always stops after a couple of blocks, so it's going to take me forever to finish if I keep like this and I was hoping it has another solution.

I'm running a VM with Manjaro Linux 23.0 in a HDD and I was running bitcoin core in my windows host before, so what I did was sharing the blocks folder with the VM and installing it again inside it. Ord version is:
```
➜  release git:(master) ./ord --version
ord 0.8.0
```

First I installer ord pre-built binary with curl, then I uninstalled it with cargo and tried to build from source but got the same error. Don't really know what to do next.

I guess it may be important to mention that I tried running ord before running Bitcoin Core 25.0 with `txindex=1` set a while ago, and it stopped indexing aroung the same block with the same error. After finishing indexing correctly I tried running again but no success.

Here is my bitcoin.conf
```
server=1
txindex=1
listen=1
irc=1
upnp=1
rpcbind=0.0.0.0
rpcallowip=10.0.2.15
rpcallowip=127.0.0.1
rpcport=8332
```

**Comment by satoshiman** [comment]
I ran `ord -t index run` 

it return `error: reorg detected at or before 2462479`

Do anyone have same problem?

**Comment by vmsobral** [comment]
I've managed to do it. I've created a script to run the indexing automatically every time it stopped by the error I mentioned:
```
#! /bin/zsh
for i in `seq 100`; do echo "executing iteraction $i" && ./ord index run; done
```

I also bought an SSD with enough space for the blockchain so I got much less errors than with the HDD, so I'm closing this.
