### ISSUE TITLE
error: JSON-RPC error: transport error: unexpected HTTP code: 404

### ISSUE THREAD

**Issue by krishnadude98** [ordinals/ord#2305]
ord not able to connect with bitcoind even after my bitcoind is fully signed 
blockchain-cli getblockchaininfo 
```{
  "chain": "main",
  "blocks": 800303,
  "headers": 800303,
  "bestblockhash": "00000000000000000001f06c2783caed9a017c70aeccebcc7eac9e015396bcf9",
  "difficulty": 53911173001054.59,
  "time": 1690349226,
  "mediantime": 1690345530,
  "verificationprogress": 0.9999960449246393,
  "initialblockdownload": false,
  "chainwork": "000000000000000000000000000000000000000050026399b5b7f78996a11610",
  "size_on_disk": 565817502639,
  "pruned": false,
  "warnings": "This is a pre-release test build - use at your own risk - do not use for mining or merchant applications"
}```

still while trying to run 
ord --cookie-file /home/ubuntu/.bitcoin/.cookie --bitcoin-rpc-user hari --bitcoin-rpc-pass hari@123 server --http-port 8332

```error: JSON-RPC error: transport error: unexpected HTTP code: 404
```

**Comment by raphjaph** [comment]
It's either the cookie file or the user and pass, not both at the same time. Try again and let me know.

**Comment by krishnadude98** [comment]
still the same error arises while using ``ord --cookie-file .cookie server``

**Comment by raphjaph** [comment]
So doing `bitcoin-cli getblockchaininfo` works?

If so then just doing `ord server` should also work, since it gets the cookie file from the default location. Try running the following to see the logs: `RUST_LOG=info ord server`

**Comment by casey** [comment]
This is probably a misconfiguration of bitcoind, and not an issue in ord.

**Comment by ylsGit** [comment]
https://github.com/rust-bitcoin/rust-bitcoincore-rpc/issues/323

https://github.com/apoelstra/rust-jsonrpc/issues/106
