### ISSUE TITLE
Need help on finding the single private key (not the 12 word phrase)

### ISSUE THREAD

**Issue by viru9** [ordinals/ord#2306]
Hi team,

I need to know what is my single private key, I already wrote down the 12 word phrase. as I understood I can't load my balance or inscribed images using this 12 words phrase on a Unisat wallet. (I need to list down my inscribed images on Unisat marketplace). I am new to this, please help to resolve this issue. really appreciate your support on this.

thank you.

**Comment by TheRealFuture42** [comment]
#2293

**Comment by casey** [comment]
Ord wallets do not have a single private key, they derive a sequence of many private keys.

**Comment by brunomanzo** [comment]
@casey so how can I export the wallet to import in another computer? this is really not clear anywhere :(

**Comment by so7ow** [comment]
> @casey so how can I export the wallet to import in another computer? this is really not clear anywhere :(
> 
> 

Most modern bitcoin wallets are capable of importing BIP39 seed phrases. 👍🏻
