### ISSUE TITLE
/content /preview caching issues on ordinals.com

### ISSUE THREAD

**Issue by timechainz** [ordinals/ord#2316]
Requests to /content/${inscription_id} and /preview/${inscription_id} are cached even when the response code is 404.  If one attempts to load inscription content prior to inscription confirmation the 404 response is cached for a considerable amount of time (forever?) resulting in incorrect 404 responses after the inscription is confirmed.  

To demonstrate this, I pulled an inscription out of the mempool, and loaded the /inscription, /preview and /content urls.  All returned 404s, as expected since they were not yet confirmed.  After confirmation I tested the same urls.  Results are as follows:

https://ordinals.com/inscription/fcef8ec1251be956a2a917a2cff7194b0d4a0c220ba1a3769104ab944b73c3e0i0  Works
https://ordinals.com/content/fcef8ec1251be956a2a917a2cff7194b0d4a0c220ba1a3769104ab944b73c3e0i0       404
https://ordinals.com/preview/fcef8ec1251be956a2a917a2cff7194b0d4a0c220ba1a3769104ab944b73c3e0i0       404

After confirmation the /preview and /content urls are incorrectly returning a 404 result.

**Comment by raphjaph** [comment]
For not found we've set the cache to the following:
see: `src/subcommand/server.rs` line 880
```rust
    let body = inscription.into_body();
    let cache_control = match body {
      Some(_) => "max-age=31536000, immutable",
      None => "max-age=600",
    };
```
So after 10 minutes the inscription should load. If this is not what you are experiencing and it doesn't show even after an hour please reopen this issue.
