### ISSUE TITLE
A simpler idea for collections

### ISSUE THREAD

**Issue by frkrueger** [ordinals/ord#2324]
I've surveyed the existing proposals which seem over-complicated and not backwards compatible

This proposal aims to solve this in a very neutral way.

A collection (text) ordinal defines the main attributes of the collection. Here’s a proposed format:
{
"p": "collection”,
“op”,”deploy”,
"name": "alaska",
"author": "fred krueger",
"max": "100",
"website": "https://twitter.com/dotkrueger"
}

Unlike brc20s, the namespace is not unique. Multiple people can deploy a collection called “alaska”. They can also create a fake collection called alaska – the website however can list the true origin bitcoin address proving authenticity

Any ordinal can be added to a collection by an ordinal of the form. In this ordinal, you can also specify metadata for the ordinal

{
“p”, “collection”,
“op”, “add”,
“Id”, “a0cec7520dcd60ccca919c2fbb3dcb6c7b6527fe63903c692a966908bfbaaac5i0”,
“Description”, “alaska on the couch in santa monica”
}

Indexers can crawl all collections, and easily build up a list of all items in the collection, together with their metadata. This allows anybody to create collections of photos, music or data on chain, with verifiable provenance.

**Comment by casey** [comment]
I don't see the benefit over [this proposal](https://github.com/ordinals/ord/pull/2278).
