### ISSUE TITLE
Ord is not indexing some transactions

### ISSUE THREAD

**Issue by macols77** [ordinals/ord#2332]
Hello! I've been running into an issue for some time now where certain UTXOs are not being indexed by ord, and they aren't showing any sat ranges. I understand that ord is designed to display the sat ranges of unspent outputs. By "unspent outputs," I mean outputs that are not spent and should be available for spending, but they aren't being recognized by ord.

I first noticed this bug earlier today, and some transactions still haven't been indexed even after waiting for over 4-5 hours. Here are some examples of transactions where this issue can be observed:

https://ordinals.com/tx/6a9ee1f79bccf8644bd417baed28d830aea5ee189368508aba6e22c66c41f0e2
https://ordinals.com/tx/7931aba3409a2f5b756b563f6ca227e32e56b8b07f8b0bf90d63cbb638abd308
https://ordinals.com/tx/95fa6612febe02b1eee0f2af52e0418cbccb970ac6204572f38626f416745ecf

If you take a look into them, the inputs still have the sat ranges, but the outputs haven't.

Thanks for looking into this!

UPDATE: Now indexer is in sync with the blockchain again! But I leave this open in case this [fix (Add reorg resistance)](https://github.com/ordinals/ord/commit/0286e79a9fc317558131c1fdf76bab72e09faa49) is not working

**Comment by lgalabru** [comment]
It looks like at feast on bitcoin re-org occurred yesterday, freezing the indexer powering https://ordinals.com in time.
Team is probably working on this, feel free to use https://ordinals.hiro.so in the meantime.

**Comment by macols77** [comment]
Thanks for your fast response! Yeah, It seems so but they've implemented a few days ago a fix to handle the reorgs. It seems it's not in production yet or it doesn't work as supposed to.

Your API looks good but it doesn't support transactions, outputs and sat ranges which is the information I need for our use case

**Comment by BillZong** [comment]
> It looks like at least on bitcoin re-org occurred yesterday, freezing the indexer powering https://ordinals.com at block 803389 (we're currently at block 803562). Team is probably working on this, feel free to use https://ordinals.hiro.so in the meantime.

We faced the same issues here.

We forked the repo from ordinals, made a self-defined server, and happy to go with its data source services.
And then, boom! The block reorg...

Now we have to sync up with upstream repo, and makes the re-sync works...
