### ISSUE TITLE
A fully onchain Counter / Controller

### ISSUE THREAD

**Issue by DrJingLee** [ordinals/ord#2342]
Recursion is a milestone update of the ordinal theory, which has brought a lot of interesting applications.

However, in terms of the ecological construction of ordinal theory, there is currently a lack of a fully onchain counter/controller, such as an onchain counter which can record the times of the inscriptions that others using your inscriptions by recursion technology; Also if there is a fully-chained controller or switch that allows the owner of the inscription to choose to be recursively enable/unable; these will greatly enhance the rights of the owner of the inscription, who not only has the full ownership of an inscription ，but also fully has the right to use and control the inscription.

Do you like the idea?

**Comment by DrJingLee** [comment]
Technically seems it's difficult to develop such product or standard. Maybe it's necessary to add such function at protocol level ?

**Comment by stet** [comment]
The current design for parent-child collections, recursion and reinscriptions do not consider multi-party participant controls. 
There are use cases for this such as art collectives and git-like repo orgs/teams as approved contributors. 
There are ways to send onchain signals that effectively create allow-lists of addresses that can formally be part of "collections" and also to be removed from collections. 

I am not sure if this has been discussed anywhere but happy to continue the discussion here.

**Comment by casey** [comment]
I'm not enthusiastic about implementing DRM for inscriptions.
