### ISSUE TITLE
error: JSON-RPC error: transport error: unexpected HTTP code: 401

### ISSUE THREAD

**Issue by simongltr** [ordinals/ord#2345]
Opening an issue to solve a 401 error I have after the 404 error solved in #2336.

My `bitcoin.conf` file is:
```
server=1
daemon=1
txindex=1
listen=1

rpcauth=<generated by rpcauth.py>

rpcallowip=0.0.0.0/0

[main]
rpcport=8332
rpcbind = 0.0.0.0
bind=0.0.0.0
```

Every command I run lead to this 401 error:
```
RUST_LOG=info  ord --rpc-url http://<user>:<pass>@127.0.0.1:8332 info

[2023-08-21T18:53:25Z INFO  ord::options] Connecting to Bitcoin Core at http://<user>:<pass>@127.0.0.1:8332/wallet/ord
error: JSON-RPC error: transport error: unexpected HTTP code: 401
```

Notice that I also have the same issue when I try the `.cookie` auth:
```
RUST_LOG=info ord --rpc-url http://127.0.0.1:8332 --cookie-file ~/.bitcoin/.cookie info

[2023-08-21T18:59:00Z INFO  ord::options] Connecting to Bitcoin Core at http://127.0.0.1:8332/wallet/ord
error: JSON-RPC error: transport error: unexpected HTTP code: 401
```

I have a fresh bitcoin install (synced), no wallets are currently created on bitcoin side. I tried to run `ord wallet create` but same 401 issue.

I spend so much time trying to solve the issues. My goal is to run the server to fetch ranges from it with the new JSON API. 

Thank you for your help.
Simon

**Comment by cypherpork** [comment]
Check:
`curl --data-binary '{"jsonrpc":"1.0","id":"curltext","method":"getblockchaininfo","params":[]}' -H 'content-type:text/plain;' http://UN:PW@IP_ADDR:PORT/`
Replace`UN:PW@IP_ADDR:PORT` with *your* connect string.
`curl` calls `bitcoind` bypassing `ord`.  It may help isolate the problem to either `ord` (if `curl` works), or to `bitcoind` (if it does not).

**Comment by so7ow** [comment]
I'd try simplifying your bitcoin.conf. All you really need is server=1 and txindex=1. Since 401 is generally access/permissions, the rpc stuff is suspect here.

**Comment by simongltr** [comment]
Thanks a lot for the help, I'm closing the issue because the problem is solved. I just waited 30min for bitcoin core to start properly and now it works ...
