### ISSUE TITLE
Pointer Locking?

### ISSUE THREAD

**Issue by AdditiveFiles** [ordinals/ord#2371]
"HTML and SVG inscriptions are sandboxed in order to prevent references to off-chain content, thus keeping inscriptions immutable and self-contained."

Certain browser features like the pointer lock API, which doesn't involve external content references, have not been permitted within this sandboxing approach. This restriction impacts modern applications, particularly those relying on pointer lock for immersive 3D environments. To address this, there is a suggestion to consider enabling the 'allow-pointer-lock' functionality within sandboxed iframes. This adjustment would retain the core principles of immutability and containment while accommodating essential features for a more interactive web experience.

**Comment by casey** [comment]
Seems reasonable to me!

**Comment by casey** [comment]
Actually, I don't think we want to do this. Inscriptions can use the pointer lock API when they're previewed full-screen at `/preview` or `/content`. However we don't want to allow inscriptions to lock the pointer from the `/inscription` page, since that would be disruptive to navigation.
