### ISSUE TITLE
ord index not completing and getting locked.

### ISSUE THREAD

**Issue by twosatsmaxi** [ordinals/ord#2375]
Getting this error for past 3 days while updating index.
Version: 0.8.2
```
/ $ ord index run
Index file "/data/.local/share/ord/index.redb" needs recovery. This can take a long time, especially for the --index-sats index.
error: Database already open. Cannot acquire lock.
```
What should be the next steps:
1. I've deleted index.redb mutilple times and tried, it's resulting into the same state for last 3 tries.
2. I don't see any recovery command for `ord index ---help`, how do I initiate recovery now that 1. is not working.

**Comment by casey** [comment]
That error is returned when the database has a file lock on it Are you sure there isn't an existing instance of `ord` running on your system, or some other processing locking the file? Try using `lslocks` or `lslk` to look for unexpected locks.

**Comment by gada001** [comment]
I encountered the same problem. Have you solved your problem? Can you tell me how to solve it, my brother?

**Comment by nybe** [comment]
> That error is returned when the database has a file lock on it Are you sure there isn't an existing instance of `ord` running on your system, or some other processing locking the file? Try using `lslocks` or `lslk` to look for unexpected locks.

having a lock problem as well, using `lslocks` returned: `ord       1 FLOCK  44G WRITE 0     0   0 /var/lib/ord/index.redb`
How do you unlock it ?

**Comment by chris3he** [comment]
what “ output in wallet but not in ord server” means , to solve it what option should be added when i run the ord server

**Comment by G1ne** [comment]
> That error is returned when the database has a file lock on it Are you sure there isn't an existing instance of `ord` running on your system, or some other processing locking the file? Try using `lslocks` or `lslk` to look for unexpected locks.

Having this same issue and can only find this thread on it.

How can I unlock or find out what is locking the file? Using ord in Umbrel.
