### ISSUE TITLE
Add version control in English Handbook

### ISSUE THREAD

**Issue by DrJingLee** [ordinals/ord#2379]
To keep synchronisation in the different languages versions of handbook,advise to add a version number in the English handbook.

The other languages versions can have a better version control to update alongside the main English handbook.

**Comment by raphjaph** [comment]
#2385

**Comment by DrJingLee** [comment]
The [mdbook-i18n-helpers](https://github.com/google/mdbook-i18n-helpers/tree/main) can solve it perfectly
