### ISSUE TITLE
Implement mdbook language switch feature

### ISSUE THREAD

**Issue by raphjaph** [ordinals/ord#2385]
Would be great to have different languages for the docs, which are made with [mdBook](https://github.com/rust-lang/mdBook). In order to do that we would probably have to use https://github.com/google/mdbook-i18n-helpers. Unfortunately I do not have time to do that at the moment but happy to review the PR when it's done.

**Comment by DrJingLee** [comment]
This is a demo of the website.

https://ordinals.education/

**Comment by ordinaHO** [comment]
just saw your demo its great  ! so with that you mean the main hand book should have a new JavaScript Code with Language Switcher and ralph will be able to add the languages , Im still trying to figure out what different mdbook helper will make for my translation.

**Comment by raphjaph** [comment]
just implemented the language picker in @DrJingLee's PR. Have a look!

**Comment by mgeisler** [comment]
Nice, thanks for setting this up! I'm adding a link back in https://github.com/google/mdbook-i18n-helpers/pull/71. Feel free to raise issues in the repository if you run into problems.

**Comment by raphjaph** [comment]
Closing since we have implemented it now
