### ISSUE TITLE
Cannot view wallet mnemonic once wallet has been created

### ISSUE THREAD

**Issue by dannybabbev** [ordinals/ord#2396]
When I create a wallet with `ord --wallet dev wallet create` ord returns a response containing `mnemonic`.

However, how I cannot view the mnemonic once the wallet has already been created. The mnemonic is also not viewable on the bitcoin core client, as it does not support mnemonics.

Is there a way to view the mnemonic of an already created wallet?

**Comment by casey** [comment]
Once created, the wallet does not store the mnemonic itself, only a seed derived from the mnemonic, so it can't display it.
