### ISSUE TITLE
Feature request: create PSBTs from ord client

### ISSUE THREAD

**Issue by rocktoshi** [ordinals/ord#2418]
Example: 
`ord wallet psbt --sell {inscriptionID} 0.1btc`

**Comment by Psifour** [comment]
Tagging to follow development.

Interested in seeing which of the multiple PSBT structures for selling an inscription is chosen.

**Comment by raphjaph** [comment]
Do you have any preference to which one should be used?

**Comment by orenyomtov** [comment]
Creating the PSBT to sell for a certain price is quite straightforward (once you know which address you want the payment sent to):

> For a sell order, the PSBT should have a single input and single output and signed with SIGHASH_SINGLE | ANYONECANPAY

https://github.com/orenyomtov/openordex/blob/main/NIP.md#verification

Taking that PSBT and creating the final purchase TX as the buyer is the more complicated part

**Comment by rocktoshi** [comment]
'--psbt' might not be the best name for the flag. I think a descriptive name like 'ord wallet {{inscriptionID}} --sell' is easier to understand.

**Comment by Psifour** [comment]
Subcommands of buy/sell would make the most sense unless we foresee a large number of PSBT templates being added. Even in such a case those subcommands could be converted to proxy the PSBT subcommand.

`ord wallet sell {inscription ID} {price}`
`ord wallet buy {psbt B64} [optional expected price]`

Optional expected price can be compared to finalized PSBT before sending as a 'checksum'
