### ISSUE TITLE
need help 【 index::updater error】 求助

### ISSUE THREAD

**Issue by khademreza688** [ordinals/ord#2469]
### Discussed in https://github.com/ordinals/ord/discussions/1870

<div type='discussions-op-text'>

<sup>Originally posted by **jingmaster** March  4, 2023</sup>
 我同步了全节点在安装ORD同步区块的时候出现index::updater error  已经勾选启用RPC且对区块没有裁剪。
![image](https://user-images.githubusercontent.com/58926137/222922619-1176c748-eef9-4941-abba-78cbcf61d87d.png)

我尝试修改bitcoin.conf文件，删除掉 txindex=1 前面的# 。再次同步，出现同样的错误。
尝试在bitcoin core中设置 【打开配置文件】记事本打开加入 txindex=1，再次同步，出现同样的错误。

求大佬帮帮忙找下问题出在哪里
</div>

**Comment by refazi** [comment]
looks similar to https://github.com/ordinals/ord/issues/2453
@raphjaph any fix?

**Comment by raphjaph** [comment]
seems to be a problem with Bitcoin Core not indexing the transaction or the txindex not yet being fully built

**Comment by raphjaph** [comment]
let's continue convo in https://github.com/ordinals/ord/issues/2453
