### ISSUE TITLE
Wrong `next` and correspondingly `genesis` transaction in inscription

### ISSUE THREAD

**Issue by alexqrid** [ordinals/ord#2472]
Hi! I'am running the latest version of the indexer `v0.9.0` and for insctiption [`34382000`](https://ordinals.com/inscription/7f5eaffc3238ad372d33db9057eceaa525f049803e24d121a7b75323fe7cd854i0) I get `next` value [`3f2d2fe2409dd126ae20ee27f33dd86edbefffdd2538278911630a7d39df0058i0`](https://ordinals.com/inscription/3f2d2fe2409dd126ae20ee27f33dd86edbefffdd2538278911630a7d39df0058i0) that is actually wrong, but on ordinals.com it is displayed correctly.

<details><summary>my ord indexer response </summary>

`curl --location 'http://myindexer/inscription/7f5eaffc3238ad372d33db9057eceaa525f049803e24d121a7b75323fe7cd854i0' \
--header 'Accept:  application/json'`

```json
{
    "address": "bc1pcspvrdxcfsg7wj45fp2rrsf25274j6txdwsrt894sqdkk330ssqsfcd3gu",
    "children": [],
    "content_length": 57,
    "content_type": "text/plain;charset=utf-8",
    "genesis_fee": 4392,
    "genesis_height": 809075,
    "inscription_id": "7f5eaffc3238ad372d33db9057eceaa525f049803e24d121a7b75323fe7cd854i0",
    "next": "3f2d2fe2409dd126ae20ee27f33dd86edbefffdd2538278911630a7d39df0058i0",
    "number": 34382000,
    "output_value": 546,
    "parent": null,
    "previous": "2c0f96a2e98e4f633ac76112ca99680c79be57593946195b9e225fd54b6fe04di0",
    "sat": 1660790158523703,
    "satpoint": "5f67267e844bb1881d8fbf4f8783032adbb9bbc9786ae6bf221d6c75fd09a0da:1:0",
    "timestamp": 1695522602
}
```
</details>

If I query inscription 3f2d2fe2409dd126ae20ee27f33dd86edbefffdd2538278911630a7d39df0058i0 it also displays wrong `previous` and genesis height

<details><summary> Wrong genesis height and previous in api response</summary>

```json
{
    "address": "bc1pm63d9aaj9vtn0mydmwrzavf9gdk25qf5ntgzqwspppdnem4gnjrsm9x9q3",
    "children": [],
    "content_length": 56,
    "content_type": "text/plain;charset=utf-8",
    "genesis_fee": 4392,
    "genesis_height": 809075,
    "inscription_id": "3f2d2fe2409dd126ae20ee27f33dd86edbefffdd2538278911630a7d39df0058i0",
    "next": "589e426e093c110a9a8a94f6760789bc57b048848971504d4ad25353ea688d58i0",
    "number": 34382001,
    "output_value": 546,
    "parent": null,
    "previous": "7f5eaffc3238ad372d33db9057eceaa525f049803e24d121a7b75323fe7cd854i0",
    "sat": 1504130770520900,
    "satpoint": "bfbe6f62fd1596c3a22d1d69ee81000c1305783503a2521c28ca82bb91f9d173:1:0",
    "timestamp": 1695522602
}
```
</details>

And [`3f2d2fe2409dd126ae20ee27f33dd86edbefffdd2538278911630a7d39df0058i0`](https://ordinals.com/inscription/3f2d2fe2409dd126ae20ee27f33dd86edbefffdd2538278911630a7d39df0058i0) has a totally different `tick=YUPA`
OKX also displays everything correctly - https://www.oklink.com/btc/inscription/brc20/34382000

Seems like a bug in `v0.9.0`

**Comment by raphjaph** [comment]
ordinals.com is running `v0.9.0`. Are you running from `master`?
