### ISSUE TITLE
Put all new new recursive endpoint under `/-/`

### ISSUE THREAD

**Issue by raphjaph** [ordinals/ord#2476]
Since there is a potential to overload paths all new recursive endpoints should be put under this top level dir

**Comment by devords** [comment]
Why not separate the explorer from the protocol with subdomains?

**Comment by raphjaph** [comment]
> Why not separate the explorer from the protocol with subdomains?

I think this would make everything more complicated. Running ord locally would become weird. You would also need to deploy with two domains.

**Comment by casey** [comment]
We switched to `/r/`.
