### ISSUE TITLE
Show cumulative file size for recursive inscriptions

### ISSUE THREAD

**Issue by rocktoshi** [ordinals/ord#2482]
As we see more recursive inscriptions consuming files of various sizes, I thought maybe it'd be informative to display the total size of all recursive elements consumed by an inscription.

Have some that are like 8mb combined by a small html file, and it is a little opaque and difficulty to see total file size.

**Comment by casey** [comment]
It isn't possible, in general, to determine the size of recusive inscriptions. For HTML inscriptions, we could parse the HTML, and see if it links to `/content`. However, this would be expensive. And there are JS inscriptions, which refer to `/content`, but those are in code, and it would be impossible to find those references.
