### ISSUE TITLE
The "inscriptions" guide in the docs needs work

### ISSUE THREAD

**Issue by gmart7t2** [ordinals/ord#2486]
Section 7.2 of the docs:
![Screenshot_2023-09-29_at_14 27 14](https://github.com/ordinals/ord/assets/49558347/53cee981-a7d1-4f54-b2b8-5ba93e830eb2)

It looks like it is a work in progress. It doesn't read like any of the other sections:

* "get the patent inscription id ...". What is this? Why does it start with a lowercase g?
* Every other command has a sentence ending with a colon before it. This `ord wallet inscribe` command doesn't.
* The command has a mismatched double quote in it
* The last sentence starts with "And" and just trails off.

**Comment by raphjaph** [comment]
First draft here: https://github.com/ordinals/ord/pull/2487

**Comment by raphjaph** [comment]
Thanks for pointing this out! I've merge the above PR.
