### ISSUE TITLE
Ord uses locked unspents as inputs

### ISSUE THREAD

**Issue by dannydeezy** [ordinals/ord#2496]
I noticed that the `get_unspent_outputs` call seems to append all locked outputs to the available utxo set:
https://github.com/ordinals/ord/blame/9bf5c69279c594c1c4dbe760c69db205018440c5/src/index.rs#L313C7-L313C7

What's the reasoning for this? It really tripped me up as I was considering locked outputs to be protected, but they ended up used as fees an inscription.

My use case is that I have some special named sats in my ord wallet and I don't want them to be spent. But ord doesn't recognize them as special, and doesn't respect me trying to lock them. What should I do?

**Comment by dannydeezy** [comment]
It might be nice to be able to omit all utxos 10k sats or smaller from coin selection (unless they are deliberately being inscribed on)

**Comment by casey** [comment]
Fixed by #2618.
