### ISSUE TITLE
Docs sidebar cannot be collapsed

### ISSUE THREAD

**Issue by casey** [ordinals/ord#2507]
The docs sidebar can't be collapsed, and the top bar appears over the sidebar, whereas on other mdbook pages it appears to the side.

Our docs:

<img width="389" alt="Screenshot 2023-10-09 at 11 56 11 AM" src="https://github.com/ordinals/ord/assets/1945/34ec3b7e-7fb9-4ab6-bd40-52f381caa6ee">

Working docs:

<img width="457" alt="Screenshot 2023-10-09 at 11 57 40 AM" src="https://github.com/ordinals/ord/assets/1945/07e680e1-4ca2-4413-9dde-a9816e4c4882">

**Comment by raphjaph** [comment]
Fixed by #2612
