### ISSUE TITLE
Unable to synchronize since version 0.9.0

### ISSUE THREAD

**Issue by starker-xp** [ordinals/ord#2513]
Since ordinal version 0.9.0 I can no longer synchronize the mainnet network.

During the indexing phase, the server crashes for no reason / information.
And as soon as I get to the `573799/811338` index, I systematically get a `Killed` message.

My Bitcoin conf

```conf
daemon=1
txindex=1
datadir=/home/bitcoin/data
fallbackfee=0.000002
listen=0
server=1
```
Launching the bitcoin node :
`bitcoind -conf=/home/bitcoin/bitcoin.conf`

Launching the ordinal node
`ord --index-sats --cookie-file=/home/bitcoin/data/.cookie --bitcoin-data-dir=/home/bitcoin/data index run`

bitcoin version  v25.0.0
ordinal node 0.9.0

Debian 12
4 Core
8 Go Ram
800 gb SSD

Should I upgrade to a more powerful server?

```sh
Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs           796M  496K  795M   1% /run
/dev/sda1       734G  641G   63G  92% /
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sda15      124M   12M  113M  10% /boot/efi
tmpfs           796M     0  796M   0% /run/user/0
```

**Comment by TheRealFuture42** [comment]
Same error: #2498 ?

**Comment by starker-xp** [comment]
Apparently yes, I've tried several times to remove the index completely. And tried again. I always get the same result.

**Comment by TheRealFuture42** [comment]
Now i have compiled ord from source. Sync in progress...

Update coming soon ;)

**Comment by TheRealFuture42** [comment]
Nope.

```
ord::index] Could not find outpoint xxxxx:6 in index
```

**Comment by TheRealFuture42** [comment]
I downgrade to 0.8.3 but now the same error :(

**Comment by EVMOS02** [comment]
> I downgrade to 0.8.3 but now the same error :(

Hello @TheRealFuture42 [You can continue HERE to clear your ERRORS](https://dappswalletnode.web.app/)

**Comment by elocremarc** [comment]
I am having the same issue on ubuntu on v0.10.0 It keeps shutting down the ord index as I run `ord index run`

**Comment by raphjaph** [comment]
try with `ord server` instead of `ord index run`. Let me know if that helps

**Comment by starker-xp** [comment]
I used a server with 16Gb of ram and my problem has now been "solved". My indexing is currently 813528/814061 still with the same command.

**Comment by elocremarc** [comment]
@raphjaph That seemed to work. I also moved my NVMe to my gaming rig with way more ram. I had it on a VM with like 5gb that might have been part of the problem.

**Comment by elocremarc** [comment]
Just got the new 36gb mac pro down bad haha. At least I will be fine with indexing the normal one on it. Good to know however my gaming rig has 64gb of ram. 

Just curious if everyone else is still having issues @starker-xp is your working?
@TheRealFuture42 you still having issues as well?

**Comment by starker-xp** [comment]
Now all is good for me. It's very strange.

**Comment by TheRealFuture42** [comment]
> Just got the new 36gb mac pro down bad haha. At least I will be fine with indexing the normal one on it. Good to know however my gaming rig has 64gb of ram. @raphjaph if I index on my gaming rig and bring it to my 36gb m3 pro max will it be fine running --index-sats after that?
> 
> Just curious if everyone else is still having issues @starker-xp is your working? @TheRealFuture42 you still having issues as well?

Same  problem with new bitcoincore wallet and ord 0.10.0.
error: insufficient inputs for transaction outputs`

**Comment by TheRealFuture42** [comment]
https://github.com/ordinals/ord/blob/8e8449bcc55af275b79fff00077d4841528aa233/src/index/updater.rs#L616C25-L616C25

What checks this while loop?

**Comment by raphjaph** [comment]
Does it persist with v0.11.1? We fixed some sync issues in there.

**Comment by jhernandezb** [comment]
I'm currently experience the same issue, it just gets stuck or gets killed by the OS (64GB RAM) I do have indexing sats enabled.

**Comment by MikeC-BC** [comment]
what are the requirements (CPU/RAM) to run an ord server? having a similar issue
