### ISSUE TITLE
Add a collections page

### ISSUE THREAD

**Issue by casey** [ordinals/ord#2524]
I'd like to be able to see in one place all the inscriptions which are using genetic provenance. "collections" might not be the right word, but something like `/collections`, where all collections are shown, in order of how recently a child was added to the collection.

**Comment by devords** [comment]
Probably a good idea to paginate the children on inscription page too, otherwise it'll try to load all the children on the same page. Maybe, the children list could be capped at 10 along with a link to this new collections page.

**Comment by a-edakin** [comment]
> Probably a good idea to paginate the children on inscription page too, otherwise it'll try to load all the children on the same page. Maybe, the children list could be capped at 10 along with a link to this new collections page.

Yep, and that is exactly a problem I encountered 

`curl --location --request GET 'http://<testnet>/inscription/4728a9610731cc4ddcc7285d3c52aa535ba73ca4400b34d002bce703612e3c68i0' --header 'Accept: application/json'`

`http://<testnet>/inscription/4728a9610731cc4ddcc7285d3c52aa535ba73ca4400b34d002bce703612e3c68i0`

This collection has over 2000+ children and page takes forever to load just like JSON API

**Comment by ordinalOS** [comment]
Good work team. Please consider a "Network Graph" style display here: https://ordinalos.github.io/bussy-tree/

**Comment by raphjaph** [comment]
Closed by #2561
