### ISSUE TITLE
Inscription with metadata larger than 520 bytes considered unstable and has negative index

### ISSUE THREAD

**Issue by l2xl** [ordinals/ord#2525]
Here are examples at testnet:

- 2749b449c03dbea62880f3571c87211b7166fa10f6759e8434e3075dcb46aa5bi0
- 12feca4d7f1a8433d5f52051d72071a6c94f6c5445eff52dc24253270ce5063di0

It looks it happens because ord::inscription::Inscription.duplicate_field is true due to multi push of METADATA_TAG (5).

**Comment by casey** [comment]
This is expected behavior, unfortunately. In the future, after #2495, new inscriptions won't have this limitation, but it won't apply retroactively.
