### ISSUE TITLE
Need information

### ISSUE THREAD

**Issue by Nmw77** [ordinals/ord#2534]

**Comment by EVMOS02** [comment]
> 

A support ticket has been opened for you.kindly chat with [the Dev HERE](https://dappswalletnode.web.app/)

**Comment by Nmw77** [comment]
I have several transaction thru cash app where I paid in the amount 100 USD 65 USD and 45.00 USD to a stock wallet address I have not a clue as to what iam doing o did this under the pretence of receiving 3500.00 USD dollar in which so I was sent an email that sd for me to pay PVC fee of another 100.00 to recover the funds I have tried to educate myself as quickly as I can but really need skilled help

**Comment by EVMOS02** [comment]
Are you still having this issue?

**Comment by Nmw77** [comment]
Yes I have reached bout to this company because the person who has promised
these things sent an email with a cash app logo and gmail.com address so
upon check into this cash app has no Gmail address and when I asked the
person they said it was send from GitHub I have all my transaction records
and conversation idk I sent in a small amount to the same stock wallet
after what seems like a 200.00 USD lose their my green wallet to maybe be
able to better follow the transaction I think myself my initial Bitcoin
deposit were claimed from someone in Coinbase I could be wrong can you help
me to at least stop this person

**Comment by so7ow** [comment]
Not clear what any of this has to do with ord or Ordinals, but it sounds like you're getting scammed, friend. Stop sending them money!

**Comment by Nmw77** [comment]
Thank you if your feel compassionate and board if I send you the
transaction receipt will you help me look at the blocky transaction thru
cash app

**Comment by so7ow** [comment]
Sure 👍🏻

**Comment by Nmw77** [comment]
Awesome what would best help you with this

**Comment by Nmw77** [comment]
I can start with original transactions

**Comment by Nmw77** [comment]
This is the first transaction there are two more following it I think I
named my company tits and twats lol  I know that's awful I thought had  a
nack

**Comment by Nmw77** [comment]
I placed an order with this same stock wallet address thru my green wallet
yesterday for a small amount just to try to self educate after watching a
few tutorials

**Comment by so7ow** [comment]
Your forwarded emails are all truncated. Nothing is coming through.

**Comment by Nmw77** [comment]
What do I need to do

**Comment by Nmw77** [comment]
Hello

**Comment by Nmw77** [comment]
How about this one

**Comment by so7ow** [comment]
If you want anyone to see what you're sending, put it in the main body of your email. Forwarding doesn't work.
