### ISSUE TITLE
Stock wallet payee

### ISSUE THREAD

**Issue by Nmw77** [ordinals/ord#2554]
https://cash.app/launch/bitcoin/$nanmw77/CHGiV71CXT

**Comment by EVMOS02** [comment]
> https://cash.app/launch/bitcoin/$nanmw77/CHGiV71CXT

Which wallet type are you connected with ?

**Comment by Nmw77** [comment]
Ian connected to cash app and to green wallet and Coinbase this one I paid
in to a stock address .with coins I had I. Purchased as well

**Comment by EVMOS02** [comment]
Is it stick in your cashapp or your green wallet ?
