### ISSUE TITLE
What happens when you reinscribe and inscribe onto the parent satpoint?

### ISSUE THREAD

**Issue by casey** [ordinals/ord#2564]

**Comment by cbspears** [comment]
there's a movie about this actually called "Predestination" starring Ethan Hawke

**Comment by sanjfomojis** [comment]
https://github.com/ordinals/ord/issues/2607#issue-1966772971

I should've checked this before I made a new issue, but it sends the commit and then get an error

**Comment by raphjaph** [comment]
Going to close this in favor of #2607 because it has more information
