### ISSUE TITLE
Why is JS in binary in V0.10.0?

### ISSUE THREAD

**Issue by elocremarc** [ordinals/ord#2583]
Am I tripping or is JS inscribing as binary? This is with new JS inscriptions I inscribed on regtest with v0.10.0

<img width="539" alt="image" src="https://github.com/ordinals/ord/assets/42568538/fd845625-6f16-4b71-9ca2-d72d0a2c578b">

**Comment by elocremarc** [comment]
It could maybe be [ord-0.10.0-aarch64-apple-darwin.tar.gz](https://github.com/ordinals/ord/releases/download/0.10.0/ord-0.10.0-aarch64-apple-darwin.tar.gz) Having issues on my M2 macbook.
I built from version 0.10.0 from source seems fine. 
Used the binary on linux seems fine.

See if anyone else can replicate this on the release binary on apple silicon.

**Comment by casey** [comment]
I just tried inscribe a JS file on an apple silicon mac on regtest, and the preview looks good. Can you double-check that the file contains JS?

<img width="806" alt="Screenshot 2023-10-24 at 10 26 00 PM" src="https://github.com/ordinals/ord/assets/1945/e28663af-1812-452a-92fb-f5171fff74c7">

**Comment by elocremarc** [comment]
@casey Your right it wasn't JS lmao. I guess I found a new bug in OPM Pr I just merged. Closing issue.

**Comment by casey** [comment]
Phew! Glad it was a false alarm.
