### ISSUE TITLE
Reinscribe Batch

### ISSUE THREAD

**Issue by elocremarc** [ordinals/ord#2593]
Now that we have batch inscriptions. It would be nice to also have the ability to do batch inscriptions onto the same sat.

**Comment by raphjaph** [comment]
Wanna take a crack at it?

**Comment by elocremarc** [comment]
Yeah I was thinking that but I might need a little help with this one? To start could you give a brief summary of what it would entail. Should I look at the batch PR for some guidance too?

**Comment by raphjaph** [comment]
It would add a new mode called `reinscribe`. If a parent is present all inscriptions would point to the parent sat/inscription and if not they would all just be reinscribed onto the first sat in the output

**Comment by sanjfomojis** [comment]
Is it worth adding a line in the batch inscribing section of the docs about the spacing requirements for .yaml files? 

I’ve already had a couple of people ask about it so might make it more understandable for people not used to .yaml 

![Image 28-10-2023 at 12 29 pm](https://github.com/ordinals/ord/assets/118575190/294035f5-0997-4431-9fae-6530c4ca61fb)


There’s a couple of bits of grammar that need fixing in it so wondering if I should add that in a PR? 

Didn’t think it was worth creating a whole new issue, so just put it here being the closest topic

**Comment by raphjaph** [comment]
@sanjfomojis just add a PR :)

**Comment by raphjaph** [comment]
Close by #2749

**Comment by brianorwhatever** [comment]
This isn't closed in #2749. This feature is huge graffiti artists desire

**Comment by brianorwhatever** [comment]
oh dang I don't think this covers the case I was hoping it would.. here is what I am hoping to do
<img width="207" alt="image" src="https://github.com/ordinals/ord/assets/7122708/cd448566-58e1-4453-bdfc-22cde024c3ce">
