### ISSUE TITLE
ord needs recovery. How to shut down ord server normally

### ISSUE THREAD

**Issue by wain1** [ordinals/ord#2595]
Index file "H:\\ord\\index.redb" needs recovery. This can take a long time, especially for the --index-sats index.

I think it’s because I didn’t shut down the server properly. I shut down PowerShell directly. This caused me to wait for a long time to repair the index. What should I do? Windows system

**Comment by DrJingLee** [comment]
https://github.com/yanowo/ORD-index.redb-Share

Index.redb is broken from time to time . Here is a download version for a quick recovery

**Comment by DrJingLee** [comment]
The system say the database is corrupted ...so that's why ....don't know if in the future we can just visit a remote index.redb , this could be much more convenient.

I confronted this several times : when I close the cmd windows when the indexing is still on going ;
And one time because of the network issue and the file is continuing reported as corrupted.....

🤓

**Comment by DrJingLee** [comment]
So a backup index.redb is uploaded to the cloud as a temporary solution

**Comment by wain1** [comment]
> So a backup index.redb is uploaded to the cloud as a temporary solution

I see, it's so troublesome, I wonder how others can export normal index.redb

**Comment by SmarakNayak** [comment]
Make you shutdown gracefully, only hit ctrl-c once.

The index will corrupt if you hit ctrl-c twice and force close

**Comment by lcgogo** [comment]
> Index file "H:\ord\index.redb" needs recovery. This can take a long time, especially for the --index-sats index.
> 
> I think it’s because I didn’t shut down the server properly. I shut down PowerShell directly. This caused me to wait for a long time to repair the index. What should I do? Windows system

I run ord in docker container, and met this issue very frequently especially for 0.10.0 version.
The 0.8.3 looks ok. But the ord 0.8.3 memory leak is another problem. Ord 0.8.3 used to use more than 80GB memory.

**Comment by windswrold** [comment]
When I press ctrl-c only once, the shell closes correctly, but json-api will also be closed. How can I keep it running correctly?
