### ISSUE TITLE
Bug <> Database already open. Cannot acquire lock

### ISSUE THREAD

**Issue by nakul1010** [ordinals/ord#2596]
Command: 

Running Server with the command

```
./target/release/ord --rpc-url http://127.0.0.1:18443 --bitcoin-rpc-pass rpcpassword --bitcoin-rpc-user rpcuser --regtest server
```

Trying to get wallet balance with the command
```
 ./target/release/ord --rpc-url http://127.0.0.1:18443 --bitcoin-rpc-pass rpcpassword --bitcoin-rpc-user rpcuser --regtest --wallet Charlie wallet balance
```

Error: 
```
Index file "/Users/nakul/Library/Application Support/ord/regtest/index.redb" needs recovery. This can take a long time, especially for the --index-sats index.
error 1 : Database already open. Cannot acquire lock.
```

I get the client is running in the background that's what causing the issue. Is there a way to fix it?

**Comment by DrJingLee** [comment]
Seems restart the computer doesn't solve my problem 
So I delete the index.redb and re download it

**Comment by so7ow** [comment]
With a single index file, you won't be able to run any other `ord` command as long as server is running against the index. Solve this by using multiple index files: one for server, one for other commands.

**Comment by DrJingLee** [comment]
> With a single index file, you won't be able to run any other `ord` command as long as server is running against the index. Solve this by using multiple index files: one for server, one for other commands. 

So we might need 60gb x multiple space 😹

**Comment by so7ow** [comment]
If you want to run simultaneous ord commands, yes.

**Comment by nakul1010** [comment]
> If you want to run simultaneous ord commands, yes. Or just stop `server` to run other commands...

It worked but in a really hacky way here's what I did 
- Stopped the server.
- Created the inscription and mined in `regtest`. 
- Deleted the `index.redb`. 
- Restarted the server to regenerate `index.redb`. 
- Stopped the server and queried the inscription. 

@DrJingLee 
> Solve this by using multiple index files: one for server, one for other commands
Just for clarification do u mean to say keep an up-to-date replica of `index.redb` which then can be used for other commands?

**Comment by so7ow** [comment]
I'm not following whether you're switching between regtest and main, sorry. All I'm saying is that as long as server is running, the index file it's referencing is not available for other uses. You can make it available for other uses by exiting server.

**Comment by elocremarc** [comment]
Yeah you can only have one instance in the index at a time. 
> My regtest blocks are already synced by the server shouldn't it release the RW lock so that it can be used by different services?

Are you sure your shutting down the process correctly maybe its hanging. On mac its `Command-C` and windows `Control-C` if your running the server and want to check balance you need to gracefully shut down the ord server first. 

> Created the inscription and mined in regtest.
Deleted the index.redb.
Restarted the server to regenerate index.redb.

You shouldn't have to keep deleting the index unless its an incompatible ord version your switching between.

**Comment by so7ow** [comment]
> On mac its `Command-C`

It's Ctrl-C on Mac, too.

**Comment by elocremarc** [comment]
Your right. Command-C will hang.

**Comment by so7ow** [comment]
Command-C is just "copy" on a Mac.

**Comment by DrJingLee** [comment]
> Yeah you can only have one instance in the index at a time. 
> 
> > My regtest blocks are already synced by the server shouldn't it release the RW lock so that it can be used by different services?
> 
> 
> 
> Are you sure your shutting down the process correctly maybe its hanging. On mac its `Command-C` and windows `Control-C` if your running the server and want to check balance you need to gracefully shut down the ord server first. 
> 
> 
> 
> > Created the inscription and mined in regtest.
> 
> Deleted the index.redb.
> 
> Restarted the server to regenerate index.redb.
> 
> 
> 
> You shouldn't have to keep deleting the index unless its an incompatible ord version your switching between. 
> 
> 

Last time I have tried everything and doesn't work without downloading a new index file 🤤 

That index.redb is quite weak and very easily to either be locked or corrupted.

**Comment by elocremarc** [comment]
> That index.redb is quite weak and very easily to either be locked or corrupted.

Yeah I nuke my regtest folder all the time its nbd always have a terminal open for it haha.

**Comment by DrJingLee** [comment]
> > That index.redb is quite weak and very easily to either be locked or corrupted.
> 
> 
> 
> Yeah I nuke my regtest folder all the time its nbd always have a terminal open for it haha. 

Is there any way to make it stronger or using different structure of index so we user don't suffer it from time to time 🎃🎃🎃

**Comment by shenqingwangyixuan** [comment]
That index.redb is quite weak and very easily to either be locked or corrupted.

Yeah I nuke my regtest folder all the time its nbd always have a terminal open for it haha.

Is there any way to make it stronger or using different structure of index so we user don't suffer it from time to time 🎃🎃🎃
