### ISSUE TITLE
Provide a way to burn an inscription

### ISSUE THREAD

**Issue by devords** [ordinals/ord#2597]
Ord client should provide an official way to burn an inscription. This way, a parent inscription can be burned after creating a collection, and we can show a "burned" label on the new collection page #2561.

cc @veryordinally

**Comment by DrJingLee** [comment]
Something like When inscription has an ownwr address of 1BitcoinEaterAddressDontSendf59kuE

then give it a tag of “burned” ?

**Comment by elocremarc** [comment]
I think burning to an unspendable output would be ideal. Then you can still sign for the inscription. It would allow for POAPs and Soul Bound Tokens.

**Comment by raphjaph** [comment]
Ideally we would want to burn to an `OP_RETURN` because this way Bitcoin can prune the output.

**Comment by casey** [comment]
Dupe of https://github.com/ordinals/ord/issues/1333.
