### ISSUE TITLE
Teleburning address may not be actual burn address?

### ISSUE THREAD

**Issue by thecolorblocks** [ordinals/ord#2609]
The inscription number 0 burn address is 0xe43A06530BdF8A4e067581f48Fae3b535559dA9e, and there were Ethereum assets sent there 259 days ago. I wonder how that was possible?

The relevant ERC-721 token transfer: https://etherscan.io/tx/0xd997785b577e685a1d532c930c9952ebc5a58080de55a74d5cc93ea633bc7ccb

**Comment by DrJingLee** [comment]
it is.
The transcoding method and result are unique . I fact checked the bayc burning and the eth address is correct.

See handbook teleburning section for more details .
