### ISSUE TITLE
assertion failed: storage.raw_file_len()? >= header.layout().len()

### ISSUE THREAD

**Issue by 11001100111011101110001** [ordinals/ord#2610]
### Ord Version
(base) yeye@macbook-Pro ~ % ord --version
ord 0.10.0

### System Version
macOS Sonoma 14.1

### Hard drive type
SSD

### Hard drive format
APFS

### ERROR
(base) yeye@macbook-Pro ~ %  RUST_LOG=info ord --cookie-file /Volumes/T7/Bitcoin/.cookie --bitcoin-data-dir /Volumes/T7/Bitcoin/blocks wallet balance
[2023-10-30T06:19:44Z INFO  ord::options] Connecting to Bitcoin Core at 127.0.0.1:8332/wallet/ord
[2023-10-30T06:19:44Z INFO  ord::options] Using credentials from cookie file at `/Volumes/T7/Bitcoin/.cookie`
[2023-10-30T06:19:47Z INFO  ord::index] Setting DB cache size to 4294967296 bytes
thread 'main' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/redb-1.3.0/src/tree_store/page_store/page_manager.rs:217:9:
assertion failed: storage.raw_file_len()? >= header.layout().len()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by 11001100111011101110001** [comment]
> This looks like a bug in redb, going to tag @cberner.
> 
> @11001100111011101110001 Can you reproduce this bug consistently?

Yes, this error keeps reoccurring, and I have been troubled by it for several days.

**Comment by cberner** [comment]
Do you have a set of steps that I can run to reproduce this from a clean index? Or did your index just get into this state and now it happens again every time you try to run ord?

**Comment by 11001100111011101110001** [comment]
> Do you have a set of steps that I can run to reproduce this from a clean index? Or did your index just get into this state and now it happens again every time you try to run ord?

An 'index recovery' error occurs after upgrading the system version, so I deleting the index database file. After deleted the database file, this error occurs. So I formatted the hard drive, resynchronized the blocks and started indexing, but this error still occurred.

**Comment by cberner** [comment]
Unfortunately, I don't think that's a redb bug then. That sounds like bad hardware. Do you have another hard drive you can try it on?

**Comment by so7ow** [comment]
If you've been reformatting your external drive and whatnot, have you touched your actual `index.redb` file? It doesn't reside on the external drive by default. It's in `~/Library/Application Support/ord`

Try deleting/renaming that file and trying again.

**Comment by 11001100111011101110001** [comment]
> If you've been reformatting your external drive and whatnot, have you touched your actual `index.redb` file? It doesn't reside on the external drive by default. It's in `~/Library/Application Support/ord`
> 
> Try deleting/renaming that file and trying again.

You are right, I found the broken index database file, deleted it and it worked. Thank you so much.

**Comment by 11001100111011101110001** [comment]
> Unfortunately, I don't think that's a redb bug then. That sounds like bad hardware. Do you have another hard drive you can try it on?

It should have been caused by not deleting the index database before formatting. It is now solved. Thank you very much.
