### ISSUE TITLE
Add media type x-javascript and Typescript

### ISSUE THREAD

**Issue by elocremarc** [ordinals/ord#2615]
I have an executable JS inscription it is similar to x-python from PR https://github.com/ordinals/ord/pull/2538.
Currently it doesn't display.

I think we should also add Typescript as well as x-typescript. I think a more generalized approach to deal with x-mediatype
```javascript
if (language.startsWith("x-")) {
    language = language.substring(2);
}
```

**Comment by raphjaph** [comment]
The MIME type of javascript should be `text/javascript`. Typescript doesn't have an official MIME type and is normally transpiled to javascript anyways. An inscription that contains typescript can't be executed by the browser. Why do you want to inscribe typescript files?

**Comment by elocremarc** [comment]
I started exploring storing executable code as inscriptions for immutable storage. I haven't used the meta protocol tag but I imaged it would be DAPP. We added support for x-python which can't be run in the browser either. The explorer would be a good way to view the code as a digital artifact.

See this inscription that is a basic ord server and parser. Since its x-javascript it is only viewable in the /content route. Which is fine for distribution however not for viewablity.
https://ordinals.com/content/c5942064bea79672efc5d8331d84171ad2ebb086873e4eb24f7184b159702b87i0

Unfortunate TS isn't a mime type with bun you can run it without transpiling it I guess however that wont play nice with the code preview. 

If this isn't in scope with ord I could just make a dedicated explorer that maybe uses autohighlight to cover executable code people might inscribe.
