### ISSUE TITLE
How to properly resync ord ?

### ISSUE THREAD

**Issue by simongltr** [ordinals/ord#2616]
A few months ago syncing ord was super slow for me (2 weeks).  I just installed 0.10.0 (coming from version 0.8.2) and `ord` asks me to resync. 
```
error: index at `/home/ubuntu/ord_data/index.redb` appears to have been built with an older, incompatible version of ord, consider deleting and rebuilding the index: index schema 0, ord schema 9
```

I really don't want to wait another 2 weeks, is there a way to migrate my DB ? Should I run incrementally each release to migrate it ?

If I have to resync I will do it, but then what are the good practices ? For the last sync I didn't have the `-rest` flag or bitcoin core, I will add it and see if it's faster. Any other recommendation ? Maybe the `ordinals.com` maintainers could provide a working DB image for each breaking relaease ?

Thanks,
Simon

**Comment by so7ow** [comment]
There is no upgrade path. For each major release you need to delete your index (index.redb by default) and re-index from scratch.

**Comment by simongltr** [comment]
Thank you, will do it. Closing the issue
