### ISSUE TITLE
Index inscriptions by address

### ISSUE THREAD

**Issue by 77656233** [ordinals/ord#2619]
Is it possible to add a search by address endpoint to get a list of all inscriptions an address holds?

**Comment by raphjaph** [comment]
It's definitely possible but I'm hesitant to add this because it adds a huge (more than 60gb) database table. It could be added behind an optional flag though

**Comment by ChristianGrieger** [comment]
> It's definitely possible but I'm hesitant to add this because it adds a huge (more than 60gb) database table. It could be added behind an optional flag though

That would be amazing as i guess a lot of users would love to use it :) Is there a chance you can take a look into it?

**Comment by elocremarc** [comment]
This would be a nice recursive endpoint too. 
Would also be nice to navigate to a address page on the inscription page when clicking it. 
Thing to consider how big will this table grow if we get millions more addresses in inscriptions or something?
If we max min this and every 460 million bitcoin addresses hold inscriptions thats a big table.

**Comment by ChristianGrieger** [comment]
True ,would be a big table but if it's an optional flag it should be fine for everyone :)

**Comment by ChristianGrieger** [comment]
@raphjaph, could you provide an estimate for this request? We, and undoubtedly others, would greatly appreciate having access to that endpoint. Thanks a lot!

**Comment by raphjaph** [comment]
Do you mean as a recursive endpoint or just a normal html page?

At the moment we're working on database optimizations so want to control the amount of tables we have. I think I'll code something quick up and do some testing to see how it impacts performance.

**Comment by ChristianGrieger** [comment]
> Do you mean as a recursive endpoint or just a normal html page?
> 
> At the moment we're working on database optimizations so want to control the amount of tables we have. I think I'll code something quick up and do some testing to see how it impacts performance.

I talk about the json api endpoint that the server offers.

**Comment by elocremarc** [comment]
> Do you mean as a recursive endpoint or just a normal html page?

That would be nice but we can add that later I think a html page would be a good start.

**Comment by markovichecha** [comment]
Hey, may I handle this task? To clarify, do we need to create an index that includes addresses and their corresponding inscription IDs? And add an html page that shows all inscriptions for given address after that.

**Comment by raphjaph** [comment]
we got this now
