### ISSUE TITLE
Database schema check broken in 0.10.0

### ISSUE THREAD

**Issue by gmart7t2** [ordinals/ord#2622]
Ord 0.10.0 changed the location in the database that the schema number is stored.  See #2541. Before 0.10.0 Schema was the first Statistic enum. In 0.10.0 it's the 9th, and in the current master branch it's the 10th.

It really should be in the same location for every version so we can detect which schema the db was created with.

It's too late now for 0.10.0 but we should put it back to being the first Statistic for 0.10.1 and 0.11.0.

**Comment by gmart7t2** [comment]
This is the specific change I'm talking about:

![Screenshot_20231102_124957_Presearch](https://github.com/ordinals/ord/assets/49558347/7d1564d4-05ed-4e14-a923-698c6d6b06e6)

**Comment by raphjaph** [comment]
Thanks, good catch! Made the fix in #2624.
