### ISSUE TITLE
why my rare.txt is a blank file?

### ISSUE THREAD

**Issue by lcgogo** [ordinals/ord#2658]
I wget ord-url:port/rare.txt but get a very small rare.txt file with only one line.

But 
https://ordinals.com/rare.txt
has 70+MB

My startup command
```
/bin/ord \
       --chain mainnet \
       --data-dir ${DATA_DIR} \
       --cookie-file ${DATA_DIR}/cookie-file \
       --index-sats \
       --rpc-url http://${BTC_RPC_URL} server
```

**Comment by lcgogo** [comment]
@devords Can you help to answer my question?

**Comment by casey** [comment]
What height is your index at? What happens when you run `index update` with your arguments?

**Comment by lcgogo** [comment]
I use the https://github.com/yanowo/ORD-index.redb-Share to recover the node, because sync from 0 needs days or weeks.

And after start from the snapshot, the rare.txt is blank like
```
sat	satpoint
```

If I sync from 0, the rare.txt is ok

**Comment by casey** [comment]
I think those snapshots don't include the `--sat-index`, which `rare.txt` requires.

**Comment by lcgogo** [comment]
> I think those snapshots don't include the `--sat-index`, which `rare.txt` requires.

I tried `index update` option, but still no content in rare.txt
```
root@0bef36f7a2af:/ord# ord --data-dir /data/ord --chain mainnet --cookie-file /data/ord/cookie-file --rpc-url http://btc.rpc.cobo.one index update
Index file "/data/ord/index.redb" needs recovery. This can take a long time, especially for the --index-sats index.
{}
root@0bef36f7a2af:/ord#
```

Is the only method sync from 0 with --sat-index option?

**Comment by casey** [comment]
That's correct. If index.redb wasn't built with `--sat-index`, then you have to rebuild from scratch to index sats.
