### ISSUE TITLE
Hide BRC-20 inscriptions from homepage

### ISSUE THREAD

**Issue by casey** [ordinals/ord#2659]
BRC-20s make the homepage look pretty ugly, we should probably figure out a way to hide them. This wouldn't change whether they're indexed or not, or whether you can look them up by inscription ID or number, just whether or not you can see them on the homepage.

Some ideas:
- Do we hide BRC-20, or all text/JSON inscriptions that are valid JSON? A good way to go might be to hide any text inscription which, when trimmed, starts with `{` and ends with `}`.
- Should we hide `.bitmap` and `.sats` names? Other names?

**Comment by onepixelinscriptions** [comment]
The "homepage explorer" can check, if the Inscription as text contains {, } and "op" then it wouldn't show that Inscription.
