### ISSUE TITLE
Is there a detailed tutorial on Batch Inscribing?

### ISSUE THREAD

**Issue by Glory-dog** [ordinals/ord#2661]
I tried Batch Inscribing
Regardless of whether there are separate-outputs or shared-output, it has n outputs, but in the end only one will succeed in Inscribing. Everything else has disappeared.
How should I write batch.yaml if I need to Inscribe something like {"p":"brc-20","op":"mint","tick":"xxx","amt":"10"}.
The configuration file I fiddled with is as follows:

`# example batch file

# there are two modes:
# - `separate-outputs`: place all inscriptions in separate postage-sized outputs
# - `shared-output`: place inscriptions in a single output separated by postage
mode: shared-output

# parent inscription:
# parent: 69a53a2e8a5f8309ce315f2d4a1f368d1b4797c6831e94acb93ec182f2a19396i0

# inscriptions to inscribe
#
# each inscription has the following fields:
#
# `inscription`: path to inscription contents
# `metadata`: inscription metadata (optional)
# `metaprotocol`: inscription metaprotocol (optional)
inscriptions:
  - file: /root/bear.json
    metaprotocol: brc-20
  - file: /root/bear.json
    metaprotocol: brc-20`

In addition, how do I inscribe N inscriptions to the one address?

**Comment by raphjaph** [comment]
I did a workshop in Amsterdam about it: https://youtu.be/MOU4vURaCmA?si=Au86wzI__bzV7jIY&t=1593

Might do a better recorded one soon though

N inscriptions to one address can't be done yet but working on it here: #2701
