### ISSUE TITLE
JSON API not enabled for ordinals.com

### ISSUE THREAD

**Issue by hans-crypto** [ordinals/ord#2672]
Could you please run ordinals.com with the `--enable-json-api` flag to access endpoints that return JSON instead of HTML.

I mean, please!!! 😇

**Comment by elocremarc** [comment]
You should run your own explorer. We don't want to create the same thing as we have on ETH where everyone runs infra off of infura and alchemy.
![FQNGIMRXsAMXldk](https://github.com/ordinals/ord/assets/42568538/796e51ae-161e-4c66-808a-18eb9b8e52ea)
