### ISSUE TITLE
Genesis_offset for JSON API /inscription/<INSCRIPTION_ID>

### ISSUE THREAD

**Issue by haynesxiang** [ordinals/ord#2675]
When I tried to get the transfer history of a certain inscription, I used these two APIs(/inscriptions/block/<BLOCK_HEIGHT> and /inscription/<INSCRIPTION_ID>) to index transactions data instead of parsing witness script of every transaction input, 
but I found that there is no genesis_offset parameter to help me index the data.

**Comment by raphjaph** [comment]
We don't track inscription transfers. I'm unsure what you mean with genesis_offset?

**Comment by haynesxiang** [comment]
The offset in the transaction(genesis transaction) output when an inscription is first inscribed, and through it I can track the inscription transfers myself.

**Comment by raphjaph** [comment]
Ah ok, that's a reasonable thing to add. Will be low priority though but will put it in the backlog. Would also be a good first issue if you want to try an implement it ;)

**Comment by casey** [comment]
I think this is probably low priority. If there's already code to parse inscriptions from witnesses, then you can parse all inscriptions in the transaction, and then use the index from the inscription ID to figure out which inscription you parsed is the one you're interested in.
