### ISSUE TITLE
Stream ideas

### ISSUE THREAD

**Issue by casey** [ordinals/ord#2677]
- Show how we cut a new release of `ord`

**Comment by elocremarc** [comment]
Is this open to discussion for more stuff?
- Go over testing how to inscribe with TransactionTemplate
- Explain the DB tables and the indexing 
- Go over how to add documentation for newcomers formatting style etc.

**Comment by casey** [comment]
Yah, definitely, ideas welcome.

**Comment by elocremarc** [comment]
Could do these. 
- https://github.com/ordinals/ord/issues/2739
- https://github.com/ordinals/ord/issues/2738
This ones already marked stream
- https://github.com/ordinals/ord/issues/2733

**Comment by raphjaph** [comment]
Going to close this in favor of #3011
