### ISSUE TITLE
Use OP_66 tag for creating permanently unbound inscriptions

### ISSUE THREAD

**Issue by devords** [ordinals/ord#2679]
Many people tried to create cursed inscriptions with `OP_66` tag early on when the cursed inscriptions became a thing. Majority of the first 10k cursed inscriptions are probably made with `OP_66` tag. It was an important lesson for the community to learn.

This proposal is to use `OP_66` tag for having inscriptions be permanently unbound. This will not affect any of the existing inscriptions in any way.

It will, however, achieve a few things:

1. Provide an official way for creating unbound inscriptions.
2. Allow people to do something with the sats they likely have locked up somewhere due to their optimism.
3. Formally recognize the lessons learned by the community in the early stages of the protocol's development.

And maybe prevent any funky situation that might happen as a result of `OP_66` tag being used for something else in the future.

**Comment by casey** [comment]
I think this is just a docs change, i.e., explicitly state that tag 66 will never be assigned.

Let's create an `UNBOUND_TAG` in `src/envelope.rs` and use that in tests which expect an unrecognized even field. (I think we use `22` currently.)

**Comment by devords** [comment]
Fixed in https://github.com/ordinals/ord/pull/2906

I was hoping to add `--unbound` flag to inscribe command. That's why I hadn't gotten around to it. But I'll open a separate PR for that when I get a chance to work on.
