### ISSUE TITLE
Error serving request: Table 'HOME_INSCRIPTIONS' does not exist

### ISSUE THREAD

**Issue by devords** [ordinals/ord#2684]
I'm getting this on the latest build. Presumably, the schema needs to be bumped?

```
Error serving request: Table 'HOME_INSCRIPTIONS' does not exist #2684
```

**Comment by raphjaph** [comment]
Yes, we forgot to bump it for that commit. We bumped the version in the 8f703d1a8cb4e00188f5cfc347bd6e3cb5e918c5 so should be good now.
