### ISSUE TITLE
Read only server mode

### ISSUE THREAD

**Issue by brianorwhatever** [ordinals/ord#2736]
It should be possible to use the wallet while the http server is running as if I understand correctly the server only ever reads. I am currently writing a program that needs to query the server for some things while also running wallet commands. To accomplish this I am creating two `ord` indexes. One for the server to always be running on and another for the wallet.. This is obviously not great and I'd like to be able to use both server and wallet at the same time. Is there anyway to accomplish what I'm trying to do now or is there a path towards that?

**Comment by raphjaph** [comment]
Yeah this would be kind of nice. Will put it in the Backlog

**Comment by casey** [comment]
This works now, you can use the wallet with the server running in the background.
