### ISSUE TITLE
Balk at high fees

### ISSUE THREAD

**Issue by casey** [ordinals/ord#2737]
Given someone fat-fingered 83 BTC on fees, we should probably complain if fee rate is too high, like over 1000 sat/vbyte

**Comment by DrJingLee** [comment]
I did enjoy a 5000sats/vbyte transaction of inscription before on the lottery of inscription number 500000

**Comment by ipoh123** [comment]
pls check this comment?
 https://github.com/ordinals/ord/issues/2693#issuecomment-1822668926

**Comment by cbspears** [comment]
Does `ord` not currently have safeguards in place?

Then definitely should put some in. 1,000 sat/vbyte sounds like a reasonable threshold to put the safeguard in.

h/t Mononaut too: https://x.com/mononautical/status/1727680731051430096?s=20
