### ISSUE TITLE
recursion broken on mobile ordinals.com

### ISSUE THREAD

**Issue by elocremarc** [ordinals/ord#2762]
It seems that normal recursion isn't working on mobile chrome.

@rot13maxi tagging you could be something in that new CSP update. 

Example of normal recursion which doesn't seem to work on mobile.
https://ordinals.com/inscription/700f348e1acef6021cdee8bf09e4183d6a3f4d573b4dc5585defd54009a0148ci0

Example with normal recursion and child recursion which doesn't seem to work on mobile.
https://ordinals.com/children/025107e06ac442f014c09a73cd97372f69619edd00dbeacca0aac55c75efe3ffi0

**Comment by rot13maxi** [comment]
looks like ordinals.com is still using the old CSP header values. Cut #2764 to try to set the origin.

**Comment by raphjaph** [comment]
Recursion works now on Safari and mobile iOS. I don't have an Android atm to test it on there. If it still doesn't work please reopen this issue.

**Comment by rot13maxi** [comment]
able to confirm it all works :)
