### ISSUE TITLE
server caching /content 404's for a year

### ISSUE THREAD

**Issue by rot13maxi** [ordinals/ord#2769]
It appears that a /content/[id] 404 is being cached (I assume by cloudflare?)

For example, consider this inscription: https://ordinals.com/inscription/a02db32b4b18174cb042d1a854fdbe27ec0aa8d9a18b24d17f00ac49bdc2937bi0

and then the content endpoint: https://ordinals.com/content/a02db32b4b18174cb042d1a854fdbe27ec0aa8d9a18b24d17f00ac49bdc2937bi0

This is reproducible by seeing an inscription reveal tx in the mempool and then going and doing a GET (browser, curl, whatever floats your boat) against the /content/ endpoint (h/t to @devords for pointing this out as a DoS vector in #2637)

Looking at the headers coming back from the content endpoint, I see `Cache-Control: max-age=31536000`. After #2637, the `Cache-Control` header *should* be set to `no-store`, but it's not. When I try to reproduce this locally on regtest, the Cache-Control header is correctly set to `no-store`. That makes me wonder if there's some Cloudflare configuration that's overwriting the Cache-Control header, or if origin cache-control isnt configured?

**Comment by raphjaph** [comment]
Thanks for hunting down this error!

In Cloudflare we were still using the to be deprecated Page Rules and the cache setting were a bit aggressive. I've moved everything to the new Cache Rules settings and explicitly told Cloudflare not to cache any 404 responses. Cache was also just purged. Please let me know if this error persists.

**Comment by rot13maxi** [comment]
did a couple of tests and it looks like this is resolved. thanks @raphjaph!
