### ISSUE TITLE
Used "Ord" for some inscription on a Linux machine, how to cleanup secrets?

### ISSUE THREAD

**Issue by nick07002** [ordinals/ord#2772]
I have use a linux box to do inscription from "Ord". I also created wallet by using Ord commands...
Now I may need to give this linux box to someone to use. Which directory should I double check to cleanup any sensitive wallet info such as private key, or seed phrase ? (I guess seed phrases are not saved locally)

e.g.
I found this file:

`./app-data/bitcoin/data/bitcoin/ord/wallet.dat
`
Is this the only file `Ord` generated regarding wallet ?
Thanks!!!

**Comment by raphjaph** [comment]
Yes, `ord` only uses a Bitcoin Core wallet so definitely back up everything in bitcoin core wallet dir. Then when you delete it there shouldn't be any secrets left. Don't forget to also power down Bitcoin Core so the wallet is released from memory.
