### ISSUE TITLE
null satpoint

### ISSUE THREAD

**Issue by brianorwhatever** [ordinals/ord#2779]
Maybe I am doing something wrong but here is what I am attempting..

I am querying wallet for outputs, filtering out the ones that have inscriptions and then grabbing the first sat number in the ranges. The user does something where they are selecting a sat by number, not output.. and then when I want to actually inscribe something I need to look the output back up so that I can use it in the inscription command. Looking at the [code](https://github.com/ordinals/ord/blob/3085fd79996ac31dcf1303067bfb3d54b4a0db24/src/subcommand/server.rs#L476) it seems like it will be null if it's not on an inscription or a rare sat.. I'm guessing this is because ord doesn't index _every_ output just the ones with inscriptions?

I thought I had this working previously.. maybe something changed?

**Comment by brianorwhatever** [comment]
My only explanation for how I had it working before was since I'm working against regtest I was always using uncommon sats..

I really don't want to have to maintain a mapping or have the user select by output but maybe I will have to?

**Comment by brianorwhatever** [comment]
I guess I can get all of the outputs in the wallet and find the one that matches the sat that was selected.. inefficient but should work

**Comment by brianorwhatever** [comment]
oooh just saw on the Ordinals coding club stream that you can inscribe with the sat directly now. Just tested and works great. Feel free to close this issue unless you think I've found a bug?

**Comment by brianorwhatever** [comment]
`--sat <sat>` is amazing I just deleted many lines of code thank you @raphjaph

**Comment by casey** [comment]
Nice! Does that mean that this can be closed?

**Comment by casey** [comment]
The issue is that `Index::find` is suuuuuuper slow, so it can't be used used by server endpoints. It iterates over all sat ranges in the database, which is super slow.

**Comment by brianorwhatever** [comment]
Ah yeah ok that makes sense. Thanks for the clarification the `--sat` param will work great for everything I want to do.
