### ISSUE TITLE
Deploy signet explorer

### ISSUE THREAD

**Issue by brianorwhatever** [ordinals/ord#2790]
The signet explorer graciously hosted at ordinals.com is out of date. Any chance we can get some of the slick new features available on there? Much appreciated!

**Comment by raphjaph** [comment]
https://signet.ordinals.com and https://itestnet.ordinals.com now up and running :)

**Comment by brianorwhatever** [comment]
legend, thank you!

**Comment by brianorwhatever** [comment]
@raphjaph sorry sir the json api didn't get turned out 😕 can I bother you for that?

**Comment by raphjaph** [comment]
we haven't enabled the json api anywhere, still considering if to do it. 

But `ord` on signet is really easy to run! And then you can just enable the json api locally :)

**Comment by brianorwhatever** [comment]
Yep all good, that's what I've done. I need 2 indexes as mentioned in https://github.com/ordinals/ord/issues/2736 which I am doing on main net as well which isn't fun 😅
