### ISSUE TITLE
Inscribe on an Sat (with its UTXO) that already has ordinals inscription, is it doable by using Ord command, or I need to modify the code to achieve this?  

### ISSUE THREAD

**Issue by nick07002** [ordinals/ord#2794]
Inscribe on an Sat (with its UTXO) that already has ordinals inscription, is it doable by using Ord command, or I need to modify the code to achieve this?  thank you.

**Comment by raphjaph** [comment]
`ord wallet inscribe --reinscribe --satpoint <SATPOINT_THAT_HAS_INSCRIPTION> --file <FILE> --fee-rate <FEE_RATE>`
