### ISSUE TITLE
How can batch inscribes implement different reveal transactions corresponding to each file?

### ISSUE THREAD

**Issue by BetterBam** [ordinals/ord#2802]
Hello, now all outputs of batch inscribes are in the same reveal transaction. Can you tell me how to do it make each file correspond to different reveal transactions?

**Comment by raphjaph** [comment]
That is not possible at the moment because the point of batch inscribing is to do it in one transaction to save on fees. If you want to inscribe multiple inscriptions with different reveal transaction I suggest writing a small bash script that wraps the `ord wallet inscribe --file <FILE>` command.
