### ISSUE TITLE
Support inscription number lookup at the top level: ordinals.com/N

### ISSUE THREAD

**Issue by casey** [ordinals/ord#2807]
It's time to bend the knee 🧎‍♂️

**Comment by raphjaph** [comment]
we've already done this with `ordinals.com/inscription/N`. 

Or do you mean the search bar?

**Comment by casey** [comment]
I mean without the `/inscription/` prefix, so you can go to `https://ordinals.com/N`, like on ord.io

**Comment by casey** [comment]
Done!
