### ISSUE TITLE
brc20

### ISSUE THREAD

**Issue by signyf** [ordinals/ord#2813]
How to inscribe brc20 tokens in ord cli wallet, if I don't want to use third party services. Is there a detailed tutorial?

**Comment by raphjaph** [comment]
`ord wallet inscribe --fee-rate 5 --file brc20.json`

Don't know any tutorial but a quick google search should suffice

**Comment by raphjaph** [comment]
`ord wallet inscribe --fee-rate 5 --file brc20.json`

Don't know any tutorial but a quick google search should suffice
