### ISSUE TITLE
Ordinals.com possible performance regressions

### ISSUE THREAD

**Issue by devords** [ordinals/ord#2814]
Request to this sat page took almost 9 seconds - https://ordinals.com/sat/736753070579047

<img width="1308" alt="Sat_736753070579047" src="https://github.com/ordinals/ord/assets/134870335/fe11c98a-d5c0-4980-9581-319e52c0be87">

The site has _felt_ laggy overall recently.

**Comment by casey** [comment]
There are a few things we can do here:

- We're making a bunch of separate calls into the index. This creates multiple read transactions and opens tables multiple times. We could refactor `Server::sat` to make one call into the index.
- This winds up fetching a block, but only needs the header. We could add a block height to block header table, which should be small, which would let us only fetch a header.

**Comment by casey** [comment]
The server is pretty fast now.
