### ISSUE TITLE
Website changes since 12.0 looks odd on some Brave and Chrome profiles

### ISSUE THREAD

**Issue by roadbuilder** [ordinals/ord#2816]
Since 12.0 on some of my Brave and Chrome browser profiles the ordinals.com website has a huge Q and doesn't look right.  This is on Windows 10.

I'm trying to figure out why it looks fine on some profiles but not others.  I have disabled all extensions, but still it persists: 
![image](https://github.com/ordinals/ord/assets/74831504/d7adad30-418d-43e9-b25e-cfaf4bca5467)

bottom part of the Q:

![image](https://github.com/ordinals/ord/assets/74831504/7ee7c068-c18d-4d20-83e3-a94ab72004d2)

**Comment by raphjaph** [comment]
Your browser might still have the old index.css cached. Try CMD+SHIFT+R

**Comment by roadbuilder** [comment]
my bad.. didn't even try a force refresh.. thank you!
