### ISSUE TITLE
Sequence number vs inscription ID

### ISSUE THREAD

**Issue by JinMaa** [ordinals/ord#2820]
Inscription IDs are easily accessible through most ordinals website.

Is there any discoverability difference between sequence numbers and inscription IDs?

I would like to leverage capabilities to reference inscriptions within a metaprotocol - would be useful to have an economical format.

**Comment by raphjaph** [comment]
Sequence numbers are not part of the protocol per se, they are only used internally. Inscription numbers on the other hand are part of the protocol and after the Jubilee (https://github.com/ordinals/ord/issues/2495 and https://github.com/ordinals/ord/pull/2656) they will reflect the same thing that sequence numbers do, namely the ordering of all inscriptions.

**Comment by JinMaa** [comment]
Thank you, I'll stick to inscriptionid for now
