### ISSUE TITLE
When using batch mode with 'same-sat', the received address is different from the expected one

### ISSUE THREAD

**Issue by albertzzzzzzzzzzzz** [ordinals/ord#2832]
When using the --batch parameter, and the mode is set to 'same-sat', I have written 'destination' under 'inscriptions'. However, I found that the address of the inscription is not the one specified after 'destination' in the YAML file. How should I set it to ensure it goes to the specified address?

inscriptions:
  - file: a.txt
     destination:  xxx
  - file: b.txt
     destination:  xxx

**Comment by raphjaph** [comment]
If you are inscribing on the same sat everything will go to the same destination. We should however add a way to specify the destination of that sat. I will have to do the following:

1. Raise an error if user specifies destination in `shared-output` mode or `same-sat` mode
2. Add a top level field called `destination-all` for those modes

**Comment by raphjaph** [comment]
Closed by some PR
