### ISSUE TITLE
Charms are off by 1

### ISSUE THREAD

**Issue by devords** [ordinals/ord#2841]
https://ordinals.com/inscription/45f24b70a8052a677b6b406436ca081d6efbdf6afba25d2d0e4eaa5680ba7e17i0
Shows "unbound", but it's not unbound.

https://ordinals.com/inscription/957926b4567402e25398cfd765068a7a9584cd9b7496c58c19e6434d3e71486fi0
Shows "lost", but it's not.

d06eaca4e93d5974acad46deb67a28afc77a8743 seems to be the culprit as the charms seem off by 1 compared to the order defined in [charms.rs](https://github.com/ordinals/ord/blob/master/src/charm.rs#L3)

**Comment by casey** [comment]
Ahh, I think this is just a result of us not rebuilding the database after adding a new charm, since the enum values changed.

**Comment by raphjaph** [comment]
@casey I will rebuild the database on stability and then copy database over to the other servers

**Comment by devords** [comment]
Ah, makes sense. Thanks guys!

**Comment by raphjaph** [comment]
Should be fixed now :)

**Comment by devords** [comment]
Thanks @raphjaph
