### ISSUE TITLE
Ord resotre does not recognize Ord wallet created with early version?

### ISSUE THREAD

**Issue by nick07002** [ordinals/ord#2844]
I had an ord wallet created with a very early version Ord.
Now I am running latest release and using "ord wallet restore <12 words>" to restore it but I got below error.

```
ord wallet cardinals 
error: wallet "ord" contains unexpected output descriptors, and does not appear to be an `ord` wallet, create a new wallet with `ord wallet create`

```
Is this known issue?  any tips on how to resolve it? thanks. @raphjaph

**Comment by veryordinally** [comment]
Yes, this is a completely different wallet implementation. You'll need to restore this with the old version of ord.

**Comment by nick07002** [comment]
Oh I see. thanks.
Which version was the cutoff between new and old version?

**Comment by raphjaph** [comment]
we use a Bitcoin Core wallet so it might be still looking for that wallet file in your directory. Either try moving/renaming that or do: `ord --wallet restored wallet restore` and then `ord --wallet restored wallet balance`

**Comment by cashrate** [comment]
> we use a Bitcoin Core wallet so it might be still looking for that wallet file in your directory. Either try moving/renaming that or do: `ord --wallet restored wallet restore` and then `ord --wallet restored wallet balance`

I tried renaming/moving & tried both commands you recommended and still not restoring wallet. 

after entering in seed phrase Im getting cookie file doesnt exist, as well as index file index.redb needs recovery, especially for the --index-sats index.

Any help is appreciated

**Comment by raphjaph** [comment]
Do non-wallet commands work? Like `ord server`?

**Comment by cashrate** [comment]
> Do non-wallet commands work? Like `ord server`?

No it doesn't, I get this error

error: cookie file 'C: location" does not exist

**Comment by raphjaph** [comment]
It seems like you are storing your bitcoin core cookie in a non-default location. Try finding out where it is and passing it in with --cookie-file or pass in the authentication directly with --bitcoin-rpc-user and --bitcoin-rpc-pass

**Comment by cashrate** [comment]
> It seems like you are storing your bitcoin core cookie in a non-default location. Try finding out where it is and passing it in with --cookie-file or pass in the authentication directly with --bitcoin-rpc-user and --bitcoin-rpc-pass

I keep getting this error now  after doing ord --cookie-file "C:\bitcoin\bitcoin-26.0\BITCOIN\.cookie" wallet restore "seed phrase"

error: JSON-RPC error: RPC error response: RpcError { code: -4, message: "Wallet file verification failed. Failed to create database path 'C:\\bitcoin\\bitcoin-26.0\\BITCOIN\\ord'. Database already exists.", data: None }

**Comment by raphjaph** [comment]
That means you already have an ord wallet. You can restore to a differently named wallet by doing `ord wallet --name ord-wallet-2 restore <SEED_PHRASE>`. Let me know if that works.

**Comment by cashrate** [comment]
I'm still having trouble getting access to my wallet back after getting a new computer. Is it because my original cookie file is gone? (C:\Users\dysto\AppData\Roaming\Bitcoin\.cookie)

C:\bitcoin\bitcoin-26.0\ORD>ord wallet --name ord-wallet-2 restore "seed phrase"
error: cookie file `C:\Users\dysto\AppData\Roaming\Bitcoin\.cookie` does not exist

C:\bitcoin\bitcoin-26.0\ORD>ord --cookie-file "C:\bitcoin\bitcoin-26.0\BITCOIN\.cookie" wallet --name ord-wallet-2 restore "seed phrase"
{}

C:\bitcoin\bitcoin-26.0\ORD>ord --cookie-file "C:\bitcoin\bitcoin-26.0\BITCOIN\.cookie" wallet balance
{
  "cardinal": 0,
  "ordinal": 0,
  "total": 0
}
C:\bitcoin\bitcoin-26.0\ORD>ord --cookie-file "C:\bitcoin\bitcoin-26.0\BITCOIN\.cookie" wallet --name ord-wallet-2 restore <seed phrase>
The syntax of the command is incorrect.

**Comment by cashrate** [comment]
> That means you already have an ord wallet. You can restore to a differently named wallet by doing `ord wallet --name ord-wallet-2 restore <SEED_PHRASE>`. Let me know if that works.


I'm still having trouble getting access to my wallet back after getting a new computer. Is it because my original cookie file is gone? (C:\Users\dysto\AppData\Roaming\Bitcoin.cookie)

C:\bitcoin\bitcoin-26.0\ORD>ord wallet --name ord-wallet-2 restore "seed phrase"
error: cookie file C:\Users\dysto\AppData\Roaming\Bitcoin\.cookie does not exist

C:\bitcoin\bitcoin-26.0\ORD>ord --cookie-file "C:\bitcoin\bitcoin-26.0\BITCOIN.cookie" wallet --name ord-wallet-2 restore "seed phrase"
{}

C:\bitcoin\bitcoin-26.0\ORD>ord --cookie-file "C:\bitcoin\bitcoin-26.0\BITCOIN.cookie" wallet balance
{
"cardinal": 0,
"ordinal": 0,
"total": 0
}
C:\bitcoin\bitcoin-26.0\ORD>ord --cookie-file "C:\bitcoin\bitcoin-26.0\BITCOIN.cookie" wallet --name ord-wallet-2 restore
The syntax of the command is incorrect.

**Comment by so7ow** [comment]
You've got it restored now but it's not reflecting your balance correctly. You need to do a blockchain rescan. 

`bitcoin-cli -rpcwallet=ord-wallet-2 rescanblockchain 770000`

**Comment by cashrate** [comment]
> You've got it restored now but it's not reflecting your balance correctly. You need to do a blockchain rescan.
> 
> `bitcoin-cli -rpcwallet=ord-wallet-2 rescanblockchain 770000`

I just keep getting unrecognized subcommand for bitcoin-cli.

C:\bitcoin\bitcoin-26.0\ORD>bitcoin-cli -rpcwallet=ord-wallet-2 rescanblockchain 770000
'bitcoin-cli' is not recognized as an internal or external command,
operable program or batch file.

C:\bitcoin\bitcoin-26.0\ORD>ord bitcoin-cli -rpcwallet=ord-wallet-2 rescanblockchain 770000
error: unrecognized subcommand 'bitcoin-cli'

Usage: ord [OPTIONS] <COMMAND>

For more information, try '--help'.

C:\bitcoin\bitcoin-26.0\ORD>ord --cookie-file "C:\bitcoin\bitcoin-26.0\BITCOIN\.cookie" bitcoin-cli -rpcwallet=ord-wallet-2 rescanblockchain 770000
error: unrecognized subcommand 'bitcoin-cli'

Usage: ord [OPTIONS] <COMMAND>

For more information, try '--help'.

**Comment by so7ow** [comment]
You need to find where your bitcoin-cli.exe file is and run from there. By default on Windows I believe it's in `C:\Program Files\bitcoin\daemon` but that location is customizable during installation.

**Comment by cashrate** [comment]
> You need to find where your bitcoin-cli.exe file is and run the command from there. By default on Windows I believe it's in `C:\Program Files\Bitcoin\daemon` but that location is customizable during installation.
> 
> (This is not an ord command. Your first attempt was right, but your system just didn't find the executable file. You might find the bitcoin-cli command requires a `-datadir=C:\bitcoin\bitcoin-26.0` switch to properly locate your Bitcoin data, too. Good luck.)

I found the bitcoin.cli application file, ran the command and I get this. 

C:\bitcoin\bitcoin-26.0\bin>bitcoin-cli -rpcwallet=ord-wallet-2 rescanblockchain 770000
error: Could not locate RPC credentials. No authentication cookie could be found, and RPC password is not set.  See -rpcpassword and -stdinrpcpass.  Configuration file: (C:\Users\dysto\AppData\Roaming\Bitcoin\bitcoin.conf)

C:\bitcoin\bitcoin-26.0\bin>-datadir=C:\bitcoin\bitcoin-26.0
'-datadir' is not recognized as an internal or external command,
operable program or batch file.

**Comment by so7ow** [comment]
Try:

```
bitcoin-cli -datadir=C:\bitcoin\bitcoin-26.0 -rpcwallet=ord-wallet-2 rescanblockchain 770000
```

**Comment by cashrate** [comment]
> Try:
> 
> ```
> bitcoin-cli -datadir=C:\bitcoin\bitcoin-26.0 -rpcwallet=ord-wallet-2 rescanblockchain 770000
> ```

I have no idea what im doing lol

C:\bitcoin\bitcoin-26.0\bin>bitcoin-cli -datadir=C:\bitcoin\bitcoin-26.0 -rpcwallet=ord-wallet-2 rescanblockchain 770000
error: Could not locate RPC credentials. No authentication cookie could be found, and RPC password is not set.  See -rpcpassword and -stdinrpcpass.  Configuration file: (C:\bitcoin\bitcoin-26.0\bitcoin.conf)

**Comment by so7ow** [comment]
I updated the command above. I had misread your data location. At any rate, this might not be the place for this...

**Comment by cashrate** [comment]
> I updated the command above. I had misread your data location. At any rate, this might not be the place for this...

Sorry dude, dont mean to bother you. Just trying anything to get my btc and ordinals back. thanks anyways


bitcoin-cli -datadir=C:\bitcoin\bitcoin-26.0\BITCOIN -rpcwallet=ord-wallet-2 rescanblockchain 770000
error code: -18
error message:
Requested wallet does not exist or is not loaded

**Comment by so7ow** [comment]
You're not bothering me. I just don't think the team likes troubleshooting in unrelated threads. Check out the Discord for a more interactive troubleshooting environment. 

https://discord.gg/ordinals

**Comment by so7ow** [comment]
`bitcoin-cli -datadir=C:\bitcoin\bitcoin-26.0\BITCOIN loadwallet ord-wallet-2

bitcoin-cli -datadir=C:\bitcoin\bitcoin-26.0\BITCOIN -rpcwallet=ord-wallet-2 rescanblockchain 770000`

**Comment by raphjaph** [comment]
Has this been resolved?

**Comment by bitoordileone** [comment]
This helped me. Thank you!
`bitcoin-cli -datadir=C:\bitcoin\bitcoin-26.0\BITCOIN -rpcwallet=ord-wallet-2 rescanblockchain 770000`
