### ISSUE TITLE
Freeze Forks / Inscription Eras

### ISSUE THREAD

**Issue by BennyTheDev** [ordinals/ord#2851]
Issue as requested, In reference to closed PR:
https://github.com/ordinals/ord/pull/2848

Take for example this fork that commits ("freezes") to 0.9 that is supporting BRC-20 & Bitmap. There are also plans to support more inscriptions/metaprotocols:

https://github.com/bestinslot-xyz/OPI

Since 0.9 is already used by the majority of marketplaces and exchanges (from which some might not understand they actually use this version instead of the latest release), this disincentivzes the Ordinals space to go with further ord wallet upgrades.

Additionally, there are entities that are affiliated (partners) with the creator of the fork above that also "froze" to the same version with their indexer and incentivize to use this version by "earning" brc20 tokens.

https://twitter.com/unisat_wallet/status/1733107544460239088

There is no problem with forking per se but ultimately this will lead to fragmentation of the Ordinal ecosystem, confusion and incompatibilities, especially since these forks do not use a custom "ord" envelop tag.

About the why this is being done this way, I can only speculate. I could understand if it was limited to brc20 but obviously it isn't and is rather about enforcing people to use this specific fork, from this specific set of partners moving forward.

Therefore I propose an Era system within the ord wallet to disincentivze the use of such forks so we are all on the same page while having the ability for independent/3rd-party indexers to commit to inscriptions, compatible with the different eras, while having the ability to follow all ord wallet upgrades. Basically filters for each era.

**Comment by NRCHST** [comment]
Possibility to add eras to avoid forks is a unique chance for a stronger protocol!

I would even say... it's highly needed.

**Comment by somebodylose** [comment]
As someone who is actually inscribing, everyone using the old version actually kills more possibilities. We need to see new things emerge and try some more complex operations. Ord the new version gives us this space, so i fully support it.

**Comment by lionelni** [comment]
What qualifications do you have to comment on unisat? You have so many projects, which one has been done well?

**Comment by NRCHST** [comment]
Freezes and forks limit the growth of meta protocols including Bitmap and more to come.

For ordinals and its meta protocols it’s extremely important to stay together in the ORD protocol as long as possible.

Some people think it’s just a small BRC20 problem that hurts nobody. But that’s not the case. It’s  much bigger than that and it hurts other meta protocols too.

**Comment by alphakey90** [comment]
support this. much needed

**Comment by HandCart** [comment]
very much needed. people can make make their own offshoots without hardforking if they so wish.

**Comment by 0xguerrero** [comment]
the fork being "the source of truth" through their gated "oracle"

ordinals "classic" in the best case!

**Comment by casey** [comment]
I don't really understand what this is proposing.

**Comment by BennyTheDev** [comment]
basically what you implemented as charm later.

> I don't really understand what this is proposing.
