### ISSUE TITLE
RUNE signet wallet RUINED

### ISSUE THREAD

**Issue by brianorwhatever** [ordinals/ord#2867]
after inscribing SAT.BLACK rune my wallet Is stuck with an error about locked outputs. I only see 3 inscription utxos that are locked in my wallet. Tried getting more faucet bitcoin and still nothing
```bash
error: JSON-RPC error: RPC error response: RpcError { code: -8, message: "Invalid parameter, output already locked", data: None }
```

**Comment by veryordinally** [comment]
This seems to happen rather frequently. You can run `bitcoin-cli -rpcwallet=ord -testnet lockunspent true` to unlock all locked outputs (if you know what you're doing) as a temporary hack.

**Comment by casey** [comment]
I think we fixed this.
