### ISSUE TITLE
Enforce no-limit open etchings and disallow pre-mining tokens at launch

### ISSUE THREAD

**Issue by devords** [ordinals/ord#2882]
I fully expect Runes launch to be one of the craziest times in Bitcoin's history, in terms of volume, fees and the sheer amount of interest/attention.

It'd be a real shame if the first couple of Rune tokens are fully/partially pre-mined by miners and VCs. As we've seen, "first is first" culture runs deep in the Ordinals space. Ensuring a fair launch that everyone can participate in, is crucial for the long term health of the protocol.

Obviously, protocol team launching a token is not a good idea for a variety of reasons. But similar to the block height activation, a _fairer_ launch may be achieved by enforcing certain parameters.

Here's _my_ proposal for that.

**Proposal**

**From halving to the first difficulty adjustment post halving, i.e roughly 2 weeks from launch:**

1. Enforce open etchings that last at least _X days_ OR _N Blocks_
2. Enforce no supply limits
3. Do not allow any supply to be pre-mined

After the first difficulty adjustment, allow all features.

**Benefits**

- Allows everyone to board the Runes train by getting some of the first tokens ever made. _Choo Choo._
- Encourages competition and punishes predatory platforms that would otherwise charge exorbitant fees.

**Downsides**

- Mempool possibly at never seen before levels, lasting days. But I suspect this might happen regardless of the outcome of this proposal.
- Big players will still likely grab a large chunk of the pie. This is inevitable in a free market. This proposal at least prevents the them from pre-mining supplies and later attempt to sell at ridiculous prices. Instead, they'd have to participate via the network, just like everyone else.

**Comment by NakaPepeMigos** [comment]
100% Agree with that

**Comment by lyndoco** [comment]
I agree with everything, in spirit. 

In practice, I'm not sure it would be a good idea to implement at the protocol level.

What about people that want to utilize runes for more intentional purposes, where control of the supply (and other parameters) is necessary? 

I think it all depends on how specific of a tool runes wants to be, and how much politics it wants to enforce.

**Comment by devords** [comment]
@lyndoco In spirit, this is very similar to block height activations for the protocol itself and the ticker lengths. Initially, tickers will be fairly long AFAIK.

The proposal is to enforce certain params only for a short period of time, before activating all the features.

**Comment by casey** [comment]
I think the intention here is good, but I think there are some wrinkles:

- It introduces additional complexity to the protocol, which is already getting pretty complex.
- If the restriction is in place for a limited time after activation, then it only applies to long runes, which aren't super desirable. It would apply to low rune numbers, although arguably only the first few rune numbers are valuable.
- It's probably fine if some people create runes that don't have open etchings, given that many people will create runes that do.

So I'm leaning towards closing this.

**Comment by devords** [comment]
@casey Totally understandable. I'll just add that the ticker length is kinda irrelevant. Just watch _HarryPotterCaseyShibaInu_ become the top token 😅

I hope you consider finding some ways to ensure for a fair distribution for the first tokens. IMO, this only really matters for the first 2-3 deploys, not that that reduces any complexity at the protocol level.

**Comment by casey** [comment]
I think that clearly delineating between fair launch and pre-mined runes is a good idea. I opened this issue: https://github.com/casey/runestone/issues/134

We could also have some delineation between long open etchings and short open etchings, since you could do a one block open etching, etch a bunch of runes, and it would show up at 0% pre-mined.

**Comment by owenstrevor** [comment]
Great idea if there's a simple way to execute it. We're already starting to see this shit show form in the community where people are out here misleading others by claiming to be the first rune, spreading misinformation that Casey is behind it, etc., just to presell their token. Some really ugly behavior is coming out in anticipation of what could be one of the biggest events in Bitcoin history, and that behavior is only likely to intensify and get worse in the lead-up. If no one can presell the "first rune" that doesn't exist yet, it basically cuts this off at the knees and calms the whole community that the first Runes will be fair launch. The grifters are trying to cash in on the comparison to ORDI, which was the first fair launch on BRC-20, by preselling vaporware of being the first rune. And degens are eating it up.
