### ISSUE TITLE
Increase transaction fees

### ISSUE THREAD

**Issue by wuyi771** [ordinals/ord#2886]
I try to increase the transaction fee, but I have to double the transaction fee before I can send it out. For example, my original fee is 100, and I have to pay 200 before I can send it out, otherwise I will get because: JSON-RPC error: RPC error response: RpcError { code: -26, message: "insufficient fee, rejecting replacement 2ade92f4ad, less fees than conflicting txs; 0.00957 < 0.02155904", data: None }, is there any way for me to increase the fee a little instead of having to pay more? times

**Comment by casey** [comment]
This looks like there is a conflicting transaction with a larger fee. You'll have to pay more than the fee paid by the conflicting transaction. This is Bitcoin Core policy, not ord.
