### ISSUE TITLE
Expand --dry-run Functionality

### ISSUE THREAD

**Issue by RobertClarke** [ordinals/ord#2887]
When using this flag, can we add an option to output the commit/inscribe PSBTs to verify in Sparrow or deconstruct with Bitcoin-core commands to verify the transactions manually before broadcasting?

Use case:
Say I have a wallet with multiple UTXOs containing uncommon sats. I'd like to manually confirm that these aren't getting accidentally spent.

Alternative:
Add the ability to define "payment" UTXOs for network fees, in addition to --sat-point

**Comment by elocremarc** [comment]
@gmart7t2 don't you have something in your version which could handle this usecase?

**Comment by raphjaph** [comment]
Something like this: #2925?

**Comment by gmart7t2** [comment]
> @gmart7t2 don't you have something in your version which could handle this usecase?

Yes. --dump causes it to output the signed transactions and --no-broadcast causes it not to broadcast them.
