### ISSUE TITLE
Indexing Sats and Runes 

### ISSUE THREAD

**Issue by HyperNomo** [ordinals/ord#2889]
Is it possible to both index sats and runes?

I am testing using signet, after successfully running the index-runes server:

>-signet --index-runes --index-sats server

I receive this:
Index file `/root/.local/share/ord/signet/index.redb` needs recovery. This can take a long time, especially for the --index-sats index.
Listening on http://0.0.0.0:80

Been waiting for a couple hours, I dont see any progress bar.

**Comment by raphjaph** [comment]
Did you index from scratch or use an existing database?

**Comment by HyperNomo** [comment]
> Collaborator

I'll try again from scratch :)
