### ISSUE TITLE
developers please build a "preview-phase for anyone that wants to run ord-server as a public nft explorer

### ISSUE THREAD

**Issue by c4pt000** [ordinals/ord#2891]
https://github.com/ordinals/ord/discussions/2890

**Comment by c4pt000** [comment]
ORD-SERVER and ORD-CLIENT NEW FEATURES HELP DECLUTTER THE BLOCKCHAIN WITH A PREVIEW PROCESS FOR NEW NFTS PSUEDOCODE BASIC IDEA DEVELOPERS OF ORD PLEASE READ

**Comment by casey** [comment]
I don't understand what's being requested here. Can you please summarize it briefly?

**Comment by casey** [comment]
I think I vaguely get what the above discussion is gesturing at. It sounds complicated and doesn't seem to add much value.
