### ISSUE TITLE
Make clear inscriptions are served from /content/:id

### ISSUE THREAD

**Issue by elocremarc** [ordinals/ord#2903]
This topic keeps coming up again and again on twitter and in issues. People seem confused that inscriptions need to be served from a web server and specifically from the content route with the id as a dynamic route. I think this needs to be better defined in the handbook. People keep asking for a recursive route to return the Id when I don't think enough people realize that inscriptions are defined with a server architecture. 

Under inscriptions in the handbook it says. 
> The inscription content model is that of the web. An inscription consists of a content type, also known as a MIME type, and the content itself, which is a byte string. This allows inscription content to be returned from a web server, and for creating HTML inscriptions that use and remix the content of other inscriptions.

We might need to be more clear about the routing here because this has become a standard way of getting the Id and mimetype since we introduced the child and metadata endpoint. Also since we introduced recursion /content/ has been solidified as well.

**Comment by raphjaph** [comment]
Yeah, seems like a good idea, feel free to add a sentence to the docs :)
