### ISSUE TITLE
Can BRC-20 inscription data be overwritten?

### ISSUE THREAD

**Issue by HyperNomo** [ordinals/ord#2915]
Sorry for the simple questions I've been asking. Really appreciate Raph and Casey's work on ordinal theory, what an amazing standard.

I was wondering:

Is it possible that some BRC-20 inscription data could be overwritten/lost, considering the use of witness data field?
Has it happened already?

I've seen people mentioning pruning or reinscription, but the ordinal theory handbook seems to indicate otherwise:

"Individual satoshis can be inscribed with arbitrary content, creating unique Bitcoin-native digital artifacts that can be held in Bitcoin wallets and transferred using Bitcoin transactions. Inscriptions are as durable, immutable, secure, and decentralized as Bitcoin itself."

If someone were to write a new indexation logic for BRC-20, would they arrive at the same user balances than Unisat?

Thank you :)

**Comment by casey** [comment]
There is no risk of inscription witnesses being made unavailable. A version of Bitcoin Core could be released which pruned old witnesses, however, even one non-pruning Bitcoin Core node would keep witness data available. And, given the number of ordinals degens running nodes, it's very likely that there would be many such nodes.
