### ISSUE TITLE
Allow setting delegate only once when batch inscribing

### ISSUE THREAD

**Issue by devords** [ordinals/ord#2930]
If I want to create a large number of inscriptions via a batch that all delegate to the same inscription, it'd result in a significant cost savings if the delegate could be set just once for all the inscriptions for that batch.

**Comment by casey** [comment]
I'm not sure it would be a good idea to do this, since we would have to make the behavior of inscriptions depend on other inscriptions in the same batch, which is possible, it's just a more confusing model.

**Comment by devords** [comment]
Fair.
