### ISSUE TITLE
Wrong header setting for contents on Testnet

### ISSUE THREAD

**Issue by alexso777** [ordinals/ord#2961]
Presumably, testnet server isn't configured properly for CSP
CSP headers look wrong
default-src https://ordinals.com/content/ https://ordinals.com/blockheight https://ordinals.com/blockhash https://ordinals.com/blockhash/ https://ordinals.com/blocktime https://ordinals.com/r/ 'unsafe-eval' 'unsafe-inline' data: blob:
Needs to be testnet.ordinal.com

This is error on testnet inscription content and you can see it has wrong header which indicationg "https://ordinals.com/" instead of "https://testnet.ordianls,com/"

I think this should be fixed asap
@casey @raphjaph

**Comment by raphjaph** [comment]
Should be fixed now. Could you give me an example recursive inscription on testnet so I can check?

**Comment by alexso777** [comment]
https://testnet.ordinals.com/content/b117ccb2b67f3567402b0ff9eaf4636ee368872883d7660c0b04e300d5964ac2i0
@raphjaph please check this one

**Comment by alexso777** [comment]
@raphjaph 
I have updated comment and plz check that one.
I need it be done asap.
Thanks

**Comment by casey** [comment]
> @raphjaph I have updated comment and plz check that one. I need it be done asap. Thanks

We have limited resources, and many things to do. This is high priority, but a lot of things are high priority.

**Comment by casey** [comment]
I did some debugging, and I believe this is now working. Give it a shot, you might need to clear your browser cache.
