### ISSUE TITLE
Nested Inscriptions

### ISSUE THREAD

**Issue by dubuqingfeng** [ordinals/ord#2968]
I have a curiosity about what happens when nested between op_if and op_endif, both of which have inscriptions and identifiers. I found an example of this on testnet, but in reality, only recognized the nested one in the middle.

https://mempool.space/zh/testnet/tx/ae5499d48eef98588ebe8909ce7b7a99401110e90346d873989045ad80259d60

https://testnet.ordinals.com/inscription/ae5499d48eef98588ebe8909ce7b7a99401110e90346d873989045ad80259d60i0

**Comment by casey** [comment]
Nested inscriptions are unsupported, and in the example you give, the second inscription is invalid, because it doesn't start with `OP_FALSE OP_IF <ord>`
