### ISSUE TITLE
Regarding the issue with the wrong index of cursed inscriptions

### ISSUE THREAD

**Issue by Areswey** [ordinals/ord#2981]
This is my wallet address：bc1pr6gswdu605s562f94m7ldj9kd9rj2z9l7aklpv9kqghpgfvrlhys0hg69p

I have inscribed some curse inscriptions. The UTXO output is in my wallet, but when I looked up them on Ordinals.com, it showed that they were at a different address.
And what is very strange is that in the information of an inscription, the output and ID should be consistent, but what is displayed on Ordinals.com is inconsistent.
https://ordinals.com/inscription/7e392507c388dc72514d5433a264b8df1094fd49b584a66cefba0393f6064c00i0
![WechatIMG1970 1](https://github.com/ordinals/ord/assets/155935473/6f85c867-94c4-4aeb-a553-2e226d0e3de2)

And I used another index website, and the query results were correct:
https://ordinals.hiro.so/inscription/7e392507c388dc72514d5433a264b8df1094fd49b584a66cefba0393f6064c00i1
![WechatIMG1968](https://github.com/ordinals/ord/assets/155935473/d795a5d1-2008-49d9-9a68-8b8547300904)

**Comment by raphjaph** [comment]
How did you make this inscription? It looks like the inscription landed in the fees and not your wallet. The id and output do not always have to match, especially when you transfer your inscription. I this case it was transferred to a miner output.

**Comment by Areswey** [comment]
I used a third party tool for the engraving. If it was transferred to the miner, why is the utxo output in my wallet?
And the curse inscription in my wallet can be found on this website：
https ://ordinals.hiro.so

**Comment by Areswey** [comment]
> How did you make this inscription? It looks like the inscription landed in the fees and not your wallet. The id and output do not always have to match, especially when you transfer your inscription. I this case it was transferred to a miner output.

I used a third party tool for the engraving. If it was transferred to the miner, why is the utxo output in my wallet?
And the curse inscription in my wallet can be found on this website：
https ://ordinals.hiro.so

**Comment by raphjaph** [comment]
Which third party tool? Which wallet are you using?

**Comment by Areswey** [comment]
> Which third party tool? Which wallet are you using?

tool：looks
wallet：unisat

After I restored the wallet to the sparrow wallet, I could see the UTXO output. I used this output to query and got the results mentioned above.

**Comment by Areswey** [comment]
> 铭文工具似乎以错误的方式构建了交易，因此它将输出记入您的钱包，但该输出不包含铭文。Hiro 索引器也是错误的。如果您将钱包放入其中，`ord`则不会表明该铭文属于您。
> 
> 这是为您创建铭文的交易。 https://mempool.space/tx/7e392507c388dc72514d5433a264b8df1094fd49b584a66cefba0393f6064c00
> 
> 该费用会消耗铭文，因为您使用的工具将其放入第二个输入中，并且没有使第一个输出足够大以包含铭文。
> 
> 我会在他们的平台上开票/问题。

OK，thanks
