### ISSUE TITLE
why json request not work

### ISSUE THREAD

**Issue by Boquaninc** [ordinals/ord#2982]
I turn on --enable-json-api with "server --enable-json-api "
when i use curl -s -H \"Accept: application/json\" 'http://0.0.0.0:80/inscriptions'\n
but it still returns HTML

**Comment by raphjaph** [comment]
`ord server --enable-json-api`
and then 
`curl -s -H "Accept: application/json" 'http://0.0.0.0:80/inscriptions'` 
works for me.

Which version of ord are you using?

**Comment by Boquaninc** [comment]
> `ord server --enable-json-api` and then `curl -s -H "Accept: application/json" 'http://0.0.0.0:80/inscriptions'` works for me.
> 
> Which version of ord are you using?

works  now
