### ISSUE TITLE
Feature request: `ord wallet restore` to accept user input for MNEMONIC

### ISSUE THREAD

**Issue by oxSaturn** [ordinals/ord#2990]
Currently you have to restore a wallet like below:

```
ord wallet restore "MY SEED HERE"
```
Problem is the shell history will keep the SEED, which is bad practice IMO.

Would like `ord wallet restore` to receive user input from stdin when no `MNEMONIC` is passed through cli argument:

```
$ ord wallet restore
...
Please input your seed below:
...
```
Does it make sense?

**Comment by so7ow** [comment]
Very good idea. 👍🏻

**Comment by raphjaph** [comment]
Agreed, that would be good enhancement :)
