### ISSUE TITLE
ord needs recovery.

### ISSUE THREAD

**Issue by windswrold** [ordinals/ord#2997]
When I press ctrl-c only once, the shell closes correctly, but json-api will also be closed. How can I keep it running correctly?

**Comment by raphjaph** [comment]
When you CTRL-C that closes down the server and with that also the json-api. If you want to keep it running keep it running in a shell window or start a tmux session. If you are on Linux you can use `systemd` to run ord for you. See our service files in `/deploy/ord.service`
