### ISSUE TITLE
Recursive Endpoint for Self-Referencing and Referencing other Inscriptions, reducing costs, enhanced accessibility and efficiency

### ISSUE THREAD

**Issue by ORDHeavens** [ordinals/ord#3015]
Proposal to introduce a new recursive endpoint. This feature would enable inscriptions to reference information about themselves without prior knowledge of the inscription IDm and information about other inscriptions. Thus, significantly reducing costs, optimizing block space usage and reduce transactions load further lowering price globally. 

Old command
```
/̶r̶/̶s̶a̶t̶/̶c̶u̶r̶r̶e̶n̶t̶:̶ ̶O̶u̶t̶p̶u̶t̶s̶ ̶t̶h̶e̶ ̶c̶u̶r̶r̶e̶n̶t̶ ̶i̶n̶s̶c̶r̶i̶p̶t̶i̶o̶n̶'̶s̶ ̶s̶a̶t̶ ̶n̶u̶m̶b̶e̶r̶.̶
̶/̶r̶/̶s̶a̶t̶/̶i̶d̶/̶c̶u̶r̶r̶e̶n̶t̶:̶ ̶O̶u̶t̶p̶u̶t̶s̶ ̶t̶h̶e̶ ̶c̶u̶r̶r̶e̶n̶t̶ ̶i̶n̶s̶c̶r̶i̶p̶t̶i̶o̶n̶'̶s̶ ̶f̶u̶l̶l̶ ̶I̶D̶.̶
```

Improved command proposed by @RabbiGains-eth 
`/r/self` returning:
```
{ 
   inscription_id: 371b1fe39a2f0463008ee1f9ab75e0af7b3d80beeb2be6eb5cfed9d848e48b54i0,
   parent_id: 3518fb0f9112542df40f31d4c7dd6e9366acd8401ce3b4cc9b6f5c00d6d21fb3i0,
   sat_number: 45026248133,
   utxo: cb7ca4e9a8c827bbbe4dcc73700b2fda39242c234f2020147d756cc3fe2787f8:2,
   genesis_blockheight: 818927
}
```

**Benefits**
_Cost Reduction:_ Up to circa 75% cost savings for inscriptions requiring their sat number or self-reference.
_Block Space Efficiency:_ Potential reduction in transaction and block space usage by up to 33% on such type of inscriptions.
_Enhanced Flexibility:_ Opens up new possibilities for creative and broader applications of inscriptions, decentralized/user mints (always more and more used).

Implementing a recursive endpoint for self-referencing in Bitcoin inscriptions offers significant efficiency improvements and cost reductions, fostering innovation in the use of digital artifacts on the blockchain. I encourage an open discussion with the community and developers to review and if considered valuable, integrate this proposal into ord.

ORDHeavens and RabbiGains - We are all innovating together!

**Comment by RabbiGains-eth** [comment]
`/r/self` returns:

```
{ 
   inscription_id: 371b1fe39a2f0463008ee1f9ab75e0af7b3d80beeb2be6eb5cfed9d848e48b54i0,
   parent_id: 3518fb0f9112542df40f31d4c7dd6e9366acd8401ce3b4cc9b6f5c00d6d21fb3i0,
   sat_number: 45026248133,
   utxo: cb7ca4e9a8c827bbbe4dcc73700b2fda39242c234f2020147d756cc3fe2787f8:2,
   genesis_blockheight: 818927
}
```

**Comment by paradisd** [comment]
That is much more compact and elegant and you can fetch out all info with a simple command! And with the new tech/protocols we have on ordinals, such a command is becoming very useful compared to months ago when that was not really necessary.

**Comment by jerryfane** [comment]
+1 on this

**Comment by ep150de** [comment]
+1 and would be nice to return the current owner wallet address

ex:
{ 
   inscription_id: 371b1fe39a2f0463008ee1f9ab75e0af7b3d80beeb2be6eb5cfed9d848e48b54i0,
   parent_id: 3518fb0f9112542df40f31d4c7dd6e9366acd8401ce3b4cc9b6f5c00d6d21fb3i0,
   sat_number: 45026248133,
   utxo: cb7ca4e9a8c827bbbe4dcc73700b2fda39242c234f2020147d756cc3fe2787f8:2,
   genesis_blockheight: 818927
   owner_address: bc1pju5qh9kqzz7szwyxnys6r22yy08er37dxqf7p54ymygz094yy9vs0890vk
}

**Comment by ORDHeavens** [comment]
Yeah that can avoid the need of having to add another line to fetch for it afterwards!!! Thanks or your contribution @ep150de much appreciated!!

**Comment by RabbiGains-eth** [comment]
> All the fields look except for maybe the `owner_address` since we don't want to encourage address reuse and stuff like that.

Awesome to get your attention on this @raphjaph. The more general endpoint as you described is definitely more powerful.




> Yeah that can avoid the need of having to add another line to fetch for it afterwards!!! Thanks or your contribution @ep150de much appreciated!!

Address could be nice, but I do understand the reuse concerns. 
What are some of the use-cases you see for the address field that would not work by using the UTXO location?

**Comment by ORDHeavens** [comment]
@raphjaph would not expect a lesser elegant and powerful command from yourself!

If I understood correctly you would get:

`/r/info/<INSCRIPTION_ID>` to get any inscription info and you would use `/r/info/self` to get the current inscription info?

Let me know and will add that to the proposal above!

**Comment by ep150de** [comment]
I was originally thinking if someone wanted to make art derive from an algo seed from the inscription owner wallet, so as the art is traded, some facets and colors or features are changed and determined by the owner wallet address. Allowing the art to evolve or be dynamic based on wallet address. -ep150de
-------- Original message --------From: "RabbiGains.eth" ***@***.***> Date: 1/24/24  7:46 AM  (GMT-08:00) To: ordinals/ord ***@***.***> Cc: ep150de ***@***.***>, Mention ***@***.***> Subject: Re: [ordinals/ord] Recursive Endpoint for Self-Referencing
  Inscriptions on Bitcoin, reducing costs, enhanced accessibility and efficiency
  of the blockchain (Issue #3015) 

All the fields look except for maybe the owner_address since we don't want to encourage address reuse and stuff like that.

Awesome to get your attention on this @raphjaph. The more general endpoint as you described is definitely more powerful.

Yeah that can avoid the need of having to add another line to fetch for it afterwards!!! Thanks or your contribution @ep150de much appreciated!!

Address could be nice, but I do understand the reuse concerns.
What are some of the use-cases you see for the address field that would not work by using the UTXO location?

**Comment by ORDHeavens** [comment]
That can be done with the UTXO which also changes when the ordinal is transferred 🤗 by referencing it you achieve a very similar outcome, or maybe more interesting cause if you send it to your same address you can still have a different outcome 💪

**Comment by raphjaph** [comment]
#2628

**Comment by ZedZeroth** [comment]
Hi everyone. I also came here to request something along these lines. Ordinals.com already shows the UTXO "location" of each inscription so I feel like it should be possible to reference this as an end point? e.g. /r/location/<INSCRIPTION_ID> or /r/utxo/<INSCRIPTION_ID>

I also believe that /r/address/<INSCRIPTION_ID> (owner address) would allow for some very interesting behaviour, particularly with regard to collection mechanics. Thank you :)

**Comment by Jrbiltmore** [comment]
To implement the functionalities you've outlined, let's provide a more detailed approach to developing the `blockchainClient.js`, `inscriptionController.js`, and the web server setup including `server.js` and `routes.js`. This implementation will serve as the backbone for creating a web application that interacts with the blockchain to fetch and display Ordinals inscription data based on UTXO location and owner address.### blockchainClient.jsThis file will be responsible for interacting with the blockchain to fetch inscription data. You'll need to utilize a Bitcoin blockchain API or library that supports Ordinals to query inscription details.```javascript// blockchainClient.jsconst axios = require('axios'); // Assuming axios for HTTP requestsconst API_BASE_URL = 'https://blockchain-api-service.com'; // Placeholder URLclass BlockchainClient {    async fetchInscriptionData(inscriptionId) {        try {            const response = await axios.get(`${API_BASE_URL}/inscription/${inscriptionId}`);            // Extract UTXO location and owner address from response            const { utxoLocation, ownerAddress } = response.data;            return { utxoLocation, ownerAddress };        } catch (error) {            console.error('Error fetching inscription data:', error);            throw error;        }    }}module.exports = new BlockchainClient();```### inscriptionController.jsThis controller will process web requests, interact with the `BlockchainClient` to fetch inscription data, and respond to the client.```javascript// inscriptionController.jsconst blockchainClient = require('./blockchainClient');class InscriptionController {    async getInscriptionDetails(req, res) {        try {            const { inscriptionId } = req.params;            const inscriptionData = await blockchainClient.fetchInscriptionData(inscriptionId);            res.json(inscriptionData);        } catch (error) {            res.status(500).send('Failed to fetch inscription details');        }    }}module.exports = new InscriptionController();```### Web Server and RoutingIn this section, you'll set up the web server using Express.js and define the routes to handle the specific queries.```javascript// server.jsconst express = require('express');const inscriptionController = require('./controllers/inscriptionController');const app = express();const PORT = process.env.PORT || 3000;// Middlewareapp.use(express.json());// Routesapp.get('/r/location/:inscriptionId', inscriptionController.getInscriptionDetails);app.get('/r/address/:inscriptionId', inscriptionController.getInscriptionDetails);// Start the serverapp.listen(PORT, () => console.log(`Server running on port ${PORT}`));``````javascript// routes.js (Optional, if you prefer to separate routing)const express = require('express');const router = express.Router();const inscriptionController = require('./controllers/inscriptionController');router.get('/r/location/:inscriptionId', inscriptionController.getInscriptionDetails);router.get('/r/address/:inscriptionId', inscriptionController.getInscriptionDetails);module.exports = router;```### Integration- Integrate the `routes.js` with `server.js` if you've separated the routing logic.- Ensure you have installed all necessary packages (`express`, `axios`, etc.) using npm or yarn.- Replace the placeholder blockchain API URL in `blockchainClient.js` with a real Bitcoin blockchain API service that supports querying Ordinals.This setup provides a basic structure for your application, allowing it to serve requests for Ordinals inscription data based on UTXO location and owner address. Remember to test thoroughly and consider adding error handling and validation as needed.Sent from my iPhoneOn 9. 2. 2024., at 08:53, ZedZeroth ***@***.***> wrote:﻿

What are some of the use-cases you see for the address field that would not work by using the UTXO location?

I can think of MANY really cool ideas if inscriptions could "know" that they were at the same address as each other :)
If this can be implemented it would be amazing IMO :)
My vote if for access to both UTXO and ADDRESS. The other data also look useful although most of it can be found indirectly currently I think? Maybe not parent ID? Thanks

**Comment by ZedZeroth** [comment]
Apologies if I've misunderstood but this appears to be a nonsensical ChatGPT response?
