### ISSUE TITLE
Help: i can't import or dump my privkey , the wallet which create by  "ord wallet create"

### ISSUE THREAD

**Issue by viniser** [ordinals/ord#3019]
operation: windows
ord --version: ord 0.13.1
bitcoin-cli --version: V25.0.0

the first create a wallet=test1
ord  --wallet=test1  wallet create

getwalletinfo show me: 
{
  "walletname": "test1",
  "walletversion": 169900,
  "format": "sqlite"
....
}
the format is sqlite.
**I want to know  how to  modify the created format?**

Because this format wallet, i don't know how to manage it.
when i use "importprivkey **** " it show me  "Only legacy wallets are supported by this command (code -4)"
when i use "dumpprivkey **** " it show me  "Only legacy wallets are supported by this command (code -4)"
....
crazy ....

**Comment by viniser** [comment]
Is there a command to search for all inscription information under a certain address?

**Comment by so7ow** [comment]
Try this to list descriptors:

`bitcoin-cli -rpcwallet=test1 listdescriptors true`


...then `importdescriptors` to import.

**Comment by raphjaph** [comment]
#3048 adds this functionality. You will be able to use this in the next release.
