### ISSUE TITLE
Specification of UTXOs/sats for batch inscribing

### ISSUE THREAD

**Issue by RobertClarke** [ordinals/ord#3022]
Example: I hold 2 546 sat UTXOs in my ord wallet containing uncommon sats on the first sat in the UTXOs. I want to inscribe on both of them with one TX using batch. Example structure:

mode: separate-outputs
postage: 546
inscriptions:
  - file: ~/example_image1.svg
    sat: d9447cf306398bd527de6f79fac7c7024dd1dc1c6643276f94417a43546a4c06:0:0:0
    destination: bc1p94xvz237p6l3cdx7xlkwvnz7pjkm2qvd2xwtzjcad7c5e48lll0sj2urha
  - file: ~/example_image2.svg
    sat: e477ef67f9197d68cbd0032432bb6c36569a0afbcb5bc625b1e233fe2707dc2f:0:0:0
    destination: bc1p94xvz237p6l3cdx7xlkwvnz7pjkm2qvd2xwtzjcad7c5e48lll0sj2urha

**Comment by RobertClarke** [comment]
I'm personally adding a bounty of 20 uncommons for the first working PR that fits within the scope of this issue.

**Comment by raphjaph** [comment]
@RobertClarke have a look at #3115
