### ISSUE TITLE
empty in enpoint of /inscriptions

### ISSUE THREAD

**Issue by wycl16514** [ordinals/ord#3033]
dear friends:
I am new to ordinals and try to use ord to get inscriptions from block. I have install a bitcoin full node in my local, and run ord to sync with it by using command : 
./ord.exe --bitcoin-rpc-user chenyi --bitcoin-rpc-pass chenyi --rpc-url http://localhost:8332 --http-port 8080 server
and the errors are like this:
![image](https://github.com/ordinals/ord/assets/7506958/626a54b5-1ade-4550-b965-1bbe354c64b0)

when I visit the endpoint by using http://localhost:8080/inscriptions, it is empty in the page:
![image](https://github.com/ordinals/ord/assets/7506958/6479b32e-3c8c-4537-b8d6-ae0f6e9e2cff)

have I done any thing wrong, please help, thank you very much

**Comment by so7ow** [comment]
You need to put `txindex=1` in your bitcoin.conf.
