### ISSUE TITLE
 How get seed phrase from wallet.dat?

### ISSUE THREAD

**Issue by KKimos** [ordinals/ord#3034]
I forgot my seed phrase. But wallet.dat still is in my computer.  How get seed phrase from wallet.dat?

**Comment by so7ow** [comment]
You can't. But you can export keys with: 

`bitcoin-cli -rpcwallet=ord listdescriptors true`

**Comment by raphjaph** [comment]
Yeah, unfortunately seed phrases only go one way.

Just merged #3048 which allows dumping and restoring from descriptors. It's basically just a wrapper around the command mentioned above but easier to use.
