### ISSUE TITLE
Inscribing with delegate shouldn't inscribe file contents

### ISSUE THREAD

**Issue by gmart7t2** [ordinals/ord#3035]
When I use --delegate to inscribe, it complains that I still need to provide --batch or --file.

If I provide --file, the file content is included in the reveal tx as well as the delegation tag. This makes the inscription bigger than if I hadn't used delegation. 

Delegation should probably skip inscribing the file content. Or better, don't require the user to specify a file when delegating the file content

**Comment by devords** [comment]
@gmart7t2 https://github.com/ordinals/ord/pull/3027 WIP

**Comment by bruffstar** [comment]
+1

**Comment by casey** [comment]
This has been implemented.
