### ISSUE TITLE
error: JSON-RPC error: transport error: HTTP response too short: length 0, needed 12

### ISSUE THREAD

**Issue by domwoe** [ordinals/ord#3037]
I'm trying to experiment with ord locally in regtest mode.

I've started `bitcoind` in regtest mode with the following `bitcoin.conf`

```
  regtest=1

  rpcuser=my_user
  rpcpassword=my_pass
```
 I can connect with `bitcoin-cli` just fine, but I'm running into issues with ord.

Trying e.g.

```
ord -r  --bitcoin-rpc-pass my_pass --bitcoin-rpc-user my_user wallet create
```

leads to

```
error: JSON-RPC error: transport error: HTTP response too short: length 0, needed 12.
```

Any idea what I'm doing wrong?

**Comment by raphjaph** [comment]
try setting `txindex=1` in your `bitcoin.conf`. If this still doesn't work feel free to reopen this issue

**Comment by domwoe** [comment]
Hi @raphjaph,

Forgot to mention that I started `bitcoind` with the `--txindex` flag, but now also tried adding `txinded=1` to `bitcoin.conf`.  Still getting the same error.

**Comment by raphjaph** [comment]
which version of ord are you using? `ord --version`

**Comment by domwoe** [comment]
```
ord --version
ord 0.12.0
```

**Comment by domwoe** [comment]
Tried with `0.15.0` as well but same error.

This what `bitcoind` logs

```
2024-01-26T08:22:36Z Imported mempool transactions from disk: 0 succeeded, 0 failed, 0 expired, 0 already there, 0 waiting for initial broadcast
2024-01-26T08:22:36Z initload thread exit
2024-01-26T08:22:36Z txindex thread start
2024-01-26T08:22:36Z txindex is enabled at height 188
2024-01-26T08:22:36Z txindex thread exit
2024-01-26T08:23:37Z Adding fixed seeds as 60 seconds have passed and addrman is empty for at least one reachable network
2024-01-26T08:23:37Z Added 0 fixed seeds from reachable networks.
```

**Comment by raphjaph** [comment]
You might have started `bitcoind` once without `-txindex` so try doing `bitcoind -txindex -regtest -reindex`.

If that doesn't work try upgrading to the newest `ord` version.

**Comment by domwoe** [comment]
Thanks @raphjaph 

I tried that already and I see `Reindexing finished` in the logs.

I also tried with `ord 0.15.0` as mentioned above. Is there a way to debug this issue better?

**Comment by raphjaph** [comment]
I don't know if this works but try:

`RUST_BACKTRACE=1 ord -r walet create`

This will print a trace to where exactly the program fails. Paste it here and we can have a look.

**Comment by m4nuC** [comment]
Did you ever solved that one @domwoe ?

**Comment by domwoe** [comment]
@m4nuC Sorry, I  forgot to close this issue. Quite embarrassing as I was using the wrong port. A better error message would have helped though.

**Comment by estevanpedro** [comment]
I had the same problem, i was using PORT 8333 instead of 8332

**Comment by m4nuC** [comment]
yup that's me too
