### ISSUE TITLE
delgate inscriptions syntax recommendation (delegates not rendering on most platforms yet)

### ISSUE THREAD

**Issue by ep150de** [ordinals/ord#3040]
When trying to make a delegate inscription, I can't manage to get it to render on most platforms (ordinals.com, ordinalswallet.com, ord.io, etc.)

What's the standard syntax for delagation? (I might suggest adding revising the docs to include an example or standard syntax for delegation)

I have attempted an example here: (which fails to render)
https://ordinals.com/inscription/f890460ccacc5e22f3f36640c3f84a1f7e8b3018efa4a658f77ad61cc04174f3i0

example source:
--
  | <html>
  | <script src="/content/87f77d56d9164260a7f07266719a01b4632ebc6fccf2dc43730d3a38c363d50ei0"></script>
  | </html>

I also tried using just 
<script src="/content/87f77d56d9164260a7f07266719a01b4632ebc6fccf2dc43730d3a38c363d50ei0"></script>
as an attempt at a delegation and had same results.

I've seen some folks get delegates to render on magic eden without issue so I'm not sure what I'm doing wrong.

This is another example that I've seen work, but can't manage to see the original syntax to compare.
When this renders on ordinals.com there is an error: inscription content encoding `gzip` is not acceptable. `Accept-Encoding` header not present; but when you click on preview, you can see it render fully.
https://ordinals.com/inscription/c8f09f08f0e31e0e50e222e8b1172c934a1518e53b6f2bfba34fbb8c9f028652i0
https://ordinals.com/preview/c8f09f08f0e31e0e50e222e8b1172c934a1518e53b6f2bfba34fbb8c9f028652i0

**Comment by raphjaph** [comment]
The delegate is a protocol feature so you don't have to add any specific content. We added that feature to the wallet but still have to make a release. Will be this week though. 

Here are some docs: https://docs.ordinals.com/inscriptions/delegate.html?highlight=delegate#specification
https://docs.ordinals.com/guides/batch-inscribing.html?highlight=delegate#example-batchyaml
