### ISSUE TITLE
[QUESTION] inscription content encoding `br` is not acceptable. `Accept-Encoding` header: `gzip`

### ISSUE THREAD

**Issue by david-dacruz** [ordinals/ord#3044]
How to not have this error? 
What is wrong with the inscription?
It appears on magic eden properly but not on ordinals website

https://ordinals.com/content/fd9e4f52b0017d11e5e0541c252505a62b8d89a3412cfeca584aadedffe2d77bi152

**Comment by david-dacruz** [comment]
Thanks for the answer mate 
Where is request coming from @Motjam ?

**Comment by Motjam** [comment]
It comes from you requesting. Depends on what your referencing with for an API as to the specific construct you use. But what I previously posted here: 

```javascript
request.setRequestHeader("Accept-Encoding", "gzip");
``` 
Is typically used in HTTPS Requests.

**Comment by david-dacruz** [comment]
It's simply using fetch in the frontend

**Comment by devords** [comment]
It's an issue with Cloudflare + Brotli #2775
