### ISSUE TITLE
Abstract index data storage and read/write

### ISSUE THREAD

**Issue by en** [ordinals/ord#3045]
We want to move ord on-chain, but redb couldn't run inside a chain.

One possible improvement is to refactor the reading and writing of index data to traits.
Then we can implement these traits for the chain state.

Another benefit is that once these traits are implemented, we can choose to use an RDBMS to store data.

What do you think?
We could implement it if we have the capacity.

**Comment by raphjaph** [comment]
At this point `ord` is pretty deeply interwoven with `redb`, so it could be difficult to abstract that away. I think some people are working on Postgres integration but it's not open-source so don't know how exactly they are doing it.

**Comment by casey** [comment]
This would be a huge refactor, so we're unlikely to do it.
