### ISSUE TITLE
ord wallet balance is extremely slow

### ISSUE THREAD

**Issue by devords** [ordinals/ord#3061]
Before:

```
$ time ./target/release/ord wallet balance
{
  "cardinal": 7315125,
  "ordinal": 676452,
  "total": 7991577
}

real    0m0.286s
user    0m0.019s
sys     0m0.033s
```

After:

```
$ time ./target/release/ord wallet --server-url http://0.0.0.0:4200 balance
{
  "cardinal": 7315125,
  "ordinal": 676452,
  "total": 7991577
}

real    0m23.050s
user    0m1.075s
sys     0m0.646s
```

**Comment by devords** [comment]
@raphjaph Server is running the latest master 13c0fa1efc8b849a55c7febaccd49b948e9edcfd. Same time with `--no-sync` as well.

**Comment by raphjaph** [comment]
I assume it's a pretty large wallet with many inscriptions?

**Comment by devords** [comment]
@raphjaph Yup, almost 1k inscriptions.

**Comment by raphjaph** [comment]
Before the next release I'll have to work on the wallet performance. I know I'm making a lot of redundant calls.

**Comment by gmart7t2** [comment]
I made a new wallet and sent just 6 cardinals to it.

Running "ord wallet cardinals" takes 6.2 seconds to return those 6 cardinals. The `/output/` endpoint is hit 18 times, 3 for each utxo in the wallet.

This is on regtest on my local machine.

This:
```
for output in utxos.keys() {
  self.get_output(output)?;
}
```
at the end of
```
  pub(crate) fn get_unspent_outputs(&self) -> Result<BTreeMap<OutPoint, TxOut>> {
```
is responsible for 2/3rds of the calls.
