### ISSUE TITLE
Add `/r/blocktime/<HEIGHT>`

### ISSUE THREAD

**Issue by raphjaph** [ordinals/ord#3065]
Or add a `/r/blockinfo/<HEIGHT>

**Comment by cliobitcoinbank** [comment]
We need this to use as a seed in generative stuff and other block based features.

**Comment by stet** [comment]
what will this output contain? entire block data or limited?

**Comment by jerryfane** [comment]
> what will this output contain? entire block data or limited?

I made a pull request for this #3075 

The output as of now contains:

-  Block Hash
-  Block Height
- Timestamp
- Number of Transactions
- Count of Confirmations
- Previous Block Hash
- Next Block Hash
- Inscriptions

Open for feedback though.

**Comment by stet** [comment]
> Open for feedback though.

Thank you. Remind me, what is the total block data fields that Ord indexes?
I will review code but if you know off-hand, thanks.
Ideally, this returns all indexed data. 
Typical block endpoint responses also include:

- ver
- mrkl_root
- bits
- fee
- nonce
- size        
- weight
