### ISSUE TITLE
proposal: make rune burns similar to claims

### ISSUE THREAD

**Issue by wagmiwiz** [ordinals/ord#3066]
Right now rune burns are behind an etching flag. Is there a reason we couldn't do burns the same way as claims (via a bit mask of the rune id in the edict?). Conceptually it feels strange they are done differently.

So for example I could have an input with 100 of rune A. First edict could do a transfer of 50 of rune A to another address, second do a burn of 50 rune A (output is ignored), third edict is claim for 20 of rune B etc.

**Comment by raphjaph** [comment]
Please reopen this issue in https://github.com/casey/runestone/issues. Even though the code is here we want the protocol discussion to happen over there.
