### ISSUE TITLE
Allow for subsequent mints for runes

### ISSUE THREAD

**Issue by womj** [ordinals/ord#3087]
Could the original minter of a rune have optional permissions to perform subsequent mints?

Runes is an awesome lightweight, data fully on chain protocol.

Giving issuers the ability to create more supply could open up the possibility of using it as a platforms native token.

**Comment by cryptographicturk** [comment]
Perhaps it would make sense to do the initial mint with 0 balance, so that the rune is forever flagged as being multiple mint capable.

**Comment by raphjaph** [comment]
Please open rune related issues here: https://github.com/casey/runestone
