### ISSUE TITLE
Wallet should show first inscription on reinscribed sat?

### ISSUE THREAD

**Issue by elocremarc** [ordinals/ord#3094]
I inscribed 6 inscriptions on a sat and only the last one is showing when running  `ord wallet inscriptions`. Should ord only show the first inscription the canonical one? Or should it show all the inscriptions even if they are the same sat/output?

This seems like a tricky UX issue even for other wallets.

**Comment by raphjaph** [comment]
I think it should show all, seems wrong to not show all inscriptions.

**Comment by raphjaph** [comment]
Fixed by #3101
