### ISSUE TITLE
Inscription span/multiplier property (even)

### ISSUE THREAD

**Issue by arik-so** [ordinals/ord#3097]
I would like to propose adding an evenly numbered property called `span`, allowing an inscription to span multiple satoshis.

What that's actually supposed to mean is that an inscription gets copied across the specified satoshi count. For example, today, the default span would be 1. However, if somebody set the span property to be 20, instead of one inscription being attached to the first satoshi in an output, twenty identical inscriptions would get created, and get sequentially attached to the first 20 satoshis of the output.

**Comment by casey** [comment]
I think the problem with this is that it's sort of a DoS vector. You could make a very small transaction which would lead to a very large number of database entries and UTXOs which would be expensive to update. Over time, I've realized that it's very important that anything that's expensive for the database to do need to be expensive in terms of fees.
