### ISSUE TITLE
Implementation of `rare_sat_satpoint` is not precise

### ISSUE THREAD

**Issue by zhiqiangxu** [ordinals/ord#3113]
Currently only the first sat of any sat range is [checked against common and stored](https://github.com/ordinals/ord/blob/989b763afa4d61c4b03e224e175446d055ca4741/src/index/updater.rs#L671-L680), but IMO it can happen subsequent sats of sat range can also be rare.

In other words, the result of [`rare_sat_satpoint`](https://github.com/ordinals/ord/blob/989b763afa4d61c4b03e224e175446d055ca4741/src/index.rs#L766) may not be complete. This may cause accidental transfer of rare sats.

**Comment by raphjaph** [comment]
Rare sats are always in the beginning of a range because of the way they are mined. Sat ranges can only be split and not joined, so rare sats will always be the first in the range.
