### ISSUE TITLE
Allow sending sat 

### ISSUE THREAD

**Issue by raphjaph** [ordinals/ord#3117]
`ord --index-sats wallet send --fee-rate 1 <ADDRESS> <SAT>`

**Comment by cryptoni9n** [comment]
Would it be possible to also be able to specify the sats to use for --postage, while we're at it? Below command would specify the sat you'd like to send, but also specify the range of sats for postage.

ord --index-sats wallet send --fee-rate 1 <ADDRESS> <SAT> --postage 999 ---postage-sats <SAT RANGE>
