### ISSUE TITLE
Improve preview of non-pixel art images

### ISSUE THREAD

**Issue by casey** [ordinals/ord#3129]
We use `image-rendering: pixelated` when upscaling, and `image-rendering: auto` when downscaling.

`image-rendering: auto` looks good for everything when downscaling, so that's okay. But `image-rendering: pixelated` only looks good when upscaling pixel art. For non pixel art, you get unattractive aliasing.

A few possible solutions:

1. Use `image-rendering: pixelated` for PNG, APNG, and GIF, which are lossless, and `image-rendering: auto` for WEBP, AVIF, and JPEG, which are lossy. Everyone who wanted pixel perfect rendering could inscribe with a lossless format, and everyone who didn't could inscribe using a lossy format. I think, however, that this might be too disruptive at this point. If I could go back in time and do this, I certainly would, but now that tons of inscriptions have been made, and likely a lot of pixel art WEBP, AVIF, and JPEG inscriptions, this would be a disruptive change.
2. Use `image-rendering: auto` for AVIF. AVIF is a very good but not very popular image format, and constitute of a small minority of image inscriptions, few of which are pixel art. If we use `image-rendering: auto` for AVIF, and encourage people to use AVIF for no pixel art, this could be a pretty simple solution.
3. Use `image-rendering: auto` for WEBP, AVIF, and JPEG for inscriptions made above a certain block height. This is a bit strange, but provides the benefits of 1, which is the ideal solution, but without the backwards compatibility issues.

I'm leaning towards 2. Using `image-rendering auto` for AVIF would not be very disruptive, would provide for simple advice going forward, i.e., "use AVIF for anything that isn't pixel art", which is also a good idea because AVIF is very efficient.

We should also write a document on how images are presented by `ord`, so that other explorers can use this to inform their own image presentation:

- Document maximum size of preview images, 1152x1152px.
- Document that we use `image-rendering: auto` when downscaling and `image-rendering: pixelated` when upscaling.
- Document, if we do this, that AVIFs use `image-rendering: auto` for downscaling as well.

**Comment by Psifour** [comment]
I would heavily support the creation of a new key that defines 'render hints'. Change nothing with the current default behavior, but use these hints to allow opt-in usage of alternative rendering strategies. The advantage of this is that it could be reused for non-image assets where we may wish to have some control over the default rendering methods (for instance, non formatted text). Single byte (8 flags) with flags being implemented as we discover a need for them. This doesn't impact 'inscribability' so misuse of undefined flags would result in default behavior until such time as it is defined.

**Comment by casey** [comment]
> I would heavily support the creation of a new key that defines 'render hints'. Change nothing with the current default behavior, but use these hints to allow opt-in usage of alternative rendering strategies. The advantage of this is that it could be reused for non-image assets where we may wish to have some control over the default rendering methods (for instance, non formatted text). Single byte (8 flags) with flags being implemented as we discover a need for them. This doesn't impact 'inscribability' so misuse of undefined flags would result in default behavior until such time as it is defined.

I thought about this, but it has the disadvantage that all inscribing tools would have to be updated to include the new field. Whereas with 2., users would just need to inscribe AVIF, and no software changes would be needed.

**Comment by cliobitcoinbank** [comment]
Tough call, it looks like its shaping up that different ordinals will want different display modes etc.  Have we precluded letting each ordinal establish its display config particulars in the meta data or some kind of other control scheme?  Is this the marketplaces realm of responsibility in ord's thin protocol vision or is it a possibility we will someday be able to customzie out display modes with json/cbor metadata?  Not sure how the team sees the scope of it all? What is ord?

**Comment by casey** [comment]
> Tough call, it looks like its shaping up that different ordinals will want different display modes etc. Have we precluded letting each ordinal establish its display config particulars in the meta data or some kind of other control scheme?

Flexibility is good, but in this case, I think that using `image-rendering: auto` for AVIF provides all desirable options:

- PIxel art: Use any format but AVIF.
- Non pixel art: Use AVIF.
- Pixel art that for some reason wants to opt-in to `image-rendering: auto` uspcaling: Use AVIF lossless.
- Pixel art that wants better compression: losslessly upscale the images before inscribing, then inscribe with a lossy image format.

> Is this the marketplaces realm of responsibility in ord's thin protocol vision or is it a possibility we will someday be able to customzie out display modes with json/cbor metadata? Not sure how the team sees the scope of it all? What is ord?

"What is ord?" is a complicated question, but in practice I think it's pretty simple. It is true that ord explorers, including the `ord` explorer which powers ordinals.com, are distinct from the ordinals protocol. However, in practice, users don't care about that distinction, nor should they have to. They make an inscription and then view an inscription, and whether something makes their inscription look a certain way because of an explorer implementation, versus whether something makes their inscription look a certain way because of something at the protocol level is irrelevant to them.

**Comment by Ruchixi** [comment]
Solution 2 seems like the best idea
