### ISSUE TITLE
Fix flaky tests

### ISSUE THREAD

**Issue by casey** [ordinals/ord#3133]
Our tests are very flaky at the moment, which is super annoying while developing, and require re-running CI frequently.

**Comment by mj10021** [comment]
Is there a list anywhere of which tests are flaky?

**Comment by casey** [comment]
I think there are a bunch, although there might be a single underlying cause. A good way to find them is to run:

```sh
while cargo test; do echo running; done
```

Which will run the tests repeatedly until one fails. I just ran this, and after a few runs, `etch::send_amount_does_not_select_runic_utxos` failed.

**Comment by casey** [comment]
However, I ran `etch::send_amount_does_not_select_runic_utxos` a bunch on its own, and it never failed, so I think it might be the interaction of some tests, or running a bunch of tests at the same time which is the issue.

**Comment by raphjaph** [comment]
They ain't flaky anymore. KNOCK, KNOCK, KNOCK
