### ISSUE TITLE
MP4s not playing in Safari

### ISSUE THREAD

**Issue by arik-so** [ordinals/ord#3134]
Here's an example of an MP4 inscription's content: https://ordinals.com/content/089ff91905de17b0eae476e61300e87ad72d7ab2245d9299aa143ce4b7a0f3b7i0

Playback works in most browsers but not in Safari. According to Stackoverflow, it's due to a missing `range` header: https://stackoverflow.com/a/36299252/299711

There are also some other workarounds mentioned in that SO thread, so maybe it's something you might want to address.

**Comment by bingryan** [comment]
Fixes #3276
