### ISSUE TITLE
Easy way to spin up regtest ord and bitcoind

### ISSUE THREAD

**Issue by casey** [ordinals/ord#3135]
We used to have a preview command, for inscribing some set of inscriptions on a local regtest node. We removed it, because it was wonky and nobody used it, but it would be nice to provide some replacement.

I think we should write an ord command which:

- Spins up a fully self-contained regtest bitcoin node
- Spins up a fully self-contained ord server
- Writes a bitcoin config to disk so you can do `bitcoin-cli --datadir=env/bitcoin`
- Writes an ord config to disk so you can do `ord --config env/ord.yaml` and have it be configured for every subcommand
- Kills both when the user exists
- Allow reusing an env

**Comment by elocremarc** [comment]
Will this address https://github.com/ordinals/ord/issues/3006 ?

**Comment by casey** [comment]
> Will this address #3006 ?

No, that's a separate change.
