### ISSUE TITLE
Cannot wallet inscribe in regtest: Bitcoin Core wallet but not in ord index

### ISSUE THREAD

**Issue by luckerninja** [ordinals/ord#3141]
Enviroment 

Bitcoin Core version v24.0.0
ord 0.15.0
Ubuntu 22.04

bitcoin.conf

txindex=1
server=1

---

I'm following the guide at https://docs.ordinals.com/guides/testing.html

I successfully execute the commands:

Run bitcoind in regtest with:

`bitcoind -regtest -txindex`

Create a wallet in regtest with:

`ord -r wallet create`

Get a regtest receive address with:

`ord -r wallet receive`

Mine 101 blocks (to unlock the coinbase) with:

`bitcoin-cli -regtest generatetoaddress 101 <receive address>`

But when I run:

`ord -r wallet inscribe --fee-rate 1 --file <file>`

I get an error:

`error: output in Bitcoin Core wallet but not in ord index: d3cc91e2117ee63b1f05f26c7913fc9d1267893ecac5a90d65169c356d685519:0`

Please, can you help me understand what might be causing this issue?

**Comment by wiz0p** [comment]
You need to delete the ord regtest folder and start from scratch. Mine was located at `~/.local/share/ord/regtest`
