### ISSUE TITLE
A question for ordinals pointer

### ISSUE THREAD

**Issue by Grivn** [ordinals/ord#3147]
I've read the guidance of ordinals `pointer` method https://docs.ordinals.com/inscriptions/pointer.html. And there is one description as following.
> If the pointer is equal to or greater than the number of total sats in the outputs of the inscribe transaction, it is ignored, and the inscription is made as usual.

Question is that. 
I'm not so sure what means 'the number of total sats in the outputs of the inscribe transaction'. Is it customized? Or it is a constant value referred to bitcoin configuration. Thanks a lot!

**Comment by raphjaph** [comment]
A Bitcoin transaction has inputs and outputs of specific sat values. The outputs describe the different addresses that sats go to. Since a transaction can have multiple outputs, the number of total sats is the sum of each individual outputs sat amount. This is configured on a per transaction basis.
