### ISSUE TITLE
有没有办法可以加速恢复速度？  Index file `/Volumes/HIKSEMI/ord/data/index.redb` needs recovery. This can take a long time, especially for the --index-sats index.

### ISSUE THREAD

**Issue by Rodert** [ordinals/ord#3150]
Index file `/Volumes/HIKSEMI/ord/data/index.redb` needs recovery. This can take a long time, especially for the --index-sats index.

我的 `index.redb` 文件大小等于 8G。

**Comment by raphjaph** [comment]
Yeah, it'll take a while but should recover
