### ISSUE TITLE
Signet Rune not displaying anymore

### ISSUE THREAD

**Issue by fabienghr** [ordinals/ord#3164]
I was etching quite a lot on signet rune here 
Last one created was this one : https://signet.ordinals.com/rune/RUNARYSSE
I etched more but it doesn't display anymore on signet.
However i still see them on ord -s runes 
For example, BUSINESS is a rune that was etched but not displayed on signet.

**Comment by cryptoni9n** [comment]
I'm assuming this is no longer an issue - will close for now.
