### ISSUE TITLE
Feature request: unique default index file names for different index types

### ISSUE THREAD

**Issue by so7ow** [ordinals/ord#3195]
Why do I have to manually manage my normal index and my sats index (and now runes index too?) like some kind of troglodyte?

**Comment by raphjaph** [comment]
Why are you making different index files for different types of indexes? Why not all in one?

**Comment by so7ow** [comment]
Huh. Perhaps I could rethink that process. I've always used sats index only when really needed, as it's bigger/slower and was more prone to corruption. I'll close this and try living with a single index file for a while.

**Comment by raphjaph** [comment]
Try out the new release! Once the heavy sats index is built you can just always run it in the background like you would `bitcoind`. It shouldn't have any problems keeping up with the chain once its synced. But please let me know if you run into corruption problems :)
