### ISSUE TITLE
Display sat name on inscription page

### ISSUE THREAD

**Issue by casey** [ordinals/ord#3199]
Maybe also the degree.

**Comment by raphjaph** [comment]
And also in the `/r/inscription` endpoint as an optional field

**Comment by casey** [comment]
I'm not super opposed to it, but I'm not sure it should be in `/r/inscription`, since the sat name can be derived from the number in JS.

**Comment by raphjaph** [comment]
True, I somehow though we didn't have the `sat` in the inscription. Disregard.
