### ISSUE TITLE
Proper consensus on how inscriptions should self reference

### ISSUE THREAD

**Issue by Vanniix** [ordinals/ord#3208]
I know this has been discussed many times before but I feel like this is still not properly resolved, so raising another issue.

I'm aware this exact issue was raised in #3015, and that #2628 closed that issue, but I disagree that this issue is resolved. 

At the moment if an inscription wants to fetch details about itself, such as metadata, children, sat number, etc, it first needs to know it's own inscription ID. Raph and Casey have both suggested in the past that you can get this from the url with something like this:
```js
let id = window.location.pathname.split("/").pop();
```
However, this is not documented anywhere in the handbook, so, as I see it, there is no guarantee that the inscription ID is in the url, or that it is the correct ID. I know pretty much every ordinals explorer does have the ID in the url, but without this being a requirement as part of the part of the protocol, there is no guarantee. 

This is actually already a problem, as ord.io behaves differently to ordinals.com in this regard. If you inscribe a HTML inscription, then inscribe a delegate of that HTML, ord.io will render the delegate in an iframe with the inscription ID of the original inscription, not the delegate, making it impossible for an inscription to retrieve information about itself. Here is an example inscription that demonstrates the problem:
733ca7d69f286ab295f09952f0c4d55daeae4b2fd8c1e3683fd377bbef215282i100

You can see in this screenshot that the ID in the iframe is different to the actual inscription ID
![309445850-f0cf4af9-bf08-420a-965c-685dd2b2c3f0](https://github.com/ordinals/ord/assets/134819232/bf9f0890-554e-4256-a7ed-e8bf159fa984)

While this behaviour from ord.io is frustrating, I don't consider it a bug, because the ordinals protocol does not specify that the url of the iframe must contain the inscription ID of the current inscription. I am just showing ord.io's behaviour to demonstrate that this is a serious issue.

I can see several possible solutions to this:
1. Define the structure of the url used to display HTML inscriptions in the ordinals handbook, making it part of the ordinals protocol. By doing this, ord.io would no longer be following the protocol and would be required to fix this
2. Add a new inscription endpoint (e.g. `/r/self`) that returns the same content as the `/r/inscription/:id` endpoint, but without ever needing to know it's own id (as suggested in #3015)
3. For any recursive endpoint that takes an inscription id in the path (`/r/children/:id`, `/r/inscription/:id`, `/r/metadata/:id`), you can use the keyword `self` instead of an actual inscription ID and it will return the corresponding payload for the current inscription. (e.g. `/r/metadata/self`, `/r/children/self`, etc)

In my opinion, option 3 is the best one, as it means you can get the children, metadata, etc, in a single fetch, rather than having to fetch the id from `/r/self`, then fetching the metadata/children as you would have to do in option 2. I think option 1 is the least desirable, as I think the ordinals protocol should concern itself as much as possible with the inscription/ordinals side of things, and not the explorers. I feel like it is preferable to allow explorers to choose how they want to design their systems, and if that means not using the standard conventions regarding the url, it shouldn't break a bunch of inscriptions.

I'm happy to raise a PR for this, but also happy for someone else to, because I've got a lot of other shit to do. But I wanted to get others opinion and consensus on the best solution before raising a PR

**Comment by devords** [comment]
How would the server determine the inscription ID from `self`?

**Comment by Vanniix** [comment]
@devords, yep, I didn't properly think through the actual implementation of the endpoints. Now I think about it, I can't think of a way the server can achieve this. I'm happy just going with getting the id from the url, but I do think it's important it's properly documented so we can be sure that we can rely on this (hence my PR)

**Comment by devords** [comment]
@Vanniix 100% agree! I think #3209 looks great.

**Comment by ZedZeroth** [comment]
@Vanniix Do you also think that "address" should be added? It's the only info that's present at /inscription but missing from /r/inscription. Thanks

**Comment by casey** [comment]
This is now documented in #3209. It isn't possible to write an endpoint which returns the ID of the requesting inscription, i.e., `/r/self`, since when the server receives a request for `/r/self` it would have no way of knowing which inscription is making the request.
