### ISSUE TITLE
Should we hide random mime-type counts on /status 

### ISSUE THREAD

**Issue by elocremarc** [ordinals/ord#3210]
Running the pre-release server. Seeing all the mime-types on /status is interesting. However visually there is a lot going on with a ton of random 1 offs. Should we only display mime-types that are supported in `media.rs` ?
<img width="786" alt="image" src="https://github.com/ordinals/ord/assets/42568538/9ec16d9f-6b2e-4b1a-8a1d-fbc1023fec49">

**Comment by raphjaph** [comment]
maybe we should just put in into its own subpage
