### ISSUE TITLE
Add a runes page 

### ISSUE THREAD

**Issue by lugondev** [ordinals/ord#3213]
I think we need pagination for runes:

1. Store data into table `NUMBER_TO_RUNE_ID` or `NUMBER_TO_RUNE_ENTRY`
2. Create endpoint for pagination

**Comment by lugondev** [comment]
@casey @raphjaph  what do you think about it?

**Comment by lugondev** [comment]
`define_table! { NUMBER_TO_RUNE, u32, u128 }`

**Comment by lugondev** [comment]
```rust
define_table! { NUMBER_TO_RUNE_INFO, u64, RuneInfoValue }

#[derive(Debug, PartialEq, Copy, Clone, Serialize, Deserialize)]
pub struct RuneInfo {
  pub id: RuneId,
  pub entry: RuneEntry,
}
pub(super) type RuneInfoValue = (
  RuneIdValue,    // rune_id
  RuneEntryValue, // rune_entry
);

```

**Comment by lugondev** [comment]
I need the feedback. @casey @raphjaph 
If this idea is not necessary, please give me comments.
Thankssss

**Comment by raphjaph** [comment]
Hey, will try to look at this tomorrow!

**Comment by raphjaph** [comment]
Left some comments on the PR!

**Comment by lugondev** [comment]
I try to use `RUNE_ID_TO_RUNE_ENTRY` to query but I dont know how to limit and chunk to pagination.
Please review this issue.

**Comment by lugondev** [comment]
@raphjaph merge latest and fix conflict
