### ISSUE TITLE
Add command to list wallets

### ISSUE THREAD

**Issue by casey** [ordinals/ord#3218]

**Comment by bingryan** [comment]
for this feat, what info should output contain?



`case 1 listwallets`:  `bitcoin-cli  -conf=bitcoin.conf listwallets`

```
[
  "ord"
]
```

`case 2 listreceivedbyaddress`: `bitcoin-cli -conf=bitcoin.conf listreceivedbyaddress 0 true`

```
[
  {
    "address": "bcrt1pzlmlufu6fp6m0ky7l4p527qrtqsnxcd20an2vz60w32676r5yrpsf3dxme",
    "amount": 0.00000000,
    "confirmations": 0,
    "label": "",
    "txids": [
    ]
  },
  {
    "address": "bcrt1pr2t5wgc0a692el9p9d5fr3398w0p9x7xnk8untmunql20d7vvwjst6kt26",
    "amount": 0.00000000,
    "confirmations": 0,
    "label": "",
    "txids": [
    ]
  },
  {
    "address": "bcrt1pxq750yhct0las72zmqzfnh8nsy8ut72m0pmt6njsq9pknylsqs2q5v6pu3",
    "amount": 0.00000000,
    "confirmations": 0,
    "label": "",
    "txids": [
    ]
  }
]
```
or other utxo info

**Comment by raphjaph** [comment]
It should probably just be a wrapper around `bitcoin-cli listwalletdir` (shows loaded and unloaded wallets). 

```
ord wallets
[
    "ord"
    "hodl"
     "throwaway"
     "test"
]
```

If you feel really motivated you could check if a wallet is an `ord` wallet by looking at the descriptors and then only show those and not normal Bitcoin Core wallets.

Let me know if you have any further questions!

**Comment by bingryan** [comment]
I plan to code an `ord-wallet-extension`, this extension only depends on `ord server`.

**Comment by raphjaph** [comment]
Only wallet name

**Comment by bingryan** [comment]
Maybe `ord wallet --list` is better choice ?

**Comment by raphjaph** [comment]
I like `ord wallets`. It's short and simple
