### ISSUE TITLE
ord 0.16.0 JSON API Response Changes

### ISSUE THREAD

**Issue by LightRider5** [ordinals/ord#3271]
Description:
In the latest ord 0.16.0 update, there have been significant changes to the JSON API response structure that could potentially impact all services utilizing this API. 
Specifically, the changes involve renaming of certain response parameters:

`inscription_id` has been renamed to `id`
`inscription_number` has been renamed to `number`

Impact:
These changes could disrupt existing integrations, as services relying on the old parameter names (inscription_id, inscription_number) might fail to recognize the new ones (id, number). This could lead to data parsing errors, functionality breakdowns, or other unforeseen issues within applications that are not updated to accommodate these changes.

**Comment by raphjaph** [comment]
Thanks for letting me know. These types of renames will probably be very rare in the future and if we do them I will accompany them with an adequate announcement.

**Comment by LightRider5** [comment]
It seems more variables have changed: 

- `inscription_id` is now `id`
- `genesis_fee` is now `fee`
-  `genesis_height` is now `height`
-  `inscription_number` is now `number`
-  `output_value` is now `value`

It is not good practice to name a value `value` or a number `number` as it is confusing and both are reserved words in some programming languages.
