### ISSUE TITLE
ord index update horror :(

### ISSUE THREAD

**Issue by xmybtc** [ordinals/ord#3278]
Hi mates,

As a developer i started using ord.
now the process updating index is yuck..
One index.redb file is so bad, chunk it please please please!
I am indexing since last friday... cause:

btcnode running on windows on m2 drive.
ord index.redb stored on same drive, too.

1. started indexing with windows v0.15 as there was no 0.16 build
2. indexing took ~2d after running into some errors for specific blocks -> had to delete index.redb and start over again (because one same block failed all the time)
4. tried to use the generated v0.15 index.redb with ord v0.16 (git clone build) on unix system -> cannot read index shema 16 -> 18.
5. started indexing via network from my unix client v0.16 as no windows client v0.16 was available that time -> was sooo slow -> aborted
6. started indexing on windows again with ord v0.16 as it just got released the day after.
7. indexing took again ~1d. 
8. all looked fine.
9. somehow the system crashed and index.redb needed repair -> repair stuck on 0 nothing was happening -> aborted
11. deleted index.redb and started update index again.
12. on the next day the computer crashed again (only indexed)
13. now i need repair index.redb again
14. repair is starting but aborts with "error: JSON-RPC error: transport error: Couldn't connect to host.. (os error 10053)"
15. started repair again now it continues at block 810000 (glad its not starting from beginning) -> have to wait for results..

-> i am tired of indexing cause i needed to start over and over again! (idk feels like the 10x+ time now) it costs way too much time.
IMHO indexing process needs big rework here (like index chunks ?) to be able to use data from the prior run.

i thought on the weekend i will be able to dig into. but this indexing prevents me from doing anything here.

Anyway awesome project!
just needed to share my thoughts.

Happy Tuesday!

**Comment by cryptoni9n** [comment]
Hi xmybtc,

The indexing process can be a particularly painful point of the setup for most of us.  The issues you describe are shared by many, and I would think most people agree with you that the indexing process could stand some major improvements.  

In the meantime, one great workaround / trade-off is to download a prebuilt index from ordstuff.info.  This is somewhat of a security trade-off, but one that many people are ok with given the time savings.

Please give a visit to the [Ordicord](https://discord.com/invite/ordinals) if you continue to experience these types of issues in the future and we can help support you there.
