### ISSUE TITLE
Can't open the Index when using library

### ISSUE THREAD

**Issue by gus4rs** [ordinals/ord#3303]
A developer can use the library by including: 

```Cargo.toml
[dependencies]
ord = "0.16.0"
```

But to open the ```Index```, a ```Settings``` struct is needed, but its module is not public:

https://github.com/ordinals/ord/blob/6864023f80b38b975ceb0f617d75f40bd8302626/src/lib.rs#L121

**Comment by bingryan** [comment]
for library, Maybe you should choose this crate: `https://crates.io/crates/ordinals`

**Comment by gus4rs** [comment]
This one looks just a bunch of data structs, no access to the Index or query

**Comment by raphjaph** [comment]
`ord` is not really a library right now but we do think it could be in the future. I'd be interested to know what you are trying to use the `Index` for. Is there an interface you want to use?

**Comment by gus4rs** [comment]
> what you are trying to use the Index for

Basically local lookup of sat ranges, inscriptions, etc without going through a HTTP/JSON overhead

**Comment by raphjaph** [comment]
The overhead of the HTTP/JSON should be pretty small compared to the work of the database looking up sat ranges. Are you building a tool to have more custom queries to the database? Just trying to figure out what you need so we can provide that

**Comment by gus4rs** [comment]
I am initially writing a "sat scanner" on top of ```ord``` to detect categories like https://magisat.io/categories
For that, the methods exposed by the server should suffice, but since there is already a lib crate, and I am coding in Rust, I was hoping to bypass running a server and  json parsing and call the methods directly

**Comment by raphjaph** [comment]
Ok that sounds reasonable. Here is what I suggest:

Clone the `ord` repo somewhere on your computer then in  your `Cargo.toml` do:

```toml
[dependencies]
ord = "0.16.0"

[patch.crates-io]
ord = { path = "../path/to/ord" }
```

This will override `ord` and use the code in the repo, by default the `master` branch.

Then go to the `ord` repo, create a feature branch, make the changes you need for so that you can use the `Index` and `Settings` structs. Try compiling your project and if everything works, open a PR from the feature branch. 

Let me know if you run into problems.

**Comment by gus4rs** [comment]
Yes, that is what I've done to troubleshoot the problem. Maybe at this point it'd be better to not expose the Index & friends directly, but to extract an interface with all the public methods currently exposed via http so users can call it directly
