### ISSUE TITLE
where to found the config guide

### ISSUE THREAD

**Issue by hongda3141** [ordinals/ord#3308]
Hi, I'm new there, I want to run ord with a bitcoin full node, but I can't find a latest tutorial to do this, 
I want to know where could I found the official tutorial to do this?

**Comment by cryptoni9n** [comment]
Hi - these types of requests are normally answered on the official Ord Discord (https://discord.gg/ordinals).  You might try asking there if you need further assistance.

The official documentation for how to run a full Bitcoin node is here: https://bitcoin.org/en/full-node
The official documentation for the Ord project is here: https://docs.ordinals.com/introduction.html

**Comment by hongda3141** [comment]
Thanks, I'll check that.
