### ISSUE TITLE
tcp error, os error 111

### ISSUE THREAD

**Issue by yadgen** [ordinals/ord#3337]
Command: 
`./ord --data-dir xxx --bitcoin-data-dir xxx --bitcoin-rpc-password xxx --bitcoin-rpc-url 127.0.0.1 --bitcoin-rpc-username xxx index run`

Error:
[2024-03-21T05:59:20Z ERROR ord::index::updater] Couldn't receive txs failed to fetch raw transactions after 5 retries: error trying to connect: tcp connect error: Connection refused (os error 111)
error: failed to get transaction for a2df039d22ce84803de677328efe3a2fe82b0102d66c32f899715608babd1214

How do I fix him?
OS: Ubuntu 22.04.3 LTS
Ord Version: 0.16.0

**Comment by yadgen** [comment]
Delete the bitcoin core rpc configuration and update the index using a cookie file to resolve the issue.

**Comment by alongdlut** [comment]
> Delete the bitcoin core rpc configuration and update the index using a cookie file to resolve the issue.

can you specify the method? I encounter the same issue

**Comment by nick07002** [comment]
@yadgen  can you add some details on how you fix the issue? appreciate it!
