### ISSUE TITLE
I get an error when creating an acceptance address. What should I do?

### ISSUE THREAD

**Issue by zzlicc** [ordinals/ord#3338]
thread 'main' panicked at src\wallet.rs:112:54: called `Result::unwrap()` on an `Err` value: ParseIntError { kind: Empty } note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
![Uploading 微信截图_20240322154247.png…]()

**Comment by bingryan** [comment]
You must start `ord server`. use the latest `ord` and you will get this tip

**Comment by zzlicc** [comment]
I don't understand. I'm a newbie. Can you be more detailed?

**Comment by raphjaph** [comment]
You need two things running to use `ord wallet`. First start `bitcoind` and the start `ord server`. Only after both of them are synced and running can you use `ord wallet`

**Comment by zzlicc** [comment]
![微信截图_20240325141304](https://github.com/ordinals/ord/assets/129487135/817b8b7a-0682-43bd-bff1-9643f624b2d5)
![微信截图_20240325141453](https://github.com/ordinals/ord/assets/129487135/82af032a-ffe6-415d-996e-982e209dd00d)
I think I have performed the service, but there is still a problem. Can you tell me a solution

**Comment by raphjaph** [comment]
`ord server` has to be running concurrently

**Comment by mineprine** [comment]
C:\Users\22345> ord --cookie-file E:\Roaming\.cookie --data-dir E:\Roaming\ordData server
Listening on http://0.0.0.0:80

I try to run on another cmd again:
C:\Users\22345> ord --cookie-file E:\Roaming\.cookie --data-dir E:\Roaming\ordData wallet balance
thread 'main' panicked at src\wallet.rs:112:54:
called `Result::unwrap()` on an `Err` value: ParseIntError { kind: Empty }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Why is this? Can someone help me, please

**Comment by xyuu98** [comment]
I got the same problem.

**Comment by so7ow** [comment]
User reported on Discord that this error was resolved by disabling VPN.

**Comment by raphjaph** [comment]
Yeah, the VPN could be proxying things of that port.
