### ISSUE TITLE
Impossible to made any commands

### ISSUE THREAD

**Issue by 0xJust1** [ordinals/ord#3357]
Hello guys, im running node btc (v26) with ordwallet (0.16.0), both fully sync and ord wallet server running in background.

I can't make any commands, like `ord wallet create` without this RPC error : `error: JSON-RPC error: RPC error response: RpcError { code: -32601, message: "Method not found", data: None }`

I run with : `ord --bitcoin-rpc-username xxx --bitcoin-rpc-passord xxx wallet create` 

If anyone here can help me to solve this.

bitcoin.conf :

daemon=1
server=1
txindex=1
rpcuser=xxx
rpcpassword=xxx
rpcport:8332 (with. or without, no change)
[main]
rpcbind=x.x.x.x
rpcbind=x.x.x.x
rpcallowip=0.0.0.0/0

**Comment by so7ow** [comment]
Check in your debug.log for messages regarding missing wallet support. Suspect you compiled bitcoin without proper prerequisites.

**Comment by 0xJust1** [comment]
> Check in your debug.log for messages regarding missing wallet support. Suspect you compiled bitcoin without proper prerequisites.

Thanks for your answer
True, i don't see wallet support :O 
I compiled from source, do you think is possible to switch with binaries or just i need to enable wallet support ?

**Comment by so7ow** [comment]
You can use a pre-built binary or look into correct prerequisites and re-compile.

**Comment by 0xJust1** [comment]
> You can use a pre-built binary or look into correct prerequisites and re-compile.

Thanks a lot sir

**Comment by 0xJust1** [comment]
Works ! Great, I searched for the solution all afternoon ^^ thanks again i close :)

**Comment by 0xJust1** [comment]
Resolved
