### ISSUE TITLE
tcp connect error: Connection refused (os error 111)

### ISSUE THREAD

**Issue by alongdlut** [ordinals/ord#3394]
when I use below command to sync 
ord --bitcoin-data-dir /root/btcdata/btc_data --data-dir /root/btcdata/ord_data wallet balance

there comes an error
error: error sending request for url (http://127.0.0.1/blockcount): error trying to connect: tcp connect error: Connection refused (os error 111)
because: error trying to connect: tcp connect error: Connection refused (os error 111)
because: tcp connect error: Connection refused (os error 111)
because: Connection refused (os error 111)

OS:ubuntu 22.04
Ord:0.16.0

How can I fix it?

**Comment by raphjaph** [comment]
start the `ord server` first
