### ISSUE TITLE
error: `ord wallet etch` requires index created with `--index-runes` flag

### ISSUE THREAD

**Issue by huhuji** [ordinals/ord#3399]
when I execute the command:"ord -r wallet --name alice etch --divisibility 0 --fee-rate 1 --rune FIRST.RUNE.TOKEN --supply 21000000 --symbol $", 
throw error:
"error: `ord wallet etch` requires index created with `--index-runes` flag",
How to resolve this problem?

**Comment by huhuji** [comment]
I test on the regtest network

**Comment by sherpya** [comment]
remove the index and recreate using `--index-runes``

**Comment by casey** [comment]
ord wallet etch has been removed on master, `ord wallet inscribe --batch` is now the way to etch runes.

**Comment by raphjaph** [comment]
now it is `ord wallet batch --batch etch.yaml`

**Comment by sherpya** [comment]
> now it is `ord wallet batch --batch etch.yaml`

could you please provide a sample etch.yaml?

also premine can already be done on main net?

**Comment by huhuji** [comment]
> ord wallet etch has been removed on master, `ord wallet inscribe --batch` is now the way to etch runes.

 ord wallet etch has not been removed on master yet .I fetch newest master code and compile , and run the command "ord -r wallet --name alice etch --divisibility 0 --fee-rate 1 --rune SECOND.RUNE.TOKEN --supply 21000000 --symbol $" is ok.

**Comment by casey** [comment]
It has definitely been removed, I think you might be using an old version of ord that is still in your `$PATH`.

**Comment by huhuji** [comment]
> It has definitely been removed, I think you might be using an old version of ord that is still in your `$PATH`.

that is right.thank  you
