### ISSUE TITLE
wallet send panicks when sending rune

### ISSUE THREAD

**Issue by JoeyKhd** [ordinals/ord#3406]
When trying to send a rune using the following command:

`wallet send tb1p4yj7uuwy60f4s69txmrvme6kx2fz693mctu42pny3r2rrje7g7ksscz0fp 1:BATEK•IS•RUNES•KING --fee-rate 10`

I am greeted with the following message:

```
thread 'main' panicked at src/subcommand/wallet/send.rs:121:9:
input ba293b6da8c126ffb4215de5396da79b674a9156b54dd9d8843dd00951feabb5:3 not found in utxos
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: ord::subcommand::wallet::send::Send::run
   3: ord::subcommand::wallet::WalletCommand::run
   4: ord::subcommand::Subcommand::run
   5: ord::arguments::Arguments::run
   6: ord::main
```

Interestingly enough, it actually does emit a valid transaction.

Checked out commit hash: `bb0e7c3e98ced5b7594a83c3cf4647d89d9fd5e6`

**Comment by gmart7t2** [comment]
Thanks Joey.

It looks like the panic only happens after signing and broadcasting the tx. It is trying to calculate the fee when it panics.

**Comment by raphjaph** [comment]
Does this still happen?

**Comment by raphjaph** [comment]
I haven't been able to reproduce this. If this is still a problem, please reopen this issue.
