### ISSUE TITLE
 Is the decimal setting "a rune with divisibility 2 " will make more useless utxos? 

### ISSUE THREAD

**Issue by hongda3141** [ordinals/ord#3410]
For example: 
If I setting a rune with "a rune with divisibility 2 ", and the rune will separate with "0.01", and when I transfer a "0.01" runes, what is the utxos like? Is that "0.01 runes = 1 satoshi"?
May be "1rune = 1 satoshi" is the easy way to make utxos clean I thought.

**Comment by casey** [comment]
Rune amounts and satoshi amounts are unrelated. A utxo may have any amount of satoshis and any amount of runes.
