### ISSUE TITLE
`ord server` Permission denied os error 13

### ISSUE THREAD

**Issue by GaloisField2718** [ordinals/ord#3433]
Hello, 

I'm running `bitcoind` with txindex=1 on Ubuntu LTS. 

When I run `ord server` I have `error: Permission denied (os error 13)`.

ord version: 0.16.0

I opened 8332 and 80 ports with ufw. 

I don't know where these error can comes from.

**Comment by GaloisField2718** [comment]
Hello, thanks for your answer. 
Activate ˋhttp-port` should be done with ord server command or another command to allow this?

**Comment by raphjaph** [comment]
yes, `ord server --http-port 8080` should work
