### ISSUE TITLE
"ord wallet mint" spent my immature etch commitment

### ISSUE THREAD

**Issue by gmart7t2** [ordinals/ord#3436]
I made a new etching:
  https://mempool.space/signet/tx/54b6bf9922956bed66c1d4f45b5e53c2ece2288da92d4b92b6e2bc1d2d690f93
It confirmed in block 189442.

I hit control-C while waiting for it to mature, to test that I could resume it later.

While waiting for it to mature, I minted some other tokens:
  https://mempool.space/signet/tx/b380a138389006893fac084b7377a5e4e4f3847f50be80523e41fe126f8e65d3

The mint tx spent my commitment! The mint confirmed in block 189446, while the commitment was 4 blocks deep.

When I went back to resume the etching, I saw:
  "Waiting for rune commitment 54b6bf9922956bed66c1d4f45b5e53c2ece2288da92d4b92b6e2bc1d2d690f93 to mature…"
even though by now the commitment was 11 blocks deep.

Checking the wait loop I see that the `.get_tx_out(&commit.txid(), ...)` call is returning None, because the output is no longer unspent.

We should:
  * avoid spending commitment utxos except by revealing them
  * detect and complain when commitment utxos have been spent, rather than entering an infinite loop

**Comment by gmart7t2** [comment]
When you etch a rune, the commit tx output is in the wallet for 6 blocks until it is spend by the reveal tx. During that time it shows up as a cardinal and is available for spending by other etchings, mints, inscriptions, etc.

The following change ignores these "commit tx recovery key" utxos so they won't be accidentally spent:

```
diff --git a/src/wallet.rs b/src/wallet.rs
index b1ff75f0..a6683631 100644
--- a/src/wallet.rs
+++ b/src/wallet.rs
@@ -245,6 +245,7 @@ impl Wallet {
       bitcoin_client
         .list_unspent(None, None, None, None, None)?
         .into_iter()
+        .filter(|utxo| utxo.label != Some("commit tx recovery key".to_string()))
         .map(|utxo| {
           let outpoint = OutPoint::new(utxo.txid, utxo.vout);
           let txout = TxOut {
```

**Comment by raphjaph** [comment]
Thanks for the report!

I have a PR open that fixes the loop thing and errors if commitment is spent. 

I think the most straightforward solution would be to lock the commitment output. The reveal can still spend it but it won't be picked in transaction construction.

**Comment by raphjaph** [comment]
#3480

**Comment by raphjaph** [comment]
We now lock the commitment output: #3504
