### ISSUE TITLE
Rune wallet balances don't take divisibility into account

### ISSUE THREAD

**Issue by gmart7t2** [ordinals/ord#3438]
`ord wallet balance` tells me I have 30000 GREG, but I really only have 3000 because the divisibility is 1:

```
$ ords3 balance
{
  "cardinal": 0,
  "ordinal": 1980,
  "runes": {
    "GREG": 30000,
    "GREG•GREG•GREG": 7535,
    "THESE•WILL•BE•WORTHLESS": 120
  },
  "runic": 70000,
  "total": 71980
}
$ ords3 send --fee-rate 1 tb1patp6wwevn5nmdg5fklnwf0uj2kz76qt3whntjysue62pmcsmx25s8hz74f 30000:GREG
error: insufficient `GREG` balance, only 3000 B in wallet
```

The interface should either always show the balance as 3000.0 or always show it as 30000. Currently it switches between the two. 

Personally I would prefer if the amount was always shown with the correct number of decimal places,  so "3000.0 B". They way we always know the last digit shown is the smallest denomination of the token and don't have to count the decimal digits to figure it out.

**Comment by twosatsmaxi** [comment]
<img width="695" alt="image" src="https://github.com/ordinals/ord/assets/112330467/5ceb76e5-f15f-4eb2-832b-5354d796a992">

**Comment by raphjaph** [comment]
Divisibility should now be accounted for in the wallet.
