### ISSUE TITLE
weird way to parse arguments

### ISSUE THREAD

**Issue by cvasqxz** [ordinals/ord#3450]
Hi, to use the HTTP server with port 8080 on the testnet you need to use

```
./ord --chain=testnet server --http-port 8080
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 4/2584962
Listening on http://0.0.0.0:8080
```

If you put the --http-port argument before *server* it doesn't work

```
./ord --chain=testnet --http-port 8080 server 
error: unexpected argument '--http-port' found
```

And if you want to check yout balance using port 8080 on the testnet you need to do this weird command

```
./ord --chain=testnet wallet --server-url http://localhost:8080 balance
```

**Comment by raphjaph** [comment]
flags are scoped to the subcommand they apply to
