### ISSUE TITLE
A few concerns about cenotaph.

### ISSUE THREAD

**Issue by twosatsmaxi** [ordinals/ord#3459]
I feel that cenotaph would open a can of worms if not guarded with precaution in the beginning. Even though a cenotaph is a sort of a feature which introduce upgrade mechanism. Consider a hypothetical scenario:

In let say ord version 0.20 - there was a field which is a pointer in edicts which tells where should rune goes if it mets "some" terms and it's valid one, but in 0.21 that field was removed because of let say some bug in the earlier feature. Now, all unupgraded (<0.21) clients would sees that as a valid rune transfer but latest clients (0.21) would see that as a new cenotaph and might create a mismatch in circulating supply among different third party integration (different marketplaces showing different value) and might create a havoc similar to a few bugs in BRC20 indexing last year and I think similar to a different versions of ord seeing different inscription number for the same inscription to due to cursed inscriptions being identified in different manner in different ord version. 

I feel that we gonna see the similars issues that we faced with curse inscription with Cenotaphs and in future we might have to introduce a jubilee kinda thing where every marketplaces get on a consensus.

How to prevent that?
We can have a very strong unit tests coverage ~ 100% to catch such scenarios in future or maybe through some engineering design, not sure.

**Comment by twosatsmaxi** [comment]
I don't know, this should have a been opened in Github Discussions than in Issues section, can move it.

**Comment by twosatsmaxi** [comment]
Other way to put it - there are chances of more cenotaphs added in future right? similar to more cursed inscription logic were added. There is no guarantee of # of scenarios were a runestone considered a cenotaph will increase or decrease, because it's a nature of software engineering.

**Comment by casey** [comment]
Thanks for making this issue! We will definitely never change the protocol in such a way that old runestones become cenotaphs.

Agree, that this requires extremely careful test coverage, we must ensure that we never make changes that accidentally prevent previously valid runes cenotaphs. Fortunately, I think we've actually done a really good job of enumerating carefully all the cases that can cause a runestone to be a cenotaph. And more tests are definitely welcome.
