### ISSUE TITLE
Clean shutdown takes an eternity

### ISSUE THREAD

**Issue by gus4rs** [ordinals/ord#3469]
Running a server with ```ord```, a clean shutdown takes no less than 10 minutes. The log prints 

```Waiting for index thread to finish...```

But there is no indexing being done, since the index is kept up-to-date

**Comment by cryptoni9n** [comment]
Hi gus4rs, I would recommend that you bring this and any other matters for troubleshooting to the tech-support channel in [Discord](https://discord.com/invite/ordinals).
