### ISSUE TITLE
error: etching runes requires index created with `--index-runes`

### ISSUE THREAD

**Issue by zhanghanke** [ordinals/ord#3470]
ord --bitcoin-data-dir=/data/bitcoin/data -r --index-runes  wallet --server-url http://0.0.0.0:8080 --name abcd batch --fee-rate 1 --batch /home/ec2-user/batch.yaml
error: etching runes requires index created with `--index-runes`

**Comment by zhanghanke** [comment]
how to i solve it?

**Comment by zhanghanke** [comment]
ord -r --index-runes  --bitcoin-data-dir=/data/bitcoin/data server --http-port 8080. when i start the server

**Comment by zhanghanke** [comment]
I have resolved the issue and need to manually delete the index cache after adding -- index tunes

**Comment by gmart7t2** [comment]
The index has to be *created* with `--index-runes`.

Adding the flag after the index has been created has no effect.

**Comment by Sotatek-VuNguyen2** [comment]
@zhanghanke Hi, I got the same error as you. Can you help me how can I delete the old index, and how to create new one
