### ISSUE TITLE
controlling `--postage` with `ord wallet mint`

### ISSUE THREAD

**Issue by cryptoni9n** [ordinals/ord#3471]
Is there a way to control the postage when we run `ord wallet mint`?  

Is this just a missing flag, or was it maybe excluded purposefully?  Or am I perhaps misunderstanding completely?

```
C:\Users\nine\ord\target\release>ord --cookie-file "F:\Bitcoin\.cookie" --datadir "F:\Bitcoin" wallet mint --postage 2000 --rune UNCOMMON.GOODS --fee-rate 20
error: unexpected argument '--postage' found

Usage: ord wallet mint --fee-rate <FEE_RATE> --rune <RUNE>

For more information, try '--help'.
```

**Comment by GaloisField2718** [comment]
👀

**Comment by atul2501** [comment]
👀👀👀👀👀

**Comment by raphjaph** [comment]
This is a great first issue! Just add a `--postage` flag to the command and do an unwrap_or on the value of the txout. Then check the dust limit for the address is not underneath
