### ISSUE TITLE
error：thread 'main' panicked at src\wallet.rs:146:16:

### ISSUE THREAD

**Issue by linlanggz** [ordinals/ord#3472]
ord0.17.01.
 problem occurred. need help

C:\Users\linla>ord --cookie-file D:\bitquanjiedian\.cookie --bitcoin-data-dir D:\bitquanjiedian --data-dir  D:\bitquanjiedian\ord\ord-data wallet --name test1 balance

thread 'main' panicked at src\wallet.rs:146:16:
wallet failed to talk to server. Make sure `ord server` is running.: ParseIntError { kind: InvalidDigit }
stack backtrace:
   0:     0x7ff625c9c042 - <unknown>
   1:     0x7ff625cc221d - <unknown>
   2:     0x7ff625c96761 - <unknown>
   3:     0x7ff625c9be6a - <unknown>
   4:     0x7ff625c9e279 - <unknown>
   5:     0x7ff625c9df35 - <unknown>
   6:     0x7ff625c9e794 - <unknown>
   7:     0x7ff625c9e669 - <unknown>
   8:     0x7ff625c9c949 - <unknown>
   9:     0x7ff625c9e336 - <unknown>
  10:     0x7ff625d16147 - <unknown>
  11:     0x7ff625d16683 - <unknown>
  12:     0x7ff62530574b - <unknown>
  13:     0x7ff624fb137b - <unknown>
  14:     0x7ff62501af2d - <unknown>
  15:     0x7ff624fff8a3 - <unknown>
  16:     0x7ff624fc17d3 - <unknown>
  17:     0x7ff624f31006 - <unknown>
  18:     0x7ff624f3101c - <unknown>
  19:     0x7ff625c8d0a2 - <unknown>
  20:     0x7ff624f3107c - <unknown>
  21:     0x7ff625ce5cdc - <unknown>
  22:     0x7ffab8b2257d - BaseThreadInitThunk
  23:     0x7ffab964aa58 - RtlUserThreadStart

**Comment by cryptoni9n** [comment]
is `ord server` running in another terminal/session when you try this?  If so, is it running on a non-standard port? If so, try using the `--server-url` flag.

`--server-url <SERVER_URL>  Use ord running at <SERVER_URL>. [default: http://localhost:80]`

**Comment by linlanggz** [comment]
> is `ord server` running in another terminal/session when you try this? If so, is it running on a non-standard port? If so, try using the `--server-url` flag.
> 
> `--server-url <SERVER_URL> Use ord running at <SERVER_URL>. [default: http://localhost:80]`

80 cannot work ，so i use 8081......and Index updated。but new problem：

PS C:\Users\linla> ord --cookie-file D:\bitquanjiedian\.cookie --bitcoin-data-dir D:\bitquanjiedian --data-dir D:\bitquanjiedian\ord\ord-data  wallet --server-url http://localhost:8081 --name test1 balance
error: wallet failed to synchronize with `ord server` after 20 attempts..

**Comment by cryptoni9n** [comment]
is your ord server completely indexed?  I would recommend that you bring this and any other matters for troubleshooting to the tech-support channel (https://discordapp.com/channels/987504378242007100/1069465367988142110) in Discord.

**Comment by zaneven** [comment]
Could you please let me know if this issue has been resolved? I am experiencing the same problem. @linlanggz

**Comment by cryptoni9n** [comment]
> Could you please let me know if this issue has been resolved? I am experiencing the same problem. @linlanggz

is your ord server completely indexed? I would recommend that you bring this and any other matters for troubleshooting to the tech-support channel in [Discord](https://discord.com/invite/ordinals).
