### ISSUE TITLE
Don't send etch reveals until runes activate

### ISSUE THREAD

**Issue by gmart7t2** [ordinals/ord#3474]
I am told that if you try to etch a rune on mainnet, ord will send the commit tx, wait for 6 confirmations, then send the reveal tx, whether or not runes are active yet. 

It should wait until runes are active before sending the reveal tx.

**Comment by raphjaph** [comment]
Jup, that would be a great feature!

**Comment by casey** [comment]
> Jup, that would be a great feature!

lol "great feature" this is definitely a bug 😅

@gmart7t2 Thank you for reporting!

**Comment by raphjaph** [comment]
> lol "great feature" this is definitely a bug 😅

A bug fix is also a great feature ;)
