### ISSUE TITLE
"wallet resume" should wait for the commit with the most confirmations first

### ISSUE THREAD

**Issue by gmart7t2** [ordinals/ord#3478]
`ord wallet resume` waits for the etchings in alphabetical order. If you have pending etchings for RUNE.A and RUNE.B, and the commit for RUNE A is unconfirmed while the commit for RUNE.B has 6 confirmations, `wallet resume` will wait for the RUNE.A commit to have 6 confirmations before sending the reveal for RUNE.B.

It would be better if it waited for all of them independently,  because if we have 2 etchings with 0 confirmations we don't know which one will get to 6 confirmations first.

**Comment by raphjaph** [comment]
Agreed, should probably just start different threads for each. The inital design had that but wanted to make a release so deleted it.

**Comment by gmart7t2** [comment]
No need for multiple threads. Just loop through each pending etch and check whether it has 6 confs yet. Then wait 5 seconds and try again, until they are all gone
