### ISSUE TITLE
Ord 17.1 not working with wallet with a large number of inscriptions

### ISSUE THREAD

**Issue by mgdevereux** [ordinals/ord#3486]
Getting the following error when trying to check balance

error trying to connect: tcp connect error: Connection reset by peer (os error 54)
because: error trying to connect: tcp connect error: Connection reset by peer (os error 54)
because: tcp connect error: Connection reset by peer (os error 54)
because: Connection reset by peer (os error 54)

**Comment by 0xprames** [comment]
this is occuring for me as well

it seems to be something about the size of the response sent back as a response from the server (?)

**Comment by cryptoni9n** [comment]
dupe of #3364

**Comment by cryptoni9n** [comment]
0.18.3 brings some improvements to this. Also this pending PR #3655

**Comment by cryptoni9n** [comment]
Additionally, #3621 should also help with this.  Please retry in the latest version of ord and reopen if you are still experiencing an issue.
