### ISSUE TITLE
get some error with "unrecognized outgoing" when send RUNEs to other address

### ISSUE THREAD

**Issue by ludete** [ordinals/ord#3487]
## send RUNEs

ord -r --index-runes wallet --name alice2 send --fee-rate 1 
 bcrt1pvvu2605u6nvphrxv28v42a48hs7uzmjsjcnyxncfu2stqqf0r2hsqtgcw6 FIRST•RUNE•TOKEN

get some error:   `error: invalid value 'FIRST•RUNE•TOKEN' for '<OUTGOING>': unrecognized outgoing: FIRST•RUNE•TOKEN`

## user balance

ord -r wallet --name alice2 balance
{
  "cardinal": 194374727832,
  "ordinal": 0,
  "runes": {
    "UNCOMMONGOODS": 300000,
    "FIRST•RUNE•TOKEN": 300000,
    "MINDY•SECOND•RUNE": 300000,
    "MINDYSECOND•GOODS": 300000
  },
  "runic": 40000,
  "total": 194374767832
}

**Comment by mcbagz** [comment]
From the [docs](https://docs.ordinals.com/guides/wallet.html#sending-runes), it seems that you should specify the amount as well, in the format `<AMOUNT>:<RUNE>`. So to send 123 of that rune, the command should be:

`ord -r --index-runes wallet --name alice2 send --fee-rate 1
bcrt1pvvu2605u6nvphrxv28v42a48hs7uzmjsjcnyxncfu2stqqf0r2hsqtgcw6 123:FIRST•RUNE•TOKEN`

I'm not sure if there is supposed to be some additional behavior to send the full balance, but this format has been working for me so far.
