### ISSUE TITLE
How to execute the ord command concurrently?

### ISSUE THREAD

**Issue by zhanghanke** [ordinals/ord#3489]
When I execute ：
`nohup ord - t -- index tunes -- bitcoin data dir=/data/bitcoin/data server -- HTTP port 8080`
I will execute: 
`ord - t -- index tunes runs again`
It will prompt error: failed to open index: Database already open Cannot acquire lock
If I stop the ord server, there is no problem executing ord - t -- index tunes runs.

How to execute the ord command concurrently?

**Comment by cryptoni9n** [comment]
Hi zhanghanke - as I understand this issue, you're starting the ord server and then trying to start another instance of it and receiving an error.  The database that is being locked is your index, so if you want to run simultaneous ord instances against the same chain, you will need to create a copy of that chains index and point your second instance at the copy.

If this issue persists, please reopen.
