### ISSUE TITLE
`ord list` doesn't work in 0.17.1

### ISSUE THREAD

**Issue by gmart7t2** [ordinals/ord#3493]
The `is_output_in_active_chain()` function in index.rs is looking at the `in_active_chain` field of the raw transaction output, but it is always None.

That field is only set if `getrawtransaction` is passed a block hash, and it isn't.

This fixes it:

```
diff --git a/src/index.rs b/src/index.rs
index bec84d0a..42047131 100644
--- a/src/index.rs
+++ b/src/index.rs
@@ -1630,7 +1630,7 @@ impl Index {
       return Ok(false);
     };
 
-    if !info.in_active_chain.unwrap_or_default() {
+    if info.blockhash.is_none() {
       return Ok(false);
     }
 
```

**Comment by raphjaph** [comment]
Thanks for the report!

Could you open a PR for this?

**Comment by cryptoni9n** [comment]
Hi @gmart7t2 - does this issue persist in the latest version?  If so, would you please open a PR for it?  Thanks!
