### ISSUE TITLE
Off-by-one error in wallet.rs

### ISSUE THREAD

**Issue by gmart7t2** [ordinals/ord#3508]
If we wait for the commit to have 6 confirmations before sending the reveal, the reveal will have at least 7 confirmations when it confirms.

```
sed -i 's/Runestone::COMMIT_CONFIRMATIONS/(Runestone::COMMIT_CONFIRMATIONS - 1)/' src/wallet.rs
```

**Comment by casey** [comment]
I think we fixed this in 0.18.0, but double check and make sure we didn't fuck it up 😅

**Comment by casey** [comment]
Whoops, we definitely didn't fix this!

**Comment by max-uxuy** [comment]
What about `  pub const COMMIT_CONFIRMATIONS: u16 = 6;` 
There are not found in any document or proposal, if the commit transaction and the reveal transaction in the same blockchain, how about it is?

**Comment by raphjaph** [comment]
https://docs.ordinals.com/runes/specification.html#etchings

```
To prevent front running an etching that has been broadcast but not mined, if a non-reserved rune name is being etched, the etching transaction must contain a valid commitment to the name being etched.

A commitment consists of a data push of the rune name, encoded as a little-endian integer with trailing zero bytes elided, present in an input witness tapscript where the output being spent has at least six confirmations.
```
