### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by heipacker** [ordinals/ord#3517]
error: failed to parse lock file at: /Users/heipacker/RustProjects/ord/Cargo.lock

Caused by:
  package `brotli` is specified twice in the lockfile

**Comment by casey** [comment]
I'm not able to reproduce this by running `cargo build` on master. Can you provide a repro?

**Comment by casey** [comment]
I did:

```
$ git checkout 0.18.0
$ cargo build
```

Which seemed to work. Is there anything else needed to reproduce the error?

**Comment by heipacker** [comment]
It looks like the problem is caused by me merging branche.
