### ISSUE TITLE
Mints confirmed in end block are not indexed by ord

### ISSUE THREAD

**Issue by benbuschmann** [ordinals/ord#3533]
I created this rune that ended on block 191035

https://signet.ordinals.com/rune/THE%E2%80%A2BEST%E2%80%A2RUNESIX

Sent a some mints that confirmed in 191035 but ord did not index those mints, one tx example of the mint

https://mempool.space/signet/tx/d580055edd234b5401d0882faa15bed7506fc5c096a83333d873d9ef81aa9372

**Comment by raphjaph** [comment]
Mint start and end are half open intervals [start, end), meaning that the end block is not included.

https://docs.ordinals.com/runes/specification.html#heightstart-and-heightend

**Comment by benbuschmann** [comment]
ord let me send that above mint tx while index height was 191034 but not at 191035. So I suggest not let ord send mints if they won't count.

error: rune THEBESTRUNESIX mint ended on block 191035

**Comment by raphjaph** [comment]
Fixed by #3659
