### ISSUE TITLE
where to download -index-sats & -index-runes database

### ISSUE THREAD

**Issue by hotbroker** [ordinals/ord#3536]
where to download -index-sats & -index-runes database

**Comment by spzjulien** [comment]
> where to download -index-sats & -index-runes database

https://ordstuff.info/indexes/

**Comment by hotbroker** [comment]
> > where to download -index-sats & -index-runes database
> 
> https://ordstuff.info/indexes/

thanks,but is this including index-sats?

**Comment by hotbroker** [comment]
> > where to download -index-sats & -index-runes database
> 
> https://ordstuff.info/indexes/

great ,big thanks,
