### ISSUE TITLE
Using "wallet balance"，error: JSON-RPC error: RPC error response: RpcError { code: -18, message: "Wallet file verification failed.

### ISSUE THREAD

**Issue by REAL1N** [ordinals/ord#3537]
im trying to do this：ord --bitcoin-data-dir "D:\BtcData\blocks" --cookie-file "D:\BtcData\.cookie" --data-dir "D:\OrdData" wallet balance

`error: JSON-RPC error: RPC error response: RpcError { code: -18, message: "Wallet file verification failed. Failed to load database path 'D:\\BtcData\\ord'. Data is not in recognized format.", data: None }`

i do not set anything about RPC in bitcoin.conf file，need help!!!

Thanks！

**Comment by cryptoni9n** [comment]
Hi - a much quicker resolution is waiting for you and others having issues like these on the Ordicord.  Please consider closing this and instead posting in the tech-support channel.  https://discord.gg/fwTTXMGJ
