### ISSUE TITLE
errors accessing ord as installed on umbrel

### ISSUE THREAD

**Issue by nybe** [ordinals/ord#3544]
I am on umbrel trying to access ord in terminal on Mac, I initially got it set up and got a wallet key phrase and whatnot but then had to restart umbrel and reinstall the ord browser in umbrel, somehow that has messed things up as I get this error when I type `ord wallet receive` :

# ord wallet receive 
[2024-04-15T19:22:08Z INFO  ord::settings] Connecting to Bitcoin Core at 10.21.21.8:8332/
error: wallet failed to synchronize with `ord server` after 20 attempts
   0: anyhow::error::<impl anyhow::Error>::msg
   1: anyhow::__private::format_err
   2: ord::wallet::wallet_constructor::WalletConstructor::construct
   3: ord::subcommand::Subcommand::run
   4: ord::arguments::Arguments::run
   5: ord::main
   6: std::sys_common::backtrace::__rust_begin_short_backtrace
   7: std::rt::lang_start::{{closure}}
   8: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at ./rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:284:13
   9: std::panicking::try::do_call
             at ./rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  10: std::panicking::try
             at ./rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  11: std::panic::catch_unwind
             at ./rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  12: std::rt::lang_start_internal::{{closure}}
             at ./rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:48
  13: std::panicking::try::do_call
             at ./rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  14: std::panicking::try
             at ./rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  15: std::panic::catch_unwind
             at ./rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  16: std::rt::lang_start_internal
             at ./rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:20
  17: main
  18: <unknown>
  19: __libc_start_main
  20: _start

#

**Comment by nybe** [comment]
Wasted an entire day trying to get this thing running on the umbrel environment with zero luck. I give up.

**Comment by mrv777** [comment]
It only works on umbrel with mainnet currently, if that was your issue
