### ISSUE TITLE
Remove /runes/balances page

### ISSUE THREAD

**Issue by casey** [ordinals/ord#3551]
It's very long, and doesn't do anyone any good.

**Comment by lugondev** [comment]
I make it, now let me remove

**Comment by lugondev** [comment]
> It's very long, and doesn't do anyone any good.

do you have any suggestion for query specific Rune's balance?

**Comment by lugondev** [comment]
> /runes/balances page

do you have any suggestion for query specific Rune's balance?

**Comment by lugondev** [comment]
> I actually think we should leave the JSON API /runes/balances page, since why not.

https://github.com/ordinals/ord/pull/3571

I don't know how to query specific Rune's balances?
