### ISSUE TITLE
Having Issues with my Ord updater

### ISSUE THREAD

**Issue by AvroJet** [ordinals/ord#3552]
I'm having issue with the indexing.

C:\Node\bitcoin-26.1\ord-0.18.1>ord index info
[indexing blocks] ███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░ 767403/839403[2024-04-16T00:52:46Z ERROR ord::index::updater] Couldn't receive txs failed to fetch raw transaction: code -5 message No such mempool transaction. Use -txindex or provide a block hash to enable blockchain transaction queries. Use gettransaction for wallet transactions.
error: failed to get transaction for a2df039d22ce84803de677328efe3a2fe82b0102d66c32f899715608babd1214

This is what i get. When i write -txindex it says the command is not recognized.

I'm confused. Thanks for the help!

**Comment by eddieyg** [comment]
I had a similar problem and solved it by adding the option `--index-transactions`

**Comment by raphjaph** [comment]
You have to run `bitcoind -txindex` for `ord`

**Comment by AvroJet** [comment]
Thanks for all your lines. It worked!
