### ISSUE TITLE
error: JSON-RPC error: transport error: Couldn't connect to host: Resource temporarily unavailable (os error 11)

### ISSUE THREAD

**Issue by Papilllion** [ordinals/ord#3557]
Inscribing on Bitcoin testnet worked fine, no problems unitl a few days ago on Ord 17.1. Ord server and bitcoind are running and serving current blocks fine. But now every time I want to inscribe I get 

error: JSON-RPC error: transport error: Couldn't connect to host: Resource temporarily unavailable (os error 11)

the inscription command is specifies the cookie path, just as before. Upgraded to Ord 18.1 with still the same error. Retrieving balances, and creating wallet addresses works fine. What is the problem, seeing more people in the discord having the same problem...

**Comment by cryptoni9n** [comment]
I haven't seen this happening recently.  Is anyone still experiencing this issue?

**Comment by ordinariusprof** [comment]
yes, we are still seeing this. specifically `importwallet` during inscribe operation, so it should be reproducible with a large number of descriptors imported into a wallet.

```
[2024-09-04T17:27:16Z DEBUG bitcoincore_rpc] JSON-RPC request: getdescriptorinfo ["rawtr(xxx)"]
[2024-09-04T17:27:16Z DEBUG bitcoincore_rpc] JSON-RPC request: importdescriptors [[{"desc":"rawtr(xxx)#xxx","timestamp":"now","active":false,"internal":false,"label":"commit tx recovery key"}]]
[2024-09-04T17:27:31Z DEBUG bitcoincore_rpc] JSON-RPC failed parsing reply of importdescriptors: JsonRpc(Transport(SocketError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" })))
error: JSON-RPC error: transport error: Couldn't connect to host: Resource temporarily unavailable (os error 11)
```

**Comment by raphjaph** [comment]
Loading a wallet can often take a while. We should probably add some sort of wait loop that checks if the Bitcoin Core is finished loading it.

**Comment by ordinariusprof** [comment]
That'll help but I think there's some time out we're hitting possibly in
bitcoincorerpc and it should be adjustable as well
