### ISSUE TITLE
Questions about etching runes in first activated block

### ISSUE THREAD

**Issue by Garbage123King** [ordinals/ord#3562]
Please see my experiment signet first:
191560 block : I commit, lowest "start" set is 191567   (should it be 191566?)
191561 block : commit confirmed 1
191562 block : commit confirmed 2
191563 block : commit confirmed 3
191564 block : commit confirmed 4
191565 block : commit confirmed 5, reveal transaction sent to net (it's 5 confirmed, should it be 6?)
191566 block : commit confirmed 6, reveal transaction confirmed 1.

My question is:
1、First valid etching means, description reveal transaction confirmed 1 on 840000 block?
2、if the answer of question 1 is true, then I need to send commit when 839994 is confirmed, and 839995 not come out. But, at that time, as I experience, "start" of rune only can be set to 840001, can't be set to 840000.

version: 1.18.1 release
os: windows

**Comment by casey** [comment]
If you don't set a start, it will be active when it's etched.
