### ISSUE TITLE
Emit events when new blocks are indexed

### ISSUE THREAD

**Issue by aximili-dev** [ordinals/ord#3563]
It would be useful for software developers if ord emitted events when indexing new blocks, similar to how a Bitcoin node emits events for new blocks or transactions. My suggestion for this would be ZMQ since it's the same system Bitcoin uses, which will be nice for developers already familiar with it.

My suggestion for events that could be emitted to subscribers:
 - `blockindexed`: Sent whenever a new block is completely indexed
 - `runeindexed`: Sent whenever a rune has been indexed
 - `inscriptionindexed`: Sent whenever an inscription has been indexed

The main use case for this improvement would be third party software that wants to operate on ordinals, runes, inscriptions, etc as soon as they are present in the blockchain

**Comment by raphjaph** [comment]
Have a look at src/index/event.rs and at src/index.rs and the `Index::open_with_event_sender`

**Comment by aximili-dev** [comment]
Hey @raphjaph thanks for the quick response. I've been looking it over and it seems that the only place that function is used is in `src/index/testing.rs`. If there is currently a way to use this to get events outside of a running `ord` instance please let me know. If there's not, I would be interested in taking it on as a project.

**Comment by raphjaph** [comment]
Yes, we don't use it internally but MagicEden wanted this so they can attach it to their Kafka messaging infra. I agree that ZeroMQ probably best choice, since it's a bit more lightweight and Bitcoin supports it as well. 

I've never integrated ZMQ, does this bring a dependency on non-rust libraries?

**Comment by aximili-dev** [comment]
There's two options according to the official ZMQ docs: https://zeromq.org/languages/rust/

- `rust-zmq`: Provides bindings for `libzmq`
- `zmq.rs`: Pure rust implementation of ZMQ (still WIP)

While `rust-zmq` does bring in a dependency on an external library, it's the same dependency that Bitcoin Core has to enable ZMQ. It could also be implemented conditionally using Rust's feature system. That way the dependency will only exist for those people that explicitly enable it.

Ideally `zmq.rs` would be ready for use in production, but since it's not I don't think it's a real option

**Comment by raphjaph** [comment]
Thanks for the overview!

I think long-term ZMQ might be good to add but for the moment it would add too much to the maintaining burden. Our JSON API needs some work and clean up if you are interested in doing some things there.
