### ISSUE TITLE
ord wallet balance

### ISSUE THREAD

**Issue by abdelhamidelkhouider** [ordinals/ord#3578]
ord wallet balance
error: error sending request for url (http://127.0.0.1/blockcount): error trying to connect: tcp connect error: No connection could be made because the target machine actively refused it. (os error 10061)
because: error trying to connect: tcp connect error: No connection could be made because the target machine actively refused it. (os error 10061)
because: tcp connect error: No connection could be made because the target machine actively refused it. (os error 10061)
because: No connection could be made because the target machine actively refused it. (os error 10061)

**Comment by cryptoni9n** [comment]
Hi Abdel - you need to make sure that you're running `ord server` for this command.  Also, issues like this are answered quicker on the Ordicord - please direct your troubleshooting needs there first in the future.  https://discord.gg/wnwxdK77

**Comment by Sumit240803** [comment]
#  error sending request for url (http://127.0.0.1/blockcount)
This is the command I run 
```
ord --config-dir . wallet receive
```
Error I received
```
error: error sending request for url (http://127.0.0.1/blockcount)

because:
- client error (Connect)
- tcp connect error: Connection refused (os error 111)
- Connection refused (os error 111)
```

My ord server is also running 
```
ord --config-dir . server --http-port 8080

Listening on http://0.0.0.0:8080
```

**Comment by so7ow** [comment]
When you run `ord server` on a nonstandard port (8080 in this case) you need to inform most wallet commands of that. Try:

```
ord --config-dir . wallet --server-url http://localhost:8080 receive
```
