### ISSUE TITLE
Commit dry run works on 0.18.1 release, not after recent commits

### ISSUE THREAD

**Issue by TheNovakAI** [ordinals/ord#3581]
on release 0.18.1 release code, I don't get this error on mainnet trying to dry run an etch commit.

when I sync to your newest commits AFTER 0.18.1, I get this error message. Is there a new limitation that we can't kick off a commit earlier than 840k to resume later?

![dry run error etch](https://github.com/ordinals/ord/assets/86676753/2be12ff6-0542-4f0f-aaa7-e2c40ac4b020)

**Comment by wizardlabsxyz** [comment]
@raphjaph should we expect to see a fix for this today or should I go figure out how to make the change myself locally?

**Comment by ryguy077** [comment]
Can you also add the PSBT into the wallet resume & resume --dry-run? 🙏

That is null too

**Comment by raphjaph** [comment]
This should be fixed now
