### ISSUE TITLE
`ord wallet inscribe` with multiple parents

### ISSUE THREAD

**Issue by shadowysathunter** [ordinals/ord#3586]
ord allows inscriptions with multiple parents (#2494) but not by it's own command.

```
$ ord wallet inscribe ... --parent X --parent Y
error: the argument '--parent <PARENT>' cannot be used multiple times
```

**Comment by raphjaph** [comment]
Yes, we still need to add that functionality.

**Comment by switch-900** [comment]
> Yes, we still need to add that functionality.

Has this been added to ord?

**Comment by switch-900** [comment]
Hey, @raphjaph It would be great if there could be a resolution to this. Could you update the progress?
