### ISSUE TITLE
Rare Satoshi Supply figures on docs.ordinals.com are inconsistent

### ISSUE THREAD

**Issue by ZedZeroth** [ordinals/ord#3587]
Hi everyone,

~~It's possible I've made some errors in my calculations but please could this be checked?~~ [Checked by sat_stats (X) and amended]

Ordinals.com is seen as the primary source of rare sat data so I think it's important that everything is correct.

From https://docs.ordinals.com/overview.html :

uncommon: 6,929,999
rare: 3437
epic: 32
legendary: 5
mythic: 1

Now, assuming that higher rarities supersede lower rarities, then the mythic is not a legendary, and hence there are 5 legendaries, as shown. However, according to this logic, the mythic and the legendaries are neither epics nor rares, so there should only be 27 epics and 3432 rares. Likewise there will only be 6,926,535 uncommons.

So assuming rarities don't overlap (the best approach imo) then the list should look like this: [figures amended based on checks performed by sat_stats (X)]

uncommon: 6,926,535
rare: 3432
epic: 27
legendary: 5
mythic: 1

If they do overlap then it would look like this: [figures amended based on checks performed by sat_stats (X)]

uncommon: 6,930,000
rare: 3438
epic: 33
legendary: 6
mythic: 1

The existing list is inconsistent even with regards to the mythic, as it removes the mythic from the legendaries, epics and uncommons, but not the rares. Personally I think the originally intended mythic logic should also be applied "all the way up". I appreciate that by purely using set logic with the definitions, then the mythic would be every sub-rarity too. However, coming from a CCG/TCG background, I don't think anyone would describe a rare trading card as also being uncommon/common according to set logic. On the ordinals.com sat pages, only the highest rarity is shown too (also with charms), e.g. there are only 27 sats displaying the epic tag/charm on ordinals.com.

Thanks :)

**Comment by ZedZeroth** [comment]
The figures at https://docs.ordinals.com/overview.html remain incorrect. Thanks

**Comment by casey** [comment]
I agree with the premise here, higher rarities should not be included in the figures for lower rarities. Please feel free to open a PR!

**Comment by ZedZeroth** [comment]
Done, thanks :) https://github.com/ordinals/ord/pull/4152

**Comment by casey** [comment]
Fixed in #4152
