### ISSUE TITLE
output in wallet but not in ord server: xxxxxxxxxxxxxxxxxxxxxx:2

### ISSUE THREAD

**Issue by chilibreaker** [ordinals/ord#3594]
After receiving btc, my ord wallet error--[root@ ord-0.18.0]#./ord --config config --cookie-file /btc_data/.cookie wallet balance error: output in wallet but not in ord server: xxxxxxxxxxxxxxxxxxxxxx:2
And my ord config is: 
index_runes: true 
index_cache_size: 26000000000
And my ord version is 0.18.0

ServerOS: linux

**Comment by ethangao** [comment]
same error here.

my config is :
no_index_inscriptions: true
index_runes: true

od version: 0.18.1

**Comment by vfeihuang** [comment]
I hava the same error .
config :

```
index_runes: true
index_cache_size: 6800000000

bitcoin_data_dir: H:\bitcoin_data
bitcoin_rpc_username: bitcoin
bitcoin_rpc_password: bitcoin2024KL
data_dir: H:\ord-data
```
new version: 0.18.2  on windows .
I  tried to delete index.redb and re-index already .

**Comment by it-honghui** [comment]
I hava the same error, Please tell me how to solve it.
config:
```
no_index_inscriptions: true
index_runes: true
```
version: 0.18.2

**Comment by chilibreaker** [comment]
> no_index_inscriptions: true

This config should be delete.
But Im already delete, still shows that error

**Comment by chilibreaker** [comment]
> All - on the Hell Money Podcast that was released yesterday https://youtu.be/anH9OoWzyKw?si=wavKLCLLDZYsaFt_, @raphjaph talks about the no_index_inscriptions option (35m30s mark) and how it **does not work in ord** and that they should probably remove the setting as an option.
> 
> As far as I can tell, all of you are using this flag and should not be. If your index was created with this setting then your index is bad and is the cause of this issue. I would highly recommend that you reindex with this setting set to FALSE, or torrent a new index from ordstuff.info if you do not have time to rebuild.

I already delete the flag 'no_index_inscriptions' and reindex but still shows the same error

**Comment by cryptoni9n** [comment]
> > All - on the Hell Money Podcast that was released yesterday https://youtu.be/anH9OoWzyKw?si=wavKLCLLDZYsaFt_, @raphjaph talks about the no_index_inscriptions option (35m30s mark) and how it **does not work in ord** and that they should probably remove the setting as an option.
> > As far as I can tell, all of you are using this flag and should not be. If your index was created with this setting then your index is bad and is the cause of this issue. I would highly recommend that you reindex with this setting set to FALSE, or torrent a new index from ordstuff.info if you do not have time to rebuild.
> 
> I already delete the flag 'no_index_inscriptions' and reindex but still shows the same error

if you check your http://localhost/status - does it show the number of inscriptions and a list of all the different inscriptions types?

you may actually have to set that setting to true and reindex if not.

**Comment by chilibreaker** [comment]
> > > All - on the Hell Money Podcast that was released yesterday https://youtu.be/anH9OoWzyKw?si=wavKLCLLDZYsaFt_, @raphjaph talks about the no_index_inscriptions option (35m30s mark) and how it **does not work in ord** and that they should probably remove the setting as an option.
> > > As far as I can tell, all of you are using this flag and should not be. If your index was created with this setting then your index is bad and is the cause of this issue. I would highly recommend that you reindex with this setting set to FALSE, or torrent a new index from ordstuff.info if you do not have time to rebuild.
> > 
> > 
> > I already delete the flag 'no_index_inscriptions' and reindex but still shows the same error
> 
> if you check your http://localhost/status - does it show the number of inscriptions and a list of all the different inscriptions types?
> 
> you may actually have to set that setting to true and reindex if not.


This is curl http://127.0.0.1/status ，you see:
<dt>started</dt>
<dd>2024-04-18 12:59:41.007958891 UT</ dd> <dt>uptime</dt>
<dd> 3h 615ms 568us 430ns</ dd>
‹do›initial sync time</dt>
<dd>Os</ dd>
‹dt>minimum rune for next block</dt> <d>AAAAAAAAAAAAA</ dd>
‹dt>version</dt>
<ad>0.18.1</ dd>
<d>unrecoverably reorged</dt>
<dd»false</dd>
<dt>rune index</dt>
<dd>true</dd>
<dt>sat index</dt>
<dd>false</dd>
‹dt>transaction index</dt> <dd>false</dd>
‹dt>git branch</dt>
<dd>HEAD</ dd>
‹at>git commit</dt>
<dd>
‹a href=https://github. com/ordinals/ord/commit/248ab53a
248ab53aef061bd8d679b7aab6e3d45e7bb8e9cd
‹/a>
</ dd>
«d›inscription content types</dt> <dd>
<dl>
<dt>text/plain; charset=utf-f</dt>
<dd>19416749</dt>
<at> text/plain</dt> <dd>15955500</dt> <dt>image/png</dt>
<d>766394</dt>
‹dt>application/json</dt>
<dd>313893</dt>
‹dt>image/webp</dt>

**Comment by chilibreaker** [comment]
Pls check. This will cause losing our btc, i cant get balance or withdraw

**Comment by cryptoni9n** [comment]
run `ord settings` and let's see what you have now.

**Comment by chilibreaker** [comment]
> run `ord settings` and let's see what you have now.

[root@ord-0.18.1]# •/ord settings
"bitcoin_data_dir": "/root/.bitcoin",
"bitcoin_rpc_password": null,
"bitcoin_rpc_url": "127.0.0.1:8332"
"bitcoin_rpc_username": null,
"chain": "mainnet"
"commit_interval": 5000,
"config": null,
"config_dir": null,
"cookie_file": "/root/.bitcoin/.cookie",
"data_dir": "/root/. local/share/ord"
"first_inscription_height": 767430,
"height_limit": null,
"hidden": [],
"index": "/root/. local/share/ord/index. redb",
"index_cache_size": 4114952192,
"index_runes": false,
"index_sats": false,
"index_spent_sats": false,
"index_transactions": false,
"integration_test": false,
"no_index_inscriptions": false,
"server_password": null,
"server_url": null,
"server_username": null
}



And  I transferred btc to dedault wallet ord, other wallets that have not transferred btc will not report an error

**Comment by AI-Chef** [comment]
same problem with 0.18.3

**Comment by LuisRain** [comment]
same problem with 0.18.3, my money, who can help me

**Comment by cryptoni9n** [comment]
> same problem with 0.18.3


Can you run `ord settings` and let me know your value for `no_index_inscriptions`?

**Comment by cryptoni9n** [comment]
> same problem with 0.18.3, my money, who can help me 

Can you run `ord settings` and let me know your value for `no_index_inscriptions`?

**Comment by vfeihuang** [comment]
@chilibreaker  hi,if you create wallet with ord and saved mnemonic，you can restore your wallet on UniSat with mnemonic .

**Comment by chilibreaker** [comment]
btccoin-cli -rpcwallet="ord" sendtoaddress your-btc-address 0.1
Finally, I use this command to get back my btc.
Hope this can help someone.
Otherwise, this team is frustrating.Its doen't matter with the config no_index_inscription.

**Comment by vfeihuang** [comment]
I soloved this problem with re-index . 
becouses "ord index" is so slow after 80w，I use "http://ordstuff.info" pre-download indexed file.
here is some steps.

1、confirm your ord config file  ,   'no_index_inscriptions' is false
`no_index_inscriptions: false`
2、delete index.redb in your ord data dir
3、open [http://ordstuff.info/indexes/](http://ordstuff.info/indexes/) and  click  "0.18" （latest version）, 
     then dowload  torrent file  like "index-0.18-without-8xxxxx.redb.gz.torrent  "  ，
     pls  select   the  latest one  contains "without"
4、open this torrent  and download with bt tools  
5、unzip file  *.gz downloaded and rename to "index.redb" . This gz file may hava some error on windows,i lost file several times when decompress.   I finally successfully decompressed using Winrar.
6、move index.redb to your  ord data dir 
7、retry  order server  or  ord  index update  until  listen on 80

**Comment by cryptoni9n** [comment]
>  btccoin-cli -rpcwallet="ord" sendtoaddress your-btc-address 0.1
> Finally, I use this command to get back my btc.
> Hope this can help someone.
> Otherwise, this team is frustrating.Its doen't matter with the config no_index_inscription.

Glad to hear you've found a resolution, thanks for letting us know.
