### ISSUE TITLE
The node startup cannot identify the url of the remote btc node

### ISSUE THREAD

**Issue by COLUD4** [ordinals/ord#3597]
### expected
Hello, I have a problem running the node and cannot read the remote btc information. I hope to get help from the project side and run the node intact.
### ordinals version
ord 0.18.2
### Remote BTC status
The btc node is the correct mainnet node and has been verified to have no problems.
The --bitcoin-rpc-url parameter provided is verified and completely OK.
curl -s -X POST -u 'xxx:xxx' -d '{"jsonrpc": "1.0", "id":"83", "method": "getblockcount", "params": [] }' http://xxx:8332 | jq
{
  "result": 839759,
  "error": null,
  "id": "83"
}
### Problem re-steps
**Start command**
./ord --data-dir==./node --bitcoin-rpc-username=xxxx --bitcoin-rpc-password=xxxx  --bitcoin-rpc-url=http://xxx:8332  server --http
**Error message**
error: Failed to connect to Bitcoin Core RPC at `http://xxx:8332/`:  JSON-RPC error: transport error: unexpected HTTP code: 401

**Comment by cryptoni9n** [comment]
Hi COLUD4 - the xxx in format for the `--bitcoin-rpc-url` flag needs to be replaced with the actual url, like `http://localhost:8332` or `http://0.0.0.0:8332`.  Please retry and reach out to the #tech-support channel on our official Discord server, [The Ordicord](https://discord.com/invite/ordinals) if you need further assistance,
