### ISSUE TITLE
Impossible to launch command ord runes if the server is running

### ISSUE THREAD

**Issue by Sid31** [ordinals/ord#3603]
~/ord# ord --signet runes
error: failed to open index: Database already open. Cannot acquire lock.
Works if the server is down. Is it just me or can't use runes if server is running (env  ubuntu/signet)

**Comment by cryptoni9n** [comment]
Hi Sid, this is by design.  You must stop ord server in order to release the database in order to run the ord runes command.  

Please post issues like this in the Ordicord (https://discord.gg/puZ5Y5fY) in the future to get quicker resolutions.

**Comment by Sid31** [comment]
Ok thank you, i just join the discord.
