### ISSUE TITLE
ord env config files are not permanent

### ISSUE THREAD

**Issue by cryptoni9n** [ordinals/ord#3604]
after executing `ord env`, we have the env directory and the bitcoin.conf inside.  Updating this file, and then stopping/restarting ord env will result in the file being rewritten.  Is it possible to make it persistent along with the other config files (ord.yaml/env.json)?

**Comment by raphjaph** [comment]
Yes, we should do it that way.

**Comment by nghuyenthevinh2000** [comment]
can I look into this issue if you don't mind? @raphjaph
