### ISSUE TITLE
Max Length Size

### ISSUE THREAD

**Issue by btcmachineordinals** [ordinals/ord#3609]
Currently in version 18.2, our node is not accessible due to its size.
Talking about over 100K png inscriptions in hundreds of different wallets.

getting this error:

error: wallet failed get outputs: Failed to buffer the request body: length limit exceeded

Is there a way to increase this limit

**Comment by casey** [comment]
This one is pretty easy, we need to configure axum to allow a longer request body size:

https://docs.rs/axum/latest/axum/extract/struct.DefaultBodyLimit.html
