### ISSUE TITLE
error: failed to open index: Manual upgrade required. Expected file format version 2, but file is version 1

### ISSUE THREAD

**Issue by hongda3141** [ordinals/ord#3610]
when I download version 0.18.2 , and move the old version (0.16.0) index.redb to /wallets dir, I start ord.exe, that error occured. 

my environment: windows 11

could I use the old version of index.redb in the version 0.18.2 ?

**Comment by cryptoni9n** [comment]
hi @hongda3141 - each major version update (from x.16.x to x.17.x to x.18.x) requires a newly created index.  The index from v0.16.0 is not compatible with v.18.0.  Please create a new index and seek help on the Ordicord (https://discord.gg/eQrEEaWc) for issues like this in the future.

**Comment by hongda3141** [comment]
> hi @hongda3141 - each major version update (from x.16.x to x.17.x to x.18.x) requires a newly created index. The index from v0.16.0 is not compatible with v.18.0. Please create a new index and seek help on the Ordicord (https://discord.gg/eQrEEaWc) for issues like this in the future.

ok thanks I'm reindexing
