### ISSUE TITLE
command "ord.exe --signet --index-runes --cookie-file ..\Bitcoin\signet\.cookie index run" will disconnect 

### ISSUE THREAD

**Issue by Sansan0990** [ordinals/ord#3614]
when i run the ord client siget ,run the command
```shell
ord.exe --signet --index-runes --cookie-file ..\Bitcoin\signet\.cookie index run
``` 
crash 
```shell
error: JSON-RPC error: transport error: Couldn't connect to host: 你的主机中的软件中止了一个已建立的连接。 (os error 10053) 
``` 
ord version 0.18.2 complied by myself，bitcoin.conf 
```shell
txindex=1 
assumevalid=00000000000000000000bb92b1406fa2902380b878329c8c161a9ff1d0bf2e69 
server=1 
signet=1
```

**Comment by Sansan0990** [comment]
![image](https://github.com/ordinals/ord/assets/161131012/f297b02c-bdf0-4033-bf20-979d118ef90c)
not crash immediately，indexing some time later happen.

**Comment by Sansan0990** [comment]
![image](https://github.com/ordinals/ord/assets/161131012/6f5592b7-3d83-4675-ae13-507ddb5d8fec)
tag information and compile debug version.

**Comment by Sansan0990** [comment]
just now ,I download the release binary, No error will be reported.

**Comment by raphjaph** [comment]
glad it works now
