### ISSUE TITLE
error `rune commitment spent, can't send reveal tx` locks new etchings

### ISSUE THREAD

**Issue by felipelincoln** [ordinals/ord#3617]
If I spend my commit output, resume command will always fail

Ex:
```
ord wallet batch --batch mybatch.json
bitcoin-cli createrawtransaction ... 
bitcoin-cli signrawtransactionwithwallet... 
bitcoin-cli sendrawtransaction ... 
ord wallet resume
```

Then I try again to etch the same rune, and get the error `Rune has a pending etching`, but the resume always fail

**Comment by huguojunsy** [comment]
> If I spend my commit output, resume command will always fail
> 
> Ex:
> 
> ```
> ord wallet batch --batch mybatch.json
> bitcoin-cli createrawtransaction ... 
> bitcoin-cli signrawtransactionwithwallet... 
> bitcoin-cli sendrawtransaction ... 
> ord wallet resume
> ```
> 
> Then I try again to etch the same rune, and get the error `Rune has a pending etching`, but the resume always fail

Hello, I used your method, but when I reached the step 'signrawtransactionwithwallet', I encountered an error: 'Witness program was passed an empty witness.' Could you provide the detailed steps of your operation? Thank you.

**Comment by felipelincoln** [comment]
what do you want to achieve @huguojunsy ?
