### ISSUE TITLE
A useless postage was added to the sending runes tx?

### ISSUE THREAD

**Issue by ZhiGuang** [ordinals/ord#3620]
Query Balance:

PS D:\Projects\bitcoin\ord> ordtest wallet balance
` 
{
  "cardinal": 46553843,
  "ordinal": 20000,
  "runes": {
    "xxxxxxx": "1000000",
    "MEME•OF•RUNES": "24",
    "xxxxxxx": "381000000",
    "xxxxxxx": "20000"
  },
  "runic": 1450000,
  "total": 48023843
}
`

send runes: 
PS D:\Projects\bitcoin\ord> ordtest wallet send --fee-rate 100 tb1pt0v7eye37l38e50lnywfu6atj2ec6dzteduqa4xasqnn6ndckcuqx83fsn 24:MEME•OF•RUNES
`
{
  "txid": "07537f2643f790535e12a2211f78ec82e2cfef866b694ba6d653a2caecf592f9",
  "psbt": "xxxx",
  "outgoing": "24:MEME•OF•RUNES",
  "fee": 27600
}
`

The payload in OP_RETURN:
`
0099ee9d0110e01202
`

Dechiper result:
`
{"edicts":[{"id":{"block":"2586393","tx":"16"},"amount":"2400","output":"2"}]}
`

[Tx in mempool](https://mempool.space/zh/testnet/tx/07537f2643f790535e12a2211f78ec82e2cfef866b694ba6d653a2caecf592f9)

This transaction only requires one postage, why are there two postage outputs in the transaction?

**Comment by gmart7t2** [comment]
I have the same problem. 

When you send runes, ord always creates 3 outputs: 1 for the op_return, one for the change runes, and one for the outgoing runes.

If you are sending all the runes from the input utxos, there is no need for a change output but it is created anyway.

**Comment by gmart7t2** [comment]
There should be a check for the case where you are sending the whole runic balance of the input utxos, because in that case no change or op_return is required. We can just send the inputs to the output and rely on the fact that the lack of an edict makes all the input runes go to the first output.
