### ISSUE TITLE
Supply on ordinals.com site is circulating supply and not max supply, mint percentage is also wrong

### ISSUE THREAD

**Issue by wizardlabsxyz** [ordinals/ord#3622]
After etching a rune on regtest off latest commit I see the recent addition of mint percentage. If for example I etch a rune with 10% premine, then the mint percentage should say 10%. It currently says 100%. I believe this is because the supply on the page is setup to show circulating supply, so the precentage calculation is done off of the circulating supply when it should be done off the max supply. Also the supply that's listed on the page should say circulating supply and not just supply. 

Request:
- Change SUPPLY on rune page to be CIRCULATING SUPPLY
- Add MAX SUPPLY to page
- Change mint percentage to be based of MAX SUPPLY and not CIRCULATING SUPPLY

**Comment by casey** [comment]
I think that premine percentage based on current supply is correct, since future mints which are possible simply may not happen.
