### ISSUE TITLE
index apears to have been built with older, incompatible version of ord, consider deleting and rebuilding

### ISSUE THREAD

**Issue by Horianu** [ordinals/ord#3623]
index "C:\users\AppData\roaming\ord\index.redb" apears to have been built with older, incompatible version of ord, consider deleting and rebuilding the index: index schema 24, ord schema 25

This is what I get when updating from 0.17.1 to any version of 0.18 , have asked and other didn't have that problem at all.

Any idea why?

**Comment by cryptoni9n** [comment]
Hi Horianu - this is by design.  Anytime ord has a major version update, it requires a new index schema and everyone must then reindex.

Additionally - questions like this are better asked on the official ord discord, called the Ordicord here https://discord.gg/ordinals

**Comment by raphjaph** [comment]
https://docs.ordinals.com/guides/reindexing.html
