### ISSUE TITLE
Reason for `ord env` `--decompress` flag?

### ISSUE THREAD

**Issue by casey** [ordinals/ord#3627]
@jahvi What's reasoning behind adding a `--decompress` flag to the `ord env` server instance? Browsers support brotli, so unless you're behind a service like clouldflare, which doesn't support brotli correctly, I'm not sure what the use-case for this is.

**Comment by jahvi** [comment]
Just because it requires https which is not usually available locally, not sure why it's only supported with https though

**Comment by casey** [comment]
Ahh, gotcha, that makes sense. Thanks for explaining!
