### ISSUE TITLE
bumpFee on reveal transaction

### ISSUE THREAD

**Issue by eriklueth** [ordinals/ord#3628]
We have committed to a rune name 6 blocks before halving and revealed it in the halving block. Because the fees went crazy, we decided to bump them using the `bitcoin-cli bumpFee` command. This has worked on signet with previous ord versions (`ord 0.18.0`). However, with `ord 0.18.3`, the rune will not be displayed on ordinals.com/runes.
Is it possible to fix the interpretation such that reveal transactions that were bumped are still valid etchings?
Thanks!

**Comment by GiantDole** [comment]
Have seen a couple of projects getting burnt by this.... :/

**Comment by onchainguy-eth** [comment]
Same 💀

**Comment by GiantDole** [comment]
By observing the mempool, I at least found these transactions that made use of RBF (e.g. `bumpFee`) for reveal transactions that didn't count as etching:
27bbb1f7776d3ac5f41c17a5cde59b4feba5e9f5c5e76f19559c787a7c771055
ed7b70fb55b8a5f6ddc850d39a0686c429feab9051da121e23bc1f953e38ee3f
6889c5955b4ebaf2bcbddcec14e22e09e0036c94cd0d143711d5968302a56de3

It should be feasible to track the commitment across a replaced reveal transaction and recognize this as valid etching.

**Comment by victorkirov** [comment]
The inputs for these etchings are not committing to the name. The original transaction did, but the RBF'd one not. It wouldn't really make sense to base etching off off transactions that never made it onto the blockchain. 🤔
