### ISSUE TITLE
Premine percentage formula should use the total supply

### ISSUE THREAD

**Issue by habacrypto68** [ordinals/ord#3630]
Correct me if I am wrong, but this premine percentage formula that is being used in the portal is wrong:
((self.entry.premine as f64 / self.entry.supply() as f64) * 10000.0) as u128

The self.entry.supply() is actually calculating the circulating supply (premine + minted) instead of the total supply (premine + (cap * amount per mint))

**Comment by kusan-thana** [comment]
Yes, I guess a lot of people don't mint because they see premint at 100%.

I think the best would be to have both. Have the premine percentage with the current supply and the percentage with the fully dullited one.

**Comment by GiantDole** [comment]
Not sure about this... This would allow the attack vector of having a considerable cap but low duration to trick people. 
Maybe having both percentages would be helpful for full transparency:
"Fully diluted percentage" and "Current percentage"

**Comment by cryptoni9n** [comment]
I feel like it needs to be presented in another way.  It doesn't answer the question of "what % was premined by the etcher?" - it answers the question "what % wasn't premined by the etcher?"

I think most people want to know the answer to the first question when it comes to premine percent.

**Comment by raphjaph** [comment]
Yes, we should add more clarification to that

**Comment by HubertusVIE** [comment]
> Yes, we should add more clarification to that

This is also related to #3677, as current total supply is what matters most, whereas the governance determined max total supply is more of an information item. 

Consider that the max supply may be limited, like in Bitcredit Protocol or unlimited like in the RWA use cases mentioned by other supporters of #3677. This means that the second CURRENT/MAX percentage mentioned by @GiantDole and @cryptoni9n may be undetermined. 

Also: Considering the BISQ scheme which we are emulating, the minting itself would be limited to the signature with governance rights.
