### ISSUE TITLE
duplicate name runestone on same block, is this a Cenotaph?

### ISSUE THREAD

**Issue by bFanek** [ordinals/ord#3631]
I etched a runestone on the halving block with fee 1000 sats/vB, the commit and reveal transactions went through, but someone else etched the same name runestone on same block at 10,000 sats/vB, so although my transactions got confirmed, my duplicate name runestone etch wasn't indexed.

Does this mean my dupe runestone etch is a Cenotaph? I understand ord doesn't allow etching a runestone if name already exists, but in this scenario the name didn't exist and it became a duplicate on the same block. Thanks!

**Comment by cryptoni9n** [comment]
Hi bFanek - this is unfortunate but expected for this type of a scenario.  I imagine it was a very popular name, and in cases where 2 different reveals for the same name get into the same block, it is a matter of which gets mined first in the block.  Like with ordinals, first is first.  

Typically, transactions are ordered within each block by fee, but not always.  Casey spoke about this during the halving live stream and showed the example of Rune 1 having not paid the highest fees in the halving block. This is also talked about fairly extensively in the Technically Bitcoin Runes episode here: https://youtu.be/FhEus2IeSN0?si=Q84ZhCbFkMDoTQIv

So, is this a Cenotaph?  I'm not sure exactly - but I think of it more as a failed reveal.  I could be wrong, but I think Cenotaphs are successful transactions that burn all of the tokens associated with them, but they would still be able to be seen as a dead unmintable rune, and that marker would be the Cenotaph.

Sorry to hear about this happening, but I bet it happened to a few people trying to get a popular name like Rune 6, for example.

Another good place to ask questions like these is on the official ord Discord (https://discord.gg/3bZCy7mr) 

I hope this helps.

**Comment by bFanek** [comment]
Thank you for the info, yes I’m very upset about this, I was hoping to leave my footprint on the blockchain on the halving block.

Since my etch transaction is confirmed on the halving block, I hope maybe future ord versions can recognize this runestone as a Cenotaph (maybe set a negative number on it), that would be nice.

Cheers!
