### ISSUE TITLE
I mint success  but i cant find Satoshi Nakamoto in UniSat wallet, how can i do? Tks

### ISSUE THREAD

**Issue by vfeihuang** [ordinals/ord#3636]
I mint success with " ord wallet mint "  command  and this is balance info

![image](https://github.com/ordinals/ord/assets/13249829/cbc77f96-6088-4cbd-a12d-582f4b3858f0)

but when i  import my mnemonic to UniSat wallet ，it's show nothing .

![image](https://github.com/ordinals/ord/assets/13249829/8bbd87e9-91d3-43e1-8fa0-8bcca730488e)
![image](https://github.com/ordinals/ord/assets/13249829/c0065283-2d03-4ea2-8ea7-63a13434b5f7)

how can i do , Tks

**Comment by cryptoni9n** [comment]
Hi vfeihuang - we have some instructions on the Ordicord at the following link: https://discord.com/channels/987504378242007100/1069465367988142110/1231116582651166720

Please utilize the Ordicord (https://discord.gg/EhzFG3GR) for any additional support questions you may have in the future.

**Comment by vfeihuang** [comment]
OK ,tks a lot !  
 I have registered and  learning with my pool english.

**Comment by vfeihuang** [comment]
Tks camario30 , my problem is solved.

![image](https://github.com/ordinals/ord/assets/13249829/ae68954d-8f3a-4e37-9604-c66ca5981684)

https://discord.com/channels/987504378242007100/1069465367988142110/1231116582651166720

中文说明：
我是使用 ord 创建的钱包打的中本聪，如果不是，以下操作可能无效
1、打开 Unisat 钱包 
2、点击右上角的按钮， 点击 + 号  
3、点击 restore wallet from mnemonic ，点击最下面的 Other Wallet 
4、输入你的助记词 下一步
5、找到 Custom Derivation Path 文本框，输入  m/86'/0'/0'/1
6、点击上面的按钮  Scan in more addresses ，可以看到有余额的地址出现,选择一个导入即可
![image](https://github.com/ordinals/ord/assets/13249829/d47f6d7a-bc5a-46bb-9d26-aab521671f3f)

**Comment by raphjaph** [comment]
This seems resolve. Please reopen if not.
