### ISSUE TITLE
Command 'ord' not found

### ISSUE THREAD

**Issue by 0AAK0** [ordinals/ord#3638]
Hi guys,
need help pls.

I'm running a node on ubuntu 22.04, node is running fine but i can't get Ord to work!
I did follow the guide and installed: libssl-dev & Rust ...
Then did the build: 
```
git clone https://github.com/ordinals/ord.git
cd ord
cargo build --release
```

To this point all good no error, but when I run: `ord --version` I get error: **command 'ord' not found**
I tried to install it using: 
`curl --proto '=https' --tlsv1.2 -fsLS https://ordinals.com/install.sh | bash -s`
**install.sh: error: ord already exists in /home/btc/bin**

Can anyone help?
Thanks.

**Comment by endangurura** [comment]
@0AAK0 did you add /home/btc/bin to your PATH?
Another alternataive is to copy  target/release/ord  to /usr/local/bin

**Comment by 0AAK0** [comment]
> @0AAK0 did you add /home/btc/bin to your PATH? Another alternataive is to copy target/release/ord to /usr/local/bin

Hi endangurura,
Thanks for your reply, I don't think I did that ... 
appreciate if you can guide me on how to do it. (not a dev, forgive me).

**Comment by endangurura** [comment]
@0AAK0 run these commands
```shell
git clone https://github.com/ordinals/ord.git
cd ord
git checkout 0.18.3
cargo build --release
sudo cp target/release/ord /usr/local/bin
ord --version
```

**Comment by 0AAK0** [comment]
> @0AAK0 run these commands
> 
> ```shell
> git clone https://github.com/ordinals/ord.git
> cd ord
> git checkout 0.18.3
> cargo build --release
> sudo cp target/release/ord /usr/local/bin
> ord --version
> ```

Man thank you sooooooooo much.
it finally worked, you saved me.

Would like to ask you if you have a ready file for Rune etching? 
would be great if you can share with me. (it's ok if not)

Again, thank you.

**Comment by 0AAK0** [comment]
> @0AAK0 run these commands
> 
> ```shell
> git clone https://github.com/ordinals/ord.git
> cd ord
> git checkout 0.18.3
> cargo build --release
> sudo cp target/release/ord /usr/local/bin
> ord --version
> ```

Trying to run: ord server
but i get: **error: cookie file `/home/btc/.bitcoin/.cookie` does not exist**

is it because we change the directory?

**Comment by endangurura** [comment]
@0AAK0 Do you have a full bitcoin node running?

**Comment by 0AAK0** [comment]
> ```shell
> /usr/local/bin
> ```

Yes I did install it using the ~snap command from the official site & synced all blocks
I did run it using: `bitcoin-core.daemon`
![image](https://github.com/ordinals/ord/assets/3874112/48a5025a-1ac1-499b-aa0d-0dc9d934963f)

If i run: bitcoin-core.cli -getinfo
![image](https://github.com/ordinals/ord/assets/3874112/d7f360b0-68b8-45f2-8433-9ac83d81fc99)

I kept it running in the backfround:
![image](https://github.com/ordinals/ord/assets/3874112/62c79b6a-0332-4eae-be46-7e65c546392b)

**Comment by 0AAK0** [comment]
> @0AAK0 Do you have a full bitcoin node running?

I see the .cookie file under this path
![image](https://github.com/ordinals/ord/assets/3874112/57853467-ade4-47e7-ac78-c73b6366e2e2)

**Comment by endangurura** [comment]
add coookie file path to ord command
`ord --cookie-file /path/to/cookie/file server`

**Comment by 0AAK0** [comment]
> ord --cookie-file

weird, it doesn't see it!

![image](https://github.com/ordinals/ord/assets/3874112/75826bc8-5190-4e9f-9965-5557eedd78d5)

**Comment by 0AAK0** [comment]
> add coookie file path to ord command `ord --cookie-file /path/to/cookie/file server`

got it to work but, 

![image](https://github.com/ordinals/ord/assets/3874112/777f2fd6-9bb0-45a3-8f28-1cc8dbe132f1)

**Comment by 0AAK0** [comment]
any idea how i can change ord .cookie path to the right path?
![image](https://github.com/ordinals/ord/assets/3874112/6615c747-4465-4fe6-b7eb-b999bc457dbc)

correct path is: `/home/btc/snap/bitcoin-core/common/.bitcoin/.cookie`

**Comment by cryptoni9n** [comment]
Hi 0AAK0 - I'd like to direct these types of questions to our #tech-support channel on the Ordicord, here: https://discord.gg/CSF5tDdR

If you run ord --help, you'll see all the various options for flags that you can provide to the ord executable.  one of the most common flags is the --cookie-file flag, which is the one you're asking about here.  

If you need further help, please consider the Ordicord.  Thanks and good luck!

**Comment by SoFTCureOrigin** [comment]
> @0AAK0 run these commands
> 
> ```shell
> git clone https://github.com/ordinals/ord.git
> cd ord
> git checkout 0.18.3
> cargo build --release
> sudo cp target/release/ord /usr/local/bin
> ord --version
> ```

Hi,  i think symbolic link 'ln -s' .... is better than copying....

**Comment by 0AAK0** [comment]
> > @0AAK0 run these commands
> > ```shell
> > git clone https://github.com/ordinals/ord.git
> > cd ord
> > git checkout 0.18.3
> > cargo build --release
> > sudo cp target/release/ord /usr/local/bin
> > ord --version
> > ```
> 
> Hi, i think symbolic link 'ln -s' .... is better than copying....

Hey man, thanks for the reply ... and what would be the command?
