### ISSUE TITLE
Feature request: command to burn runes

### ISSUE THREAD

**Issue by kusan-thana** [ordinals/ord#3640]
Would be nice to have a burn command that would either send the runes to a special address or that would make a cenotaph to burn them. The number of burned runes would be displayed on the rune page.

**Comment by pauldemarco** [comment]
For all the shameful pre-miners, this could allow for a redemption arc if some / all of the premine can be burned -- and subsequently show a lesser percentage of premine.

This perhaps should be a separate issue: "Premine percentage should account for burned runes"

**Comment by nghuyenthevinh2000** [comment]
I think this could be fairly easily done by:
* sending runes to a recognized burn address X by Rune protocol
* try to create Cenotaph to make sure it stays burned. Cenotaphs may be created if a runestone contains an edict with an output number greater than the number of inputs

Hmm, I will try to produce a working logic for this one if you don't mind @raphjaph
