### ISSUE TITLE
Feature Request: MultiOutput Edict for Airdrops

### ISSUE THREAD

**Issue by gamedevalice** [ordinals/ord#3658]
This would make it a lot simpler to do large airdrops, and would require much fewer transactions, making it more cost efficient as well.

Based on:
https://github.com/ordinals/ord/blob/91a14fd9ed0270d021a0dac99087182c2cedeaae/crates/ordinals/src/edict.rs#L4-L8

I can see that the type of `output` is `u32`, i.e can have a maximum value of: `4,294,967,295`

According to: https://bitcoinops.org/en/tools/calc-size/
You could probably fit `roughly 100,000 outputs` in a transaction that would be large enough to hit the block size limit.

So, given that the higher values are actually far from achievable, I suggest when `output` has a value of `u32::MAX`, we treat it as meaning: 

- send `amount` to every output (except the output to which the remaining change is sent to)

This approach requires no changes to the runestone's data structure or size, so it is 'free' as far as the runestone size fitting in a `OP_RETURN` is concerned.

**Comment by cryptoni9n** [comment]
I would like to second this request on behalf of many in the Ordicord. This has been the number one ask since halving by those wishing to airdrop their premined runes.

**Comment by gamedevalice** [comment]
Actually, according to this post from less than 2 hours ago, this feature is already implemented. To use it you set amount to zero and output to the total number of outputs (including OP_RETURNs) 

Since this is already implemented, I guess the remaining issues are to add it to the documentation so people can know about it, and also adding a command to the wallet for constructing runestones with edicts and multiple outputs

![image](https://github.com/ordinals/ord/assets/124552025/e7fb05f5-ab70-4ced-8455-3c7014f747ad)

**Comment by gamedevalice** [comment]
Something to verify is whether it also airdrops to the output that is used for sending the remaining change, i.e the remaining unspent inputs, which is typically yourself. (defaults to first output, but can be changed with pointer)
It sounds like it might, but I haven't tested it yet. I think it would be more intuitive if it did not.

**Comment by revofusion** [comment]
@raphjaph the current split all works great already, what is needed rather is a flag for excluding an output # from the split all

**Comment by gamedevalice** [comment]
following the pattern that's already in place,
`output == tx.output.len()` means split to all outputs
so perhaps 
`output == tx.output.len() + 1` could mean split to all outputs except pointer

this allows the possibility for other kinds of special Edicts with new behaviors in the future, like:
`output == tx.output.len() + 2` 
`output == tx.output.len() + 3` 
etc

**Comment by demonkes** [comment]
@raphjaph

**Comment by raphjaph** [comment]
We now have the `split` command #4030 and also documentation for it #4062. 

> * send `amount` to every output (except the output to which the remaining change is sent to)

You can actually implicitly exclude the change output by prepending an edict that allocates the surplus runes to the change output. The second edict then allocated 10 UNCOMMON•GOODS evenly to all remaining outputs but since we already transferred the surplus to the change output it won't receive any. 

Example: Airdrop 10 UNCOMMON•GOODS  each to 8 people.

Inputs: 
```
0: 100 UNCOMMON•GOODS
1: Only sats
```
Outputs:
```
Outputs:
0: OP_RETURN 
  Edict {
    rune: UNCOMMON•GOODS,
    amount: 20, 
    output: 9, 
  },
  Edict {
    rune: UNCOMMON•GOODS,
    amount: 10, 
    output: 10, 
  }
1: 330 sats + 10  UNCOMMON•GOODS
2: 330 sats + 10  UNCOMMON•GOODS
3: 330 sats + 10  UNCOMMON•GOODS
4: 330 sats + 10  UNCOMMON•GOODS
5: 330 sats + 10  UNCOMMON•GOODS
6: 330 sats + 10  UNCOMMON•GOODS
7: 330 sats + 10  UNCOMMON•GOODS
8: 330 sats + 10  UNCOMMON•GOODS
9: change sats  + 10  UNCOMMON•GOODS  + 10  UNCOMMON•GOODS
```

I will close this since you can actually exclude the change output and airdrop efficiently. I will open a new issue to actually implement this logic in `ord`.

**Comment by raphjaph** [comment]
#4081
