### ISSUE TITLE
I mint success but i cant find my Rune in my UniSat wallet, what should I do?

### ISSUE THREAD

**Issue by steventswu** [ordinals/ord#3665]
I have a Unisat Wallet address, I import it into ord to use it to mint rune with my full node.
I mint  #1 Rune `Z•Z•Z•Z•Z•FEHU•Z•Z•Z•Z•Z` and when I run`ord wallet balance`  it seems like i got it but...
<img width="303" alt="image" src="https://github.com/ordinals/ord/assets/12851761/8e189dcc-ba64-48bc-9ecd-36d4e86d0db9">
when i check my unisat wallet it isn't there and my ₿ isn't showing correctly as well
<img width="328" alt="image" src="https://github.com/ordinals/ord/assets/12851761/193f177c-3c6e-4367-9e56-25bbd198c1b7">
my ₿ from `OP_RETURN` is send to another address 
https://mempool.space/tx/d2578349104a8a052618223a65ab747d166a2686e4f42c988f422b5354abbc8e
<img width="1163" alt="image" src="https://github.com/ordinals/ord/assets/12851761/17f7500b-4ecf-4309-ac66-386f10af6f7e">

And this is what is showing up on Bitcoin Core
<img width="404" alt="image" src="https://github.com/ordinals/ord/assets/12851761/52e8d09a-03b5-4739-b2aa-fc4c89c455ec">

I need help with this, thanks so much 🙏🏽🙏🏽🙏🏽

**Comment by raphjaph** [comment]
Unisat and `ord` do not have compatible wallets. They work in different ways. You can't import the one into the other and expect it to work. You'll have to transfer the rune from `ord` to a new unisat wallet.

**Comment by cnsilvan** [comment]
> your receive address is `bc1pnatshhkatm5m8482m54f6k2cz4td97uf5dmqpuuygxr0vty55dws7rgq45`, and this address is a derived child address from the root address(your unisat wallet root address).
> 
> 2 options:
> 
> 1. add sub account from your unisat account(check to Taproot(P2TR) Address type) -> once may not work
> 2. `ord wallet dump`, select your private key, and import it to your wallet.  -> Recommend
> 
> Don't worry, everything is under control. :)

dump some descriptors ，how to get private key? thank u

**Comment by cnsilvan** [comment]
> > your receive address is `bc1pnatshhkatm5m8482m54f6k2cz4td97uf5dmqpuuygxr0vty55dws7rgq45`, and this address is a derived child address from the root address(your unisat wallet root address).
> > 2 options:
> > 
> > 1. add sub account from your unisat account(check to Taproot(P2TR) Address type) -> once may not work
> > 2. `ord wallet dump`, select your private key, and import it to your wallet.  -> Recommend
> > 
> > Don't worry, everything is under control. :)
> 
> dump some descriptors ，how to get private key? thank u

or how to specify the change address?I know that runes can specify the receiving address, but what about the UTXO for change?

**Comment by bingryan** [comment]
> > your receive address is `bc1pnatshhkatm5m8482m54f6k2cz4td97uf5dmqpuuygxr0vty55dws7rgq45`, and this address is a derived child address from the root address(your unisat wallet root address).
> > 2 options:
> > 
> > 1. add sub account from your unisat account(check to Taproot(P2TR) Address type) -> once may not work
> > 2. `ord wallet dump`, select your private key, and import it to your wallet.  -> Recommend
> > 
> > Don't worry, everything is under control. :)
> 
> dump some descriptors ，how to get private key? thank u

ord command not support descriptor to private key, i use my local tool.  :)

**Comment by bingryan** [comment]
> > > your receive address is `bc1pnatshhkatm5m8482m54f6k2cz4td97uf5dmqpuuygxr0vty55dws7rgq45`, and this address is a derived child address from the root address(your unisat wallet root address).
> > > 2 options:
> > > 
> > > 1. add sub account from your unisat account(check to Taproot(P2TR) Address type) -> once may not work
> > > 2. `ord wallet dump`, select your private key, and import it to your wallet.  -> Recommend
> > > 
> > > Don't worry, everything is under control. :)
> > 
> > 
> > dump some descriptors ，how to get private key? thank u
> 
> or how to specify the change address?I know that runes can specify the receiving address, but what about the UTXO for change?

use `--destination xxx` to specify receive address is better way, not use random change address, unless you are familiar with BTC dev.

**Comment by cnsilvan** [comment]
> > > > your receive address is `bc1pnatshhkatm5m8482m54f6k2cz4td97uf5dmqpuuygxr0vty55dws7rgq45`, and this address is a derived child address from the root address(your unisat wallet root address).
> > > > 2 options:
> > > > 
> > > > 1. add sub account from your unisat account(check to Taproot(P2TR) Address type) -> once may not work
> > > > 2. `ord wallet dump`, select your private key, and import it to your wallet.  -> Recommend
> > > > 
> > > > Don't worry, everything is under control. :)
> > > 
> > > 
> > > dump some descriptors ，how to get private key? thank u
> > 
> > 
> > or how to specify the change address?I know that runes can specify the receiving address, but what about the UTXO for change?
> 
> use `--destination xxx` to specify receive address is better way, not use random change address, unless you are familiar with BTC dev.
Yes, I received the runes using the specified address, but the change UTXO could not be seen in unisat, resulting in an error in the balance calculation.

**Comment by bingryan** [comment]
you can use `ord wallet transactions` or `ord wallet outputs` to get txid, then check it.

**Comment by cnsilvan** [comment]
> you can use `ord wallet transactions` or `ord wallet outputs` to get txid, then check it.


Previously, because rune could not be seen in unisat, the receiving address was specified. Now I can't find the balance again。But the balance in ord is normal。

**Comment by PirateCodeWeb3** [comment]
> If we could set the change address for outputs just like the `--destination` option, it might be even better.
> 
> @casey

be supported now?
