### ISSUE TITLE
 Can /r/inscription/ please return the inscription's current address?

### ISSUE THREAD

**Issue by ZedZeroth** [ordinals/ord#3670]
Currently there are two bits of information provided on an inscription's /inscription page that are not included in the /r/inscription data:

1. Parents: Being discussed here: https://github.com/ordinals/ord/issues/3309
2. Address: This appears to have been removed from https://github.com/ordinals/ord/pull/2628 but the rationale for the decision is unclear.

There are some references to address reuse concerns but it looks as though some of the discussion may have taken place elsewhere? Unless I've overlooked something. Either way, my two main points on this would be:

1. I don't agree that address reuse should be a barrier to implementing this (assuming that's the reason it was removed). Firstly, we shouldn't be "nannying" what people do with their inscriptions. People are welcome to keep every inscription in a separate address for privacy reasons, but they are also welcome not to. Secondly, I think it's worth noting that (a) clearly the majority of people do not do this, (b) the ordinal-aware wallets are certainly not encouraging this, and (c) many people like showing off their inscriptions so I think privacy should **of course** be an option, but it should not be forced upon people.
2. The use-cases for this feature would be phenomenal. Inscriptions could know if they were in the "same place" as other inscriptions, and interact accordingly. To me, the use-case question is like a game developer asking "Why would it be useful for a game sprite / character / NPC to know it's XYZ location?". Imagine what we would be missing if the last 50 years of games and simulations could not determine where things are in 2D/3D space?

I foresee this addition becoming a cornerstone of future complex ordinal mechanics should it be implemented.

Tagging @devords @raphjaph @wagedu @Vanniix as people I have noticed in related discussions.

Thanks :)

**Comment by literalmonkey** [comment]
i strongly agree with this. I made a post almost a year ago asking for it for gallery and artistic reasons amongst others. 

And now with runes potentially being added as a recursive endpoint, simply having them in the same address to boost or change an inscription would be fantastic.

**Comment by ZedZeroth** [comment]
Thanks :) Do you have a link to your original post? Also, where's the best place to read about the upcoming runes endpoints so that I can get a feel for what might be possible? I'd love to integrate runes with my responsive ordinals :)

**Comment by ep150de** [comment]
I also commented on this re: to #2628 and I agree, this is limiting the potential for so many possibilities to expand the technical/art capability for ordinals.People should be free to choose if they wish to re use address and we shouldn't control that or limit ordinals if this is the only technical reason not to.
-------- Original message --------From: ZedZeroth ***@***.***> Date: 4/23/24  10:50 PM  (GMT+01:00) To: ordinals/ord ***@***.***> Cc: Subscribed ***@***.***> Subject: [ordinals/ord]  Can /r/inscription/ please return the inscription's
  current address? (Issue #3670) 
Currently there are two bits of information provided on an inscription's /inscription page that are not included in the /r/inscription data:

Parents: Being discussed here: #3309
Address: This appears to have been removed from #2628 but the rationale for the decision is unclear.

There are some references to address reuse concerns but it looks as though some of the discussion may have taken place elsewhere? Unless I've overlooked something. Either way, my two main points on this would be:

I don't agree that address reuse should be a barrier to implementing this (assuming that's the reason it was removed). Firstly, we shouldn't be "nannying" what people do with their inscriptions. People are welcome to keep every inscription in a separate address for privacy reasons, but they are also welcome not to. Secondly, I think it's worth noting that (a) clearly the majority of people do not do this, (b) the ordinal-aware wallets are certainly not encouraging this, and (c) many people like showing off their inscriptions so I think privacy should of course be an option, but it should not be forced upon people.
The use-cases for this feature would be phenomenal. Inscriptions could know if they were in the "same place" as other inscriptions, and interact accordingly. To me, the use-case question is like a game developer asking "Why would it be useful for a game sprite / character / NPC to know it's XYZ location?". Imagine what we would be missing if the last 50 years of games and simulations could not determine where things are in 2D/3D space?

I foresee this addition becoming a cornerstone of future complex ordinal mechanics should it be implemented.
Tagging @devords @raphjaph @wagedu @Vanniix as people I have noticed in related discussions.
Thanks :)

**Comment by ZedZeroth** [comment]
Thanks @ep150de :)

**Comment by ZedZeroth** [comment]
I found an earlier discussion here: https://github.com/ordinals/ord/issues/3015

@raphjaph says "All the fields look except for maybe the owner_address since we don't want to encourage address reuse and stuff like that."

@raphjaph, with regards to my comments above (https://github.com/ordinals/ord/issues/3670#issue-2259743641) are you able to go into more detail regarding what you see as the issue(s) with addresses being available via /r/inscription?

Thanks :)

**Comment by cryptoni9n** [comment]
If this is the same topic I'm thinking of, it has been addressed many times, including once by Casey in one of the coding clubs from a couple of months ago. Casey started the explanation by saying it was impossible to get the self-referential inscription ID in any other way than from the url. I might be able to dig up a clip, if necessary.

**Comment by ZedZeroth** [comment]
> it was impossible to get the self-referential inscription ID in any other way than from the url

This isn't strictly true. I have inscribed two collections that refer to themselves by embedding the sat number within the inscription data. This method could be further optimised by modifying ord such that the inscribe function has a "--self" flag which automatically appends <script>self="sat_number:reinscription_point"</script> onto the inscription data. The IID can then be pulled from /r/sat/sat_number/at/reinscription_point.

**Comment by raphjaph** [comment]
It does now :)
