### ISSUE TITLE
It does not index anymore after a certain block in testnet

### ISSUE THREAD

**Issue by Trisato** [ordinals/ord#3672]
I have been attempting to index sats and spent-sats on the Bitcoin testnet, but the indexing process stops at block 2604789, it show the current best height is 2634113. (Actually the best height is 2644994)
If I stop the ord server, the best height will be refreshed.

The command is : ./ord --bitcoin-data-dir /path/to/bitcoin/data --bitcoin-rpc-username xxxx --bitcoin-rpc-password xxxxx--chain testnet --index-runes --index-sats --index-spent-sats --commit-interval 500 --index-cache-size 32000000000 server --http-port 8081
It show like: [progress bar .................]     2604789/2645053Listening on http://0.0.0.0:8081
It will return right data when call api related indexed blocks like 2604788

If i just run index update like : ./ord --bitcoin-data-dir /path/to/bitcoin/data --bitcoin-rpc-username xxxx --bitcoin-rpc-password xxxxx--chain testnet --index-runes --index-sats --index-spent-sats --commit-interval 500 --index-cache-size 32000000000 index update
It will report: error: unrecoverable reorg detected

How can I resolve this issue to continue indexing new blocks? 
Any suggestions or guidance would be greatly appreciated!

**Comment by cryptoni9n** [comment]
Hi Tristin, many users are experiencing similar issues, and not just on testnet.  I ran into this today both with my sats and non-sats index on a machine with 32GB RAM.  Essentially, our machines are underpowered and when the index blocks hit runes on whatever chain, things get thick and the indexing will restart.  

There's a workaround and that is where you let the index go for about 100 blocks at a time, then ctrl-c once to gracefully shutdown and wait for those blocks to be committed to the index before your command prompt returns.  Then, repeat - run for 100, graceful shut down, wait - you should be able to slowly catch up this way.

**Comment by TristinHS** [comment]
Thank you so much!!!!!
 I will try it!  

> Hi Tristin, many users are experiencing similar issues, and not just on testnet. I ran into this today both with my sats and non-sats index on a machine with 32GB RAM. Essentially, our machines are underpowered and when the index blocks hit runes on whatever chain, things get thick and the indexing will restart.
> 
> There's a workaround and that is where you let the index go for about 100 blocks at a time, then ctrl-c once to gracefully shutdown and wait for those blocks to be committed to the index before your command prompt returns. Then, repeat - run for 100, graceful shut down, wait - you should be able to slowly catch up this way.

**Comment by cryptoni9n** [comment]
Good luck - let us know in the #tech-,support channel of the [Ordicord](https://discord.com/invite/ordinals) if you continue to experience any further issues.

**Comment by Trisato** [comment]
Update: 
If I rebuild the index and set the --commit-interval to 10, it will continuously index without any pauses.
