### ISSUE TITLE
Add /decode/<txid> and maybe /encode

### ISSUE THREAD

**Issue by simongltr** [ordinals/ord#3676]
Hi, 

I'm running a python monitoring tool for runes where I compute stats based on transactions in the block template and in the mempool.

Currently it works by running a subprocess calling the command `ord --data-dir /home/ubuntu/ord_data decode --txid {txid} | jq '.runestone.Runestone'` on transactions of the template/mempool.

It would be better to have access to a decode endpoint. 

Optionnally, I would like to access an encode endpoint to generate a mint runestone when needed. I currently have to run a rust server accessing the internal runestone encoding function, and I make API requests with my python monitoring tool.

It's not urgent because everything is working well with the workarounds I described, but it would definitely help simplifying my code and allow non rust devs to build cool tools.

Best,
Simon

**Comment by raphjaph** [comment]
Closed by #3733
