### ISSUE TITLE
Runes: Restricted Issuer

### ISSUE THREAD

**Issue by vforvilela** [ordinals/ord#3680]
To enhance the Rune protocol for issuing tokens reliant on a central entity, such as bonds, stocks, and asset-backed instruments, I suggest adding an "issuer" field to the existing `Terms` structure. 
```rust
struct Terms {
    ...
    issuer: Option<BitcoinAddress>, // Bitcoin address of the designated issuer
}
```

The minting input would be restricted to transactions originating from the specified Bitcoin address, ensuring that only authorized transactions from the designated issuer can mint new tokens.

**Comment by cryptoni9n** [comment]
pretty sure this is a clone of #3677

**Comment by HubertusVIE** [comment]
> I suggest adding an "issuer" field to the existing `Terms` structure.
>     issuer: Option<BitcoinAddress>, // Bitcoin address of the designated issuer
Agree with @cryptoni9n - it appears to be a clone. The difference is governance flag vs. issuer field. A field seems redundant as the deployer can be the governance holder. PS: In the future, there could be a governance transfer to another address with an edict but again a special field would be redundant.

**Comment by casey** [comment]
Continuing discussion in #3677. See comments there about using a fixed address.
