### ISSUE TITLE
索引BTC全节点时报错

### ISSUE THREAD

**Issue by loneboygan** [ordinals/ord#3684]
C:\Users\10536>ord --cookie-file "I:\Bitcoin\blocks\.cookie" --data-dir "I:\ord_data" --index-runes index update
[indexing blocks] ████████████████████████████████████████████████████████████████████████████████████████████░ 840357/840762thread 'main' panicked at src\index\lot.rs:78:9:
attempt to divide by zero
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by cryptoni9n** [comment]
Hi, this was an issue that has been resolved in the latest version. Please consider upgrading to v0.18.3 and retrying. 

In the future, I'd encourage you to post issues like this on the [Ordicord](https://discord.com/invite/ordinals) - we have foreign language channels for non-English speakers. 

Good luck!

**Comment by loneboygan** [comment]
谢谢你，我再试一下
