### ISSUE TITLE
0.18.3 get error: output in wallet but not in ord server

### ISSUE THREAD

**Issue by Sylor-huang** [ordinals/ord#3689]
- [x] ord version: 0.18.3
- [x] config setting:

```js
bitcoin_data_dir: /Volumes/Bitcoin/Bitcoin/
bitcoin_rpc_password: xxxx
bitcoin_rpc_url: http://127.0.0.1:8332
bitcoin_rpc_username: xxx
chain: mainnet
data_dir: /Volumes/Bitcoin/ORD/
index: /Volumes/Bitcoin/ORD/index.redb
index_cache_size: 1000000000
index_runes: true
# no_index_inscriptions: true  // true or false also get this error
first_inscription_height: 2580000
```

- [x] ord settings

```js
{
  "bitcoin_data_dir": "/Users/mac/Library/Application Support/Bitcoin",
  "bitcoin_rpc_password": null,
  "bitcoin_rpc_url": "127.0.0.1:8332",
  "bitcoin_rpc_username": null,
  "chain": "mainnet",
  "commit_interval": 5000,
  "config": null,
  "config_dir": null,
  "cookie_file": "/Users/mac/Library/Application Support/Bitcoin/.cookie",
  "data_dir": "/Users/mac/Library/Application Support/ord",
  "first_inscription_height": 767430,
  "height_limit": null,
  "hidden": [],
  "index": "/Users/mac/Library/Application Support/ord/index.redb",
  "index_cache_size": 4294967296,
  "index_runes": false,
  "index_sats": false,
  "index_spent_sats": false,
  "index_transactions": false,
  "integration_test": false,
  "no_index_inscriptions": false,
  "server_password": null,
  "server_url": null,
  "server_username": null
}
```

- [x] ord status (  http://127.0.0.1/status)

<details>

<summary>click to see
</summary>

```js
Status
chain
mainnet
height
[840827](http://127.0.0.1/block/840827)
inscriptions
[70764753](http://127.0.0.1/inscriptions)
blessed inscriptions
70292710
cursed inscriptions
472043
runes
[11090](http://127.0.0.1/runes)
lost sats
0
started
2024-04-25 14:55:00.609373 UTC
uptime
3s 777ms 995us
initial sync time
0s
minimum rune for next block
YTZKKGJYRCBZ
version
0.18.3
unrecoverably reorged
false
rune index
true
sat index
false
transaction index
false
git branch
master
git commit
[c22a78141e4799836321a69f21f16be289da3303](https://github.com/ordinals/ord/commit/c22a78141e4799836321a69f21f16be289da3303)
inscription content types
text/plain;charset=utf-8
36017398
text/plain
27695483
image/png
1627875
text/html;charset=utf-8
1453473

....
```

</details>

- [ ] Last week with `0.18.2`, it works fine, but today, when I retry, then get this error. 
- [ ] And I had updated to `0.18.3`, it also display this error.  Please help thanks.

```
 ./ord --config config wallet balance

> error: output in wallet but not in ord server: 1d412d10xxxx
```

**Comment by cryptoni9n** [comment]
Hi Sylor,

We've been seeing this issue occur for a few users recently.  It seems that most who experience it have indexed with the setting `no_index_inscriptions: true`, or something has prevented their index from including inscriptions.  For you, it could have been that or your first inscription height being set incorrectly.  Note also that your yaml and config are conflicting on a few things. 

In most cases, this issue points at a problem with the index and I would strongly recommend starting a new index with the --config flag pointing at a known good config excludes the `first_inscription_flag` and has `no_index_inscriptions` set to false.

Please give these suggestions a try and reach out to us on the [Ordicord ](https://discord.com/invite/ordinals) if you need more assistance troubleshooting in the future.

**Comment by Sylor-huang** [comment]
OK, I will try, thanks.

**Comment by himanshu64** [comment]
0.18.5 still same error for me , anyone know how to fix this issue @casey @Sylor-huang

**Comment by cryptoni9n** [comment]
> 0.18.5 still same error for me , anyone know how to fix this issue @casey @Sylor-huang

Hi himanshu64,

There are a few troubleshooting steps in this thread that should help, [here](https://github.com/ordinals/ord/issues/3689#issuecomment-2078380112).  If this isn't working for you, I strongly suggest you visit the [Ordicord ](https://discord.com/invite/ordinals) so we can help you troubleshoot there.

Thanks!
