### ISSUE TITLE
thread '<unnamed>' panicked at src/index/lot.rs:78:9:

### ISSUE THREAD

**Issue by zhanghanke** [ordinals/ord#3696]
thread '<unnamed>' panicked at src/index/lot.rs:78:9:
attempt to divide by zero
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Is there a solution?

**Comment by zhanghanke** [comment]
impl Div<u128> for Lot {
  type Output = Self;
  fn div(self, other: u128) -> Self::Output {
    Lot(self.0 / other)
  }
}

Has anyone encountered it? What are the solutions @casey

**Comment by zhanghanke** [comment]
Can I add a non zero check and recompile it？

**Comment by casey** [comment]
Can you run with `export RUST_BACKTRACE=1` and post the stack trace? Which version are you running? Do you know if this is being triggered by a particular block?

**Comment by zhanghanke** [comment]
Yes, I have already done so, but it will take time

**Comment by zhanghanke** [comment]
> Can you run with `export RUST_BACKTRACE=1` and post the stack trace? Which version are you running? Do you know if this is being triggered by a particular block?

version: 1. 0.18.3,I have seen both index. redb=69GB and index. redb=83GB. After the first appearance, I restarted and ran for 7 hours before still appearing

**Comment by casey** [comment]
And this is on mainnet?

**Comment by zhanghanke** [comment]
> And this is on mainnet?

yes

**Comment by emilcondrea** [comment]
This probably isn't 0.18.3, we had that issue with older versions 0.18.0 but its fixed. Ensure you rebuild and consume latest updates.

**Comment by zhanghanke** [comment]
> This probably isn't 0.18.3, we had that issue with older versions eg. 0.18.0 but its fixed on latest version. Ensure you rebuild and consume latest updates.

ord -V
ord 0.18.3.   I confirm the version of ord

**Comment by zhanghanke** [comment]
> > This probably isn't 0.18.3, we had that issue with older versions eg. 0.18.0 but its fixed on latest version. Ensure you rebuild and consume latest updates.
> 
> ord -V ord 0.18.3. I confirm the version of ord

Sorry, you're right. There are two orders stored on my machine

**Comment by casey** [comment]
Okay, nice, glad to get to the bottom of this!
