### ISSUE TITLE
Have some way to return content on the envelop if there is a delegate.

### ISSUE THREAD

**Issue by elocremarc** [ordinals/ord#3700]
It would be nice if there was some way to return the content inside the envelope of a delegate inscription. This would be useful for generative inscriptions. 

For example a 3D scene that uses a GLB file inside the content and the scene is rendered by the delegate inscription. We can get unique data in `/r/metadata` however we can't create unique files for a delegate.

**Comment by elocremarc** [comment]
@raphjaph @casey any thoughts on this?  I keep coming up with all these ideas that need the inscribed content of a delegate. Another example is having a GLSL shader as the content and then the delegate will handle the rendering of the shader code. With GLSL the content are strings so you would need a delegate inscription in order to render them.

**Comment by elocremarc** [comment]
Found a third reason. I am working on an onchain music engine. People would delegate the music engine then inscribe the mod files into the content then the music engine would generate the sound. 
https://en.wikipedia.org/wiki/MOD_(file_format)

**Comment by casey** [comment]
I think this is a good feature. We'd need a new endpoint, like `/r/content-no-delegate` or `/r/delegee`.

**Comment by elocremarc** [comment]
@casey 
To clarify would that be 
`/r/content-no-delegate` returns the content that is in the envelope which we can't access now?
`/r/delegee` returns the content of the delegate like `/content/` does currently?

Wouldn't we only need the first one?

We also need  to make a new cache for those new routes.

I was brainstorming a solution to still use the current  cached`/content/` by using some key that we parse off as a query param.
Example:
Key `raw:`
`/content/<raw:><id>`
`/content/raw:6fb97....799i0`

Then around where we proxy the delegate if it has that key in the URL string for the route param we parse it off and then return the envelope inside the inscription Tx. 

Would this break the `/r/` recursion convention?

**Comment by casey** [comment]
Whoops, sorry, I meant `/r/delegator`, it could also be `/r/delegator-content`

**Comment by elocremarc** [comment]
How about
`/r/delgatee-content/`
or maybe just
`/r/delegatee`
