### ISSUE TITLE
`ord list <UTXO>` won't list inscriptions and runes

### ISSUE THREAD

**Issue by shadowysathunter** [ordinals/ord#3701]
The command `ord list <utxo>` lists all sats that belong to that UTXO, but it (or any other command) won't list the inscriptions and runes.

**Comment by cryptoni9n** [comment]
Hi shadowy,

You're correct, `ord list <OUTPUT>` lists all sats in a utxo - that is all it purports to do:

>Usage: ord list <OUTPOINT>
>
>Arguments:
> <OUTPOINT>  List sats in `<OUTPOINT>`.

If you want to list the inscriptions, you can use `ord wallet output` and if you want to list the runes, you can use `ord wallet balance`.

I hope this helps.

**Comment by shadowysathunter** [comment]
> If you want to list the inscriptions, you can use `ord wallet output` and if you want to list the runes, you can use `ord wallet balance`.
> 
> I hope this helps.

I need to list runes/inscriptions for any arbitrary UTXO, that do not necessary belongs to me, juts like I can do with rare sats and the `ord list`command.

**Comment by cryptoni9n** [comment]
> > If you want to list the inscriptions, you can use `ord wallet output` and if you want to list the runes, you can use `ord wallet balance`.
> > I hope this helps.
> 
> I need to list runes/inscriptions for any arbitrary UTXO, that do not necessary belongs to me, juts like I can do with rare sats and the `ord list`command.

I see - @raphjaph I've tagged this as an enhancement request for your review

**Comment by raphjaph** [comment]
This makes sense, it should return more info. I think this command hasn't been updated since we first implemented sat tracking so it should be updated to reflect all kinds of assets that can be held in a utxo. It's probably quite an easy change if @shadowysathunter wants to take a stab at it.
