### ISSUE TITLE
Custom inscription handler

### ISSUE THREAD

**Issue by GopherJ** [ordinals/ord#3708]
People may submit new kinds of inscriptions to bitcoin, it'll be good to allow custom defined inscription module, I can image these modules to include the following parts:

- Namespace -> to allow easily access from other module
- Parser -> define how should the new inscription be parsed
- Storage -> define new redb tables
- Execution -> read/write tables
- Context -> access data defined by other modules via namespace
- Module as a crate, people should import and enable explicitely via `.add_module(ModuleName::new())`

Why I'm asking this is because we have brc-21 and l2o-a standards at https://l2o.io, currently I'm forking okx ord to achieve this, but ordinals/ord is the open source and best maintained one, in long term I'd expect to only import ordinals/ord and add my own logic, maybe okx can also deprecate their okx/ord fork with the new modular design

**Comment by GopherJ** [comment]
This helps also cleanup the code, currently ord has many mixed logic and it can be error prone

**Comment by casey** [comment]
I think that this would come at a cost of increased complexity, i.e., increased indirection and more code in support of modularity, which doesn't seem like it would be worth it. The focus of `ord` should be on supporting the existing protocol, not on arbitrary extensions.
