### ISSUE TITLE
0.18.3 

### ISSUE THREAD

**Issue by thewrlck** [ordinals/ord#3718]
`ord --index-runes --bitcoin-rpc-username NAME --bitcoin-rpc-password PASS  server --http-port 8080`

It did not synced runes 😮‍💨 

What's wrong? I need to resync entire ord?

**Comment by so7ow** [comment]
3 identical posts on The Ordicord, plus this one.

**Comment by cryptoni9n** [comment]
> `ord --index-runes --bitcoin-rpc-username NAME --bitcoin-rpc-password PASS server --http-port 8080`
> 
> It did not synced runes 😮‍💨
> 
> What's wrong? I need to resync entire ord?

this was already answered in the Ordicord by Greg
