### ISSUE TITLE
How to check Rune amount

### ISSUE THREAD

**Issue by Sotatek-MinhNguyen11** [ordinals/ord#3725]
I have an utxo include Rune, so how to check or decode that many Runes does it contain?

**Comment by cryptoni9n** [comment]
Hi Sotatek-MinhNguyen11,

When using the ord wallet, you can run the command `ord wallet balance` while the `ord server` is running in the background to see your Bitcoin and Rune balances.  [The Ordicord](https://discord.com/invite/ordinals) is the official Discord server for the open-source ord project - we have a team of mods and tech help that can quickly help you answer questions like these in the future.  Please be sure to seek help there first in the future.
