### ISSUE TITLE
Search broken

### ISSUE THREAD

**Issue by elocremarc** [ordinals/ord#3730]
Search only seems to work now on a route basis. If you search an inscriptionId on the /output page then it will error for instance. I think this might have changed when we added top level search?

**Comment by raphjaph** [comment]
I don't know what you mean. If I put an inscription id into the search bar while looking at an output it works for me. Could you give more details?

**Comment by elocremarc** [comment]
@raphjaph Hmm can't replicate it now It was having issues for me yesterday I wrote the issue while away form my computer when I remembered it. I will close the issue and reopen if I can replicate it again. 
> I think I was running my own server instance on V 0.18.2
