### ISSUE TITLE
assertion `left == right` failed

### ISSUE THREAD

**Issue by robanb** [ordinals/ord#3736]
Encountered the following issue while running the ord server: 
thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/redb-2.1.0/src/tree_store/page_store/region.rs:321:9:
assertion `left == right` failed
  left: 1
 right: 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
I am seeking possible solutions

**Comment by cryptoni9n** [comment]
Hi Robo - I've been following the conversation you've had today in the #tech-support channel with the Ordicord mods ETS and K4Bong.  I believe that your issue has been resolved.

In the future, please stick to the [Ordicord](https://discord.com/invite/ordinals) for help requests like this.  The Github is more suitable for bug reporting or making enhancement requests.
