### ISSUE TITLE
Update docs to show new JSON API endpoints

### ISSUE THREAD

**Issue by raphjaph** [ordinals/ord#3742]
Steps:

1. Enumerate all endpoints that return JSON (basically update this list here: https://docs.ordinals.com/guides/explorer.html#json-api)
2. Add short description 
3. Add an example `curl` command with JSON response.

We should make a new section under Guides and call it API and pull out the JSON API stuff from the Explorer section.

**Comment by cryptoni9n** [comment]
in progress
