### ISSUE TITLE
Update to latest Ord release.

### ISSUE THREAD

**Issue by 0AAK0** [ordinals/ord#3743]
Hi guys, 
good day,

I see there's a new release for Ord "0.18.5", I'm running a node on Ubuntu and would like to update my Ord but:
1- Do I use below code and just change checkout version?     
```
git clone https://github.com/ordinals/ord.git
cd ord
git checkout 0.18.5
cargo build --release
sudo cp target/release/ord /usr/local/bin
ord --version
```
2- Re-indexing will be required after updating? I use pre-built index (downloaded from ordstuff.info)
3- Will be able to use same Ord wallet after the update?

**This is my current setup:**

- I've my Ord library copied inside "bin" (based on the above mentioned command)

![image](https://github.com/ordinals/ord/assets/3874112/ecff9ae5-cad0-411f-a381-307453089399)
![image](https://github.com/ordinals/ord/assets/3874112/ce6a2b40-2da7-45c8-aa58-70021c75f8c7)

- Also have my "pre-built" index and wallet folder inside "runes" folder under "Home/ord/runes" 

![image](https://github.com/ordinals/ord/assets/3874112/e427b6bf-113f-4e50-8a2c-94bd1860650e)
![image](https://github.com/ordinals/ord/assets/3874112/ca8c71e0-17d2-4a94-b92b-cdb907c26aee)
![image](https://github.com/ordinals/ord/assets/3874112/f99b7d93-c19c-4946-ace4-9f3cd784ddc3)

Do I need to take the "runes" folder out to perform the update then return it or everything will be the same?

Moreover, at the beginning someone suggested below command to install "Ord" library: (which i used & worked fine)

![image](https://github.com/ordinals/ord/assets/3874112/eaa182b7-269a-4966-b71d-3c2a852cb428)

But someone else replied with this:

![image](https://github.com/ordinals/ord/assets/3874112/f29940a3-2cf5-4a7e-948a-5cb04df82028)

So i'm not sure which is correct and how to use the "simple link" method (for future installations).

Thank you.

**Comment by cryptoni9n** [comment]
Hi 0AAK0,

I've been following your conversation with Greg on the Ordicord and know that a few of these questions have been answered already.  We like to try and keep all of the troubleshooting and general questions on the Ordicord, while the Github is mostly for bug reports and/or enhancement requests.
