### ISSUE TITLE
Why is ordinals' testnet explorer inaccessible?

### ISSUE THREAD

**Issue by junpengdong** [ordinals/ord#3747]

**Comment by junpengdong** [comment]
https://testnet.ordinals.com/

**Comment by cryptoni9n** [comment]
Hi junpengdong - as you may be aware, testnet has been undergoing a lot of issues recently.  There's a good blog writeup about it here: https://blog.lopp.net/griefing-bitcoin-testnet/  These issues have carried through to ord when indexing testnet, causing problems for everyone.  It seems that those issues have subsided for the time being, so I'd expect it won't be too much longer until testnet.ordinals.com is backup and running.

in the meantime, @gmart7t2 has his testnet explorers up and running: https://without18testnet.ordstuff.info/ (without sats) or https://with18testnet.ordstuff.info/ (with sats)

**Comment by cryptoni9n** [comment]
> I just restarted it, should be at the chain tip in a couple hours

Hi Raph, an Ordicord user informed me this morning that [testnet](https://testnet.ordinals.com/status) appears to be out of sync at height https://testnet.ordinals.com/block/2809999

[mempool ](https://mempool.space/testnet)shows 2817440 as the current block

**Comment by raphjaph** [comment]
I've restarted the server, let's see if it catches up

**Comment by cryptoni9n** [comment]
> I've restarted the server, let's see if it catches up

looks to be stuck in the same spot now.

**Comment by raphjaph** [comment]
Yeah I'll have to investigate

**Comment by 0xAlmir** [comment]
@gmart7t2 any ETA when the ordinal testnet will be back up on your site https://without18testnet.ordstuff.info ?

**Comment by ordiwriter** [comment]
testnet explorer is down again
