### ISSUE TITLE
plan to integrate testnet4

### ISSUE THREAD

**Issue by ordinariusprof** [ordinals/ord#3750]
since testnet3 is unusable, is there a plan to utilize testnet4 as discussed here: https://github.com/bitcoin/bitcoin/pull/29775 ?

**Comment by cryptoni9n** [comment]
as an aside to this, I saw today that the latest version of Sparrow (v1.9.1) has integrated testnet4 https://x.com/SparrowWallet/status/1790312602918126026

**Comment by raphjaph** [comment]
We'll definitely run it as soon as it is in a release version of Bitcoin Core

**Comment by Vardominator** [comment]
@raphjaph Do you have plans for releasing support for testnet4? Bitcoin Core 28.0 was released recently.

**Comment by raphjaph** [comment]
As soon as I merge https://github.com/ordinals/ord/pull/3962 `ord` will be compatible with v28

**Comment by cryptoquick** [comment]
@raphjaph I just tried running ord on testnet4 but bitcoind uses port 48332 by default. Setting that to 18332 results in this error:

```
Oct 23 01:43:12 testnet4-deployment sh[30535]: error: Failed to connect to Bitcoin Core RPC at `127.0.0.1:18332/`:  JSON error: invalid value: string "testnet4", expected bitcoin network encoded as a string
```

Might be an issue you'll need to reopen this for.

**Comment by raphjaph** [comment]
You'll have to change some parsing logic in the code, we look for `testnet3` in places instead of `testnet4`. We're not going to officially support testnet4 until next year because we only want to support one testnet

**Comment by donnlee** [comment]
testnet3 transactions fee are >4000 sats/vB, making it unusable because there are no faucets that give enough sats.
I've moved to testnet4, but now I need `ord` or unisat.io or ordinals.com to support testnet4.
I tried search-n-replace of `testnet3` to `testnet4` but the error persists.

Does anyone have a fork of `ord` that supports testnet4 today?

**Comment by raphjaph** [comment]
you could also try signet. If you drop be a signet address I'll send you some sats

**Comment by donnlee** [comment]
Oh awesome. Thank you!
And it seems ordinals.com supports signet, https://signet.ordinals.com

**Comment by raphjaph** [comment]
#4135
