### ISSUE TITLE
Ordinals smart contract proposal

### ISSUE THREAD

**Issue by vendersen** [ordinals/ord#3755]
**Add 3 mimetypes**

1. deploy (This opcode is the deployment contract opcode)
2. send (This opcode changes the contract status)
3. call (This operation code is to read the contract status)

When the opcode is send or call
`{
    kid: 'kind Id',
    method: 'method name',
    params: [...params],
}`

**it looks like this**

`const script = [
    'Your Pubkey',
    'OP_CHECKSIG', 
    'OP_0', 
    'OP_IF', 
    ec.encode('ord'), 
    '01', 
    ec.encode('send' || 'deploy'), 
    'OP_0', 
    ec.encode(source code || data),
    'OP_ENDIF'
]`

When people put the operation code on the chain through Segregated Witness, the indexer deploys the contract or loads the contract to perform the corresponding operation.

We can fully realize the same functions as the Ethereum smart contract in this form. If there is a contract that manages tokens belonging to the user on the chain, this will greatly reduce gas expenses and the number of transactions, and can complete n transactions in one transaction. Token transfer can also realize GameFi, Dex and other scenarios

We can also use musig2 to submit immutable transactions on behalf of users through nodes, multi-signature groups to increase user interaction speed. At the same time, we can also extract gas fees to complete the node incentive mechanism.

Regarding the issue of data trust, we can use ChainLink's off-chain reporting scheme to provide weighted aggregated data responses to users to increase data credibility.

**Comment by casey** [comment]
I think this is just out-of-scope due to complexity, as well as potentially introducing MEV on Bitcoin, if it has an ethereum-like execution environment. If people want to use runes with smart contracts, I think they'll need to bridge them to L2s.
