### ISSUE TITLE
Mint Rune custom --postage

### ISSUE THREAD

**Issue by TheRealFuture42** [ordinals/ord#3763]
Hey,

is it right that the postage is to safe future tx of the inscription and can someone explain why the --postage is [default: 10000sat]? 

I see some TX with postage of 330Sats for Rune Mints. What if i set the postage to 0?

Example:
```
ord --cookie-file /.cookie --data-dir /... wallet mint --fee-rate 12 --rune UNCOMMON.GOODS --destination <XYZ> --postage 330sats
```

**Comment by cryptoni9n** [comment]
Hi TheRealFuture42 - the postage is to set the size of the utxo.  The default is 10,000 sats and that is to make sure the utxo is big enough to be sent around and have the fees taken from itself without having to provide another utxo.  The postage is subject to the dust limit and so it can not be set beneath it.

In the future, please present questions like these in [the Ordicord](https://discord.com/invite/ordinals).  We have a #tech-support channel with lots of mods and trusted tech helpers who answer questions like this all the time.  You will usually receive a much quicker response then when posting to the Github.
