### ISSUE TITLE
One of the ordinals.com instances is out of sync

### ISSUE THREAD

**Issue by gmart7t2** [ordinals/ord#3767]
Occasionally I get old results from ordinals.com.

After hitting the /status page a few times I saw this: 

![Screenshot_20240518_131733_Presearch](https://github.com/ordinals/ord/assets/49558347/8a60cfa6-0a94-45dd-b80b-709a756d7f53)

I don't know if it got stuck somehow or if it is just catching up, but either way it shouldn't be used by the load balancer until it finishes syncing.

**Comment by cryptoni9n** [comment]
this may be why I saw varying blockhashes the past few days.  @raphjaph is this a known issue?

**Comment by casey** [comment]
Our test server was accidentally behind the load balancer when it shouldn't be. I removed it, so this should be resolved.
