### ISSUE TITLE
Block should returns tx ids

### ISSUE THREAD

**Issue by thewrlck** [ordinals/ord#3770]
The html returns the txs when you point to /block/840000 but not the json api.

Should be very cool that also the api returns the txs ids, in this way you have two options for syncing on top of ordinals.

1 - use events emitted by rust mounting rust on rust
2 - use whatever language you want to query block x block / tx x tx.

Can you add Vec Transaction also to the response of the json at /block endpoint?

I know that you can do directly using bitcoind but should be useful to have it on that endpoint

@raphjaph

**Comment by raphjaph** [comment]
Yeah we could add this. Shouldn't be too hard if you want to take a stab at it ;)

**Comment by thewrlck** [comment]
Yes I would like to try! Let me make a pr :)

**Comment by raphjaph** [comment]
Closed by #3805
