### ISSUE TITLE
ord decode fails with raw hex

### ISSUE THREAD

**Issue by encloinc** [ordinals/ord#3772]
ord decode <<< "020000000001019cc18818b2d45c130554594705f192d40dbc1cfb9706f0eeb4ae7ee0a21f68e70000000000fdffffff0322020000000000002251205cd1864bddd803a9fd80c4f163bf2d97fa22cba877557c000c7b480c2390889c0000000000000000226a5d1f020304ba9cb190f0bebde5b32c03a8040588ec0706d0e80c0ae80708b6a2019910000000000000160014862e9c37baad895d8cef4df215ca8fe9b36b93b8034076ccf5fabb6dcf97b6cb22e35160313d2a76e6bd76f750c5d90fc84affe6c594fab8569f87cdb9a90640ce43cc1454487823d5091dd3111282f01b22929ce1842f20a9d14a472f5d3786e435dc19c9e941045614540bde207d08e65accde14a0ea31ac0063093a4e0c02f7f5ca33166821c1a9d14a472f5d3786e435dc19c9e941045614540bde207d08e65accde14a0ea3100000000"
 
error: IO error
because: failed to fill whole buffer

This is the raw hex transaction from: 8f05dea1a02e680bd6ded75bbcbb017505404235697e4cfc465ac4f3cea640cc

**Comment by cryptoni9n** [comment]
I've never used this command before, so I'm not sure I'm running it correctly - but I think I was able to reproduce this by first running `bitcoin-cli -datadir=F:\Bitcoin getrawtransaction 6eb37452215ad7136ca6f02898b207db0b0aeced320f98f22b442038d00494ec false > decode_test.txt` 

and then running `ord --data-dir F:\Bitcoin --cookie-file F:\Bitcoin\.cookie decode --file "C:\ord\decode_test.txt"`

I get this error in 0.18.5:

```
error: IO error
because: failed to fill whole buffer
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: BaseThreadInitThunk
  13: RtlUserThreadStart
```

@raphjaph are we running this command correctly?

**Comment by raphjaph** [comment]
```
echo "020000000001019cc18818b2d45c130554594705f192d40dbc1cfb9706f0eeb4ae7ee0a21f68e70000000000fdffffff0322020000000000002251205cd1864bddd803a9fd80c4f163bf2d97fa22cba877557c000c7b480c2390889c0000000000000000226a5d1f020304ba9cb190f0bebde5b32c03a8040588ec0706d0e80c0ae80708b6a2019910000000000000160014862e9c37baad895d8cef4df215ca8fe9b36b93b8034076ccf5fabb6dcf97b6cb22e35160313d2a76e6bd76f750c5d90fc84affe6c594fab8569f87cdb9a90640ce43cc1454487823d5091dd3111282f01b22929ce1842f20a9d14a472f5d3786e435dc19c9e941045614540bde207d08e65accde14a0ea31ac0063093a4e0c02f7f5ca33166821c1a9d14a472f5d3786e435dc19c9e941045614540bde207d08e65accde14a0ea3100000000" | xxd -r -p | ord decode
```

At the moment we only accept binary transaction data not hex. But would make sense to allow hex as well. Would be glad to review a PR if any of you want to do that
