### ISSUE TITLE
Wont compile on windows (x64)

### ISSUE THREAD

**Issue by encloinc** [ordinals/ord#3782]
Tried compiling the source on windows and it fails on a crate, I’ll leave the error logs here below

What rustup toolkit / gcc target architecture should I use to build this? Thanks

==== error below =====

The following warnings were emitted during compilation:

warning: ring@0.17.8: crypto/curve25519/curve25519.c:1:0: sorry, unimplemented: 64-bit mode not compiled in
warning: ring@0.17.8:  /* Copyright (c) 2020, Google Inc.

**Comment by raphjaph** [comment]
I don't have a Windows to test this but our CI compiles on `x86_64-pc-windows-msvc`. Which exact command did you run to compile?

**Comment by elocremarc** [comment]
@encloinc I just built on windows from commit [abd7f6cc00ada499fc3b7ee2e80423bfafea5c3e](https://github.com/ordinals/ord/commit/abd7f6cc00ada499fc3b7ee2e80423bfafea5c3e)

I just installed rust from here and it worked fine.
https://www.rust-lang.org/tools/install
