### ISSUE TITLE
Unable to set server http port in config file?

### ISSUE THREAD

**Issue by so7ow** [ordinals/ord#3795]
Am I missing a way to set the server http port in the config yaml file? (Equivalent to the `--http-port` flag that can be passed to `ord server`?)

I tried adding an `http_port` entry (that I just made up!) to the yaml file, just as a shot in the dark, but that's clearly not a valid entry:

```
 $ ord --config signet.yaml server
error: failed to deserialize config file `signet.yaml`
because: unknown field `http_port`, expected one of `bitcoin_data_dir`, `bitcoin_rpc_limit`,
`bitcoin_rpc_password`, `bitcoin_rpc_url`, `bitcoin_rpc_username`, `chain`,
`commit_interval`, `config`, `config_dir`, `cookie_file`, `data_dir`, `first_inscription_height`,
`height_limit`, `hidden`, `index`, `index_cache_size`, `index_runes`, `index_sats`,
`index_spent_sats`, `index_transactions`, `integration_test`, `no_index_inscriptions`,
`server_password`, `server_url`, `server_username`
```
```
 $ cat /home/so7ow/.local/share/ord/signet.yaml       
http_port: 81
index_runes: true
chain: signet
```
```
 $ ord --version
ord 0.18.5
```
```
 $ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
```

If there is no way to do it currently, could we get that added?

**Comment by raphjaph** [comment]
#3796

If you want to add some other `server` setting to the yaml file you can take that PR as a template to add the others as well :)

**Comment by so7ow** [comment]
I'd love to but I'm GitHub and Rust illiterate. You don't want me breaking your app.
