### ISSUE TITLE
Does an ordinal child inscription tx have to spend parent inscription tx?

### ISSUE THREAD

**Issue by xhliu** [ordinals/ord#3802]
It says in the [provenance spec](https://docs.ordinals.com/inscriptions/provenance.html#specification): child inscription tx T has to spend the parent P in one of the inputs of T.

But looking at some example, the child does NOT spend parent, but only reference it, e.g.:
child: b4be862a8ef7062f96c679731ff2c505d13dc80b7f04fdfbcd4d8e5534349d99i130
parent: 9a8db4559b2dfdfd2e06dd6d139f5de597f6e257423bc7b21debc85a27782954i0

Am I missing sth?

**Comment by xhliu** [comment]
Tx A **spends** Tx B, if an input of A's txid equals to txid of B, which is not the case in the [example](https://blockstream.info/tx/b4be862a8ef7062f96c679731ff2c505d13dc80b7f04fdfbcd4d8e5534349d99?expand=) and thus confusing. 
![image](https://github.com/ordinals/ord/assets/1017252/3b499489-38f5-4400-99af-72a69608f3fa)

But I can see the first input spends the UTXO that contains the parent inscription using [this API](https://docs.hiro.so/ordinals/inscription-transfers).

So does it mean child inscription tx T has to spend **the current UTXO that**, not necessarily P's inscription tx, contains parent P in one of the inputs of T, since P may have been transferred after being inscribed?

**Comment by cryptoni9n** [comment]
> So does it mean child inscription tx T has to spend **the current UTXO that**, not necessarily P's inscription tx, contains parent P in one of the inputs of T, since P may have been transferred after being inscribed?

Yes.

> If so, a child must be inscribed by the **current owner** of a parent inscription, who may NOT be one that inscribed it. If the parent is transferred afterwards, it may be owned by a different person from child's owner.

Yes.  Inscribing a child for an inscription doesn't necessarily mean that you were the inscriber of the parent, just that you held the parent at the time of child creation and created on-chain provenance for it.

Does this better explain?

**Comment by xhliu** [comment]
Yes.

Can this be a problem in identifying inscriptions in a collection?

Say an artist Alice inscribed P. She inscribed a child C with P as parent. C and P now belong a collection. Later P is transferred to Bob. Bob can now inscribe another child C' of P, which will be mistakenly regarded to be in the collection.

Does this mean Alice always has to transfer P to herself when inscribing any child/descendant?

**Comment by cryptoni9n** [comment]
> Yes.
> 
> Can this be a problem in identifying inscriptions in a collection?

Not really, I explain below.
 
> Say an artist Alice inscribed P. She inscribed a child C with P as parent. C and P now belong a collection. Later P is transferred to Bob. Bob can now inscribe another child C' of P, which will be mistakenly regarded to be in the collection.

Sort of, not really.  Most collections that use provenance have one main parent inscription that is permanently held by the collection creator, with all children inscribed under that one parent.  The collection is identified by the direct descendants of the main parent P.  If parent P has 100 children that are sold and someone inscribes a child of the child (grandchild), then that is fine but doesn't prove that the original parent was held by the grandchild inscriber - and therefore is not really part of the collection.  It proves that the grandchild inscriber held a child C from parent P which are part of collection X.  This process essentially turns child C into a new parent P2 for a second collection.

> Does this mean Alice always has to transfer P to herself when inscribing any child/descendant?

Yes, anytime Alice wants to make a child C of parent P, she herself will need to have parent P and include it in the child inscribe command.  

I hope I've answered all of your questions.  Let me know if anything is still unclear.

**Comment by xhliu** [comment]
What if I have more inscriptions than what can fit into a single transaction, say 100k? How do I use child-parent to mark them in a single collection?

**Comment by cryptoni9n** [comment]
> What if I have more inscriptions than what can fit into a single transaction, say 100k? How do I use child-parent to mark them in a single collection?

I'm not exactly sure I understand your question.  Do you mean that you want 100K parents for a child?  Or are you saying that you want to create 100K children for a parent?

For the former - multi-parent is a new thing and I'm not sure of the limits just yet.  While I know ord the protocol supports multi-parent, I don't think there is a way yet to inscribe multi-parent in the software.

For the latter - it doesn't matter how many can fit into a single tx.  The children in the collection do not all have to be inscribed in one single tx.  You could do them all separately, if you wanted to.  The parent inscription just has to be in each tx.

Anything else still unclear?
