### ISSUE TITLE
ordinals.com blocking requests (cloudflare)

### ISSUE THREAD

**Issue by emilcondrea** [ordinals/ord#3827]
It seems that Cloudflare blocks requests when trying to access ordinals.com. It also happens to other people I talked to. Is this a known issue?

<img width="1057" alt="Screenshot 2024-06-21 at 07 38 18" src="https://github.com/ordinals/ord/assets/3403905/c8a925b4-f54f-4b6e-ba04-e4d0be1466ee">

**Comment by DriveOneFirst** [comment]
I encountered the same issue...

**Comment by casey** [comment]
I misconfigured a firewall rule and accidentally blackholed all traffic 😅 Should be fixed!
