### ISSUE TITLE
Ord don't fetch data when restart from connect rpc issue

### ISSUE THREAD

**Issue by Sotatek-MinhNguyen11** [ordinals/ord#3829]
I restarted the process after a crash, but nothing was fetched
![Screenshot from 2024-06-24 18-40-18](https://github.com/ordinals/ord/assets/146687333/88b4b66a-414b-40ad-b8dc-031e3a8cc09c)

The data is still in block 2821491
![Screenshot from 2024-06-24 18-43-49](https://github.com/ordinals/ord/assets/146687333/4db29c5a-db40-4852-9509-36a3bb1fee09)

**Comment by cryptoni9n** [comment]
Hi @Sotatek-MinhNguyen11 - I don't understand the issue that you're having.  Please provide more detail on 1) what crash?

**Comment by cryptoni9n** [comment]
If the testnet instance is still stuck, I'd recommend starting over and reindexing.  You could also download an index from [Ordstuff.info](https://ordstuff.info/indexes/0.18/test-networks/).  If you're still experiencing issues, please ask in the #tech-support channel of the [Ordicord](https://github.com/ordinals/ord).
