### ISSUE TITLE
How to withdraw tokens

### ISSUE THREAD

**Issue by Vero7979** [ordinals/ord#3839]

**Comment by cryptoni9n** [comment]
Hi @Vero7979 - you can send runes from the ord wallet by using the `ord wallet send` command.  There are many missing details in your post that would help us answer your question better.  In the future, please try asking questions like these over in the [Ordicord](https://discord.com/invite/ordinals) where we can help you in real time.

**Comment by Vero7979** [comment]
****``[having issues transferring to a wallet that’s beginner friendly ****
