### ISSUE TITLE
abnormal startup time.

### ISSUE THREAD

**Issue by heipacker** [ordinals/ord#3848]
Now starting a node requires waiting for several hours to initialize. 
it is not starting indexing for the first time, it is already have a fully built index and then start the server with something like `nohup ./ord --config ord.yaml --data-dir /ord/bin/data --index-cache-size 77309411328 --commit-interval 5000 --bitcoin-rpc-url 127.0.0.1:8335 --index-sats --index-runes server >>console.log 2>&1 &` and then it takes hours for the server to start?

12core  96G RAM  230G SSD

`#!/usr/bin/env bash
export RUST_LOG=debug
nohup ./ord --config ord.yaml --data-dir /ord/bin/data --index-cache-size 77309411328 --commit-interval 5000 --bitcoin-rpc-url 127.0.0.1:8335 --index-sats --index-runes server >>console.log 2>&1 &`

**Comment by so7ow** [comment]
Just a guess but you're probably not stopping `ord` cleanly and therefore it is having to repair the index at startup. That can take hours, as you've seen. If you skip all the nohup and output redirection you could probably see the message it's displaying during that long wait.

**Comment by cryptoni9n** [comment]
as a side note, the current default value for the --commit-interval flag is 5000, so no need to specify that unless you want a different value.

**Comment by heipacker** [comment]
> Just a guess but you're probably not stopping `ord` cleanly and therefore it is having to repair the index at startup. That can take hours, as you've seen. If you skip all the nohup and output redirection (or maybe just check whatever logs you're getting?) you could probably see the message it's displaying during that long wait.

Often times it is caused by OOM.

**Comment by so7ow** [comment]
Yes, any abnormal stop or crash will generally cause the index file to require repair at next launch.

**Comment by cryptoni9n** [comment]
@heipacker please seek help for this issue in the [Ordicord](https://discord.com/invite/ordinals), if it persists.
