### ISSUE TITLE
Addition of burn charm requires database reindex, but schema not bumped

### ISSUE THREAD

**Issue by gmart7t2** [ordinals/ord#3851]
#3836 adds a new charm. It needs the index to be rebuilt, but the database schema number wasn't bumped. 

As a result ordinals.com is currently not showing the burn charm on any inscriptions that were burned before this PR was merged.

1. Reindex ordinals.com
2. Bump the schema number

**Comment by raphjaph** [comment]
Thanks, that was an oversight, will be more careful in the future.
