### ISSUE TITLE
Contradiction in runes spec?

### ISSUE THREAD

**Issue by gmart7t2** [ordinals/ord#3855]
![Screenshot_2024-07-13_12-30-16](https://github.com/user-attachments/assets/1764afc2-312f-4fb8-8c5f-24846590c7a5)

Are unknown odd tags ignored or forbidden? It can't be both!

I guess they aren't forbidden because "ord decode" happily decodes the runestone in these 3 txs, which each have unknown odd tags:

* e6c190a563824cebac0821fece3ea477d6d93a39095dd2b5de8379b56de6ae54
* e8d4998a4df7c64400d6c05f3caa939ed45d51a301125be1a33db584b9e0a18a
* 24a0fc977fef46fd6b7661a503a159c2d2e172d7d6905fe28676b1ac3cb30743

**Comment by raphjaph** [comment]
Yes, they aren't forbidden, just ignored.

I guess we should change the phrasing of the last sentence to `..., and should not be used.` It would then conform more to the language used in [RFCs]( https://www.ietf.org/rfc/rfc2119.txt#:~:text=MUST%20NOT%20This%20phrase%2C%20or,absolute%20prohibition%20of%20the%20specification). You can use odd tags but it will very likely lead to weird behaviour in the future.

**Comment by casey** [comment]
Unrecognized odd tags are ignored, but they are *reserved*, in the sense that future protocol upgrades may give them meaning, and so they should not be used for ad-hoc protocol extensions.

Updating the language in #3885.
