### ISSUE TITLE
Should the ord protocol add swap and destroy operations?

### ISSUE THREAD

**Issue by sharphill2022** [ordinals/ord#3869]
The ordinals protocol does not provide a swap function for on-chain transactions, which requires some stub utxo when using psbt for on-chain transactions, which makes transactions more complicated and more expensive. Can a swap instruction like the following be provided to make ord's on-chain transactions simpler?

<img width="322" alt="image" src="https://github.com/user-attachments/assets/dea6cf4c-6e1d-4f3d-93b2-65adb3a3aab8">

The exchange starts with the first satoshi of the utxo until one party exhausts all satoshis.

Similarly, the destroy function can also be provided like this:
<img width="349" alt="image" src="https://github.com/user-attachments/assets/9738928c-f874-4ace-9f58-6dc8c87c5a21">
The user merges the inscriptions in their wallet together and destroys all inscriptions with this instruction, which are removed from the ord indexer and are no longer indexed.

**Comment by raphjaph** [comment]
Inscriptions are tied to the underlying sat, so the flow of those sats has to be respected. Lifting them of one sat and putting on another would break the immutability guarantees.

Inscriptions are immutable so can never be removed from the index, the only operation that we have is burning the inscription, which makes in untransferable #2766
