### ISSUE TITLE
Why is the first push to a Rune OP_13?

### ISSUE THREAD

**Issue by melvincarvalho** [ordinals/ord#3871]
This is not explained anywhere, does it equal "R"?

Search: OP_PUSHNUM_13 : https://github.com/search?q=repo%3Aordinals%2Ford+OP_13&type=code

Tweet: https://x.com/rodarmor/status/1781494967657247199

Docs: https://docs.ordinals.com/runes.html#etching

Unanswered issue: https://github.com/ordinals/ord/issues/3360

I've been searching alot, a simple explanation might help folks like me trying to understand the protocol.

Thanks!

**Comment by raphjaph** [comment]
It's chosen pretty arbitrarily, we wanted a short and not too often used OP_CODE to identify Runestones. 13 was also nice since we hadn't used that tag in the inscription envelope yet so could add it in there as well.

**Comment by melvincarvalho** [comment]
> It's chosen pretty arbitrarily, we wanted a short and not too often used OP_CODE to identify Runestones. 13 was also nice since we hadn't used that tag in the inscription envelope yet so could add it in there as well.

Thanks alot.  Now that I've read much more on runes, this seems clearer.  Though it wasnt for me at the start.

Can I ask, is the magic number different on testnet, for example 16?

**Comment by raphjaph** [comment]
No, it's the same on all networks. We did have a placeholder on signet and testnet before the launch but changed that to OP_13 at launch

**Comment by melvincarvalho** [comment]
Thanks alot, closing.  FWIW I've seen OP_16 alot on testnet, and thought they were runes.  Curious.

Closing.
