### ISSUE TITLE
ordinals.com down?

### ISSUE THREAD

**Issue by wagedu** [ordinals/ord#3873]
At first I got a Timeout error. It has since "evolved" into an unknown error, according to Cloudflare...
Should I panic?

<img width="1016" alt="Screenshot 2024-07-23 at 12 34 02" src="https://github.com/user-attachments/assets/8b4ee585-a50e-4151-b54b-71c2b3757195">
<img width="1087" alt="Screenshot 2024-07-23 at 13 16 00" src="https://github.com/user-attachments/assets/9d64d69b-394d-4ea0-978b-eca5241abbeb">

**Comment by so7ow** [comment]
Panic would seem to be in order 🤣

**Comment by cryptoni9n** [comment]
@raphjaph @casey

**Comment by cryptoni9n** [comment]
looks like it is back to now

**Comment by wagedu** [comment]
Honestly still trying to wrap my head around the idea that it can be down at all 🫣

**Comment by cryptoni9n** [comment]
> Honestly still trying to wrap my head around the idea that it can be down at all 🫣

Don't get it twisted. Just because ordinals.com is inaccessible doesn't mean that Bitcoin or the data stored on Bitcoin is inaccessible.

**Comment by casey** [comment]
On it!

**Comment by casey** [comment]
I turned it off and on again and it's working now. I also blackholed a service which was hotlinking to ordinals.com, which caused a large surge in traffic. Not sure if it's related. Things should be working now.

**Comment by wagedu** [comment]
> > Honestly still trying to wrap my head around the idea that it can be down at all 🫣
> 
> Don't get it twisted. Just because ordinals.com is inaccessible doesn't mean that Bitcoin or the data stored on Bitcoin is inaccessible.

@cryptoni9n mate, what makes you think I am implying any of that?! Like, at all?! lol You're saying everything yourself, lol
Why the hell would anyone post here, in the Ords GitHub Issues, use the subject "ordinals.com down", use screenshots from Cloudflare saying, literally "ordinals.com" and **not a single time write anything related to** "accessing Bitcoin", if that person was thinking what you, for some weird reason, assumed that I think?
Talk about twisting, lol
