### ISSUE TITLE
New runes are not displayed on the ord wallet balance after etching.

### ISSUE THREAD

**Issue by Werwolf888** [ordinals/ord#3874]
I got one strange problem after updating the wallet to version 0.19.0. After any rune etching operation, these new runes do not appear on the wallet balance, although the etching operations always end successfully. The created new runes are visible on the website https://ordinals.com if you enter the rune name in the search. That is, these new runes exist, but they seem to be outside the access of the original ord wallet in which they were created.

I checked the outputs list after creating the next rune and I see that the new rune is on one of the outputs that is on my wallet and is displayed in the list when executing the command: "ord wallet outputs"
I attached screenshots where this problem is visible step by step:

1. I created a new rune "UNCOMMON•OLD•GODS•BTC" and saw the output on which it is located ("08fd0acf27a56ae73c0ba5c4db101684ff76a4f2637eac320d1d5603207d7363:0:0")

2. I checked the outputs list on my server via the "ord wallet outputs" command and found that this output 08fd0acf27a56ae73c0ba5c4db101684ff76a4f2637eac320d1d5603207d7363:0:0 is on my server

3. I opened the website https://ordinals.com and entered the name UNCOMMON•OLD•GODS•BTC in the search. This rune was found and I see that this rune is placed on this output. Example:
https://with19.ordstuff.info/rune/UNCOMMON•OLD•GODS•BTC

4. I execute the command "ord wallet balance" but my new rune is not in the list of runes.

I tried to create 4 different runes for several days and each time they do not show up in the wallet balance. When I try to send the rune via the send command, I also get the error "error: insufficient `UNCOMMON•OLD•GODS•BTC` balance, only 0 $ in wallet"

I carefully read the previously created issues about this problem and tried to apply the following solutions to this problem:

1. Restarted bitcoind and ord server after the poison operation, after the new rune was created. And I also rebooted my VPS

2. Tried to execute commands to unlock UTXO, for example:
> bitcoin-cli -rpcwallet=ord listunspent | wc -l
> bitcoin-cli -rpcwallet=ord lockunspent true

3. I tried to manually specify the wallet address where the inscription and rune should be created via the --destination field in the .yaml file

All these methods did not give any effect and all new runes are still not displayed on the balance of the ord wallet.

Maybe someone knows how to fix this bug and make these runes available for my ord wallet?

<img width="1034" alt="1" src="https://github.com/user-attachments/assets/4e0ed4a1-c7f2-4bd7-b8fb-729ecaffd899">
<img width="936" alt="2" src="https://github.com/user-attachments/assets/c798e962-0159-44a4-98af-5e63a092f7e8">
<img width="725" alt="3" src="https://github.com/user-attachments/assets/63e811ce-5ab4-4d49-8ac3-fa7002a03220">

**Comment by cryptoni9n** [comment]
I think the step that corrected this issue previously was to `rescanblockchain` from Bitcoin Core.

**Comment by Werwolf888** [comment]
Yes, I did rescanblockchain after each rune etching.
I tried rescanblockchain starting from block 767430 or later blocks.

**> bitcoin-cli -rpcwallet=ord rescanblockchain 767430**

It did not give any result. It did not affect the balance display of new runes

**Comment by so7ow** [comment]
Did you fix it? What was it?
