### ISSUE TITLE
Support get sats/BTC balance for address (REST API)

### ISSUE THREAD

**Issue by kevinfaveri** [ordinals/ord#3875]
Similar to get runes balances API, could we have one that returns sats?

**Comment by cryptoni9n** [comment]
> Similar to get runes balances API, could we have one that returns sats?

this curl command works for me - how about you?

`curl -s 'https://ordinals.com/address/bc1pqaxt572lqqrpvvxajfxltjhq0et37ynczfxty8zz53phnqyuht4sutx04y' | grep -A 1 '<dt>sat balance</dt>' | tail -n 1 | sed 's/<\/\?dd>//g; s/^[ \t]*//; s/[ \t]*$//'`

**Comment by raphjaph** [comment]
We should put it in the JSON API though. Should be a super easy PR. Does one of you want to try it? @cryptoni9n @kevinfaveri

**Comment by cryptoni9n** [comment]
> We should put it in the JSON API though. Should be a super easy PR. Does one of you want to try it? @cryptoni9n @kevinfaveri

thanks raph, I'll take a stab at it shortly.

**Comment by cryptoni9n** [comment]
@raphjaph @kevinfaveri how does this look? 

![image](https://github.com/user-attachments/assets/68b04c71-5891-4fb3-bfbd-68ac4e865c29)
![image](https://github.com/user-attachments/assets/706ea4e5-b9db-4379-b8b7-1a16d60a67f1)

**Comment by raphjaph** [comment]
Perfect!

**Comment by twosatsmaxi** [comment]
while we are at it, can we also add rune balances too? to have it with the parity of html page. @cryptoni9n @raphjaph

**Comment by twosatsmaxi** [comment]
oh it has now, it's just not released it yet.

**Comment by raphjaph** [comment]
> while we are at it, can we also add rune balances too? to have it with the parity of html page. @cryptoni9n @raphjaph

yes and also inscription ids

**Comment by twosatsmaxi** [comment]
> > while we are at it, can we also add rune balances too? to have it with the parity of html page. @cryptoni9n @raphjaph
> 
> 
> 
> yes and also inscription ids

I have added it in this PR by the way 🤝 https://github.com/ordinals/ord/pull/3924

**Comment by cryptoni9n** [comment]
> I have added it in this PR by the way 🤝 #3924

merged
