### ISSUE TITLE
Whitelist domains to external requests

### ISSUE THREAD

**Issue by kevinfaveri** [ordinals/ord#3876]
I propose that instead of overloading Ord with external features, such as tracking Runes balance or Sats balance (https://github.com/ordinals/ord/issues/3875), we consider whitelisting popular domains like mempool or blockchain.info. This would allow us to make API requests to these services directly within Ordinals.

Additionally, we should develop a way for Ord to communicate more effectively with marketplaces and galleries that those whitelisted addresses ARE whitelisted so they can whitelist on their iframe too.

**Comment by casey** [comment]
This would make it impossible to run a self-contained index, as well as break whenever those externals sites went down, or changed their API, which is likely to happen because they have much less stringent backwards compatibility guarantees compared to ord.
