### ISSUE TITLE
Getting inscription id from inscriptions page doesn't work

### ISSUE THREAD

**Issue by raphjaph** [ordinals/ord#3877]
getting the inscription id from the inscriptions page doesn't work:

Doesn't work: https://ordinals.com/inscription/9d83495690204174b7b95f22955733f28a0c487eb44f06b8ab57852a1a0353a6i0

Works: https://ordinals.com/content/9d83495690204174b7b95f22955733f28a0c487eb44f06b8ab57852a1a0353a6i0

**Comment by cryptoni9n** [comment]
did some testing around in some different environments - it looks like this is only an issue on ordinals.com?
![image](https://github.com/user-attachments/assets/5f3fff02-334a-4319-b85e-7861317b643b)

**Comment by cryptoni9n** [comment]
> I think this was due to the ordinals.com server being down around this time last week :)

except that it is ongoing.  retested this morning with the exact same results.

**Comment by vinkim** [comment]
This does work as intended, doesn't it? The ordinal is using [OrdJS](https://ordinals.com/content/3280180e7872eaef3cae589f3122f2f9527d3c1c30445cb13fc6eef03435aa66i0) 's `getInscription()` function
```
getInscriptionId() {
    const parts = window.location.pathname.split("/");
    if (
            parts.length >= 3
            && parts[1] === "content"
        ) {
        return parts[2]; 
    } else {
        console.error("URL does not contain a valid inscription ID.");
        return null; 
    }
}
```

which explicitly checks for  `&& parts[1] === "content"` in the `window.location.pathname`, so it will return **null** for all urls except `/content/<inscription id>`. On **null** the `initialize()` function throws an error, since `getChildren()` returns a 400 when trying to access `/r/children/null`

**Comment by raphjaph** [comment]
Do you guys have an example inscription where this works in the preview window?

**Comment by cryptoni9n** [comment]
> Do you guys have an example inscription where this works in the preview window?

I don't - I get this same failure in **all** environments when trying this:

```
$ curl -s --location 'https://ordinals.com/preview/9d83495690204174b7b95f22955733f28a0c487eb44f06b8ab57852a1a0353a6i0' --header 'Accept: application/json' | jq -r .id

jq: parse error: Invalid numeric literal at line 1, column 8
```

**Comment by raphjaph** [comment]
The OrdJs library is specifically looking for content, it should do `window.location.pathname.split("/").pop()`. Then it will work in both cases. You should definitely open a PR on the OrdJs repo for this.
```
 getInscriptionId() {
        const parts = window.location.pathname.split("/");
        if (
                parts.length >= 3
                && parts[1] === "content"
            ) {
            return parts[2]; 
        } else {
            console.error("URL does not contain a valid inscription ID.");
            return null; 
        }
    }
 ```
