### ISSUE TITLE
RBF for ordinals transaction

### ISSUE THREAD

**Issue by takanamiharuki0115** [ordinals/ord#3878]
I want to change transaction fee rate of my ordinals transaction.
How can I do this?
Please help me with example code.
Thank you in advance.

**Comment by cryptoni9n** [comment]
Hi @takanamiharuki0115 - bumping the fee of a transaction hasn't yet been implemented within `ord`.  See #1519 

Try the tech-support channel on the [Ordicord](https://discord.com/invite/ordinals) for help with how to do this using Bitcoin Core.
