### ISSUE TITLE
Duplicate Index

### ISSUE THREAD

**Issue by JD-Wang** [ordinals/ord#3883]
Index can never be 100%, index.redb from https://ordstuff.info/indexes/0.19/, I downloaded the latest one, 853446 to 853993 continuously updated in a loop
The latest block transactions can be queried locally, but runes and inscriptions cannot be found。
Ord.exe is 0.19.1, We have attempted to remove index.redb and reinstall it, but it did not work。

**Comment by cryptoni9n** [comment]
Hi JD - this is a known issue, #3804.  Please see that issue for workarounds.  If you continue to experience issues, please reach out to the tech-support channel on the [Ordicord ](https://discord.com/invite/ordinals)for troubleshooting assistance.
