### ISSUE TITLE
Rune Vesting discuss: How to design rune vesting module for token unlock/airdrop/etc

### ISSUE THREAD

**Issue by bingryan** [ordinals/ord#3886]
> Before I start this PR, I want to discuss it first.

## Abstract

Use `vesting` to replace `premine`(or add vesting, not replace).

## Motivation

Implement the vesting module of rune to feat:

- Airdrop
- Token Unlocks & Vesting

## Description

For the group with A(Like DOG/LOBO/Others user group) rune/inscription, when etching a new `B` rune, you can set vesting to the token unlock of B rune (at etch stage, premine -> vesting) to achieve token unlock. at B etch's vesting info, you can set A's Rune ID info to distribute premine tokens to A group.

### Linear Vesting

```
ord RuneID/Inscription -> {
	start: // start block
	count: // vesting count
	period: // period
	per_period: // rune token to release per vest
}
```

### Graded Vesting

TODO

### Cliff Vesting

TODO

@casey @raphjaph

**Comment by casey** [comment]
I think this is better accomplished with timelocks / lock heights. In general, if functionality can come from the bitcoin base later, it should.
