### ISSUE TITLE
Ordinals.com having intermittent issues today

### ISSUE THREAD

**Issue by so7ow** [ordinals/ord#3910]
@raphjaph @casey @cryptoni9n 

https://discord.com/channels/987504378242007100/1069465367988142110/1277296052944375909

![image](https://github.com/user-attachments/assets/cf8fdc1a-ff2b-4973-b4c9-3cdf1c858429)

**Comment by cryptoni9n** [comment]
Seems good for me right now.

**Comment by so7ow** [comment]
Can't get it to fail right now either. 👍🏻

**Comment by so7ow** [comment]
Spoke too soon. Still failing intermittently:

![ScreenShot 2024-08-25 - LnHOvCoF](https://github.com/user-attachments/assets/9d0a20cc-46e3-490a-8fdf-c13ebedc1d32)

**Comment by casey** [comment]
Thanks for the report! Not sure what's going on. I'm going to reboot the servers and hope for the best.

**Comment by so7ow** [comment]
Looks fixed to me 👍🏻
