### ISSUE TITLE
Delegates not returning as inscription in output

### ISSUE THREAD

**Issue by switch-900** [ordinals/ord#3911]
/output/{delegate inscripiton/TXID} < this is not showing delegates as an inscripiton.

**Comment by cryptoni9n** [comment]
Hi switch-900, 

I ran this test against a known delegate on mainnet and had success.  Here's what I did,

https://docs.ordinals.com/guides/explorer.html?highlight=API#json-api First, note the syntax should be `/output/<OUTPOINT>`

`curl -s -H "Accept: application/json" 'http://with19.ordstuff.info/output/44cc0fd04fe9fa69b41b3d928c11b42efa653b4a23785da8454746a4ae60a28f:0' | jq` lists `44cc0fd04fe9fa69b41b3d928c11b42efa653b4a23785da8454746a4ae60a28fi0` as the inscription which is the delegate for `4ea5c3965886a7ced8e6afaad127473744a7a3b548af0c557f55a8930edbc021i0`

If this example doesn't help, please share the commands you're running and the errors you're receiving.

**Comment by switch-900** [comment]
I have tried this in all these instance including locally and this is not returning. https://www.ordinals.com/output/e0d67f72719e0a61a619b9747cd980191242f8ebc18dd9b3015d3939b6c9ce5e:0  ccurl -s -H "Accept: application/json" 'http://with19.ordstuff.info/output/e0d67f72719e0a61a619b9747cd980191242f8ebc18dd9b3015d3939b6c9ce5e:0'
{"address":"bc1p9268tenu5ayncz5hqsxhvrdw93hsr346zpcfxxhq7677p7uc9r8q7n4ur2","indexed":false,"inscriptions":[],"runes":{},"sat_ranges":null,"script_pubkey":"OP_PUSHNUM_1 OP_PUSHBYTES_32 2ab475e67ca7493c0a97040d760dae2c6f01c6ba1070931ae0f6bde0fb9828ce","spent":true,"transaction":"e0d67f72719e0a61a619b9747cd980191242f8ebc18dd9b3015d3939b6c9ce5e","value":546}  this one too: https://with19.ordstuff.info/output/0ef72d903bce5a68cdeb574e0da06cbd6852e2bbca72eb67669964df237c2508:0

**Comment by cryptoni9n** [comment]
> ccurl -s -H "Accept: application/json" 'http://with19.ordstuff.info/output/e0d67f72719e0a61a619b9747cd980191242f8ebc18dd9b3015d3939b6c9ce5e:0'

Hi switch-900, it looks like you're just querying the wrong outpoint.  The inscription is in e0d67f72719e0a61a619b9747cd980191242f8ebc18dd9b3015d3939b6c9ce5ei0:1 not e0d67f72719e0a61a619b9747cd980191242f8ebc18dd9b3015d3939b6c9ce5ei0:0.  If you change your command to `curl -s -H "Accept: application/json" 'http://with19.ordstuff.info/output/e0d67f72719e0a61a619b9747cd980191242f8ebc18dd9b3015d3939b6c9ce5e:1' | jq` you'll get the proper inscription id returned.

>  this one too: https://with19.ordstuff.info/output/0ef72d903bce5a68cdeb574e0da06cbd6852e2bbca72eb67669964df237c2508:0

Again, just the wrong outpoint.  Try `curl -s -H "Accept: application/json" 'http://with19.ordstuff.info/output/0ef72d903bce5a68cdeb574e0da06cbd6852e2bbca72eb67669964df237c2508:1' | jq`

**Comment by switch-900** [comment]
Awesome, yeah my bad. I was taking the inscription id and replacing the i with : thank you for catching this.
