### ISSUE TITLE
Non-existant output lookups return 500 error

### ISSUE THREAD

**Issue by casey** [ordinals/ord#3919]
For example:

https://ordinals.com/output/0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef:123

This is because the JSON RPC status code / message for output not found was changed, so we don't correctly transform it into a 404 not found HTTP error.

**Comment by cryptoni9n** [comment]
When reproduced in the `env` terminal I see this error:

`error serving request: JSON-RPC error: RPC error response: RpcError { code: -5, message: "No such mempool or blockchain transaction. Use gettransaction for wallet transactions.", data: None }`

I hope this information will help in getting to the bottom of it.  I looked into the code and wasn't able to get very far in fixing it.
