### ISSUE TITLE
Ord consuming mem% 

### ISSUE THREAD

**Issue by SoFTCureOrigin** [ordinals/ord#3925]
hi,
ord is, step by step, consuming memory.
Then stop growing when 16Gb is reach, around 30 hours after reboot.

ord v18.5  [x86_64-unknown-linux-gnu.tar.gz]
got index with sat (18)

see my htop 8 hours after reboot:
![image](https://github.com/user-attachments/assets/73ab9090-858f-4fee-b0e2-9f34a2667698)

**Comment by so7ow** [comment]
Did you have a question? You might try the latest version of ord and check `ord --help` for some memory settings if you're not happy with the memory footprint. Also, the sats index is more intensive than the "without" sats. You might consider whether you need to track sats.

**Comment by SoFTCureOrigin** [comment]
hi,  thk, found and now trying lowering the "index_cache_size".

do i need to change the index file as i change from v18 to v19 (i read that few month ago)

**Comment by so7ow** [comment]
> do i need to change the index file as i change from v18 to v19

Yes
