### ISSUE TITLE
Errors on testnet.ordinals.com

### ISSUE THREAD

**Issue by so7ow** [ordinals/ord#3935]
![image](https://github.com/user-attachments/assets/a53adb0f-c692-4f7b-ae11-c672694657b6)

![image](https://github.com/user-attachments/assets/07d776ac-6aaf-42c7-b277-e604cd59b0c8)

**Comment by cryptoni9n** [comment]
seeing the same thing on my end, mobile and windows browsers.

**Comment by so7ow** [comment]
> Let me know and if it works

Still broken for me

**Comment by cryptoni9n** [comment]
> > Let me know and if it works
> 
> Still broken for me

same

**Comment by raphjaph** [comment]
We have it running on a too small disk size machine, disk space keeps running out and crashing bitcoind. Will have to upgrade

**Comment by raphjaph** [comment]
I've upgraded the server and https://testnet.ordinals.com should be working again

**Comment by cryptoni9n** [comment]
LGTM!
