### ISSUE TITLE
Allow iframe scroll on HTML Inscriptions

### ISSUE THREAD

**Issue by bruffstar** [ordinals/ord#3944]
See here: 
https://ordinals.com/inscription/124181f2d2f1f1e3cd95ebe0ccd064a4f48bb60849e918ece9d8ccd76a984d6ei0

Compared to here where it scrolls nicely:
https://ordiscan.com/inscription/75724848

Here is issue:
<img width="414" alt="image" src="https://github.com/user-attachments/assets/c82746fd-f02e-465b-8103-eefcebcd6a80">

**Comment by raphjaph** [comment]
#3947
