### ISSUE TITLE
Inscriptions not displayed

### ISSUE THREAD

**Issue by gus4rs** [ordinals/ord#3946]
Some multi layered inscriptions aren't being displayed in my local server. E.g, going to 

https://ordinals.com/children/0e383b8af3e7f8767bc9ec0a48fbf837d82b0d537f4dbc7a8853e6828112ea41i0

Shows all the children of the ordinal collection

While going to the same URL in my local server doesn't display any image and doesn't log any error

http://server/children/0e383b8af3e7f8767bc9ec0a48fbf837d82b0d537f4dbc7a8853e6828112ea41i0 

I am using version 0.2.0 with full indexing (```--index-transactions --index-sats --index-runes ```)

Any clues on how to troubleshoot the issue?

**Comment by raphjaph** [comment]
Did you maybe set custom CSP headers?

**Comment by gus4rs** [comment]
No, I didn't

**Comment by raphjaph** [comment]
Ok so only recursive inscriptions aren't displayed and every other inscription is?

And there are no errors in the browser console? Not something like 404 or policy errors?

**Comment by gus4rs** [comment]
Also it prints tons of 404 errors, but so does ordinals.com

**Comment by gus4rs** [comment]
MORE UPDATE: 

Inspecting the requests in  the browser developer panel, some contents (accessed via ```http://server/content/...```) are loaded, some others aren't. The CSP header in the response for the contents that work contains ```default-src *:*/content/ *:*/blockheight *:*/blockhash *:*/blockhash/ *:*/blocktime *:*/r/ 'unsafe-eval' 'unsafe-inline' data: blob:```

And the requests that fail usually contain ```default-src 'self'``` in the response

**Comment by gus4rs** [comment]
```/usr/local/bin/ord --index-transactions --index-addresses --index-sats --index-runes --index-cache-size 500000000 --data-dir /ordinals/ --bitcoin-rpc-url 127.0.0.1:8332  --bitcoin-rpc-username bitcoin --bitcoin-rpc-password bitcoin server --http-port 1880 --polling-interval 10m```

**Comment by raphjaph** [comment]
Try setting the CSP header to the URL you want it displayed on.

```
--csp-origin <CSP_ORIGIN>
          Use <CSP_ORIGIN> in Content-Security-Policy header. Set this to the public-facing URL of your ord instance.
```

**Comment by gus4rs** [comment]
I am not running ord in a public facing website with domain, but in my local network
I tried putting: 
```  --csp-origin http://192.168.1.34:81``` to no avail.
