### ISSUE TITLE
Get rune balance use user's address in Regtest

### ISSUE THREAD

**Issue by FCBtc1116** [ordinals/ord#3951]
Now I am running my bitcoind and ord server
How can I get user's rune balance use user's address in regtest?
Is there any command that support that?

**Comment by cryptoni9n** [comment]
Hi FCBtc1116 - regtest is a local test chain.  There are no other addresses in regtest besides the ones you create.

Given this fact - getting your rune balance is the same as on mainnet, `ord wallet balance`  Your wallet will show you an address when you run `ord wallet receive`

If you need any further assistance with regtest, please reach out to the tech-support channel on [the Ordicord](https://discord.com/invite/ordinals).
