### ISSUE TITLE
ERROR ord::index::updater 767430/861913 

### ISSUE THREAD

**Issue by Qvantitative** [ordinals/ord#3953]
I keep getting the following issue:

[indexing blocks] ██████████████████████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░ 767430/861913[2024-09-19T02:11:00Z ERROR ord::index::updater] Couldn't receive txs failed to fetch raw transaction: code -5 message No such mempool or blockchain transaction. Use gettransaction for wallet transactions.
error: failed to get transaction for a2df039d22ce84803de677328efe3a2fe82b0102d66c32f899715608babd1214: channel closed

I have already reindexed my blocks, and my txindex=1 is already set in my bitcoin.config. I have also tried different versions of ord 0.19 and 0.20, both had the same issues. The fact that it keeps happening on block 767430 should give some type of insight into the possible solutions surrounding this (since thats the block of inscription #0)

**Comment by so7ow** [comment]
> my txindex=1 is already set in my bitcoin.config

Often when people see this error and say "I already set txindex=1" they only *think* they set it, but it's in a wrongly named/located conf file, or it's commented out, or there's a typo or something. Check your indexing status with:

```bitcoin-cli getindexinfo```

...and look for `synced:true` or check out this [thread on the Ordicord](https://discord.com/channels/987504378242007100/1226690883097854036/1226690883097854036) for more troubleshooting steps.

**Comment by Qvantitative** [comment]
> > my txindex=1 is already set in my bitcoin.config
> 
> Is that the real name of your file? The correct name is `bitcoin.conf`. Often when people see this error and say "I already set txindex=1" they only _think_ they set it, but it's in a wrongly named/located conf file, or it's commented out, or there's a typo or something. Check your txindex status with:
> 
> `bitcoin-cli getindexinfo`
> 
> ...and look for `txindex / synced:true` or check out this [thread on the Ordicord](https://discord.com/channels/987504378242007100/1226690883097854036/1226690883097854036) for more troubleshooting steps.



> > my txindex=1 is already set in my bitcoin.config
> 
> Is that the real name of your file? The correct name is `bitcoin.conf`. Often when people see this error and say "I already set txindex=1" they only _think_ they set it, but it's in a wrongly named/located conf file, or it's commented out, or there's a typo or something. Check your txindex status with:
> 
> `bitcoin-cli getindexinfo`
> 
> ...and look for `txindex / synced:true` or check out this [thread on the Ordicord](https://discord.com/channels/987504378242007100/1226690883097854036/1226690883097854036) for more troubleshooting steps.


Mine shows the ["synced":true] ->


D:\bin>bitcoin-cli getindexinfo
{
  "txindex": {
    "synced": true,
    "best_block_height": 861922
  }
}

**Comment by so7ow** [comment]
To quote [the Ordicord](https://discord.com/channels/987504378242007100/1083363982963908640/1167096758216691744):

> I saw (only one time) where txindex was reporting complete, like yours, but ord didn't seem to recognize it, like yours. In that instance the guy fixed it by simply stopping bitcoin, deleting the indexes/txindex folder and then restarting bitcoin to make it regenerate txindex from scratch. Might be worth a try.

**Comment by Qvantitative** [comment]
I just deleted my indexes folder, and rebuilding it now. Hope this works. Will comment back here when its done.

> Ah, yes, that does look correct. To quote from [the Ordicord](https://discord.com/channels/987504378242007100/1083363982963908640/1167096758216691744):
> 
> > I saw (only one time) where txindex was reporting complete, like yours, but ord didn't seem to recognize it, like yours. In that instance the guy fixed it by simply stopping bitcoin, deleting the indexes/txindex folder and then restarting bitcoin to make it regenerate txindex from scratch. Might be worth a try.

i

**Comment by Qvantitative** [comment]
do you know how long this usually takes? Its been over 36 hours now, im only on block 610654 now. My dbcache was at 2048 but I increased it to 16384, but I havent stopped and restarted the reindexing yet since I made that change because Im worried its going to corrupt a block and force me to restart the whole indexing again for the 3rd time. Can you confirm whether this will be the case or not?

{
  "txindex": {
    "synced": false,
    "best_block_height": 610654
  }
}

> Ah, yes, that does look correct. To quote from [the Ordicord](https://discord.com/channels/987504378242007100/1083363982963908640/1167096758216691744):
> 
> > I saw (only one time) where txindex was reporting complete, like yours, but ord didn't seem to recognize it, like yours. In that instance the guy fixed it by simply stopping bitcoin, deleting the indexes/txindex folder and then restarting bitcoin to make it regenerate txindex from scratch. Might be worth a try.

**Comment by so7ow** [comment]
My standard line is usually only a few hours, sometimes longer. Seems like you are experiencing the latter.

**Comment by so7ow** [comment]
I don't think restarting bitcoin would normally restart the txindex process but I wouldn't confidently guarantee that. I also don't think increasing the dbcache would increase indexing performance. Same level of confidence there. 🙃

**Comment by Qvantitative** [comment]
This solved the issue. Thank you for the help

> Ah, yes, that does look correct. To quote from [the Ordicord](https://discord.com/channels/987504378242007100/1083363982963908640/1167096758216691744):
> 
> > I saw (only one time) where txindex was reporting complete, like yours, but ord didn't seem to recognize it, like yours. In that instance the guy fixed it by simply stopping bitcoin, deleting the indexes/txindex folder and then restarting bitcoin to make it regenerate txindex from scratch. Might be worth a try.

**Comment by so7ow** [comment]
Glad to hear it
