### ISSUE TITLE
href target: works ONLY from /content/ and /preview/ but NOT from /inscription/

### ISSUE THREAD

**Issue by wagedu** [ordinals/ord#3958]
Edit: rewrite for clarity

Hi, 

I'm trying to add a humble link to move from /inscription/ID to /preview/ID so people can easily reach the full sized inscription (without having to scroll the screen)
But it doesn’t work, as mentioned in the “subject” above.

In HTML: target=”_top” and target=”_parent”. In JS: window.parent.location.href and window.top.location.href

1.	WORKS as expected, when used from /content/ and /preview/
2.	Sandbox ERROR*, when used from /inscription/ 

I know the source of the problem is that /inscription/ is the only where the inscription is inside of an iFrame. But it has some bug to it, considering it shows different behaviors.
At least links INSIDE ordinals, since we already use recursion. No? 

How I reproduce/est it: Just copypaste the code below inside @lifofifoX  ‘s fabulous code tester and click the link. The best way to understand the error, is by accessing the tester via the 3 different paths
https://ordinals.com/inscription/c24b53e7733d72a8662676bd2067fa7e715fa5c2ea614b7727da9787def47aeai0

https://ordinals.com/content/c24b53e7733d72a8662676bd2067fa7e715fa5c2ea614b7727da9787def47aeai0
https://ordinals.com/preview/c24b53e7733d72a8662676bd2067fa7e715fa5c2ea614b7727da9787def47aeai0

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
  </head>
  <body>
    <a href="/preview/335b2826ee1e540527471b32bd7ec12c48ecfcae34be61043477066d958b7a5ai0" target="_top">CLICK ME</a>
  </body>
</html> 
```

*Error thrown ONLY from /inscription/

Unsafe JavaScript attempt to initiate navigation for frame with URL 'https://ordinals.com/inscription/c24b53e7733d72a8662676bd2067fa7e715fa5c2ea614b7727da9787def47aeai0' from frame with URL 'https://ordinals.com/preview/c24b53e7733d72a8662676bd2067fa7e715fa5c2ea614b7727da9787def47aeai0'. The frame attempting navigation of the top-level window is sandboxed, but the 'allow-top-navigation-by-user-activation' flag is not set and navigation is not triggered by user activation.

**Comment by wagedu** [comment]
Again, this all works perfectly from **/content/** and **/preview/** paths but DOESNT WORK from **/inscription/** path:

**_top** and **_parent**: throw the above mentioned error
-**blank**: simply ignored, doesn't throw error but doesn't work either
-**self**: works as expected

It appears to be intentional but its advantages aren't clear. From a user perspective it sure looks confusing:
1. Not consistent: Different behaviour depending on path?
2. Same-domain href should be considered secure
3. The error-triggering href (click to move from /**inscription**/ID to /**preview**/ID) is available a few lines below, on "preview: link", right between "sat name: sat_name" and "content: link"

Thanks in advance :)

**Comment by casey** [comment]
To clarify, I think this is what you want: While viewing an inscription on `/inscription/ID`, provide a link inside of that inscription that the user can click to navigate the top-level page to `/preview/ID`.

This is not possible, because I don't think there is an existing browser feature which would let us do this. iframes are sandboxed, so they are not allowed to change the location of the top level page. I don't think there's a way to whitelist specific navigation targets, i.e., whitelist a location change if it's pointed to the same origin. Also, I'm not sure we would want to allow even that, since we wouldn't want to allow an inscription to navigate to another inscription.

**Comment by casey** [comment]
How could what you want be implemented using widely available browser features?

**Comment by wagedu** [comment]
> How could what you want* be implemented using widely available browser features?

It could be added on the inscription template:
 Instead of (currrent) `<iframe sandbox=allow-scripts` just 

`<iframe sandbox="allow-scripts allow-top-navigation-by-user-activation"` **to allow JS's** `window.top.location`

`<iframe sandbox="allow-scripts allow-top-navigation"` **to allow HTML's** `target="_top"` : 



*About wanting: Part of me hopes you don't implement, lol. I might've been a wee impatient... and already inscribed 400 files WITHOUT the functionality 😬

**Comment by casey** [comment]
`allow-top-navigation-by-user-activation` would allow changing the location to any location, not just another location on ordinals.com.

**Comment by wagedu** [comment]
`allow-top-navigation-by-user-activation` in the HTML doesn't affect local/remote links permissions.

The ability/inability to 
> change the location to any location, not just another location on ordinals.com

is set in the Content Security Policy (CSP) of the server. My guess is that's where you made recursion local-only?
`Setting Content-Security-Policy: default-src 'self';` on the server, would block links to external URLs. 

Currently, external URLs are allowed sitewide... with the exception of a specific situation: targeting top/main page + from an iframe (like the one on /inscription/) because of the sandbox default. 
`allow-top-navigation-by-user-activation` only aims to make it behave like everyone else, not an exception.

**Comment by casey** [comment]
I'm not sure this is the case. The CSP determines what can be embedded *on the page*. However, I don't believe that it prevents navigation of the top-level page to an external URL.

**Comment by wagedu** [comment]
Honestly I'm (and was) unable to check, and replied based on second-hand info **
Of course, I'll trust you before stackoverflow.
RN I have no method that blocks external links specifically from **/inscription/** BUT allows them from **/content/** and **/preview/**

[
What's coming reads like I'm demanding an explanation. Sorry!! I'm non-native english speaker. 
I actually only want to understand because it's a "different than expected" behaviour which made it impossible for me to predict. Maybe if I understand, I'll avoid future mistakes. Nothing more, really
]

May I ask why top navigation is prevented only for/from **/inscription/** but ok for the other two?
I mean, I would 200% get it if ordinals.com wants to limit ALL links to local.
But currently, the navigation of the top-level page to an external URL is **allowed sitewide** in ordinals.com ->**/inscription** and **/content/** and **/preview/** can all navigate to external URLs. 

The only difference/exception is that **/inscription/** is limited to do so on the iframe reserved for content display, while **/content/** and **/preview/** do so on the top-level.
What prevents  **/inscription/** to do "what's allowed", is nothing "active" but the (default) lack of sandbox's `allow-top-navigation-by-user-activation`




**Gathered (but not tested) info:
`default-src 'self';:` This directive restricts the loading of resources (including navigation) to the same origin. When a link attempts to navigate to an external URL, the browser checks this CSP directive. If the URL is not from the same origin (not compliant with `'self'`), the browser will block the navigation.

**Comment by wagedu** [comment]
😢
https://content-security-policy.com/navigate-to/

<img width="1166" alt="Screenshot 2024-10-05 at 20 07 46" src="https://github.com/user-attachments/assets/bda3fa1e-6282-446f-9c88-bfa1d3756aea">
