### ISSUE TITLE
Inscription Sandbox Content Security Policy directive: /output/ 🙏

### ISSUE THREAD

**Issue by 1stBitcoinSent** [ordinals/ord#3966]
🙏 please support Content Security Policy directive: https://ordinals.com/output/ 🙏

Would be Awesome 😁 if the Inscription Sandbox allowed anything under https://ordinals.com/* to be accessed 🙏

**Comment by cryptoni9n** [comment]
Hi @1stBitcoinSent - have you tried using the `ord env --proxy` flag?  If so, could you please explain in more detail what you are trying to do that isn't currently supported by it?

**Comment by 1stBitcoinSent** [comment]
Hi @cryptoni9n Thank you 😀 drafting an HTML inscription that fetches data from /output/*
I can fetch data from /r/* as it is included in the Content Security Policy directive

`Refused to connect to 'https://ordinals.com/output/x' because it violates the following Content Security Policy directive: "default-src https://ordinals.com/content/ https://ordinals.com/blockheight https://ordinals.com/blockhash https://ordinals.com/blockhash/ https://ordinals.com/blocktime https://ordinals.com/r/ 'unsafe-eval' 'unsafe-inline' data: blob:". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback`

**Comment by lifofifoX** [comment]
@1stBitcoinSent All recursive endpoints need to be under `/r/` namespace. If you wish to add a new recursive endpoint (i.e `/r/output`), you'd need to submit a PR that implements the new endpoint, along with reasoning to convince the protocol team re: why it's a good addition.

**Comment by 1stBitcoinSent** [comment]
@lifofifoX Thank you for letting me know 🧡 
Will think on this 😀
Looking forward to the day I can secure some Wizards 🧙‍♂️
