### ISSUE TITLE
```ord``` fails with Bitcoin Core v28.0

### ISSUE THREAD

**Issue by gus4rs** [ordinals/ord#3982]
```
[INFO  ord::index] Failed to connect to Bitcoin Core RPC at `127.0.0.1:8332/`:  JSON error: invalid type: sequence, expected a string
[WARN  ord::subcommand::server] Updating index: Failed to connect to Bitcoin Core RPC at `127.0.0.1:8332/`:  JSON error: invalid type: sequence, expected a string
```

![image](https://github.com/user-attachments/assets/76e7b46a-b0e0-4a6d-98f9-7ce3948fb7be)

**Comment by gus4rs** [comment]
probably related 
https://github.com/bitcoin/bitcoin/pull/29845

**Comment by so7ow** [comment]
You can fix it by downgrading to bitcoin core v27.1, presuming you're running and unreleased x.99 version.

**Comment by gus4rs** [comment]
sure, but but this needs to be addressed because v28 was already officially released

**Comment by so7ow** [comment]
> sure, but this needs to be addressed because v28 was already officially released

Yep, for sure. Edited my previous reply.

**Comment by gus4rs** [comment]
Can be "fixed" by adding ```-deprecatedrpc=warnings``` to bitcoin core v28 startup params

**Comment by so7ow** [comment]
> Can be "fixed" by adding ```-deprecatedrpc=warnings``` to bitcoin core v28 startup params
> 
> 
> 
> FTR: the correct way to do it, it should've just worked. And in the bitcoin core logs, a message should be printed like this:
> 
> 
> 
> ```
> 
> The RPC method getXXX() is deprecated and will be removed next version. Please use getXXX_WithCosmetics() instead
> 
> ```

Nice to know.

**Comment by gmart7t2** [comment]
https://crates.io/crates/bitcoincore-rpc/0.19.0 supports the new API. Is there a good reason we aren't using it instead of the old ord-bitcoincore-rpc fork?

**Comment by raphjaph** [comment]
We've removed the dependency on the old `ord-bitcoincore-rpc` [here](https://github.com/ordinals/ord/pull/3959).

https://crates.io/crates/bitcoincore-rpc/0.19.0 relies on `rust-bitcoin` 0.32.x and unfortunately that crate has many breaking changes. I'm currently working on upgrading here: https://github.com/ordinals/ord/pull/3962 but it's an incredibly manual and frustrating task. v28 incompatibility means I'm going to prioritise that now.

**Comment by gmart7t2** [comment]
Consider something like #3996 as a short term fix.
