### ISSUE TITLE
Issues with wallet creation and receiving transactions on testnet using Fractal Bitcoin node and Ord wallet

### ISSUE THREAD

**Issue by AksharPrajapati03** [ordinals/ord#4001]
I've set up everything in mainnet, but for testing purposes, I am trying to set up the testnet. The Fractal Bitcoin node is running properly in testnet, and I have successfully created an Ord wallet. However, I am encountering issues when trying to perform any operations (such as receiving transactions) after wallet creation.

**Steps to Reproduce:**

Set up the Fractal Bitcoin node on testnet using the following command:
`bitcoind -daemon -testnet -datadir=/home/ubuntu/fractald-0.2.1-x86_64-linux-gnu/data`

Note: I'm receiving the following warning:
`Warning: bitcoin.conf:693 Section [signet] is not recognized.`

We are using an alias for the ord-testnet-fractal command as follows:
`alias ord-testnet-fractal='/home/ubuntu/fractald-0.2.1-x86_64-linux-gnu/ord/target/release/ord --cookie-file /home/ubuntu/fractald-0.2.1-x86_64-linux-gnu/data/testnet3/.cookie --datadir /home/ubuntu/fractald-0.2.1-x86_64-linux-gnu/data --bitcoin-rpc-url http://127.0.0.1:18332'`

Create the Ord wallet:
`ord-testnet-fractal --chain=testnet wallet create`

Output:
```
{
  "mnemonic": "oppose lunch frost bounce desert about amused muscle hybrid upper bench weekend",
  "passphrase": ""
}
```

Attempt to dump or receive funds using the wallet:

Dump wallet:
`ord-testnet-fractal --chain=testnet wallet dump`

Error:
`error: wallet "ord" contains unexpected output descriptors, and does not appear to be an `ord` wallet, create a new wallet with `ord` wallet create`

Receive funds:
`ord-testnet-fractal --chain=testnet wallet receive`

Error:
`error: wallet "ord" contains unexpected output descriptors, and does not appear to be an `ord` wallet, create a new wallet with ord wallet create`

**Expected Behavior:**
I expected to be able to receive transactions and interact with the wallet after creating it successfully. However, I am met with errors indicating unexpected output descriptors in the wallet.

**Environment:**
Fractal Bitcoin Node: Testnet
Ubuntu: 24.04 LTS
Ord Version: Testnet Fractal version

**Additional Context:**
The warning regarding the [signet] section in the bitcoin.conf is unexpected since I am only using testnet. I suspect this might be related to the issue, or there could be an issue with how the wallet is being created or handled.

**Comment by so7ow** [comment]
FYI the fractal version is released by a different team. I don't think you'll find much support for it here. (Perhaps I'm mistaken 🤷🏻‍♂️)

**Comment by AksharPrajapati03** [comment]
Actually I've already ask over fractal community but not getting any response, So I thought I can ask here as well.

https://github.com/fractal-bitcoin/ord/issues/16

**Comment by cryptoni9n** [comment]
sorry, this isn't something that's currently supported.

**Comment by AksharPrajapati03** [comment]
I understand that the Fractal node doesn't support the Ord wallet for the testnet (I’ve confirmed that it works on the mainnet). However, do we have support for the Bitcoin Core node's Ord wallet in testnet?

**Comment by cryptoni9n** [comment]
> I understand that the Fractal node doesn't support the Ord wallet for the testnet (I’ve confirmed that it works on the mainnet). However, do we have support for the Bitcoin Core node's Ord wallet in testnet?

yes, wallet question/issues using `ord` with Bitcoin core with testnet/regtest/signet/mainnet are supported.  but do understand that testnet3 has been increasingly difficult to index for several months now.  If you're having a problem with the wallet in testnet, please seek help in the [Ordicord ](https://discord.com/invite/ordinals) or open a new issue here if you believe it to be a bug.

**Comment by AksharPrajapati03** [comment]
Sure, Thank you @cryptoni9n.
