### ISSUE TITLE
Consider moving the database to a more performant library

### ISSUE THREAD

**Issue by gus4rs** [ordinals/ord#4004]
Here's a summary of historic performance issues with redb (generated by AI)

---

* Bulk loading: Redb’s performance might suffer when loading large amounts of data into the database at once. This could be due to inefficiencies in tracking dirty pages or the B-Tree implementation. The author of Redb acknowledges this issue and plans to optimize it.
* Memory-mapped file I/O: Redb relies on the operating system for file I/O, including mmap and fsync. This might introduce overhead and slow down the database. The author notes that simulating IO with crates could help improve efficiency.
* Single-process limitation: Currently, Redb can only be opened by a single process at a time. Implementing multi-process support would allow concurrent access, but this feature is not yet finished.
* Lack of optimizations: Redb is still an evolving project, and the author is focusing on completing the core architecture before optimizing performance. This might mean that some inefficiencies remain, contributing to slower performance.

Some issues may be already fixed, but It’s essential to note that Redb is a relatively new project, and the author is actively working on addressing these issues. The addition of a single-phase commit strategy (1PC+C) in version 0.4.0 has already improved performance, making it 2x faster for commits compared to the previous two-phase commit (2PC) approach.

To further improve performance, the author might consider:

Optimizing the tracking of dirty pages
Implementing multi-process support
Enhancing the B-Tree implementation
Exploring alternative file I/O strategies

As Redb continues to evolve, these issues are likely to be addressed, and the database’s performance will improve.

---

It's a fact that ord has several performance issues (see https://github.com/ordinals/ord/issues/3999#issuecomment-2423573845) for a small database of a few GBs of data, and more battle tested databases are available such as LevelDB (currently being used by Bitcoin Core) and [Pebble](https://github.com/cockroachdb/pebble) currently being used by Geth

**Comment by casey** [comment]
Please do not post AI-generated slop. If you do it again you will be banned.
