### ISSUE TITLE
`--index runes` help message

### ISSUE THREAD

**Issue by cryptoni9n** [ordinals/ord#4010]
`ord --help` shows the following message:

`--index-runes
          Track location of runes. RUNES ARE IN AN UNFINISHED PRE-ALPHA STATE AND SUBJECT TO CHANGE AT ANY TIME.`

Is this still accurate, or can we change this help message now?  I can make a quick PR if so.

**Comment by raphjaph** [comment]
Yes, open a PR, thanks!
