### ISSUE TITLE
Commit hanged

### ISSUE THREAD

**Issue by anonqoder** [ordinals/ord#4031]
Hi, I am using the latest ord release and indexing with 

ord --index-transactions --index-addresses --index-sats --index-runes index update

But it's been stuck since yesterday on this operation:

[2024-10-26T15:11:42 INFO  ord::index::updater] Committing at block height 840000, 43483800 outputs traversed, 17388480 in map, 52250235 cached

Looking the OS, there seems to be no IO activity from the ord process. How long does it usually take to "commit"? 

My machine specs: Linux/96GB RAM/8 TB disk/12 cpu

**Comment by cryptoni9n** [comment]
Hi anonqoder - make sure you're using at least the 0.21.1 version of ord, as it corrected a similar indexing issue.  Also, 840000 was the first rune block, so it has a lot of stuff to index in it.  96GB of RAM should be fine, but if you're having this kind of an issue on 0.21.1 or later, you should consider setting your `--commit-interval` flag to a lowish value of 100 or so when running the `ord server`.  For further assistance, please ping in the **#tech-support** channel of the [Ordicord](https://discord.com/invite/ordinals).
