### ISSUE TITLE
#3851 but for palindromes

### ISSUE THREAD

**Issue by gmart7t2** [ordinals/ord#4080]
![Screenshot_20241114_120039_Presearch](https://github.com/user-attachments/assets/3b70a86c-2eec-474a-b087-474208518204)

**Comment by gmart7t2** [comment]
Examples: 

* https://ordinals.com/inscription/5f922ae6e2ebc9f9fa6ffeb95ab5b63d3309de92c711d302df6f7152016452ddi0
* https://ordinals.com/inscription/cafebc5816eb429ea02b8e9041dc5f06d401e807e906331c491508b51439ccfci10

**Comment by raphjaph** [comment]
Making new release now
