### ISSUE TITLE
invalid charm `palindrome` running wallet balance

### ISSUE THREAD

**Issue by mvdnbrk** [ordinals/ord#4103]
```bash
ord wallet --name <NAME> balance
```

gives an error:
```
error: invalid charm `palindrome` at line 1 column 99
```

Guess that `palindrome` should be added here:

https://github.com/ordinals/ord/blob/5ac126d02f784063b6cb0284504e23e8ce826d58/crates/ordinals/src/charm.rs#L110-L128

**Comment by casey** [comment]
Whoops, thanks for reporting this!

**Comment by mvdnbrk** [comment]
Can you deploy a patch release please?

**Comment by casey** [comment]
Sorry for the wait! 0.22.0 on its way: #4125
