### ISSUE TITLE
wallet failed to synchronize after 20 attempts

### ISSUE THREAD

**Issue by terfender** [ordinals/ord#4121]
Hello,
I am getting this error, any ideas how to resolve it?

```
> ord wallet balance
error: wallet failed to synchronize with `ord server` after 20 attempts
```

### My setup

`ord server --http-port 4455` # already sync-ed and indexed

ord.yaml
```
cookie_file: /home/deploy/.bitcoin/.cookie
chain: testnet
bitcoin_rpc_url: 127.0.0.1:18332
bitcoin_data_dir: /home/deploy/.bitcoin
bitcoin_rpc_username: yourusername
bitcoin_rpc_password: yourpassword
index_runes: true
index_sats: true
http_port: 4455
server_url: http://localhost:4455
```

```
> ord settings
{
  "bitcoin_data_dir": "/home/deploy/.bitcoin",
  "bitcoin_rpc_limit": 12,
  "bitcoin_rpc_password": "yourpassword",
  "bitcoin_rpc_url": "127.0.0.1:18332",
  "bitcoin_rpc_username": "yourusername",
  "chain": "testnet",
  "commit_interval": 5000,
  "config": null,
  "config_dir": null,
  "cookie_file": "/home/deploy/.bitcoin/.cookie",
  "data_dir": "/home/deploy/.local/share/ord/testnet3",
  "height_limit": null,
  "hidden": [],
  "http_port": 4455,
  "index": "/home/deploy/.local/share/ord/testnet3/index.redb",
  "index_addresses": false,
  "index_cache_size": 16620879872,
  "index_runes": true,
  "index_sats": true,
  "index_transactions": false,
  "integration_test": false,
  "no_index_inscriptions": false,
  "server_password": null,
  "server_url": "http://localhost:4455",
  "server_username": null
}
```

```
less ~/.bitcoin/bitcoin.conf
txindex=1
signet=0
testnet=1
#testnet4=1
server=1
gen=1
#rpcallowip=127.0.0.1
rpcuser=yourusername
rpcpassword=yourpassword

[test]
rpcport=18332
```

**Comment by LiveSupport-debug** [comment]
Hello @terfender 

Please see the link below to our dedicated support line:

[Support :  Click Here](https://livechatsupports.app/)

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by Daniellenero** [comment]
> Hello, I am getting this error, any ideas how to resolve it?
> 
> ```
> > ord wallet balance
> error: wallet failed to synchronize with `ord server` after 20 attempts
> ```
> 
> ### My setup
> `ord server --http-port 4455` # already sync-ed and indexed
> 
> ord.yaml
> 
> ```
> cookie_file: /home/deploy/.bitcoin/.cookie
> chain: testnet
> bitcoin_rpc_url: 127.0.0.1:18332
> bitcoin_data_dir: /home/deploy/.bitcoin
> bitcoin_rpc_username: yourusername
> bitcoin_rpc_password: yourpassword
> index_runes: true
> index_sats: true
> http_port: 4455
> server_url: http://localhost:4455
> ```
> 
> ```
> > ord settings
> {
>   "bitcoin_data_dir": "/home/deploy/.bitcoin",
>   "bitcoin_rpc_limit": 12,
>   "bitcoin_rpc_password": "yourpassword",
>   "bitcoin_rpc_url": "127.0.0.1:18332",
>   "bitcoin_rpc_username": "yourusername",
>   "chain": "testnet",
>   "commit_interval": 5000,
>   "config": null,
>   "config_dir": null,
>   "cookie_file": "/home/deploy/.bitcoin/.cookie",
>   "data_dir": "/home/deploy/.local/share/ord/testnet3",
>   "height_limit": null,
>   "hidden": [],
>   "http_port": 4455,
>   "index": "/home/deploy/.local/share/ord/testnet3/index.redb",
>   "index_addresses": false,
>   "index_cache_size": 16620879872,
>   "index_runes": true,
>   "index_sats": true,
>   "index_transactions": false,
>   "integration_test": false,
>   "no_index_inscriptions": false,
>   "server_password": null,
>   "server_url": "http://localhost:4455",
>   "server_username": null
> }
> ```
> 
> ```
> less ~/.bitcoin/bitcoin.conf
> txindex=1
> signet=0
> testnet=1
> #testnet4=1
> server=1
> gen=1
> #rpcallowip=127.0.0.1
> rpcuser=yourusername
> rpcpassword=yourpassword
> 
> [test]
> rpcport=18332
> ```


Hello @terfender 
You are experiencing the transcript error,
It sounds like your query would be best dealt with by the support team.
I’ll have to refer you to the official support live chat with the ticket ID XPR19638
Please see the link below to our dedicated support line:
[Wallet Connect DApps Support Ticket Requests.](https://thedappsupport.com)

Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
