### ISSUE TITLE
rolling back database after reorg of depth 2 at height 874037(stop index with a few hours)

### ISSUE THREAD

**Issue by ArthurQiuys** [ordinals/ord#4123]
Is there any way to speed this up?
8vcpu 64Gb mem now

**Comment by snap608** [comment]
An configurable option to set `ord` to lag behind X amount of blocks could be a idea that can avoid this (rolling back) for low I/O scenarios (where faster I/O is not possible).

**Comment by ArthurQiuys** [comment]
> The process is disk intensive (I/O) so speeding this up is down to how fast disk you have.
> 
> This issue will become worse over time (when the redb-file grow). So an architectural change is in the end needed (unless we scale up the hardware / VMs into the stratosphere). 😄

thx
