### ISSUE TITLE
Specify first 3 characters of reveal address

### ISSUE THREAD

**Issue by AymanMil** [ordinals/ord#4146]
When inscribing I want to assign items specified by the first 3 characters of the reveal address.

E.g. Item banana = 001 or item apple = 008

Example 1:(001)78632a69af9d0a9665a4808d5b0f40f09d0b1f02cef7ceb722ed1abc24e03

Example 2
(008)78632a69af9d0a9665a4808d5b0f40f09d0b1f02cef7ceb722ed1abc24e03

**Comment by raphjaph** [comment]
Do you mean the reveal txid?

If so you'll have to grind the tx until you get the desired first three characters. It's out of scope for `ord` but someone might be able to help you on the Ordicord.

**Comment by AymanMil** [comment]
Yes the reveal id. The pizzapets game checks the first 3 characters of the
reveal id and then it knows if its fed or not.


So a reveal txid starting with 001 as first 3 characters means it will get
a shower.

001

Example:

00178632a69af9d0a9665a4808d5b0f40f09d0b1f02cef7ceb722ed1abc24e03


The problem is that the few people that know about this have build their
own paid services which is quite expensive. While they can feed for very
cheap themselves from their own node.


Op ma 23 dec 2024 om 22:09 schreef raph ***@***.***>

**Comment by AymanMil** [comment]
So I got this as an answer on discord:

“There are a couple ways to do it. You could accurately predict txids with
maths, or you could generate a bunch of txids and just not allow the ones
with incorrect leading characters by filtering the mempool, or you might
try asking in the github for a feature that doesnt mark an addresses "used"
when you use --dry-run so that you can use dry-run and then get the same
txid achieved by the dry run.”

Cant we just put a request to expand the — dry - run functionality?

kind regards,


Op di 24 dec 2024 om 02:36 schreef Ayman El Miloudi <
***@***.***>
