### ISSUE TITLE
Liability

### ISSUE THREAD

**Issue by casey** [ordinals/ord#742]
- Liability in the event something goes wrong. No company means unlimited join and several liability
- Copyright infringement by users
- Illegal content

**Comment by casey** [comment]
Filed to incorporate a delaware C corp w/clerky, waiting to hear back, so this is blocked.

**Comment by tyjvazum** [comment]
Did you consider an LLC? C Corps have to deal with the issue of double taxation and more strict operational requirements, which usually cost more than running an LLC. Electing S Corp status is an alternative to help with some of these issues if you do want a corporation.

**Comment by casey** [comment]
@tyjvazum Thanks for the input! For now, I'm just creating a delaware c corp because it's easy with clerky, not actually doing anything with it. Anything I do with it will be on the advice of a lawyer, and if they say an LLC or S corp is better, I'll modify the existing corp or create a new one and just let the old one rot.
