### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by casey** [ordinals/ord#785]
Copyright is complicated, costly, and at odds with the notion of digital ownership tracked in a decentralized ledger.

We should have some story for inscription content licensing. Ideas:

- Ignore licensing. People can figure it out for themselves.
- Include a license field that people can put whatever they want in.
- Include a license field, but if it isn't the CC0 (or maybe the CC0 with the patent and trademark limitations removed) don't display it on ordinals.com and don't allow the default tools to produce such an inscription.

Notes:
- Users will not like to be forced by dev fiat. It might be a major turnoff.
- Might want to strongly suggest a permissive license.
- Might want to require license during signet testing and see how people react to the concept.
- No matter the restrictions in the ord codebase, users can always publish content and claim that they didn't publish it, and thus the license is ineffective, and sue people for copyright infringement.

Overall very unsure about this. I think there's a good chance that this whole line of thinking is more trouble than it's worth. Maybe free-for-all is better. Or maybe just including a license field that people can put whatever they want in, and display the field on the website, or summarize as "permissive" / "non permissive".

**Comment by casey** [comment]
I think I'm now inclined to not do this. The law is complicated and stupid. I don't think there's much we can do at the protocol level without a whole bunch of conceptual overhead.

**Comment by casey** [comment]
Gah, now can't decide. It would be nice if there was some very gentle encouragement to use an all-permissive license. Even if it wasn't mandatory. Even that very minor encouragement might change the direction the ecosystem goes in.

It could be as simple as:

- There is a license field.
- You can put a hash of a license in the license field.
- If the hash is of the CC0, then it shows with `License: CC0` in green when displayed on ordinals.com
- If it is some other hash, it shows up with: `License: HASH`. (Doesn't even have to be too scary or red.)
- The tool requires that you supply a license with `--license PATH`. If the license is CC0, it doesn't complain. If it isn't CC0, it requires `--allow-unknown-license`.

This isn't too onorous, and could make a big difference in setting a baseline standard for the community.

**Comment by rot13maxi** [comment]
Just spitballing here, but another option would be to have a "license" field, and have the value be variable length:
```
0x00 - No license
0x01 - CC0
... insert the other licenses that you like ... 
0xFF - "Other license"
```

Is someone uses a license on the list, then the license field is one byte. For example, CC0 is just 0x01. ordinals.com can render a nice badge, etc. If someone wants a different license than what's available in the enum, they pick "other" (0xFF). and then they provide a hash of the license.

That way there is a good incentive to use a standard license (you get a nice badge on the ordinals.com explorer, and it's cheaper in blockspace), but there's still an "escape hatch" that people can pay a little extra for.

**Comment by nammaki** [comment]
I like the idea of having a license field 🚀

**Comment by casey** [comment]
There doesn't seem to be much demand for this, so closing.
