### ISSUE TITLE
Add compression via content-encoding

### ISSUE THREAD

**Issue by casey** [ordinals/ord#891]
We should add a field to inscriptions which contains a text string which is served with resources as the `content-encoding` header value. Users can then apply compression which should lead to a nice size reduction for lots of kinds of content. The command line tools should automatically apply compression if it results in a size decrease.

Brotli is well supported and very good, so we can use that: https://caniuse.com/?search=brotli

**Comment by staccDOTsol** [comment]
ha. it appears you'd already merged this 2 months ago and didn't clear the to-do item here.

Lmk if anything in my pr is useful

**Comment by tyjvazum** [comment]
This issue is still open because compression still isn't supported. PR https://github.com/casey/ord/pull/1713 was worked on to implement support for Brotli. PR https://github.com/casey/ord/pull/1366 only involves the block explorer website code.

**Comment by nammaki** [comment]
I really want compression 🙏

**Comment by casey** [comment]
This is done in #1713 although keep in mind that there is a cloudflare bug which prevents this from working #2775.
