### ISSUE TITLE
Link to inscriptions in docs

### ISSUE THREAD

**Issue by casey** [ordinals/ord#949]
Link to example inscriptions in docs.

**Comment by cryptoni9n** [comment]
> Link to example inscriptions in docs.

Hi @casey - sorry for dredging up old issues, but I'm beginning to look through them to see if there are any that can be closed.  I'm not sure what is needed for this issue, if anything.  I'm fairly sure you weren't referring to the creation of  https://docs.ordinals.com/inscriptions.html but would appreciate some clarification.  If you could provide some directionof what you had in mind, perhaps I can pepper some examples throughout the docs to help satisfy this issue?

**Comment by casey** [comment]
I think what I had in mind here was linking to examples of inscriptions which use particular features, so people can see those features in action. For example, an inscription that delegates to another inscription, an inscription that has metadata, etc.

**Comment by cryptoni9n** [comment]
we now have https://docs.ordinals.com/inscriptions/examples.html !
